### ISSUE TITLE
How to setup polyfill for crypto package?

### ISSUE THREAD

**Issue by MrPhyaeSoneThwim** [solana-labs/wallet-adapter#100]
I want to integrate my Gatsby project with solana wallet adapter.  I've already installed solana related packages according to the documentation. 

yarn add @solana/wallet-adapter-wallets
         @solana/wallet-adapter-base
         @solana/wallet-adapter-react
         @solana/wallet-adapter-react-ui
         @solana/web3.js

But when I start the project, the following error raised 

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }

You can see detail about error in the following picture

![error](https://user-images.githubusercontent.com/83585609/134938014-625047e7-ce2d-446d-aca6-2477b4137835.png)

**Comment by jordansexton** [comment]
Thanks for the report, is this something you were able to workaround by adding the fallback? This is something it would help to add documentation for @ https://github.com/solana-labs/wallet-adapter/blob/master/FAQ.md#can-i-use-this-with-___

**Comment by ibrica** [comment]
Removing polyfills for crypto (Torus wallet dependency I believe)  works for me. In webpack.config.js should be added: 
resolve: {
        fallback: {
            "crypto": false,
        } 
  }

**Comment by MrPhyaeSoneThwim** [comment]
Thanks jordansexton and ibrica. I've already solved the issues. I am using Gatsby so I used gatsby-node.js file and configured the deprecated packages manually by installing some packages..

And the code inside gatsby-node.js file just like this...

`const webpack = require("webpack")
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    plugins: [
      new webpack.ProvidePlugin({
        process: "process/browser",
      }),
      new webpack.ProvidePlugin({
        Buffer: [require.resolve("buffer/"), "Buffer"],
      }),
    ],
    resolve: {
      fallback: {
        crypto: require.resolve("crypto-browserify"),
        stream: require.resolve("stream-browserify"),
      },
    },
  })
}`

**Comment by jordansexton** [comment]
Nice, thank you both for posting your workarounds. I'll update the FAQ.

I think the fix @ibrica made is slightly better in principle, since it doesn't polyfill the Node crypto package that shouldn't be used in the browser anyway.

However, Buffer is used in the browser by Ledger at least, so it's good to polyfill that.

**Comment by jordansexton** [comment]
Fixed by 81e80d5cc5cdda58c01de93fc3050b5b931e14a9 / added to https://github.com/solana-labs/wallet-adapter/blob/master/FAQ.md#webpack--gatsby
