### ISSUE TITLE
useWallet() not working 

### ISSUE THREAD

**Issue by Maxtho8** [solana-labs/wallet-adapter#106]
Hi ,

When i'm trying to use the code on githhub, the connection with wallets works , but the button to send 1 lamport is always disable because the publicKey is empty. When i'm trying to console.log(publicKey) it returns undefined. Why ?

`import React, { FC, useMemo, useCallback } from 'react';
import { ConnectionProvider, WalletProvider,useConnection, useWallet } from '@solana/wallet-adapter-react';
import { WalletAdapterNetwork,WalletNotConnectedError } from '@solana/wallet-adapter-base';
import {
    getLedgerWallet,
    getPhantomWallet,
    getSlopeWallet,
    getSolflareWallet,
    getSolletExtensionWallet,
    getSolletWallet,
} from '@solana/wallet-adapter-wallets';
import {
    WalletModalProvider,
    WalletDisconnectButton,
    WalletMultiButton
} from '@solana/wallet-adapter-react-ui';
import { clusterApiUrl,Keypair, SystemProgram, Transaction } from '@solana/web3.js';

// Default styles that can be overridden by your app
require('@solana/wallet-adapter-react-ui/styles.css');

export const App: FC = () => {
    // Can be set to 'devnet', 'testnet', or 'mainnet-beta'
    const network = WalletAdapterNetwork.Devnet;

    // You can also provide a custom RPC endpoint
    const endpoint = useMemo(() => clusterApiUrl(network), [network]);

    // @solana/wallet-adapter-wallets includes all the adapters but supports tree shaking --
    // Only the wallets you configure here will be compiled into your application
    const wallets = useMemo(() => [
        getPhantomWallet(),
        getSlopeWallet(),
        getSolflareWallet(),
        getLedgerWallet(),
        getSolletWallet({ network }),
        getSolletExtensionWallet({ network }),
    ], [network]);

    const { connection } = useConnection();
    const { publicKey, sendTransaction } = useWallet();

    const onClick = useCallback(async () => {
        if (!publicKey) throw new WalletNotConnectedError();

        const transaction = new Transaction().add(
            SystemProgram.transfer({
                fromPubkey: publicKey,
                toPubkey: Keypair.generate().publicKey,
                lamports: 1,
            })
        );

        const signature = await sendTransaction(transaction, connection);

        await connection.confirmTransaction(signature, 'processed');
    }, [publicKey, sendTransaction, connection]);

    return (
       <div>
          <ConnectionProvider endpoint={endpoint}>
              <WalletProvider wallets={wallets} autoConnect>
                  <WalletModalProvider>
                      <WalletMultiButton />
                      <WalletDisconnectButton />
                  </WalletModalProvider>
              </WalletProvider>
          </ConnectionProvider>
          <button onClick={onClick} disabled={!publicKey}>
          Send 1 lamport to a random address!
          </button>
        </div>
    );
};`

**Comment by jordansexton** [comment]
This is an instance of this error: https://github.com/solana-labs/wallet-adapter/blob/master/FAQ.md#-is-not-a-function---is-undefined--uncaught-typeerror-cannot-destructure-property--uncaught-in-promise-walletnotconnectederror

This is happening because you're trying to use `useWallet` outside of the WalletProvider. It needs to be inside a descendant component of the React context created by that provider.
