### ISSUE TITLE
Warning ..... has unmet peer dependency ....

### ISSUE THREAD

**Issue by elonplant** [solana-labs/wallet-adapter#108]
[4/5] Linking dependencies...
warning " > @solana/wallet-adapter-angular@0.1.0" has unmet peer dependency "@angular/core@^12.2.0".
warning " > @solana/wallet-adapter-angular@0.1.0" has unmet peer dependency "@ngrx/component-store@^12.4.0".
warning " > @solana/wallet-adapter-angular@0.1.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-angular@0.1.0" has unmet peer dependency "rxjs@^6.6.0".
warning " > @solana/wallet-adapter-base@0.6.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-react@0.12.3" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-react@0.12.3" has unmet peer dependency "react@^17.0.2".
warning " > @solana/wallet-adapter-ant-design@0.8.0" has unmet peer dependency "@ant-design/icons@^4.6.3".
warning " > @solana/wallet-adapter-ant-design@0.8.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-ant-design@0.8.0" has unmet peer dependency "antd@^4.16.11".
warning " > @solana/wallet-adapter-ant-design@0.8.0" has unmet peer dependency "react@^17.0.2".
warning " > @solana/wallet-adapter-ant-design@0.8.0" has unmet peer dependency "react-dom@^17.0.2".
warning " > @solana/wallet-adapter-material-ui@0.12.3" has unmet peer dependency "@material-ui/core@^4.12.1".
warning " > @solana/wallet-adapter-material-ui@0.12.3" has unmet peer dependency "@material-ui/icons@^4.11.2".
warning " > @solana/wallet-adapter-material-ui@0.12.3" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-material-ui@0.12.3" has unmet peer dependency "react@^17.0.2".
warning " > @solana/wallet-adapter-material-ui@0.12.3" has unmet peer dependency "react-dom@^17.0.2".
warning " > @solana/wallet-adapter-react-ui@0.5.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-react-ui@0.5.0" has unmet peer dependency "react@^17.0.2".
warning " > @solana/wallet-adapter-react-ui@0.5.0" has unmet peer dependency "react-dom@^17.0.2".
warning " > @solana/wallet-adapter-bitkeep@0.1.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-bitpie@0.2.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-blocto@0.2.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-clover@0.1.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-coin98@0.2.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-ledger@0.6.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-mathwallet@0.6.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-phantom@0.6.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-safepal@0.2.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-slope@0.2.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-solflare@0.3.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-sollet@0.7.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-solong@0.6.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-torus@0.7.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning " > @solana/wallet-adapter-walletconnect@0.1.0" has unmet peer dependency "@solana/web3.js@^1.20.0".
warning "workspace-aggregator-18bb6364-646f-437a-9f14-53bf3557b80c > @solana/wallet-adapter-angular > @angular/core@12.2.7" has unmet peer dependency "zone.js@~0.11.4".
warning "workspace-aggregator-18bb6364-646f-437a-9f14-53bf3557b80c > @solana/wallet-adapter-material-ui-starter > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "workspace-aggregator-18bb6364-646f-437a-9f14-53bf3557b80c > @solana/wallet-adapter-torus > @toruslabs/openlogin@0.10.2" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-18bb6364-646f-437a-9f14-53bf3557b80c > @solana/wallet-adapter-torus > @toruslabs/openlogin-ed25519@0.10.2" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-18bb6364-646f-437a-9f14-53bf3557b80c > @solana/wallet-adapter-example > next-plugin-antd-less > less-loader@7.3.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-18bb6364-646f-437a-9f14-53bf3557b80c > @solana/wallet-adapter-example > next-plugin-antd-less > null-loader@4.0.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-18bb6364-646f-437a-9f14-53bf3557b80c > @solana/wallet-adapter-react-ui-starter > react-hot-toast > goober@2.0.41" has unmet peer dependency "csstype@^2.6.2".
warning "workspace-aggregator-18bb6364-646f-437a-9f14-53bf3557b80c > @solana/wallet-adapter-torus > @toruslabs/openlogin > @toruslabs/http-helpers@1.4.0" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-18bb6364-646f-437a-9f14-53bf3557b80c > @solana/wallet-adapter-torus > @toruslabs/openlogin > @toruslabs/openlogin-jrpc@0.10.2" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-18bb6364-646f-437a-9f14-53bf3557b80c > @solana/wallet-adapter-torus > @toruslabs/openlogin > @toruslabs/openlogin-utils@0.10.2" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-18bb6364-646f-437a-9f14-53bf3557b80c > @solana/wallet-adapter-example > next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".

**Comment by jordansexton** [comment]
This appears to be saying that you are missing the `@solana/web3.js` dependency in your project.

This warning message also doesn't have enough context to act on and isn't following the template for bug reports. If you're opening an issue, please complete this: https://github.com/solana-labs/wallet-adapter/issues/new?assignees=&labels=&template=bug_report.md&title=
