### ISSUE TITLE
Flutter(Dart) support

### ISSUE THREAD

**Issue by Sharaddition** [solana-labs/wallet-adapter#110]
Problem-
Currently, there seems to be no way to connect Solana wallet in flutter cross-platform apps.

Solution-
A flutter pub package to integrate solana wallet in flutter web,android,ios apps.

I tried Dart JS interop, but had no luck in integrating it.

**Comment by jordansexton** [comment]
@Sharaddition is this something you're interested in working on a PR for?

**Comment by jordansexton** [comment]
I see. I think Flutter/Dart may be out of scope for this library, which is primarily for wallets that run in user's browser or a webview. I'm going to close this issue for now. If someone comes along that is interested in implementing this, please comment and reopen.
