### ISSUE TITLE
Property 'connected' does not exist on type 'WalletContextState'.

### ISSUE THREAD

**Issue by iurage** [solana-labs/wallet-adapter#115]
Error of `Property 'connected' does not exist on type 'WalletContextState'.` shows up when running the latest @solana/wallet-adapter-react@0.12.5 for dapp-scafold project.

**Comment by jordansexton** [comment]
It looks like dapp-scaffold is using older versions of the wallet-adapter packages:

https://github.com/solana-labs/dapp-scaffold/blob/00aa49c1a290937ae65463e7f17fe5364f2b2f5b/package.json#L31-L34

Please file an issue to update the dependencies with that project, and feel free to tag me on it.

**Comment by jordansexton** [comment]
FWIW, this PR in review updates these versions: https://github.com/solana-labs/dapp-scaffold/pull/46

I might suggest trying to use that code.
