### ISSUE TITLE
Make packages proper ESM with "type": "module"

### ISSUE THREAD

**Issue by vovacodes** [solana-labs/wallet-adapter#121]
**Is your feature request related to a problem? Please describe.**
The packages from this repo currently export modules in "loose" ESM format which means you cannot import them into a webpack 5 or nodejs project that uses "native" node ESM module resolution.  

**Describe the solution you'd like**
We could solve it by making the files in `lib/*` proper ESM (add file extensions to imported  module specifiers) and add `"type": "module"` to `package.json`.

See https://webpack.js.org/guides/ecma-script-modules/ for more details

**Comment by jordansexton** [comment]
I've tested out building the library after converting all the relevant packages to ESM: https://github.com/solana-labs/wallet-adapter/pull/132

It seems to work okay, since apps that use this already need to transpiling the modules one way or another and the import/export syntax hasn't changed.

This could be expanded to build ESM and CJS versions if needed, but I'd rather not unless there's an obvious benefit.

Let me know what you think.

**Comment by jordansexton** [comment]
This has been implemented. All the core and wallet packages are ESM modules. The React, Angular, and Vue UI packages are not, as I ran into issues with these when using `sideEffects: false`, which was necessary to fix #69.

**Comment by jordansexton** [comment]
Published:
 - @solana/wallet-adapter-base@0.7.0
 - @solana/wallet-adapter-react@0.13.0
 - @solana/wallet-adapter-vue@0.3.0
 - @solana/wallet-adapter-wallets@0.11.0
 - @solana/wallet-adapter-example@0.14.0
 - @solana/wallet-adapter-material-ui-starter@0.10.0
 - @solana/wallet-adapter-nextjs-starter@0.5.0
 - @solana/wallet-adapter-react-ui-starter@0.6.0
 - @solana/wallet-adapter-ant-design@0.9.0
 - @solana/wallet-adapter-material-ui@0.13.0
 - @solana/wallet-adapter-react-ui@0.6.0
 - @solana/wallet-adapter-bitpie@0.3.0
 - @solana/wallet-adapter-blocto@0.3.0
 - @solana/wallet-adapter-clover@0.2.0
 - @solana/wallet-adapter-coin98@0.3.0
 - @solana/wallet-adapter-ledger@0.7.0
 - @solana/wallet-adapter-mathwallet@0.7.0
 - @solana/wallet-adapter-phantom@0.7.0
 - @solana/wallet-adapter-safepal@0.3.0
 - @solana/wallet-adapter-slope@0.3.0
 - @solana/wallet-adapter-solflare@0.4.0
 - @solana/wallet-adapter-sollet@0.8.0
 - @solana/wallet-adapter-solong@0.7.0
 - @solana/wallet-adapter-tokenpocket@0.2.0
 - @solana/wallet-adapter-torus@0.8.0
