### ISSUE TITLE
WalletSignTransactionError: Blocked a frame with origin "https://domain.xyz" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by ilmoi** [solana-labs/wallet-adapter#125]
After integrating the sol wallet adapter, some of the wallets work fine (phantom, sollet extensions) but with others (sollet in particular) I'm getting this error:

```
Transaction failed, WalletSignTransactionError: Blocked a frame with origin "https://domain.xyz" from accessing a cross-origin frame.
Some transactions failed. Please re-run or see browser console to debug.
```

Connecting to the wallet works fine - the issue arises only when actually trying to sign the transction.

Test both on localhost (http) and in prod (https) - same result.

Any ideas?

**Comment by jordansexton** [comment]
At a glance, it doesn't look like you are using https://www.npmjs.com/package/@solana/wallet-adapter-vue which was recently published. Can you try that? At least then we'll be looking at the same code to test.

**Comment by jordansexton** [comment]
Thinking about this a bit more:

> I would have easily assumed it's a general cors/vue issue - but what's weird is that only this wallet is throwing the error.

Sollet is the only wallet package (though there are a few that derive from it) that opens a popup window with no browser extension like this. So it's not _too weird_ if this is the only wallet experiencing this if it's on your local environment.

**Comment by steveluscher** [comment]
Refs to the rescue! https://github.com/2501babe/revoken/pull/1

**Comment by jordansexton** [comment]
Closing as this has been determined to be a Vue issue, but the vue and vue-ui packages here aren't believed to be affected. Thanks for bughunting!

**Comment by ilmoi** [comment]
Just in case others are finding this thread and want the TLDR solution it's:

Wherever you store you `WalletAdapter` (not just `Wallet`!) variable, change it from this:
```js
wallet: null; //options api
const walletAdapter = ref(null); //composition api
```

to this:
```js
import {shallowRef} from 'vue'

wallet: shallowRef(null); //options api
const walletAdapter = ref(shallowRef(null)); //composition api
```

At first I thought it wouldn't work coz we're overwriting the adapter when we assign it, but it does work and solve the issue. Vue magic ¯\_(ツ)_/¯

See [this PR](https://github.com/2501babe/revoken/commit/661aa1f5bc5551a241badfc6748f9042014a0a77) for an example.

@steveluscher @2501babe @lorisleiva absolute legends you all, thank you so much for saving the day <3

**Comment by jordansexton** [comment]
You can also sidestep this issue by using the [vue](https://github.com/solana-labs/wallet-adapter/tree/master/packages/core/vue) & [vue-ui](https://github.com/solana-labs/wallet-adapter/tree/master/packages/ui/vue-ui) packages in the library now (unless you really only want low-level access to the adapter).

**Comment by laurensV** [comment]
What would be the best way to solve this issue in Vue2?

**Comment by jordansexton** [comment]
@laurensV Vue 2 is not supported. Vue 3 is required by the related packages in WalletAdapter.
