### ISSUE TITLE
Unable to run the NextJS example

### ISSUE THREAD

**Issue by s-pcode** [solana-labs/wallet-adapter#127]
Followed the example folder and copied the whole code. Installed all the required dependencies but when I open that page in the browser I encounter an error : 

node_modules\@solana\wallet-adapter-bitpie\lib\index.js:1        
export * from './adapter';
^^^^^^

SyntaxError: Unexpected token 'export'

I'm adding this to my existing nextjs application.

**Comment by s-pcode** [comment]
Do I need to install all the dependencies mentioned in the next.config.js file ?? Actually, I had done this but installed only the necessary dependencies that were used in the component file.

**Comment by jordansexton** [comment]
No, you only need the ones you use directly. Having extras in the config won't do anything.

**Comment by s-pcode** [comment]
Thanks @jordansexton . That worked 👍 

Can you help me how to use the UI with nextjs as the example only contains a provider and when I use the react UI I get error.

![image](https://user-images.githubusercontent.com/85111021/137594618-9a3fb30f-53d4-485a-ade8-a5ed40853c07.png)

**Comment by s-pcode** [comment]
Thanks a lot, @jordansexton 👍
