### ISSUE TITLE
ConnectionProvider doesn't allow changing connection end point

### ISSUE THREAD

**Issue by leofisG** [solana-labs/wallet-adapter#149]
**Is your feature request related to a problem? Please describe.**
We cannot change the end point that passed into `ConnectionProvider`.

**Describe the solution you'd like**
```
export interface ConnectionProviderProps {
    children: ReactNode;
    endpoint: string;
    config?: ConnectionConfig;
    setEndpoint: (endpoint: string) => void;
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by jordansexton** [comment]
Closing this as stale, but potentially will be implemented in https://github.com/solana-labs/wallet-adapter/pull/328
