### ISSUE TITLE
Sollet wallet does not work

### ISSUE THREAD

**Issue by praskoson** [solana-labs/wallet-adapter#154]
**Describe the bug**
I'm unable to connect with Sollet wallet in starter projects or in the example: https://solana-labs.github.io/wallet-adapter/example/

**To Reproduce**
Change the wallet to Sollet and try to connect. It gets stuck in a "Connecting" state. There are no errors in the browser console.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Tried Chrome and Firefox

**Comment by jordansexton** [comment]
Interesting, I'm seeing the same issue with no error. I'll work on it, thanks for the report.

**Comment by QZIG** [comment]
Ok it seems to be the provider url in getSolletWallet function, change to https://www.sollet.io works for me. Don't know why...

**Comment by jordansexton** [comment]
Good catch, thanks for finding that. I'll fix and release

**Comment by jordansexton** [comment]
This is fixed in e73d6275c29b96d01a9ad18282c61687d3cfd7c4 / @solana/wallet-adapter-wallets@0.11.3. Please let me know if it's not working after updating!

**Comment by QZIG** [comment]
It's working !

**Comment by variantpanda** [comment]
It still not working what's going on?

**Comment by IvanBurzakovskyi** [comment]
The `sollet.io` is not responding. The Chrome extension also is not working (infinite loader is shown)

**Comment by jordansexton** [comment]
Sollet is deprecated, and no longer works because it relies on Serum RPCs which are no longer active.

Check out this thread for how to export your key from Sollet, which you can use with a different wallet:

https://twitter.com/steveluscher/status/1593075105042944000
