### ISSUE TITLE
Allow for WalletMultiButton customization

### ISSUE THREAD

**Issue by andrehadianto** [solana-labs/wallet-adapter#155]
**Is your feature request related to a problem? Please describe.**
I can't seem to create a custom UI for the wallet button aside from the provided templates. Although I can add more styles and classNames using the props, the button is stuck with `wallet-adapter-button` class which clashes with most of the style additions I would like to use.

**Describe the solution you'd like**
`wallet-adapter-button` className should be a fallback.

**Additional context**
`<Button/>` component can be seen here
https://github.com/solana-labs/wallet-adapter/blob/c64705db3523bd3e3da79bd06355b23e30add8de/packages/ui/react-ui/src/Button.tsx#L13

**Comment by jordansexton** [comment]
I'm not sure I understand. Since you can add your own classes, you can override the styles on the button, right?

```css
.wallet-adapter-button.your-class-here {
    /* These styles should have higher specificity and override the defaults */
}
```

**Comment by andrehadianto** [comment]
Oh I got it. Thanks a lot! I was trying to change it by directly editing `.wallet-adapter-button {}` and forgot about the priority order. 

For those who prefer to directly manipulate everything from scratch, I was using `styled-components` package as a temporary fix before this. 

Thank you sir!
