### ISSUE TITLE
How to use `useWallet()` hook?

### ISSUE THREAD

**Issue by topcoder1208** [solana-labs/wallet-adapter#157]
import React, { FC, useMemo } from 'react';
    import {
        ConnectionProvider,
        WalletProvider,
        useConnection,
        useWallet
    } from '@solana/wallet-adapter-react';
    import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
    import {
        getPhantomWallet,
    } from '@solana/wallet-adapter-wallets';
    import {
        WalletModalProvider,
        WalletDisconnectButton,
        WalletMultiButton
    } from '@solana/wallet-adapter-react-ui';
    import { clusterApiUrl } from '@solana/web3.js';

    // Default styles that can be overridden by your app
    require('@solana/wallet-adapter-react-ui/styles.css');

    export default function Wallet() {
        // Can be set to 'devnet', 'testnet', or 'mainnet-beta'
        const network = WalletAdapterNetwork.Devnet;

        // You can also provide a custom RPC endpoint
        const endpoint = useMemo(() => clusterApiUrl(network), [network]);

    // @solana/wallet-adapter-wallets includes all the adapters but supports tree shaking --
    // Only the wallets you configure here will be compiled into your application
    const wallets = useMemo(() => [
        getPhantomWallet(),
        getSlopeWallet(),
        getSolflareWallet(),
        getTorusWallet({
            options: { clientId: 'Get a client ID @ https://developer.tor.us' }
        }),
        getLedgerWallet(),
        getSolletWallet({ network }),
        getSolletExtensionWallet({ network }),
    ], [network]);

    const { connection } = useConnection();
    const wallet = useWallet();
    console.log(connection, wallet)
    return (
        <ConnectionProvider endpoint={endpoint}>
            <WalletProvider wallets={wallets} autoConnect>
                <WalletModalProvider>
                    <WalletMultiButton />
                </WalletModalProvider>
            </WalletProvider>
        </ConnectionProvider>
    );
    };

This is my code. But this code is not working.
When I try to use `const wallet = useWallet();` wallet variable is empty object. What is problem? How to fix?

**Comment by jordansexton** [comment]
This is an instance of this problem: https://github.com/solana-labs/wallet-adapter/blob/master/FAQ.md#-is-not-a-function---is-undefined--uncaught-typeerror-cannot-destructure-property--uncaught-in-promise-walletnotconnectederror

`useWallet` cannot be called at the level you're calling it -- your context providers need to wrap your application. `useWallet` can only be called as a descendant of the WalletProvider context.
