### ISSUE TITLE
WalletConnect2 question

### ISSUE THREAD

**Issue by MexicanSparker** [solana-labs/wallet-adapter#158]
I know that WalletConnect2 implementation isn't ready to publish yet even when you can go ahead and port the Wallet Adapter implementation to your local project, which I did.

It is a nightmare finding a project where you can test a single successful connection via WalletConnect2 since there is a very poor adoption in Solana. The Implementation was apparently working until days ago but today the QR code modal is not popping up and in the console I get this error.
```
WebSocket connection to 'wss://relay.walletconnect.com/?env=browser&host=localhost%3A3000&protocol=wc&version=2' failed: 
error.ts:66 Uncaught TypeError: Cannot read properties of undefined (reading 'message')
    at parseConnectionError (error.ts:66)
    at WsConnection.parseError (ws.ts:148)
    at WebSocket.socket.onerror (ws.ts:108)
```
It everything became something to me when I got the news that Solflare mobile wallet now supports it so I went to test and here I am.
Any Idea of whats happening?
PD: The error is still the same running from the official domain of my dApp or from my local dev env.

**Comment by jordansexton** [comment]
I'm not aware of WalletConnect working on Solana yet. Can you point to me to what you found documenting Solflare's support of it?

**Comment by MexicanSparker** [comment]
That is a fair asking, I would be interested in their implementation details too, I'm going to try contacting them to see how they tested it and even if the implementation details are in a private repo at least to see the implementation of the client connecting code.

**Comment by jordansexton** [comment]
https://medium.com/walletconnect/walletconnect-v2-0-protocol-whats-new-3243fa80d312 was published 2 days ago. Unfortunately there are no details on when the Solana provider may be implemented.

**Comment by jordansexton** [comment]
Closing this issue as there's a tracking PR now: https://github.com/solana-labs/wallet-adapter/pull/187

Please subscribe to that PR!
