### ISSUE TITLE
ConnectionProvider is not exported from @solana/wallet-adapter-react

### ISSUE THREAD

**Issue by angshumanHalder** [solana-labs/wallet-adapter#159]
Wallet.tsx - 

```
import React, { FC, useMemo } from "react";
import { ConnectionProvider, WalletProvider } from "@solana/wallet-adapter-react";
import { WalletAdapterNetwork } from "@solana/wallet-adapter-base";
import {
  getLedgerWallet,
  getPhantomWallet,
  getSlopeWallet,
  getSolflareWallet,
  getSolletExtensionWallet,
  getSolletWallet,
  getTorusWallet,
} from "@solana/wallet-adapter-wallets";
import { WalletModalProvider, WalletDisconnectButton, WalletMultiButton } from "@solana/wallet-adapter-react-ui";
import { clusterApiUrl } from "@solana/web3.js";

// Default styles that can be overridden by your app
require("@solana/wallet-adapter-react-ui/styles.css");

export const Wallet: FC = () => {
  // Can be set to 'devnet', 'testnet', or 'mainnet-beta'
  const network = WalletAdapterNetwork.Devnet;

  // You can also provide a custom RPC endpoint
  const endpoint = useMemo(() => clusterApiUrl(network), [network]);

  // @solana/wallet-adapter-wallets includes all the adapters but supports tree shaking --
  // Only the wallets you configure here will be compiled into your application
  const wallets = useMemo(
    () => [
      getPhantomWallet(),
      getSlopeWallet(),
      getSolflareWallet(),
      getTorusWallet({
        options: { clientId: "Get a client ID @ https://developer.tor.us" },
      }),
      getLedgerWallet(),
      getSolletWallet({ network }),
      getSolletExtensionWallet({ network }),
    ],
    [network]
  );

  return (
    <ConnectionProvider endpoint={endpoint}>
      <WalletProvider wallets={wallets} autoConnect>
        <WalletModalProvider>
          <WalletMultiButton />
          <WalletDisconnectButton />
        </WalletModalProvider>
      </WalletProvider>
    </ConnectionProvider>
  );
};

```
`Module '"@solana/wallet-adapter-react"' has no exported member 'ConnectionProvider'.  TS2305

    23 | // };
    24 | import React, { FC, useMemo } from "react";
  > 25 | import { ConnectionProvider, WalletProvider } from "@solana/wallet-adapter-react";
       |          ^
    26 | import { WalletAdapterNetwork } from "@solana/wallet-adapter-base";
    27 | import {
    28 |   getLedgerWallet,

`
Seems like ConnectionProvider is not exported. I checked in the npm modules but there is no file called ConnectionProvider.js in the module. Is there any solution / workaround to this other than cloning the repo?

These are my dependencies - 

    "@emotion/react": "^11.5.0",
    "@emotion/styled": "^11.3.0",
    "@mui/material": "^5.0.6",
    "@solana/wallet-adapter-base": "^0.7.0",
    "@solana/wallet-adapter-react": "^0.7.2",
    "@solana/wallet-adapter-react-ui": "^0.6.0",
    "@solana/wallet-adapter-wallets": "^0.6.2",
    "@solana/web3.js": "^1.30.2",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "typescript": "^4.1.2",
    "web-vitals": "^1.0.1"

**Comment by UncleBill** [comment]
Looks like because of an old version `0.7.2` was set as latest

https://www.npmjs.com/package/@solana/wallet-adapter-react/v/0.7.1?activeTab=versions 

![image](https://user-images.githubusercontent.com/1141198/140864074-387b3ef9-3f3d-4ddf-9e98-458d585aa8aa.png)

**Comment by angshumanHalder** [comment]
> Looks like because of an old version `0.7.2` was set as latest a day ago.
> 
> https://www.npmjs.com/package/@solana/wallet-adapter-react/v/0.7.1?activeTab=versions
> 
> ![image](https://user-images.githubusercontent.com/1141198/140864074-387b3ef9-3f3d-4ddf-9e98-458d585aa8aa.png)
> 
> ## Update
> Also in @solana/wallet-adapter-wallets
> 
> ![image](https://user-images.githubusercontent.com/1141198/140864345-26cd1b1b-dddc-43ce-bd38-5ab3d2e6fda4.png)

Thanks. This resolved my issue. I am closing this.

**Comment by jordansexton** [comment]
Ah, thanks. A change was backported to an older version, and it looks like I need to refine the release process.

**Comment by jordansexton** [comment]
This is fixed, the latest version is correctly tagged now. Sorry about that!
