### ISSUE TITLE
Current version of @solana/wallet-adapter-wallets is 0.6.2?

### ISSUE THREAD

**Issue by callmewhy** [solana-labs/wallet-adapter#160]
**Describe the bug**
The current version in npm is 0.6.2, is it by design?
https://www.npmjs.com/package/@solana/wallet-adapter-wallets

![image](https://user-images.githubusercontent.com/6276527/140947324-8072f0cb-69f7-4cba-b5dd-fc85c47fd1ad.png)

**Expected behavior**
Use latest version as Current Tag.

**Comment by jordansexton** [comment]
This is fixed, the latest versions are correctly tagged now. This was caused by backporting a patch release to an older version. Sorry about that!
