### ISSUE TITLE
Support mui v5 (material-ui 's new version)

### ISSUE THREAD

**Issue by chrisirhc** [solana-labs/wallet-adapter#168]
**Is your feature request related to a problem? Please describe.**
Currently, the material-ui adapter is for material-ui v4.
mui v5 has been released recently: https://mui.com/blog/mui-core-v5/

**Describe the solution you'd like**
Codemods are available at: https://mui.com/guides/migration-v4/

**Additional context**
Creating this issue to start gauging interest in this. I might be able to create a PR if there's interest.

**Comment by jordansexton** [comment]
Makes sense, a PR would be welcome!

**Comment by kirksgithub** [comment]
Already got the code ready to be contributed, @jordansexton want to get some folders ready, and I can contribute there

**Comment by chrisirhc** [comment]
Added #170 which outlines one way to do this. Please take a look :)

**Comment by jordansexton** [comment]
Closing this issue as there's a tracking PR now. Please subscribe to #170 which will be merged soon.
