### ISSUE TITLE
Sollet web extension support

### ISSUE THREAD

**Issue by ZhengYuTay** [solana-labs/wallet-adapter#17]
Hey, I tried to use sollet web extension with `SolletWalletAdapter`. I found an issue with `.connect` which the Promise is immediately resolved whether the user click connect or not.

Not sure whether it's the Sollet web extension or the library, just wanna bring this up

**Comment by jordansexton** [comment]
Thanks for the report. The Sollet browser extension is currently unsupported by the `@solana/wallet-adapter-sollet` package, though it should be. I'll get this fixed.

**Comment by danmt** [comment]
I was going crazy with this. I had to put together a [repro repo](https://github.com/danmt/solana-wallet-adapter-sollet-repro) just for sanity.

**Comment by jordansexton** [comment]
This is being addressed by https://github.com/solana-labs/wallet-adapter/pull/64

**Comment by jordansexton** [comment]
Fixed @ https://solana-labs.github.io/wallet-adapter/example/ and released on NPM.

**Comment by ZhengYuTay** [comment]
thanks!
