### ISSUE TITLE
Slope Wallet doesn't work as expected in Android Device while working on iPhone

### ISSUE THREAD

**Issue by leonardgee** [solana-labs/wallet-adapter#174]
**Describe the bug**
Slope Wallet doesn't work in Android device but it works on iPhone.

**To Reproduce**
1. Go to Port Finance
2. Click on Deposit
3. No transaction is sent if check block explorer if it is on Android device, while it works on iOS.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
Android

**Additional context**

**Comment by jordansexton** [comment]
Slope has reported the issue as fixed!
