### ISSUE TITLE
Build Error evaluating SSR module with SvelteKit

### ISSUE THREAD

**Issue by mikhail-karan** [solana-labs/wallet-adapter#175]
**Describe the bug**
SvelteKit seems to not play well with any solana/wallet packages. Gives a ` [vite] Error when evaluating SSR module /src/routes/index.svelte: ` error

I can sometimes refresh and get the application to still work though. Also if I build and preview it does not throw the error. 

It also appears as soon as you import 

**To Reproduce**
[https://github.com/mikhail-karan/sveltekit-solana-wallet-error](https://github.com/mikhail-karan/sveltekit-solana-wallet-error)

Clone this repo, install packages and run. You will see the error show up after you run ` npm run dev `

EDIT: Really cool new tech with svelteKit web containers lets you run this code in the browser, don't have to pull down the repo locally! 

[https://stackblitz.com/edit/sveltekit-zc3rma?file=src%2Froutes%2Findex.svelte](https://stackblitz.com/edit/sveltekit-zc3rma?file=src%2Froutes%2Findex.svelte)

**Expected behavior**
With just Svelte it built fine, only with SvelteKit did the error appear. 

**Screenshots**
The build error
<img width="866" alt="Screen Shot 2021-11-19 at 10 07 28 PM" src="https://user-images.githubusercontent.com/8340258/142712523-733a479a-8907-49fc-99d2-ddfc26dcfdb7.png">

**Comment by jordansexton** [comment]
I realize your reproduction doesn't use these, but FWIW the Svelte core and UI packages aren't published yet (https://github.com/solana-labs/wallet-adapter/pull/173, https://github.com/solana-labs/wallet-adapter/pull/162, https://github.com/solana-labs/wallet-adapter/pull/161).

Outside of reviews for that work, I haven't tested anything related to Svelte. Can you see if the configuration in those PRs helps? @cogoo or @silvestrevivo may have some insight.

**Comment by mikhail-karan** [comment]
> I realize your reproduction doesn't use these, but FWIW the Svelte core and UI packages aren't published yet (#173, #162, #161).
> 
> Outside of reviews for that work, I haven't tested anything related to Svelte. Can you see if the configuration in those PRs helps? @cogoo or @silvestrevivo may have some insight.

Yup! I'll try right now and report back.

**Comment by cogoo** [comment]
@mikhail-karan yup I recognise this error. You have to add eventemitter3 to your dev dependencies with `npm i eventemitter3 -D`. @jordansexton this is why we added it to our svelte core package

**Comment by mikhail-karan** [comment]
> @mikhail-karan yup I recognise this error. You have to add eventemitter3 to your dev dependencies with `npm i eventemitter3 -D`. @jordansexton this is why we added it to our svelte core package

Yup that solved it!

Going to close this issue now. Thanks everyone!

**Comment by jordansexton** [comment]
https://github.com/solana-labs/wallet-adapter/issues/204 was implemented, which should allow wallets to be safely used in an SSR context because their potentially unsafe dependencies aren't loaded until `connect` is called.
