### ISSUE TITLE
Vue Documentation

### ISSUE THREAD

**Issue by kris** [solana-labs/wallet-adapter#178]
Curious if/when there will be documentation on integrating with Vue. As someone new to Solana, it's a bit difficult to grok the workflow by looking at limited practical examples.

**Comment by bowtietech** [comment]
Plus one for documentation. 

Got the wallet adapter and multi-button working, but having issue interacting with the wallet once connected. Would expect an interface from the component, as hitting useWallet directly causes errors prior to initialization. 

Followed the old code (prior to modularization), but difficult to port as it is pre-encapsulation. 

Any support would be very helpful, thanks! (also, big thank you for this feature!!!)

**Comment by bowtietech** [comment]
@lorisleiva Thank you for the package, btw! Very nice!

**Comment by 0xzachvai** [comment]
In the meantime, for anyone looking I found this example to be a huge help figuring things out: https://github.com/lorisleiva/solana-vue3-counter

**Comment by djordjevucinic** [comment]
@bowtietech Would you be willing to share your code, I'm struggling to connect anything , seems like i need additional loaders..

**Comment by bowtietech** [comment]
@djordjevucinic  This is a rough outline (pardon the sloppiness) of what I've got working for the button:
https://gist.github.com/bowtietech/7b6cbf51e6069f668ec1b8a88523110d

Thanks, @0xzachvai, that's actually what I referenced to get this part working.

**Comment by lorisleiva** [comment]
Hi there 👋 

Unfortunately, most of the packages of this repository have no documentation yet. I might help with that at some point when I have more time available.

However, today I've released an article that explains **how to integrate wallets in your Vue 3 application**.

Here's the link. I hope this helps. 🍀

https://lorisleiva.com/create-a-solana-dapp-from-scratch/integrating-with-solana-wallets

**Comment by bowtietech** [comment]
This is epic; thank you @lorisleiva!

**Comment by djordjevucinic** [comment]
This is very helpful, thanks @lorisleiva 👍

**Comment by lmvdz** [comment]
@lorisleiva Hi I have this issue after following your blog post that my wallet from useAnchorWallet is undefined in initWorkspace, even though I've connected it through the UI. If I make a small change to the initWorkspace and save, then the hot module replacement picks up the wallet as a valid anchorWallet... weird right?

**Comment by lorisleiva** [comment]
@lmvdz I think this could be related to https://github.com/solana-labs/wallet-adapter/issues/256

**Comment by lmvdz** [comment]
@lorisleiva thanks, I tried to follow along with the thread, but I got really confused... will just wait until it's working for vite

**Comment by davidgiga1993** [comment]
@lorisleiva Thanks, I've followed your guide but apparently the injection from the `WalletProvider` doesn't work:
```
runtime-core.cjs.js?b7d1:40 [Vue warn]: provide() can only be used inside setup().
warn	@	runtime-core.cjs.js?b7d1:40
provide	@	runtime-core.cjs.js?b7d1:1588
provideWallet	@	useWallet.mjs?067d:16
setup	@	WalletProvider.mjs?96fe:24
```

Because of that the child components fail:
```
Wallet not initialized. Please use the `WalletProvider` component to initialize the wallet.
```

Any ideas?

**Comment by jordansexton** [comment]
Vue support has been moved to https://github.com/lorisleiva/solana-wallets-vue via #297
