### ISSUE TITLE
Is there any standard document about `signMessage`?

### ISSUE THREAD

**Issue by kinosang** [solana-labs/wallet-adapter#179]
Just like BIP-322 and ERC-191?

**Comment by jordansexton** [comment]
Not to my knowledge -- it's just arbitrary bytes. The method signature is just any bytes in, signature bytes out: https://github.com/solana-labs/wallet-adapter/blob/75388bd6774e0b5ed68cf0a4737d656adf14110f/packages/core/base/src/signer.ts#L56

This FAQ shows how to use it: https://github.com/solana-labs/wallet-adapter/blob/master/FAQ.md#how-can-i-sign-and-verify-messages

Hope this helps!
