### ISSUE TITLE
Sollet web throws WalletWindowClosedError

### ISSUE THREAD

**Issue by danmt** [solana-labs/wallet-adapter#18]
# Overview

@solana/wallet-adapter-sollet throws WalletWindowClosedError right after calling `connect` method, the popup opens but the error shows in the console and the "connect" event is never fired. I made a [repro repo](https://github.com/danmt/solana-wallet-adapter-sollet-repro).

![This is the error I'm seeing](https://user-images.githubusercontent.com/7496781/130688983-10dc2c2f-2839-4aab-88c8-4fd2e1899737.png)

I'm trying to figure out if it's related to @project-serum/sol-wallet-adapter

**Comment by jordansexton** [comment]
Thanks for the reproduction. So I understand clearly, is this related to the Sollet browser extension, or the sollet.io web wallet?

**Comment by danmt** [comment]
Web wallet. I misread the other issue, I think this is a different thing.

Let me know if I can help somehow

**Comment by danmt** [comment]
I replied in the PR but for easier follow up for others facing this issue I copy-pasted it here.

After merging I'm facing the same problem.

I tested using Chrome@92.0.4515.159 and Firefox@91.0.2.

Steps to reproduce:

- Clone the repo
- Install dependencies (I tried with Yarn and NPM)
- Run npm run serve
- Click Connect Sollet button
- Proceed to connect

The weird things I noticed so far:

- As soon as sollet's window opens the app console throws a WindowClosedError.
- After authenticating in Sollet, the new window redirects me to the wallet instead of authorizing my app.
- Even though the .ready() getter from the Sollet adapter is hard-coded, I'd expect a "sollet ready" event to be fired which isn't the case.

BTW - I tried this using a fresh NPM install, fresh yarn install and yarn install --frozen-lockfile none of em worked for me.

**Comment by danmt** [comment]
I believe the issue is related to parcel, more specifically to this issue parcel#1747. Apparently, there's some weirdness about the global variables when using this bundler. Will close the issue for now since I was able to workaround it by using webpack instead.

**Comment by jordansexton** [comment]
Thanks for following up on this. Good to know about the issue with Parcel. There's an open PR that might help: https://github.com/solana-labs/wallet-adapter/pull/32

The additional checks for `typeof window != 'undefined'` to fix server side rendering issues might also fix the issue with Parcel.

**Comment by danmt** [comment]
I think the problem relates to the fallbacks (crypto, path, os and so on) or polyfills.
