### ISSUE TITLE
Errors emitted multiple times

### ISSUE THREAD

**Issue by cmitjans-at-wiris** [solana-labs/wallet-adapter#182]
**Describe the bug**
When user cancels the transaction, the same error is emitted twice by the adapter.

**To Reproduce**
```typescript
this.wallet = getPhantomWallet();
this.adapter = this.wallet.adapter();

this.adapter.on('error', this.onWalletError);
```

**Expected behavior**
Only one error should be emitted.

**Additional context**
Analyzing the code, I've seen that `BaseSignerWalletAdapter` calls `this.signTransaction` inside a try/catch block. In turn the method `signTransaction` uses a try/catch block. In both try/catch blocks, the error is emitted and thrown. This means that when `signTransaction` catches the error, it emits it, and then it throws it to the `BaseSignerWalletAdapter`, who in turn emits it and throws it again.

Would it be possible for the client to only receive 1 error event?

**Comment by jordansexton** [comment]
Good catch, and thanks for the detailed context. I'll fix this, some other wallets probably have the same behavior.
