### ISSUE TITLE
Allow installing @solana/wallet-adapter-wallets without installing all wallets

### ISSUE THREAD

**Issue by vpontis** [solana-labs/wallet-adapter#183]
Right now `@solana/wallet-adapter-wallets` lists all of the wallets as dependencies in the [package.json](https://github.com/solana-labs/wallet-adapter/blob/master/packages/core/wallets/package.json).

This makes this package very hard to use because some of the wallets imported are not very well maintained. For example, Torus has had [an open issue over a month](https://github.com/torusresearch/eccrypto/pull/14) about not being able to build it on ARM architectures. Additionally, Torus requires Python just to `npm install`. 

Instead of bundling all of the wallets in  `@solana/wallet-adapter-wallets`, you could define a standard interface that wallets would adhere to if they want to integrate with the rest of your packages.

**Comment by alanpilloud** [comment]
Hi @vpontis, I had the same kind of issue with Torus causing trouble in my package build.

I uninstalled `@solana/wallet-adapter-wallets` and installed the independent packages I was interrested in (only Phantom in fact `@solana/wallet-adapter-phantom`).

Then, I rewrote the `getPhantomWallet` function to mimic `@solana/wallet-adapter-wallets` exact behaviour :

```
import { PhantomWalletAdapter } from "@solana/wallet-adapter-phantom"

export const getPhantomWallet = (config = {}) => ({
  name: "Phantom",
  url: "https://phantom.app",
  icon: "data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiBoZWlnaHQ9IjM0IiB3aWR0aD0iMzQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGxpbmVhckdyYWRpZW50IGlkPSJhIiB4MT0iLjUiIHgyPSIuNSIgeTE9IjAiIHkyPSIxIj48c3RvcCBvZmZzZXQ9IjAiIHN0b3AtY29sb3I9IiM1MzRiYjEiLz48c3RvcCBvZmZzZXQ9IjEiIHN0b3AtY29sb3I9IiM1NTFiZjkiLz48L2xpbmVhckdyYWRpZW50PjxsaW5lYXJHcmFkaWVudCBpZD0iYiIgeDE9Ii41IiB4Mj0iLjUiIHkxPSIwIiB5Mj0iMSI+PHN0b3Agb2Zmc2V0PSIwIiBzdG9wLWNvbG9yPSIjZmZmIi8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjZmZmIiBzdG9wLW9wYWNpdHk9Ii44MiIvPjwvbGluZWFyR3JhZGllbnQ+PGNpcmNsZSBjeD0iMTciIGN5PSIxNyIgZmlsbD0idXJsKCNhKSIgcj0iMTciLz48cGF0aCBkPSJtMjkuMTcwMiAxNy4yMDcxaC0yLjk5NjljMC02LjEwNzQtNC45NjgzLTExLjA1ODE3LTExLjA5NzUtMTEuMDU4MTctNi4wNTMyNSAwLTEwLjk3NDYzIDQuODI5NTctMTEuMDk1MDggMTAuODMyMzctLjEyNDYxIDYuMjA1IDUuNzE3NTIgMTEuNTkzMiAxMS45NDUzOCAxMS41OTMyaC43ODM0YzUuNDkwNiAwIDEyLjg0OTctNC4yODI5IDEzLjk5OTUtOS41MDEzLjIxMjMtLjk2MTktLjU1MDItMS44NjYxLTEuNTM4OC0xLjg2NjF6bS0xOC41NDc5LjI3MjFjMCAuODE2Ny0uNjcwMzggMS40ODQ3LTEuNDkwMDEgMS40ODQ3LS44MTk2NCAwLTEuNDg5OTgtLjY2ODMtMS40ODk5OC0xLjQ4NDd2LTIuNDAxOWMwLS44MTY3LjY3MDM0LTEuNDg0NyAxLjQ4OTk4LTEuNDg0Ny44MTk2MyAwIDEuNDkwMDEuNjY4IDEuNDkwMDEgMS40ODQ3em01LjE3MzggMGMwIC44MTY3LS42NzAzIDEuNDg0Ny0xLjQ4OTkgMS40ODQ3LS44MTk3IDAtMS40OS0uNjY4My0xLjQ5LTEuNDg0N3YtMi40MDE5YzAtLjgxNjcuNjcwNi0xLjQ4NDcgMS40OS0xLjQ4NDcuODE5NiAwIDEuNDg5OS42NjggMS40ODk5IDEuNDg0N3oiIGZpbGw9InVybCgjYikiLz48L3N2Zz4K",
  adapter: () => new PhantomWalletAdapter(config),
})
```

Then just imported it in my Wallet.js and use the getPhantomWallet function like advised in the docs.

Hope it helps !

**Comment by jordansexton** [comment]
I think this is a valid issue. I'll try to think about how the architecture or build system can be improved. The value of having everything in an enum is pretty limited.

**Comment by zicklag** [comment]
Yeah, I've run into similar issues with my Quasar/Vue.js application. I ended up downloading the whole library locally and commenting out all the wallets and dependencies that I didn't want.

**Comment by jordansexton** [comment]
Please review! https://github.com/solana-labs/wallet-adapter/pull/195

**Comment by vpontis** [comment]
@jordansexton that looks awesome! I'll check it out tomorrow :)

**Comment by jordansexton** [comment]
This is fixed in master, but still needs to be published to NPM as a breaking change.

**Comment by jordansexton** [comment]
To be clear, `@solana/wallet-adapter-wallets` still has all the wallets as dependencies, but you can now use all of them individually without using `@solana/wallet-adapter-wallets` at all, since the dependency on it has been removed from the core.

**Comment by jordansexton** [comment]
This is published on npm. It's a breaking change for the base package, so it's a breaking change for everything. The new versions:

 - @solana/wallet-adapter-base@0.8.0
 - @solana/wallet-adapter-react@0.14.0
 - @solana/wallet-adapter-vue@0.4.0
 - @solana/wallet-adapter-example@0.15.0
 - @solana/wallet-adapter-ant-design@0.10.0
 - @solana/wallet-adapter-material-ui@0.14.0
 - @solana/wallet-adapter-react-ui@0.7.0
 - @solana/wallet-adapter-vue-ui@0.2.0
 - @solana/wallet-adapter-bitkeep@0.2.0
 - @solana/wallet-adapter-bitpie@0.4.0
 - @solana/wallet-adapter-blocto@0.4.0
 - @solana/wallet-adapter-clover@0.3.0
 - @solana/wallet-adapter-coin98@0.4.0
 - @solana/wallet-adapter-coinhub@0.2.0
 - @solana/wallet-adapter-ledger@0.8.0
 - @solana/wallet-adapter-mathwallet@0.8.0
 - @solana/wallet-adapter-phantom@0.8.0
 - @solana/wallet-adapter-safepal@0.4.0
 - @solana/wallet-adapter-slope@0.4.0
 - @solana/wallet-adapter-solflare@0.5.0
 - @solana/wallet-adapter-sollet@0.9.0
 - @solana/wallet-adapter-solong@0.8.0
 - @solana/wallet-adapter-tokenpocket@0.3.0
 - @solana/wallet-adapter-torus@0.10.0
 - @solana/wallet-adapter-wallets@0.13.0
