### ISSUE TITLE
Add some kind of `activate` to do both select and connect in one go similar to web3React

### ISSUE THREAD

**Issue by Superjo149** [solana-labs/wallet-adapter#184]
**Is your feature request related to a problem? Please describe.**

The select/connect API is a bit frustrating if wou need to do both in 1 function. Because of this, to work with the library, you need to give up a lot of control.

**Describe the solution you'd like**
Similar to Web3React, I suggest adding some kind of `activate` function where we could just pass the wallet, and the promise returns the activated walletAdapter.

```ts
const adapter = await activate(phantomWallet);

const { publicKey } = adapter;
```

The benefit of having something like this, is that everything would still be managed through and in the logic of the hooks, while the connect can just happen async while returning the user info and adapter.

Web3React Source: https://github.com/NoahZinsmeister/web3-react/blob/be1a23e290f208e5edc7490b7010e5a9561448e6/packages/core/src/manager.ts#L122

**Describe alternatives you've considered**
/

**Additional context**
I have tried this in our codebase, and it seems to work pretty nicely. If I have time, I might clean this up and write a PR if this is something that you guys like to see.

**Comment by jordansexton** [comment]
Yeah, I'd like to see how you've implemented this. And just to check, have you tried using autoConnect in the React context?

web3-react doesn't really have a concept of "selecting" a wallet, so it's not clear to me yet what problem you want to solve for.

**Comment by jordansexton** [comment]
@Superjo149 do you have any more info on this?

**Comment by jordansexton** [comment]
Closing for now since there's been no response. Please comment if you want to reopen!
