### ISSUE TITLE
Not getting wallet not installed error

### ISSUE THREAD

**Issue by designOm** [solana-labs/wallet-adapter#186]
Code snapshots
![image](https://user-images.githubusercontent.com/42335697/144444018-e9fba9b9-0a07-4cf2-942b-7f454c54791a.png)

Click  handler
![image](https://user-images.githubusercontent.com/42335697/144444309-b73eea9d-82b9-4b22-942d-4776218aaac1.png)

Error handler 
![image](https://user-images.githubusercontent.com/42335697/144444480-4d6edb29-4504-41bd-a377-bf8fa9173e44.png)

When i open application in any browser where  no extension is installed , I am expecting an warning but that is not happening , because i am not getting  expected error strings in errors

**Comment by jordansexton** [comment]
It's a bit hard to tell what's going on from these code snippets. Can you link a repo that reproduces the issue?

**Comment by designOm** [comment]
hi @jordansexton 
Here is the repo that  is replica of my current aaplication 

 https://github.com/designOm/solana-adapter-ui  

I want to prompt a Notification to user , Who is not installed extensions in their browser

**Comment by jordansexton** [comment]
I checked out the project. I see it's using redux to duplicate the wallet state, and a lot of the logic around managing the state and `localStorage` is duplicated and may conflict with the React context. I recommend using the React context the `react` package in this library provides, which already does most of what you want.
