### ISSUE TITLE
Angular Documentation

### ISSUE THREAD

**Issue by adibbz** [solana-labs/wallet-adapter#197]
I know the Angular package is pretty fresh but I was wondering if there's any documentation on how to implement into my Angular project? Even a stackblitz example would be very helpful!

**Comment by jordansexton** [comment]
Your best bet for now is probably to check out https://github.com/solana-labs/wallet-adapter/pull/87#issuecomment-939554600 and subsequent discussion with the author of that package, @danmt.

**Comment by adibbz** [comment]
@danmt following along with the comment mentioned above. I installed the following packages:
```
@danmt/wallet-adapter-angular 
@solana/wallet-adapter-base
@solana/wallet-adapter-wallets
@solana/web3.js
```
I omitted `@danmt/wallet-adapter-angular-material-ui` because I'm going to try to do my own styling. But I'm getting the following compilation errorr when running `ng serve`. Any ideas?

I can look at getting a stackblitz together once I've successfully implemented in my project.

**Comment by adibbz** [comment]
@danmt I was able to at least get this compiling today by updating the type files in your package. 

Essentially update these in `wallet.types.d.ts` and `wallet.store.d.ts`
```
import { SendTransactionOptions, Wallet, WalletAdapter, WalletName } from '@solana/wallet-adapter-base';
// import { Wallet, WalletName } from '@solana/wallet-adapter-wallets';
```

However seeing this error in the console
<img width="1047" alt="Screen Shot 2021-12-15 at 4 32 33 PM" src="https://user-images.githubusercontent.com/6921939/146275411-5764b729-6b1a-4c98-9b40-e602ad81e4bc.png">

**Comment by jordansexton** [comment]
@adibbz these issues are because of https://github.com/solana-labs/wallet-adapter/pull/195 -- they are fixed in master, but the Angular package isn't quite ready for use there. If you're using @danmt's released version, you'll need to use a previous version of the `wallet-adapter-*` dependencies.

**Comment by jordansexton** [comment]
Basically, it looks like you're installing the latest packages from here along with his, and they aren't compatible (yet). Should be fixed within a few days and then we'll cut an official release.

**Comment by danmt** [comment]
I'm working on this today @adibbz. Hopefully, we can have the official release soon to avoid incompatibility issues.

**Comment by adibbz** [comment]
@jordansexton @danmt -  Right on, thanks guys! Looking forward to the release 🥳

**Comment by danmt** [comment]
Hey @adibbz I created this repo a while back and totally forgot about it. It shows [how to use the wallet-adapter in Angular](https://github.com/danmt/wallet-adapter-angular-sample). I just recently updated it to have what's going to be released soon.

Let's wait until the official release to port that into stackblitz, it shouldn't be too hard.

**Comment by jordansexton** [comment]
Blocked on https://github.com/solana-labs/wallet-adapter/pull/208 which is almost ready to merge. The build is currently broken due to an esoteric issue with a dependency.

**Comment by jordansexton** [comment]
Closing this since #285 has removed Angular from this repo and over to its new home: https://github.com/heavy-duty/platform/tree/master/libs/wallet-adapter
