### ISSUE TITLE
Detect which wallets are installed / able to connect

### ISSUE THREAD

**Issue by jordansexton** [solana-labs/wallet-adapter#201]
https://github.com/solana-labs/wallet-adapter/pull/195 has added persistent adapter objects, which makes it much more practical to detect all the available wallets when the page loads.

The React / Vue / Angular / Svelte packages should provide a simple way to do this so the user isn't shown a bunch of invalid options to select from.

**Comment by jordansexton** [comment]
So the idea is basically this -- now that every `wallet.adapter` is already instantiated, and each has an async `ready` function, we should be able to set up something that

1. Takes a list of `Wallet` instances
2. Calls `ready` on all their adapters
3. Filters out all the ones that resolve false
4. Provides the filtered list to the React/Angular/Vue context

You could initially provide the entire list, then in useEffect or whatever, filter it. Ideally we handle all this for the dev, maybe with a feature flag, so they just pass in a list like they do now and it just works. We will also likely want to do some kind of device detection, so that on mobile devices we prioritize mobile app wallets for example, which may require some type of addition to the adapter API.

One possible option is to add a `getWallets()` function to the `wallets` package and suggest using this in the examples. We will need to figure out whether to show wallets that aren't installed, and what to show when the user has no wallets installed.

Most of the adapters have almost no overhead to load, so a dapp could load them all and then just filter out most of them the user doesn't have. We could perhaps asynchronously load the dependencies for wallets like Torus, Ledger, Blocto, and Sollet that use libraries. This could be done in the `connect` function, so that each adapter can report that it's ready, but the footprint for initial loading will be tiny.

@danmt and @rathishubham7, you both expressed interest in working on this, so I'd love to get your ideas.

**Comment by danmt** [comment]
The only change I would propose is to rather than having the full list of wallets and the list of ready wallets in the state, I'd like it if the wallets had a "ready" field that would be updated using some sort of useEffect. This way package consumers will be able to choose between the full list (with the ready status) and only the ready wallets.

**Comment by tyirenkyi** [comment]
Hey, I'd love to take a crack at this. Could you point me to where the best starting would be? @jordansexton @danmt

**Comment by danmt** [comment]
Heyo @tyirenkyi here's a PR @jordansexton has been working on https://github.com/solana-labs/wallet-adapter/pull/206 

Take a look at it and feel free to drop suggestions.

**Comment by jordansexton** [comment]
Closing this since the filtering can be done in the UI components now.
