### ISSUE TITLE
How do I change color or theme of wallet-adapter-material-ui?

### ISSUE THREAD

**Issue by gaolingxiao** [solana-labs/wallet-adapter#202]

**Comment by jordansexton** [comment]
Solana Discord's #developer-support channel is the best place for questions, but this isn't really a wallet-adapter question, just a MUI question. Check out the starter project:

https://github.com/solana-labs/wallet-adapter/blob/137794254bdd45d8ebc0f59394d7919bf8599f6e/packages/starter/material-ui-starter/src/App.tsx#L11-L16
