### ISSUE TITLE
Not able to get wallet id for store in my app

### ISSUE THREAD

**Issue by sanjayfullstackltd** [solana-labs/wallet-adapter#209]
After successful connect wallet 
I need to store my wallet id in my storage so no method is there

any help will be great.

**Comment by jordansexton** [comment]
Storing the name of the selected wallet in LocalStorage is handled by the WalletProvider: https://github.com/solana-labs/wallet-adapter/blob/296b7e17a6b14093f49ab4d1a3066cc0606718c5/packages/core/react/src/WalletProvider.tsx#L45

If you have `autoConnect` enabled, the stored wallet will automatically try to connect when your app loads.
