### ISSUE TITLE
× ←→1 of 2 errors on the page Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:

### ISSUE THREAD

**Issue by lakshmankashyap** [solana-labs/wallet-adapter#218]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jordansexton** [comment]
This is probably an issue with your code, not the library. Closing this because no code or context was provided.
