### ISSUE TITLE
Add fully functioning examples

### ISSUE THREAD

**Issue by CalebEverett** [solana-labs/wallet-adapter#220]
While there are some code snippets in the README and some packages that can be run to connect to a wallet, it would be more helpful to have fully functioning examples that work with yarn start that show how to submit a transaction signed by a connected wallet.

**Comment by jordansexton** [comment]
Have you checked the [example](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/example) package? [SendTransaction.tsx](https://github.com/solana-labs/wallet-adapter/blob/master/packages/starter/example/components/SendTransaction.tsx) has something like this.

**Comment by CalebEverett** [comment]
Thanks, I missed that. I'll check it out and maybe add to the material ui packages as well if that would be helpful.

**Comment by jordansexton** [comment]
Yeah, that would be great! The other starter projects are pretty sparse and could definitely be more illustrative.

**Comment by CalebEverett** [comment]
[SendTransaction.tsx](https://github.com/solana-labs/wallet-adapter/blob/master/packages/starter/example/components/SendTransaction.tsx) was complaining about needing a recentBlockhash - adding below got it to submit, but it wouldn't confirm.

```js
            let recentBlockhash = await connection.getRecentBlockhash();
            const transaction = new Transaction({ recentBlockhash: recentBlockhash.blockhash, feePayer: publicKey }).add(
                SystemProgram.transfer({
                    fromPubkey: publicKey,
                    toPubkey: Keypair.generate().publicKey,
                    lamports: 1,
                })
            );
```

The console error says:
```
Error: Promised response from onMessage listener went out of scope
```

Any ideas on how to track down?

**Comment by CalebEverett** [comment]
Apparently [that was related to an installed extension](https://stackoverflow.com/questions/69506506/what-does-error-promised-response-from-onmessage-listener-went-out-of-scope-m). I moved to a private window and am not getting the error anymore, but the transaction still times out after 30 seconds.

**Comment by 0xPratik** [comment]
> Apparently [that was related to an installed extension](https://stackoverflow.com/questions/69506506/what-does-error-promised-response-from-onmessage-listener-went-out-of-scope-m). I moved to a private window and am not getting the error anymore, but the transaction still times out after 30 seconds. The airdrop transaction is working. Not sure if this is related, but thought I would pass along just in case - the wallet dialog is also saying it is unable to fetch balance changes:
> 
> ![image](https://user-images.githubusercontent.com/8947267/147039199-ef823e44-b62a-4cc4-9bb1-bff2c87e5d5c.png)

I think the amount of lamports that you are trying to send is very less So its no able to fetch balance change. you can check  https://solanacookbook.com/ has great snippets to work with the wallet adapter. Hope you find it usefull

**Comment by Veterangrail** [comment]
> While there are some code snippets in the README and some packages that can be run to connect to a wallet, it would be more helpful to have fully functioning examples that work with yarn start that show how to submit a transaction signed by a connected wallet.

https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by jordansexton** [comment]
Closing since I think this was done a while ago. The example starter project has a bunch of different things like this now, but beyond that, it's probably out of scope for Wallet Adapter itself. Thanks!
