### ISSUE TITLE
Unable to send transaction in devnet: Transaction recentBlockhash required

### ISSUE THREAD

**Issue by tanin47** [solana-labs/wallet-adapter#226]
**Describe the bug**

I can't send a transaction in devnet. I'm new to Solana, so I'm not quite sure what is wrong.

**To Reproduce**
Go to the demo page and connect the wallet: https://solana-labs.github.io/wallet-adapter/example/

I can request an airdrop but I can't send transaction.

**Screenshots**

![image](https://user-images.githubusercontent.com/494417/147377794-122a467b-7dc5-4e36-ab5c-4de869ca52e4.png)

**Comment by jordansexton** [comment]
Check out this: https://github.com/solana-labs/wallet-adapter/pull/223

This appears to affect Phantom when you don't set the recent blockhash before calling `sendTransaction`. I'll make a fix very soon.

**Comment by tanin47** [comment]
Yes, I was using Phantom (forgot to mention it). Thank you for taking a look. Looking forward to the fix.

**Comment by jordansexton** [comment]
Just a quick followup -- I'm getting clarification from the Phantom team on the expected behavior here. A fix will be published tomorrow.

**Comment by tanin47** [comment]
I wonder if adding the line: `transaction.recentBlockhash = (await connection.getRecentBlockhash()).blockhash;` would make it work. It seems to work in my prototype.

**Comment by jordansexton** [comment]
Confirmed that this is a bug in Phantom. I'll add a workaround to WalletAdapter.

**Comment by jordansexton** [comment]
This is fixed in master but the example/demo hasn't been updated yet due to unrelated build issue introduced in #227.
