### ISSUE TITLE
Error: @solana/wallet-adapter-react error

### ISSUE THREAD

**Issue by ntirinigaSr** [solana-labs/wallet-adapter#236]
After changing react-scripts from version "5.0.0" to "4.0.3"  and installed solana wallets adapters successfully. Then importing this 
@solana-wallet-react brings this error, 

./node_modules/@solana/wallet-adapter-react/lib/esm/WalletProvider.js 27:29
Module parse failed: Unexpected token (27:29)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     connected
|   }, setState] = useState(initialState);
>   const readyState = adapter?.readyState || WalletReadyState.Unsupported;
|   const [connecting, setConnecting] = useState(false);
|   const [disconnecting, setDisconnecting] = useState(false);

Has anyone got this kind of error?

**Comment by cogoo** [comment]
> After changing react-scripts from version "5.0.0" to "4.0.3" and installed solana wallets adapters successfully. Then importing this @solana-wallet-react brings this error,
> 
> ./node_modules/@solana/wallet-adapter-react/lib/esm/WalletProvider.js 27:29 Module parse failed: Unexpected token (27:29) File was processed with these loaders:
> 
> * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
>   You may need an additional loader to handle the result of these loaders.
>   |     connected
>   |   }, setState] = useState(initialState);
> 
> > const readyState = adapter?.readyState || WalletReadyState.Unsupported;
> > |   const [connecting, setConnecting] = useState(false);
> > |   const [disconnecting, setDisconnecting] = useState(false);
> 
> Has anyone got this kind of error?

Would it be possible to share a link to a repository that has this issue or could you share the code that causes this issue?

I've just started a new react app with CRA and couldn't reproduce this issue.

Could you check your `package.json` to see if you're using the latest version of the wallet related packages.

```json
"@solana/wallet-adapter-base": "^0.9.0",
"@solana/wallet-adapter-react": "^0.15.0",
"@solana/wallet-adapter-wallets": "^0.14.0",
"@solana/web3.js": "^1.31.0",
```

**Comment by ntirinigaSr** [comment]
CODES 

`import './App.css';
import {useWallet} from '@solana/wallet-adapter-react'
import {PublicKey} from '@solana/web3.js';
import {PhantomWalletAdapter} from '@solana/wallet-adapter-wallets'
import {WalletAdapterNetwork} from '@solana/wallet-adapter-base';



function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;`

**PACKAGE.JSON**
`{
  "name": "f1",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@solana/wallet-adapter-base": "^0.9.0",
    "@solana/wallet-adapter-react": "^0.15.0",
    "@solana/wallet-adapter-wallets": "^0.14.0",
    "@solana/web3.js": "^1.31.0",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^2.1.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

**AFTER IMPORTING EITHER @solana/wallet-adapter-base or @solana/wallet-adapter-wallets I GET THIS ERROR**
./node_modules/@solana/wallet-adapter-base/lib/esm/signer.js 16:16
Module parse failed: Unexpected token (16:16)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|           ...sendOptions
|         } = options;
>         signers?.length && transaction.partialSign(...signers);
|         transaction = await this.signTransaction(transaction);
|         const rawTransaction = transaction.serialize();


**AND I IMPORT ONLY @solana/wallet-adapter-react I GET THIS ONE**
`./node_modules/@solana/wallet-adapter-react/lib/esm/WalletProvider.js 27:29
Module parse failed: Unexpected token (27:29)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     connected
|   }, setState] = useState(initialState);
>   const readyState = adapter?.readyState || WalletReadyState.Unsupported;
|   const [connecting, setConnecting] = useState(false);
|   const [disconnecting, setDisconnecting] = useState(false);
`

**AND THAT'S IT**

**Comment by zhangxiaoshang** [comment]
![image](https://user-images.githubusercontent.com/19658966/147870763-07c8008d-c915-4940-bc4e-38dff3b519de.png)

I have the same error

**Comment by jordansexton** [comment]
These kind of issues are generally caused by something wrong with your project configuration.

First, please check out this starter project which is built using CRA:
https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/react-ui-starter

Try to see if anything in your configuration is different.

If you can't figure it out, please post a link to a repository that reproduces your issue -- we'll need the entire thing to be able to see why it's not building.

**Comment by cogoo** [comment]
@ntirinigaSr @zhangxiaoshang 

I've noticed that the default create-react-app ships with some incompatible configurations. 

```diff
 "browserslist": {
    "development": [
-      "last 1 chrome version",
-      "last 1 firefox version",
-      "last 1 safari version"
+      "defaults"
    ]
```

Making the above changes in `package.json` will resolve the above issues.

CC: @jordansexton

**Comment by jordansexton** [comment]
@cogoo great find, that's really interesting. Any idea why it is that "last 1 * version" is no good?

**Comment by ntirinigaSr** [comment]
Errors still exists, It's not about browserlist I think and may be something else which I don't know

**Comment by cogoo** [comment]
> Errors still exists, It's not about browserlist I think and may be something else which I don't know

Could you share your entire `package.json` or share a link to the repo that has the error?

**Comment by dranikpg** [comment]
Same issue. I've created a fresh react app with create-react-app 5.0.0 (the latest) and ran into the same issue. Updating the browserlist fixed the issue.
_However_, a lot of babel incompatibilities follow that have to be resolved manually 😞

**Comment by felixtilli** [comment]
I get this problem when using the latest packages. I have tried the browserlist change without any result.

My project works fine when I use:
`"@project-serum/anchor": "^0.15.0",
"@solana/wallet-adapter-base": "^0.7.1",
"@solana/wallet-adapter-react": "^0.13.1",
"@solana/wallet-adapter-react-ui": "^0.6.1",
"@solana/wallet-adapter-wallets": "^0.11.3",
"@solana/web3.js": "^1.26.0",`

**Comment by ntirinigaSr** [comment]
> GITHUB  https://github.com/ntirinigaSr/nft-ui

**Comment by jordansexton** [comment]
> I get this problem when using the latest packages. I have tried the browserlist change without any result.
> 
> My project works fine when I use: `"@project-serum/anchor": "^0.15.0"` `"@solana/wallet-adapter-base": "^0.7.1",` `"@solana/wallet-adapter-react": "^0.13.1",` `"@solana/wallet-adapter-react-ui": "^0.6.1",` `"@solana/wallet-adapter-wallets": "^0.11.3",` `"@solana/web3.js": "^1.26.0",`

These are all older versions than the latest. Please follow these instructions: https://github.com/solana-labs/wallet-adapter#build-from-source

This will help you run the react-ui-project, which uses Create React App.

**Comment by akutruff** [comment]
I pulled the started repo and followed the instructions to the letter.  The current version of the code in the repo unfortunately produces this error with zero changes:

```
Failed to compile.

/workspaces/solana-wallet-adapter/packages/core/base/lib/esm/signer.js 19:16
Module parse failed: Unexpected token (19:16)
File was processed with these loaders:
 * ../../../node_modules/react-scripts/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ../../../node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|           ...sendOptions
|         } = options;
>         signers?.length && transaction.partialSign(...signers);
|         transaction = await this.signTransaction(transaction);
|         const rawTransaction = transaction.serialize();
```

**Comment by jordansexton** [comment]
Thanks for reporting! I'll try it out.

**Comment by cogoo** [comment]
> > GITHUB  https://github.com/ntirinigaSr/nft-ui

Thanks, I looked at this and your error is not related to the wallet adapter packages. It's an unrelated error about react hooks.

**Comment by akutruff** [comment]
Tried material ui starter as well.  Sorry to nudge, but any idea on when a fixed package will be published?  I'm 100% blocked by the wallet adapter unfortunately.

**Comment by jordansexton** [comment]
We're working on a fix now! We'll update the thread when it ships.

**Comment by jordansexton** [comment]
If you're blocked and need a workaround now, I recommend the Next.js starter project and example which don't have the issues that CRA does right now.

**Comment by akutruff** [comment]
> We're working on a fix now! We'll update the thread when it ships.

Thanks so much!

**Comment by jordansexton** [comment]
This is fixed! Huge thanks to @cogoo for working all day on this. All the Next.js and Create React App 4-based starter projects build and run now.

However, CRA 5 is not supported yet. See https://github.com/solana-labs/wallet-adapter/issues/241#issuecomment-1006239019 for context.

**Comment by akutruff** [comment]
Is this going to get reflected in the main NPM soon, or does this only fix the starters?  I see the change is basically a yarn.lock and tsconfig change.

**Comment by jordansexton** [comment]
Yeah, I'll need to publish all the packages today. It fixes the starters when run from source, but only because their deps are resolved locally

**Comment by jordansexton** [comment]
@akutruff 

Published:
 - @solana/wallet-adapter-base@0.9.1
 - @solana/wallet-adapter-react@0.15.1
 - @solana/wallet-adapter-vue@0.4.2
 - @solana/wallet-adapter-example@0.17.1
 - @solana/wallet-adapter-material-ui-starter@0.12.1
 - @solana/wallet-adapter-nextjs-starter@0.7.1
 - @solana/wallet-adapter-react-ui-starter@0.8.1
 - @solana/wallet-adapter-ant-design@0.11.1
 - @solana/wallet-adapter-material-ui@0.16.1
 - @solana/wallet-adapter-react-ui@0.9.1
 - @solana/wallet-adapter-vue-ui@0.2.1
 - @solana/wallet-adapter-bitkeep@0.3.1
 - @solana/wallet-adapter-bitpie@0.5.1
 - @solana/wallet-adapter-blocto@0.5.1
 - @solana/wallet-adapter-clover@0.4.1
 - @solana/wallet-adapter-coin98@0.5.1
 - @solana/wallet-adapter-coinhub@0.3.1
 - @solana/wallet-adapter-ledger@0.9.1
 - @solana/wallet-adapter-mathwallet@0.9.1
 - @solana/wallet-adapter-phantom@0.9.1
 - @solana/wallet-adapter-safepal@0.5.1
 - @solana/wallet-adapter-slope@0.5.1
 - @solana/wallet-adapter-solflare@0.6.1
 - @solana/wallet-adapter-sollet@0.10.2
 - @solana/wallet-adapter-solong@0.9.1
 - @solana/wallet-adapter-tokenpocket@0.4.1
 - @solana/wallet-adapter-torus@0.11.2
 - @solana/wallet-adapter-wallets@0.14.1

**Comment by akutruff** [comment]
Worked like a charm!  Thanks so much to both of you. =D

**Comment by jordansexton** [comment]
@zhangxiaoshang this is probably because `yarn create next-app` is using the latest version of Next (v12) which isn't supported yet. See #246

**Comment by zhangxiaoshang** [comment]
> 

yes, when I use `"next": "11.0.0"`, It works.

**Comment by arthurbolsoni** [comment]
still no working with default create-react-app
