### ISSUE TITLE
Cannot verify Wallet signed messages (JS) using Solana-py (Python)

### ISSUE THREAD

**Issue by AnderUstarroz** [solana-labs/wallet-adapter#243]
**Describe the bug**
Signed  messages (JS) cannot be verified using Solana-py (Python)

**To Reproduce**
Sign a message using [Solana's wallet adapter example](https://github.com/solana-labs/wallet-adapter/blob/master/FAQ.md#how-can-i-sign-and-verify-messages):

```
import { useWallet } from '@solana/wallet-adapter-react';
import bs58 from 'bs58';
import React, { FC, useCallback } from 'react';
import { sign } from 'tweetnacl';

export const SignMessageButton: FC = () => {
    const { publicKey, signMessage } = useWallet();

    const onClick = useCallback(async () => {
        try {
            // `publicKey` will be null if the wallet isn't connected
            if (!publicKey) throw new Error('Wallet not connected!');
            // `signMessage` will be undefined if the wallet doesn't support it
            if (!signMessage) throw new Error('Wallet does not support message signing!');

            // Encode anything as bytes
            const message = new TextEncoder().encode('Hello, world!');
            // Sign the bytes using the wallet
            const signature = await signMessage(message);
            // Verify that the bytes were signed using the private key that matches the known public key
            if (!sign.detached.verify(message, signature, publicKey.toBytes())) throw new Error('Invalid signature!');

            alert(`Message signature: ${bs58.encode(signature)}`);
        } catch (error: any) {
            alert(`Signing failed: ${error?.message}`);
        }
    }, [publicKey, signMessage]);

    return signMessage ? (<button onClick={onClick} disabled={!publicKey}>Sign Message</button>) : null;
};

````
Try to  verify the signed message using [PyNaCl](https://pypi.org/project/PyNaCl/) and [Solana-py](https://michaelhly.github.io/solana-py/):

```
from nacl.signing import VerifyKey
from solana.publickey import PublicKey

result = VerifyKey(bytes(PublicKey("HERE_THE_PUB_KEY"))
  ).verify(
    smessage=bytes("HERE_THE_MESSAGE", "utf8"),
    signature=bytes("HERE_THE_SIGNATURE", "utf8"),
)
```
But verification returns: `nacl.exceptions.BadSignatureError: Signature was forged or corrupt.`

**Expected behavior**
The verification should be successful, same way as when using `sign.detached.verify()` in JS.

**Actual behavior**
The verification  throws: `nacl.exceptions.BadSignatureError: Signature was forged or corrupt.`

**Comment by AnderUstarroz** [comment]
Maybe is because the encoding in Python is different? In JS the bytes have the following types:
```
Pubkey:  Uint8Array(32) [144, 188, 240, ...
Message: Uint8Array(44) [57,   85,  65, ...
Signed:  Uint8Array(64) [82,  220, 242, ...
```
And in python:
```
Pubkey:  <class 'bytes'> b'\x90\xbc\xf...'
Message: <class 'bytes'> b'9UA...'
Signed:  <class 'bytes'> b'2f68j5...'

```

**Comment by jordansexton** [comment]
This sounds like it's either an issue with Solana-py, which I'm not familiar with, or an individual wallet's implementation of signing? Unless there's a fix that can be made to this repo, I kindly propose closing this issue and raising it where it can be fixed.

**Comment by AnderUstarroz** [comment]
Not a wallet adapter issue

**Comment by vmpyre** [comment]
Hi, were you able to solve the issue and verify the signed message with python? If yes, could you help point me to the right direction.

**Comment by CrackerHax** [comment]
Did you try without bytes()? Try with just a normal string.

**Comment by crypt0miester** [comment]
anyone still looking for an answer here you guys go:

python:
https://gist.github.com/crypt0miester/6d4743403705f7c93de68d97d5d29b6f

js:
https://gist.github.com/crypt0miester/ce0d10100aefa4e7352664b2de34df14
