### ISSUE TITLE
AnchorWallet type not compatible with Anchor provider class

### ISSUE THREAD

**Issue by Findiglay** [solana-labs/wallet-adapter#244]
`useAnchorWallet` [defines its own](https://github.com/solana-labs/wallet-adapter/blob/7e950ad07ce9cab6c3bfc570ab3ba251f3cfb7a2/packages/core/react/src/useAnchorWallet.ts#L11) wallet type `AnchorWallet` which is incompatible with the `Wallet` type [defined in anchor](https://github.com/project-serum/anchor/blob/e026e9e8741fdd17117570a9d54be58fefda8230/ts/src/provider.ts#L223). 

In addition, `undefined` will not be accepted.

See related issue here: https://github.com/project-serum/anchor/pull/1122#issuecomment-1004941422

Perhaps it makes more sense for this hook to exist as an example? Otherwise, will require adding anchor as a dependency in order to import the correct type.

**Comment by jordansexton** [comment]
Sorry, how is this not compatible?

https://github.com/project-serum/anchor/blob/e026e9e8741fdd17117570a9d54be58fefda8230/ts/src/provider.ts#L223-L227

https://github.com/solana-labs/wallet-adapter/blob/7e950ad07ce9cab6c3bfc570ab3ba251f3cfb7a2/packages/core/react/src/useAnchorWallet.ts#L5-L9

These interfaces look the same to me.

**Comment by jordansexton** [comment]
As for the hook, when a wallet is not connected, `publicKey` will be `null`. The hook therefore returns `AnchorWallet | undefined` because `AnchorWallet` requires that `publicKey` is a `PublicKey`. This is really a workaround for Anchor's type being more strict and assuming the existence of the key.

**Comment by Findiglay** [comment]
@jordansexton sorry "compatible" not the correct way to describe this, but the interfaces are different so means type error, since anchor wallet type is not currently exportable.

**Comment by smart2021codedev** [comment]
@jordansexton I have a progem.
When I use the custom program in Anchor framework, How to sign the tx using Phantom wallet?

**Comment by jordansexton** [comment]
@smart2021codedev GitHub issues aren't for general support questions. Please try the Anchor Discord or #developer-support on the Solana Discord.

**Comment by mindell** [comment]
> @jordansexton sorry "compatible" not the correct way to describe this, but the interfaces are different so means type error, since anchor wallet type is not currently exportable.

hi, did you solve this? i also encountered this issue [https://github.com/solana-labs/wallet-adapter/issues/331](https://github.com/solana-labs/wallet-adapter/issues/331)  and still trying to solve it.

**Comment by mindell** [comment]
> 

hi, did you solve this? i also encountered this issue [https://github.com/solana-labs/wallet-adapter/issues/331](https://github.com/solana-labs/wallet-adapter/issues/331) and still trying to solve it.

**Comment by ved08** [comment]
hey @Findiglay how did you solve this issue?
