### ISSUE TITLE
Type error: Module '"@solana/wallet-adapter-wallets"' has no exported member 'LedgerWalletAdapter'. 

### ISSUE THREAD

**Issue by Aysel9** [solana-labs/wallet-adapter#251]
import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';                                                                                                                
  3 | import {                                                                                                                                                                                          
> 4 |     LedgerWalletAdapter,                                                                                                                                                                          
    |     ^                                                                                                                                                                                             
  5 |     PhantomWalletAdapter,                                                                                                                                                                         
  6 |     SlopeWalletAdapter,                                                                                                                                                                           
  7 |     SolflareWalletAdapter,

**Comment by jordansexton** [comment]
Sorry, there isn't enough context to understand this issue. That's what the bug report issue template is for. Please fill it out instead of deleting it next time.
