### ISSUE TITLE
Type error: Property 'WalletConnectionProvider' does not exist on type 'typeof import("C:/Users/user/Desktop/wallet-adapter/packages/starter/nextjs-starter/components/WalletConnectionProvider")'.

### ISSUE THREAD

**Issue by Aysel9** [solana-labs/wallet-adapter#252]
() =>                                                                                                                                                                                        
  12 |         import('../components/WalletConnectionProvider').then(                                                                                                                                   
> 13 |             ({ WalletConnectionProvider }) => WalletConnectionProvider                                                                                                                           
     |                ^                                                                                                                                                                                 
  14 |         ),                                                                                                                                                                                       
  15 |     {

**Comment by jordansexton** [comment]
Sorry, there isn't enough context to understand this issue. That's what the bug report issue template is for. Please fill it out instead of deleting it next time.
