### ISSUE TITLE
Transaction too large error - using the latest wallet adapter

### ISSUE THREAD

**Issue by kirksgithub** [solana-labs/wallet-adapter#255]
**Describe the bug**

Using the latest wallet adapter I am having the following error (Slope/Solflare):
"WalletProvider.tsx:153 WalletSendTransactionError: Transaction too large: 1288 > 1232"

Phantom:
inpage.js:315 Phantom - RPC Error: Transaction creation failed. {code: -32003, message: 'Transaction creation failed.'}

The snippet of my code is the following (this is using ORCA swap https://github.com/orca-so/typescript-sdk):
```
                const tokenPairA = tokenPoolA.getTokenB(); // USDC
                const tokenAmount = new Decimal(amountToSwap); // amount in USDC
                const quote = await tokenPoolA.getQuote(tokenPairA, tokenAmount);
                const convertedAmount = quote.getMinOutputAmount();
                const swapPayload = await tokenPoolA.swap(publicKey, tokenPairA, tokenAmount, convertedAmount);
                swapPayload.transaction.partialSign(...swapPayload.signers);
                 const signedTransaction = await sendTransaction(swapPayload.transaction, connection);
                await connection.confirmTransaction(signedTransaction, 'processed');
```
Previous wallet adapter this worked fine:
```
    "@solana/wallet-adapter-base": "^0.7.0",
    "@solana/wallet-adapter-react": "^0.13.1",
    "@solana/wallet-adapter-react-ui": "^0.6.1",
    "@solana/wallet-adapter-wallets": "^0.11.3",
```
Wallet Adapter used:
```
    "@solana/wallet-adapter-base": "^0.9.1",
    "@solana/wallet-adapter-react": "^0.15.1",
    "@solana/wallet-adapter-react-ui": "^0.9.2",
    "@solana/wallet-adapter-wallets": "^0.14.1",
```
               
I do believe that this may be caused by the partial sign - any feedback would be much appreciated

**Comment by jordansexton** [comment]
Could you link a repo with a reproduction? Happy to take a look at this.

**Comment by kirksgithub** [comment]
Thanks alot for the super quick response just uploaded it

Full code for this is here:
https://github.com/Grape-Labs/OrcaSwap/blob/main/OrcaSwap.tsx

call would be:
`<OrcaSwap swapfrom={"USDC"} swapto={"GRAPE"} portfolioPositions={portfolioPositions} />`

variable for positions would be:
`let portfolioPositions = { "portfolio":[{"mint":"8upjSpvjcdpuzhfR1zriwg5NXkwDruejqNE9WNbPRtyA","symbol":"GRAPE","coingeckoId":"grape-2","balance":1,"price":0.053341,"value":0.053341,"tokenInfo":{"chainId":101,"address":"8upjSpvjcdpuzhfR1zriwg5NXkwDruejqNE9WNbPRtyA","symbol":"GRAPE","name":"Grape","decimals":6,"logoURI":"","extensions":{"coingeckoId":"grape-2","website":"https://grapes.network"}},"usd_24h_change":-2.61696938875755},{"mint":"So11111111111111111111111111111111111111112","balance":1,"price":141.94,"value":141.94,"tokenInfo":{"chainId":101,"address":"So11111111111111111111111111111111111111112","symbol":"SOL","name":"SOL","decimals":9,"logoURI":"","extensions":{"coingeckoId":"solana","serumV3Usdc":"9wFFyRfZBsuAha4YcuxcXLKwMxJR43S7fPfQLusDBzvT","serumV3Usdt":"HWHvQhFmJB3NUcu1aihKmrKegfVxBEHzwVX6yZCKEsi1","website":"https://solana.com/"}},"usd_24h_change":-3.1622724372417026}}] }`

**Comment by jordansexton** [comment]
Thanks for the response, but there's a lot going on in this code, and this repo is missing the entire project structure necessary to test this.

To spend time looking at this, I'll need to see an isolated piece of code that is runnable on its own and produces the issue.

**Comment by kirksgithub** [comment]
Jordan thanks again for taking the time, here is a full version of the specific implementation including the wallet adapter (same error):
https://github.com/Grape-Labs/orca-swap

**Comment by kirksgithub** [comment]
just a small update I downgraded my code (not the repo) - to the older wallet adapter - transactions not throwing that error and go through fine

**Comment by jordansexton** [comment]
These lines look suspicious:
```
                swapPayload.transaction.partialSign(...swapPayload.signers);

                const signedTransaction = await sendTransaction(swapPayload.transaction, connection);
```

You're partially signing a transaction without setting the recent blockhash or fee payer on it directly. I'm not sure if Orca's SDK sets these, but it needs to be done before signing or else the signature will change (and be invalid).

This is what `sendTransaction` is expected to do: https://github.com/solana-labs/wallet-adapter/blob/468815e6f6e722ca3e711f674c26a524f3ec921e/packages/core/base/src/signer.ts#L21-L29

Additionally, `sendTransaction` takes an options param which does partial signing:
https://github.com/solana-labs/wallet-adapter/blob/468815e6f6e722ca3e711f674c26a524f3ec921e/packages/core/base/src/adapter.ts#L14-L16

I would try just calling `sendTransaction(swapPayload.transaction, connection, { signers: swapPayload.signers })` to use this functionality, and don't partial sign first.

**Comment by kirksgithub** [comment]
Jordan I cannot thank you more for your recommendation! this works:
sendTransaction(swapPayload.transaction, connection, { signers: swapPayload.signers })
(no partial signing) - quite odd that this was not causing and issue before in the older wallet-adapter
