### ISSUE TITLE
Invalid hook call inside React app

### ISSUE THREAD

**Issue by k0beLeenders** [solana-labs/wallet-adapter#258]
**Describe the bug**
I'm trying to setup my existing react app with the wallet adapter but I keep encountering this error: 
```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```
when trying to setup the connection & wallet providers.

The error seems to occur in the `<ConnectionProvider>` component itself. It is inside a functional component (I took refrence from the readme) and it doesn't matter where I apply the provider (toplevel & somewhere inside the app) it keeps throwing this error leading me to believe the issue comes from the package itself. Also if I temporarly remove the `<ConnectionProvider>` it throws the exact same error but then from the `<WalletProvider>` component.

**Screenshots**
![image](https://user-images.githubusercontent.com/32452483/149123597-6aa0dd31-6803-495e-9d43-15720e04cc5f.png)

**Additional context**
 "react": "^16.13.1",
 "react-dom": "^16.13.1",
 "typescript": "^4.2.4",
 "@solana/wallet-adapter-base": "^0.9.2",
 "@solana/wallet-adapter-react": "^0.15.2",
 "@solana/wallet-adapter-react-ui": "^0.9.3",
 "@solana/wallet-adapter-wallets": "^0.14.2",

````
import React, { FC, ReactNode, useCallback, useMemo } from 'react'
import { WalletAdapterNetwork, WalletError } from '@solana/wallet-adapter-base'
import {
  ConnectionProvider,
  WalletProvider,
} from '@solana/wallet-adapter-react'
import { WalletModalProvider as ReactUIWalletModalProvider } from '@solana/wallet-adapter-react-ui'
import {
  LedgerWalletAdapter,
  PhantomWalletAdapter,
  SlopeWalletAdapter,
  SolflareWalletAdapter,
  SolletExtensionWalletAdapter,
  SolletWalletAdapter,
  TorusWalletAdapter,
} from '@solana/wallet-adapter-wallets'
import { clusterApiUrl } from '@solana/web3.js'
import { useAutoConnect } from './autoConnectProvider'

const WalletContextProvider: FC<{ children: ReactNode }> = ({ children }) => {
  const { autoConnect } = useAutoConnect()

  const network = WalletAdapterNetwork.Devnet

  const endpoint = useMemo(() => clusterApiUrl(network), [network])

  const wallets = useMemo(
    () => [
      new PhantomWalletAdapter(),
      new SlopeWalletAdapter(),
      new SolflareWalletAdapter(),
      new TorusWalletAdapter(),
      new LedgerWalletAdapter(),
      new SolletWalletAdapter({ network }),
      new SolletExtensionWalletAdapter({ network }),
    ],
    [network],
  )
  return (
    <ConnectionProvider endpoint={endpoint}>
      <WalletProvider wallets={wallets} autoConnect={autoConnect}>
        <ReactUIWalletModalProvider>{children}</ReactUIWalletModalProvider>
      </WalletProvider>
    </ConnectionProvider>
  )
}

export const ContextProvider: FC<{ children: ReactNode }> = ({ children }) => {
  return <WalletContextProvider>{children}</WalletContextProvider>
}
```

**Comment by jordansexton** [comment]
I closed this because this isn't a bug with the library. But if you want to link a full repo that reproduces the issue, I'm happy to take a look.

**Comment by k0beLeenders** [comment]
I'm not calling useWallet from a component, I've traced the bug and it comes from inside the library.

I downgraded the library a few releases back and it works perfectly with the exact same code.
