### ISSUE TITLE
On wallet selection, show connect popup immediately as before

### ISSUE THREAD

**Issue by heldrida** [solana-labs/wallet-adapter#260]
**Is your feature request related to a problem? Please describe.**
Yes, in the previous version on Wallet selection the popup connect would show to the enduser.
From the latest version, that is NOT the case and the user has to: Select Wallet -> Connect Wallet.
In my opinion, that's bad UX. What else could the user do? Why does the user have to click to Connect?
Can't that be simplified, as the previous version?

```
    "@solana/wallet-adapter-base": "^0.7.0",
    "@solana/wallet-adapter-react": "^0.13.0",
    "@solana/wallet-adapter-react-ui": "^0.6.0",
    "@solana/wallet-adapter-wallets": "^0.11.3",
    "@solana/web3.js": "^1.31.0",
```

**Describe the solution you'd like**
On wallet selection, the popup connect should be displayed as before, there's no need for another click.
I understand there's `autoconnect`, but that will show a popup to connect when the application launches,
which is also not the greatest user experience.

**Describe alternatives you've considered**
Bring back the flow, the previous version add.

**Comment by heldrida** [comment]
Maybe there's an option to do so, as I suggest but does not seem to be documented. Let know otherwise!

The current version were this was tested and is happening, and is not nice at all is:

```
    "@solana/wallet-adapter-base": "^0.9.2",
    "@solana/wallet-adapter-react": "^0.15.2",
    "@solana/wallet-adapter-react-ui": "^0.9.3",
    "@solana/wallet-adapter-wallets": "^0.14.2",
    "@solana/web3.js": "^1.31.0",
```

**Comment by jordansexton** [comment]
AutoConnect will only show a popup to the user initially if the user has previously connected.

It sounds like what you want is --

1. `autoConnect = false` (this is the default, so just don't pass `autoConnect` to the provider)
2. Call `select()` so the user selects the wallet.
3. Add a `useEffect(...)` so that when the selected wallet changes, you call `connect()`

This should be doable right now in your code without any change to the library. Does this make sense?

**Comment by heldrida** [comment]
@jordansexton yes it does and will work! Thank you!

**Comment by jordansexton** [comment]
Something like this should work to auto connect only when a wallet is manually selected and ready:

```tsx
const { name, connect, readyState } = useWallet();
const [selected, setSelected] = useState(name);

useEffect(() => {
    // Make sure we only connect if the name has changed, and don't autoconnect on the initial render
    if (name === selected) return;
    setSelected(name);

    if (name && readyState === WalletReadyState.Installed || readyState === WalletReadyState.Loadable) {
        connect().catch(() => {}); // Ignore this error because it'll be handled by the provider
    }

    // We don't need to worry about disconnecting if this changes, the provider handles that
}, [name, selected, readyState]);

// ...

return <WalletModalButton/>;
```

**Comment by heldrida** [comment]
@jordansexton appreciate the time you took to provide feedback. I did something like what you have suggested, although for `select`, used the default `WalletMultiButton`, as the selection requires to pass the wallet name I believe.

Although the approach you shared provides a bit more control and will use it as a reference. Sure other people will find this valuable too, thank you very much!
