### ISSUE TITLE
Is there a way to invoke the dialog without using the UI?

### ISSUE THREAD

**Issue by zkhalapyan** [solana-labs/wallet-adapter#271]
**Is your feature request related to a problem? Please describe.**
I am building my own UI style, but still want to use the adapter's modal dialog for selecting a wallet. 

**Describe the solution you'd like**
Provide API for invoking the wallet selector via JS/TS. 

**Describe alternatives you've considered**
I can use your UI but it doesn't fit into my website's style.

**Comment by jordansexton** [comment]
Sorry, this request doesn't make sense to me. How do you envision being able to open the dialog, which is itself a UI component, without using the dialog's user interface, at a minimum?

There's a lot of custom logic in how the wallet ready states are used to intelligently filter the wallets shown to the user.

What I would recommend is using the react-ui package and overriding the styles (`wallet-adapter-` namespaced classnames are provided for most of the components in it so this is easy to do.

If you really need to customize it beyond what you can do with CSS, just fork that package.

**Comment by zkhalapyan** [comment]
Thanks, let me see if I can clarify. I do want to use the modal selector, but invoke it with my own button if that makes sense. 

![Screen Shot 2022-01-19 at 1 58 38 PM](https://user-images.githubusercontent.com/796815/150220761-baedc51b-6693-4c5d-b47e-3c6dbeca16e8.png)

**Comment by jordansexton** [comment]
Oh, that's easy then. Just do what the button does and call `setVisible(true)` from `const { setModal } = useWalletModal()`

**Comment by jordansexton** [comment]
But by the same token, can't you just the connect buttons provided and then style them?

**Comment by zkhalapyan** [comment]
Worry is that customization means using class specificity to override some properties, but not all; it's not a future proof solution — future styles added to `wallet-adapter-button` will need to be manually overridden 😢. Similar discussion here: https://github.com/solana-labs/wallet-adapter/issues/155

Interestingly, don't think there is a way I can say, "clear all styles from wallet-adapter-button class, and add my own instead" — if you have a clever solution, would be curious to hear 🙂

I think the best solution here is to come up with my own Button component and use the APIs directly.

**Comment by jordansexton** [comment]
You know you can just not import the styles?

**Comment by jordansexton** [comment]
Don't need to clear the styles if you never use them. 😉

**Comment by zkhalapyan** [comment]
I just need to customize the button's style, not the entire modal flow, if that makes sense. For example, if I don't import `@solana/wallet-adapter-react-ui/styles.css`, need will need to style everything; in my case, just want to make the button layer different, but keep the rest the same. 

Now would be cool to say, import `@solana/wallet-adapter-react-ui/styles.css` except `wallet-adapter-button` 😛

**Comment by jordansexton** [comment]
I'm not sure I understand the issue. Overriding styles with higher specificity is literally in the name for CSS. If you have an alternative proposal, please open a PR!

**Comment by zkhalapyan** [comment]
Might not be explaining correctly. Here is a specific example: 

```CSS
// @solana/wallet-adapter-react-ui/styles.css 
.wallet-adapter-button {
   color: white;
}
```

```CSS
// my copy with additional specificity
.wallet-adapter-button {
   color: white !important;
}
```

The problem I was trying to point out is that this solution is fragile and could break in the future in case `styles.css` adds additional attributes `.wallet-adapter-button` that I am not overriding in my own copy i.e. 

```CSS
// @solana/wallet-adapter-react-ui/styles.css  (V2)
.wallet-adapter-button {
   color: white;
   background-color: #021289;
}
```

Here `background-color` will get shipped as a break in my app, without us knowing other than through visual inspection. 

Not a big deal, I think just writing my own button and using the API directly was the right solution to avoid this; thanks for helping out! 🙂
