### ISSUE TITLE
How can i use wallet adapter in svelte

### ISSUE THREAD

**Issue by areb0s** [solana-labs/wallet-adapter#278]
Is there a way to use wallet-adapter in svelte? I don't think I can use the svelte-store that I have now.

**Comment by jordansexton** [comment]
Ah, it hasn't been published yet, so it's not ready for use. There have been some changes to the base package since the svelte package was written and it just needs to be updated a bit, but the maintainers of that package have been busy. It may take a few weeks to pick that work up.

**Comment by areb0s** [comment]
>

**Comment by areb0s** [comment]
Thx for reply. i hope it comes out as soon as possible.

**Comment by jordansexton** [comment]
@silvestrevivo @cogoo is there a published unofficial package that people can use now?

**Comment by jordansexton** [comment]
An important caveat is that the latest versions of the official packages likely won't work with a previously published version of a Svelte package because of the breaking changes.

**Comment by areb0s** [comment]
build completed in svelte, window.solana as a variable in the onMount lifecycle results in undefinded, do you know why?
 When i checked on dev (npm run dev) There's no problem
![image](https://user-images.githubusercontent.com/33321699/150357647-db2d8ba6-cacc-40b9-81b2-cbc5cae71826.png)

**Comment by jordansexton** [comment]
Sorry, we can't provide help with general support questions. Because the Svelte package isn't published, it's also not supported yet.

**Comment by jordansexton** [comment]
Closing this, but please subscribe to #162 if you want to track progress with Svelte.

**Comment by areb0s** [comment]
Thx!!
