### ISSUE TITLE
Token transfer transaction detail "Amount" missing

### ISSUE THREAD

**Issue by tolui** [solana-labs/wallet-adapter#281]
**Describe the bug**
Token transfer instruction displayed without amount and gives warning message "Transaction may fail to confirm". 
This transaction well displayed on Sollet adapter
I am using following versions of libraries
"@solana/wallet-adapter-base": "^0.9.2",
"@solana/wallet-adapter-wallets": "^0.14.2",
"@solana/wallet-adapter-phantom": "0.9.2",

**To Reproduce**
Constructed Token transfer instruction using  "@solana/spl-token": "^0.1.8"
sign and execute on phantom adapter

**Expected behavior**
It should be display token transaction information correct

**Screenshots**
![image](https://user-images.githubusercontent.com/10773668/150480744-ebf55e20-abc4-49f1-ab75-3a11443a00a4.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jordansexton** [comment]
Sorry, this isn't a bug with WalletAdapter. This library doesn't have anything to do with how wallets choose to display transaction details. If you believe there's an issue with Phantom, please contact them. :)

**Comment by tolui** [comment]
@jordansexton Ok thank you
