### ISSUE TITLE
Wallet Detection for Mobile Wallets

### ISSUE THREAD

**Issue by everythingspirals** [solana-labs/wallet-adapter#282]
**Describe the bug**
On the browser, this package is able to detect which wallets the user has installed and show only those. On mobile however it does not show them (SolFlare, Slope, etc). I assume this is because it is difficult to detect which mobile apps are installed.

**To Reproduce**
1. Test any app using this plugin on web vs mobile.

**Expected behavior**
Wallets installed on the phone should appear.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Version 1.34.80

**Smartphone (please complete the following information):**
 - Device: Samsung S20
 - OS: Android 10
 - Browser Brave
 - Version 1.34.80

**Comment by PatrykXDD** [comment]
I do not think any phone browsers have the permissions to see your installed apps. All mobile wallets that work to mint right now have their own built-in browser to their app.

**Comment by jordansexton** [comment]
> I do not think any phone browsers have the permissions to see your installed apps.

This is correct.

Ways for wallets and dapps to communicate are being worked on, but are outside the current scope of this library.

Closing this issue as it isn't a bug, but if you have thoughts on specific mechanisms that could help accomplish what you want, please do comment.
