### ISSUE TITLE
Wiring redirect if wallet is not connected — should connected default be true? 

### ISSUE THREAD

**Issue by zkhalapyan** [solana-labs/wallet-adapter#294]
I have a react/next page where if the user is not connected to a wallet, I need to redirect them to the wallet login page. Currently, once I detected `!(connecting || connected)`, I redirect, but if you trace out the logs, you can see that on initial render both are false. 

It's hard to determine the difference between "state has been set and public key wasn't found" vs. "just initializing, haven't tried to read public value".

Should `connecting` be set to true by default?

```JS
const { connecting, connected, publicKey } = useWallet();
const router = useRouter();

// If the wallet is neither connecting nor connected, redirect the user to login page. 
useEffect(() => {
  console.log(`connecting: ${connecting}, connected: ${connected}, public key: ${publicKey}`)
  if (!(connecting || connected)) {
    // router.push("/")
    console.log("redirect")
  }
}, [connected, publicKey, connecting, router]);
```

```
connecting: false, connected: false, public key: null
redirect
connecting: true, connected: false, public key: null
connecting: true, connected: true, public key: 6zsuBDfuvtxK5FD9tf8u8LfrYBVnxDWRhj43snmC6Qx6
Initialized a Wonka with candy machine ID: Hkunn4hct84zSPNpyQygThUKn8RUBVf5b4r975NRaHPb.
connecting: false, connected: true, public key: 6zsuBDfuvtxK5FD9tf8u8LfrYBVnxDWRhj43snmC6Qx6
```

**Comment by zkhalapyan** [comment]
We can hack around it with `setTimeout(..)` and `useRef(..)`, but it's pretty fragile.
```
const { connecting, connected } = useWallet();
const connectingRef = useRef(connecting);
connectingRef.current = connecting
const connectedRef = useRef(connected);
connectedRef.current = connected

useEffect(() => {
  setTimeout(() => {
    checkWallet()
  }, 100)
}, [connected, publicKey, connecting, router]);

function checkWallet() {
  console.log(`connecting: ${connectingRef.current}, connected: ${ connectedRef.current}`)
  if (!(connectingRef.current || connectedRef.current)) {
    console.log("redirect")
  }
}
```

**Comment by jordansexton** [comment]
This is expected behavior. On the initial render, the state is never connected or connecting because there isn't necessarily anything to connect to.

Often wallets aren't available immediately on the window object at initial render or they must be loaded asynchronously -- see some of the adapters for the complicated polling/loading/ready state logic involved.

Anyway, this isn't a bug, and I also wouldn't rely on timeouts for this. There is no way to predict (in 100ms or at any time, really) whether a browser wallet will eventually be connected if you can't find that wallet on the window object.

**Comment by jordansexton** [comment]
Hmm, it's a good question. If the user has previously connected, the `name` property in the context should be set from LocalStorage. In the unlikely event that the user no longer has that wallet it could be unsafe to rely on, but could be useful?

**Comment by zkhalapyan** [comment]
Using `name` seems a bit fragile — it's peeking through implementation detail (`localStorage`) and could break easily if the underlying assumptions change. 

What if there is some `loading` flag? `true` if we're still trying to look for the wallet, `false` if we looked for the wallet and it's not connected/not present/not-detected. 

Or maybe a `useWalletDetected()` hook, that could wrap this logic.

**Comment by jordansexton** [comment]
Unfortunately that would add another kind of fragility. I think https://github.com/solana-labs/wallet-adapter/issues/215 is the ideal solution for reliable detection, but it does away with any notion of loading or polling for browser extension wallets, and I think wouldn't help with your use case.

**Comment by jordansexton** [comment]
I think one way you could do this is to record the public key of the user in LocalStorage if they connected and clear it on disconnect. Then if it's found, treat the user as "logged in", while trying to find the wallet. Once you need them to sign, you hard fail if they aren't actually connected.

**Comment by zkhalapyan** [comment]
Ah, I see; that's probably a decent solution to go with right now, thank you!
