### ISSUE TITLE
Latest version of `wallet-adapter-wallets` breaks when trying to compile `wallet-adapter-torus`

### ISSUE THREAD

**Issue by TomLisankie** [solana-labs/wallet-adapter#302]
**Describe the bug**
The latest version of the `wallet-adapter-torus` seems to not compile due to an issue very similar to #241. The error I get states

```
ERROR in ../../node_modules/cipher-base/index.js 3:16-43
Module not found: Error: Can't resolve 'stream' in '/opt/ui/node_modules/cipher-base'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
```

And then the trace as to where it comes from:

```
@ ../../node_modules/@toruslabs/base-controllers/dist/baseControllers.esm.js 5:0-142 939:15-25 940:15-25 941:15-26 942:29-39 943:29-39 944:15-29 945:9-21 1034:13-32 1040:18-32 1041:17-23 1042:30-41
@ ../../node_modules/@toruslabs/solana-embed/dist/solanaEmbed.esm.js 3:0-173 362:19-41 614:21-62 624:28-69 631:28-68 633:28-70 639:28-71 686:16-61 730:14-54 739:16-56 802:14-54 1029:21-60 1031:28-71 1033:28-64 1065:16-56 1411:38-77 1586:14-47 1634:14-53 1642:14-59 1667:14-50 1680:14-46
@ ../../node_modules/@solana/wallet-adapter-torus/lib/esm/adapter.mjs 38:35-68
@ ../../node_modules/@solana/wallet-adapter-torus/lib/esm/index.mjs 1:0-30 1:0-30
 @ ../../node_modules/@solana/wallet-adapter-wallets/lib/esm/index.mjs 16:0-45 16:0-45
@ ./components/SolanaWalletConnectionProvider/SolanaWalletConnectionProvider.tsx 5:0-121 21:16-36 21:44-63 23:12-40
```

**To Reproduce**
Import from `@solana/wallet-adapter-wallets` like 

```
import {
  getPhantomWallet,
  getSolletExtensionWallet,
  getSolletWallet,
} from '@solana/wallet-adapter-wallets';
```

**Expected behavior**
I expect it to compile without any errors.

**Desktop (please complete the following information):**
 - OS: On macOS but running in a Linux Docker container
 - Browser: Brave / Chrome / Safari

**Additional context**
We are trying to add Solana integration to one of our products and the continued bugs that seem to come from Webpack 5 usage and this repo seem to keep coming up. I know that this bug is upstream in some other repos that this repo relies on, but I figured this would be a good starting point.

**Comment by jordansexton** [comment]
Can you see if https://github.com/solana-labs/wallet-adapter/issues/241#issuecomment-1030957797 helps?

If you're using Webpack 5, you'll need to add the config and `process` dependency described there.

**Comment by TomLisankie** [comment]
> Can you see if [#241 (comment)](https://github.com/solana-labs/wallet-adapter/issues/241#issuecomment-1030957797) helps?
> 
> If you're using Webpack 5, you'll need to add the config and `process` dependency described there.

Yes, I added those and I'm still getting the same issues. Is there anything else I have to do than just add that config file and add that dependency?

**Comment by jordansexton** [comment]
It would help to see your entire project as a repo that reproduces the issue.

**Comment by TomLisankie** [comment]
> It would help to see your entire project as a repo that reproduces the issue.

Unfortunately I can't do that because it's a private repo and owned by the company that I work for.

**Comment by jordansexton** [comment]
I'm afraid I can't help much then. If you decide you're open to sharing it privately, feel free to invite me.

Besides that, I would recommend trying to build the create-react-app-starter project first. If that works, introduce changes and see what breaks?

**Comment by TomLisankie** [comment]
> I'm afraid I can't help much then. If you decide you're open to sharing it privately, feel free to invite me.

Unfortunately it's not my decision to make, otherwise I would.

> Besides that, I would recommend trying to build the create-react-app-starter project first. If that works, introduce changes and see what breaks?

Will try this.

I appreciate your time.

**Comment by jordansexton** [comment]
No problem. At a higher level I recommend using Parcel or Next.js or esbuild instead. It's very easy to switch, you don't have to deal with the Webpack 5 opinionated errors, and you get MUCH faster builds (thanks to Rust-based tooling).

**Comment by jordansexton** [comment]
Closing as I can't replicate, but please follow up if you narrow down the problem.

**Comment by Ajayneueworld** [comment]
I am using esbuild and got this error, Not very different from webpack error and most important fact is that I got this after installing -->  yarn add @solana/wallet-adapter-base \
         @solana/wallet-adapter-react \
         @solana/wallet-adapter-react-ui \
         @solana/wallet-adapter-wallets \
         @solana/web3.js \
         react

$ NODE_ENV=production node builder.js
 > node_modules/cipher-base/index.js:2:24: error: Could not resolve "stream" (use "platform: 'node'" when building for node)
    2 │ var Transform = require('stream').Transform
      ╵                         ~~~~~~~~

/home/aduttya/Documents/my-app/node_modules/esbuild/lib/main.js:1478
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/cipher-base/index.js:2:24: error: Could not resolve "stream" (use "platform: 'node'" when building for node)
    at failureErrorWithLog (/home/aduttya/Documents/my-app/node_modules/esbuild/lib/main.js:1478:15)
    at /home/aduttya/Documents/my-app/node_modules/esbuild/lib/main.js:1136:28
    at runOnEndCallbacks (/home/aduttya/Documents/my-app/node_modules/esbuild/lib/main.js:1054:65)
    at buildResponseToResult (/home/aduttya/Documents/my-app/node_modules/esbuild/lib/main.js:1134:7)
    at /home/aduttya/Documents/my-app/node_modules/esbuild/lib/main.js:1243:14
    at /home/aduttya/Documents/my-app/node_modules/esbuild/lib/main.js:614:9
    at handleIncomingPacket (/home/aduttya/Documents/my-app/node_modules/esbuild/lib/main.js:711:9)
    at Socket.readFromStdout (/home/aduttya/Documents/my-app/node_modules/esbuild/lib/main.js:581:7)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      location: {
        column: 24,
        file: 'node_modules/cipher-base/index.js',
        length: 8,
        line: 2,
        lineText: "var Transform = require('stream').Transform",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: `Could not resolve "stream" (use "platform: 'node'" when building for node)`
    }
  ],
  warnings: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jordansexton** [comment]
@Ajayneueworld please stop hijacking random issues, this is the second time today that you've done this. This issue has othing to do with what you are reporting.

Using esbuild and targeting Node makes no sense, this is a library is only meant to run in the browser. Please read the docs and use the starter projects provided.
