### ISSUE TITLE
Overrides directive in package.json causes build to fail

### ISSUE THREAD

**Issue by brainyapegang** [solana-labs/wallet-adapter#303]
**Describe the bug**
Fails to run `yarn build` on a clean repo due to dependency conflict

**To Reproduce**
1. Follow the installation guide up to `yarn build`.
2. Fails to build due to dependency conflict.

**Expected behavior**
Expected it to build cleanly.

**Solution/Workaround**
Remove `"buffer": "^6.0.3"` from `overrides` in packages/wallet/ledger/package.json

Remove 
```
"overrides": {
        "assert": "npm:assert@^2.0.0",
        "process": "npm:process@^0.11.10",
        "stream": "npm:stream-browserify@^3.0.0"
}
```
 in packages/wallet/torus/package.json

**Screenshots**
Ledger
<img width="837" alt="Screenshot 2022-02-08 at 7 13 20 PM" src="https://user-images.githubusercontent.com/96899207/152976503-bdad3fc5-191e-4ab3-9d3a-bf739d0aab65.png">

Torus
<img width="839" alt="Screenshot 2022-02-08 at 7 23 31 PM" src="https://user-images.githubusercontent.com/96899207/152977724-52b22212-8dc0-462c-b930-c166b4d6e52e.png">

**Desktop**
 - OS: macOS Catalina

**Comment by jordansexton** [comment]
Thanks for the report! Fixed in #305 and published in

 - @solana/wallet-adapter-ledger@0.9.8
 - @solana/wallet-adapter-torus@0.11.10
 - @solana/wallet-adapter-wallets@0.15.4
