### ISSUE TITLE
Setting `autoConnect` to false prevents login with `setVisible(true)`

### ISSUE THREAD

**Issue by zkhalapyan** [solana-labs/wallet-adapter#307]
**Describe the bug**
Setting `autoConnect` to false from `WalletProvider` prevents PhantonWallet from getting presented. Setting it to true, fixes it. 

**To Reproduce**

1. Set `autoConnect` to false. 
2. Set `isVisible(true)` 
3. Tap Phantom Wallet
4. See that nothing happened. 
Setup in a default Next.js example app.

**Expected behavior**
Should prompt the user to login; similar to when `autoConnect` is set to true. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome
 - Version: 98

**Additional context**
```
"@solana/wallet-adapter-base": "^0.9.3",
"@solana/wallet-adapter-react": "^0.15.2",
"@solana/wallet-adapter-react-ui": "^0.9.3",
"@solana/wallet-adapter-wallets": "^0.14.2",
```

Here is an example custom button I am building: 

```js
import { useWallet } from "@solana/wallet-adapter-react";
import { useWalletModal } from "@solana/wallet-adapter-react-ui";
import Button, { ButtonStyle } from "./Button";
import { useMemo } from "react";
import { truncateAddress } from "../utils/address-utils";

const WalletButton = () => {
  const { connected, publicKey, disconnect, select, connect } = useWallet();
  const { setVisible } = useWalletModal();
  const base58 = useMemo(() => publicKey?.toBase58(), [publicKey]);
  const walletName = useMemo(() => {
    if (base58) {
      return truncateAddress(base58);
    }
  }, [base58]);

  async function didTapWalletButton() {
    if (connected) {
      await navigator.clipboard.writeText(base58!);
      await disconnect()
    } else {
      setVisible(true);
    }
  }

  return (
    <Button
      title={walletName || "Connect Wallet"}
      didTapButton={didTapWalletButton}
      style={ButtonStyle.Small}
    />
  );
};

WalletButton.defaultProps = {};

export default WalletButton;
```

Here is the main wrapper inside `_app.tsx`

```JS
import { WalletAdapterNetwork } from "@solana/wallet-adapter-base";
import {
  ConnectionProvider,
  WalletProvider,
} from "@solana/wallet-adapter-react";
import { WalletModalProvider } from "@solana/wallet-adapter-react-ui";
import {
  LedgerWalletAdapter,
  PhantomWalletAdapter,
  SlopeWalletAdapter,
  SolflareWalletAdapter,
  SolletExtensionWalletAdapter,
  SolletWalletAdapter,
  TorusWalletAdapter,
} from "@solana/wallet-adapter-wallets";
import { clusterApiUrl } from "@solana/web3.js";
import { AppProps } from "next/app";
import { FC, useMemo } from "react";

require("@solana/wallet-adapter-react-ui/styles.css");
require("../styles/globals.css");

const App: FC<AppProps> = ({ Component, pageProps }) => {
  const network = WalletAdapterNetwork.Devnet;
  const endpoint = useMemo(() => clusterApiUrl(network), [network]);
  const wallets = useMemo(
    () => [
      new PhantomWalletAdapter(),
      new SolflareWalletAdapter(),
      new SlopeWalletAdapter(),
      new TorusWalletAdapter(),
      new LedgerWalletAdapter(),
      new SolletWalletAdapter({ network }),
      new SolletExtensionWalletAdapter({ network }),
    ],
    [network]
  );

  return (
    <>
      <ConnectionProvider endpoint={endpoint}>
        <WalletProvider wallets={wallets} autoConnect={false}>
          <WalletModalProvider>
            <Component {...pageProps} />
          </WalletModalProvider>
        </WalletProvider>
      </ConnectionProvider>
    </>
  );
};

export default App;
```

**Comment by jordansexton** [comment]
This isn't what autoConnect does. It's not related in any way to the modal being visible. Please check the code.

**Comment by jordansexton** [comment]
Related: https://github.com/solana-labs/wallet-adapter/issues/273#issuecomment-1017061229

If you don't set `autoConnect` (it's false by default) you are responsible for calling `connect` after the wallet is selected.

**Comment by jordansexton** [comment]
See implementation: https://github.com/solana-labs/wallet-adapter/blob/fd543782d9fed22c564855308216dacfc75c0c32/packages/core/react/src/WalletProvider.tsx#L99-L125

**Comment by scottwilson312** [comment]
hey @zkhalapyan did you figure out how to make phantom not auto-popup until the user clicks connect?

**Comment by zkhalapyan** [comment]
My guess is that it's from Phantom, not from wallet adapter. @jordansexton there isn't an eager connect logic built in, correct?

**Comment by jordansexton** [comment]
Please read the implementation 🙂 The auto connect functionality is more nuanced than most aspects of the React lib.

**Comment by zkhalapyan** [comment]
For context, the symptom that @scottwilson312  and I have are trying to debug is phantom wallet randomly/automatically popping up when the user comes back to the site after they have initially authenticated. 

Looking at the `autoConnect` use above, there are a lot of states being checked, so could be from this path. @scottwilson312  would fork this repo, place a breakpoint and see if you can debug this path. 

My question was if there is another code path **outside** of `autoConnect` that is responsible for eagerly connecting.

**Comment by scottwilson312** [comment]
Alrighty, so I got this working how I want with Phantom @zkhalapyan. Turning off autoConnect succesfully got rid of phantom  auto-popping up. However, the side effect of that is after you click Phantom from the list of wallets on the modal, the WalletMultiButton changes from "select wallet" to "connect", and the user needs to press the changed button to connect.

If you don't want the user to have to do the two clicks, you can grab `wallet` from the `useWallet` hook and throw that into a `useEffect` and call `connect when you see wallet become not-null.

However, if they have already selected Phantom and that's saved in localStorage, then we're back at the Popup problem. My solution was to extend WalletMultiButton, and set a global variable once they click for the first time, and only run the above stuff in `useEffect` if they've already clicked.

```import React, { Component, useMemo, useState, useEffect} from "react"
import { WalletModalProvider, WalletMultiButton, WalletConnectButton } from '@solana/wallet-adapter-react-ui';
import { useWallet } from '@solana/wallet-adapter-react';
import  Waves from "./assets/icons/Waves"
import {
    WalletReadyState,
} from '@solana/wallet-adapter-base';


require('@solana/wallet-adapter-react-ui/styles.css');


const WalletButton = (props) => {

  const { name, readyState, wallet, connect, connecting, connected } = useWallet();


  const content = useMemo(() => {
      if (connecting) return 'Connecting ...';
      if (connected) {
        props.cart.onWalletConnected()
        return 'Connected';
      }
      if (wallet) return 'Connect';
      return 'Connect Wallet';
  }, [connecting, connected, wallet]);

  useEffect(() => {
    if(wallet && window.CLICKED_WALLET){
      connect().catch(() => {}); // Ignore this error because it'll be handled by the provider
    } 
  }, [wallet]);


  return (
    <WalletMultiButton>
      <div className='button' onClick={()=>window.CLICKED_WALLET = true}>
        {content}
        <Waves/>
      </div>
    </WalletMultiButton>
  )

}

**Comment by jordansexton** [comment]
`window.CLICKED_WALLET = true`

![eyetwitch](https://user-images.githubusercontent.com/1173161/156071325-fe2b971d-bb6c-44d3-9ef2-5b883a0c8e52.gif)

**Comment by scottwilson312** [comment]
It's not meant to be pretty or an example of good code 🤣🤣🤣
