### ISSUE TITLE
Wallet Adapter of Phantom iOS app

### ISSUE THREAD

**Issue by saito-kosuke** [solana-labs/wallet-adapter#309]
**Is your feature request related to a problem? Please describe.**

When I try to connect wallet with `solana-labs/wallet-adapter` on the iOS smartphone, I can't start the Phantom iOS application.

**Describe the solution you'd like**

When I try to connect wallet with `solana-labs/wallet-adapter` on the iOS smartphone, I'd like to start the Phantom iOS application.

**Describe alternatives you've considered**

**Additional context**

**Comment by Pancrisp** [comment]
Are you trying to connect through a browser on your iPhone? The adapter only works when you are using the Phantom app's built-in dApp browser.
