### ISSUE TITLE
detect an existing wallet adapter button if available and use it

### ISSUE THREAD

**Issue by maninkari** [solana-labs/wallet-adapter#315]
Hi, 
First of all thank you for writing and maintaining this library. 
I am working on a widget that uses the multibutton component. The problem is that our widget will be used now within one of our clients' site that also uses a wallet-adapter multibutton. 

Is there a way to re-use or access the wallet-adapter instance of the containing site to avoid having visitors connecting twice to their wallets? what could be passed to our widget in this case? Is there an event that the widget could listen to?

Thank you!

**Comment by tyirenkyi** [comment]
In your client's site, you can check if a visitor has connected already with `useWallet()`. You can read more about it [here](https://solana-labs.github.io/wallet-adapter/modules/_solana_wallet_adapter_react.html#useWallet)

**Comment by jordansexton** [comment]
This really depends a lot on how your widget is being used on the page. For example, is it a child of the application's React WalletProvider context? What if the application doesn't use React? Is it running in an iframe?

Please check out the code, API docs, and Discord, but we don't provide support for applications on Github issues, which are only for library bugs and feature requests in scope.
