### ISSUE TITLE
Uncaught TypeError: wallets is undefined

### ISSUE THREAD

**Issue by lillichoung** [solana-labs/wallet-adapter#318]
**Describe the bug**
`Uncaught TypeError: wallets is undefined` error on opening the wallet modal (from connect wallet button)

**To Reproduce**

1) Wrap app in context providers as followed:

solana-wallet-provider:
```
export function SolanaWalletProvider({ children }) {
  const network = WalletAdapterNetwork.Devnet;
  const endpoint = useMemo(() => clusterApiUrl(network), [network]);

  const wallets = useMemo(
    () => [
        new PhantomWalletAdapter(),
        new LedgerWalletAdapter(),
    ],
    [network]
  );
  return (
    <ConnectionProvider endpoint={endpoint}>
        <WalletProvider wallets={wallets} autoConnect>
            <WalletModalProvider>
                {children}
            </WalletModalProvider>
        </WalletProvider>
    </ConnectionProvider>
  );  
}
```

App.js
```
const App = () => {
  return (
    <SolanaWalletProvider>
      <AppContainer />
    </SolanaWalletProvider>
  );
};
```

2) Create a component within the app that renders the wallet button
```
export const WalletButton = () => {
  return <WalletMultiButton />;
};
```

3) npm start, click on the wallet button

**Expected behavior**
Modal pops up

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version 97.0

**Comment by jordansexton** [comment]
Thanks. Can you link to a repo with a reproduction of the issue?

**Comment by lillichoung** [comment]
https://github.com/brianliyang/chainbay

**Comment by lillichoung** [comment]
I got it working, it probably was because i was on CRA4 due to this issue: https://github.com/facebook/create-react-app/issues/11756 
I upgraded to CRA5 and followed some of the mitigations in the thread above and am no longer getting this issue
