### ISSUE TITLE
Issue staying connected when using Link tag with Next js

### ISSUE THREAD

**Issue by nibbus0x** [solana-labs/wallet-adapter#324]
**Describe the bug**
When traversing to a different page of the application using a Next js `Link` tag the wallet disconnects from the site. However, the wallet stays connected when using an `a`. Is this something that is not implemented, or am I doing something wrong?

1. Run Next js application in development mode
1. Connect to wallet on the site
2. Click a link that redirects using a `Link` tag
3. Once the page loads the wallet will be disconnected

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 21.04
 -  - Browser: Brave
 - Version latest

**Comment by jordansexton** [comment]
This repo isn't the right place for general (or framework-specific) support questions, sorry.

The wallet context works just like any other React context. And if you're triggering a navigation away from a page, or reloading a page, the browser extension will disconnect.

**Comment by nibbus0x** [comment]
I appreciate the response, thank you.
