### ISSUE TITLE
Latest wallet adapters, don't detect solflare

### ISSUE THREAD

**Issue by heldrida** [solana-labs/wallet-adapter#329]
After installing latest versions of the packages, solflare is not detected, even though solflare is latest under brave.

**To Reproduce**

On Brave, latest Solflare at this date of writing 1.21

```
    "@solana/wallet-adapter-base": "^0.9.3",
    "@solana/wallet-adapter-react": "^0.15.3",
    "@solana/wallet-adapter-react-ui": "^0.9.5",
    "@solana/wallet-adapter-wallets": "^0.15.4",
    "@solana/web3.js": "^1.35.1",
```

**Expected behavior**
Expect to detect solflare

**Screenshots**
<img width="360" alt="Screenshot 2022-02-24 at 03 08 37" src="https://user-images.githubusercontent.com/236752/155450408-3e6bc428-b376-4ff9-96d8-e6ee976fac87.png">

<img width="376" alt="Screenshot 2022-02-24 at 03 08 04" src="https://user-images.githubusercontent.com/236752/155450330-963b23be-b2c7-4dbf-8b48-1612e6ef0fd2.png">

**Desktop (please complete the following information):**
 - OS: macos
 - Browser brave
 - Version V1.35.104 for Mac (Feb 23, 2022)

**Smartphone (please complete the following information):**
n/a

**Additional context**

Also, if choosing the solflare anyway, the following error is shown, which hints about phantom while the selected wallet is solflare

<img width="621" alt="Screenshot 2022-02-24 at 03 10 06" src="https://user-images.githubusercontent.com/236752/155450573-24a0acab-4959-4e0f-a52c-c53a08298563.png">

**Comment by vsakos** [comment]
@heldrida  I can not reproduce this (Mac, same version). Can you show us the code you're using, or a minimum working example?

![image](https://user-images.githubusercontent.com/3372353/156163957-e909f0e7-6f16-4f9f-acd2-e4c02fa83899.png)

**Comment by ktae13-npnf** [comment]
Hi @vsakos I also had this issue, and this is my code.
```
...
const wallets = useMemo(
    () => [
      new PhantomWalletAdapter(),
      new SolflareWalletAdapter({ network }),
      new SlopeWalletAdapter(),
      new TorusWalletAdapter(),
      new LedgerWalletAdapter(),
      new SolletWalletAdapter({ network }),
      new SolletExtensionWalletAdapter({ network }),
    ],
    [network],
  );
...
<ConnectionProvider endpoint={process.env.SOLANA_RPC_ENDPOINT}>
    <WalletProvider wallets={wallets} onError={onError} autoConnect>
        <WalletModalProvider>
        ...
        </WalletModalProvider>
    </WalletProvider>
</ConnectionProvider>
```

Any help would be great.

Thank you.

**Comment by alirezaayande** [comment]
#Hello_to_the_freedom_fighters_of_the_world
🪖 🚨 🇺🇦 Let us unite so that light triumphs over darkness 
Long live the united people of the free world Long live Ukraine🇺🇦
I am a young Iranian who wants to fight for peace and freedom🇺🇦🇺🇦🇺🇦🪖🚨

**Comment by alirezaayande** [comment]
Www.un.com @alirezaayande 🙏🇺🇦

**Comment by vsakos** [comment]
@ktae13-npnf I just created a new project with CRA, copied the _Setup_ code from the README and it works just fine. Are you sure you have the latest version of the Solflare adapter?

You can try installing the latest version with
```
npm install @solana/wallet-adapter-solflare@latest
```
or
```
yarn add @solana/wallet-adapter-solflare@latest
```

**Comment by ktae13-npnf** [comment]
@vsakos adding `@solana/wallet-adapter-solflare` worked!!

I was importing solflare from `@solana/wallet-adapter-wallets` package, and it seems the package has old version of solflare.

Do you recommend me to install each wallet packages instead of using single `@solana/wallet-adapter-wallets` package?

Thank you for the help!!!

**Comment by jordansexton** [comment]
> Do you recommend to install each wallet packages instead of using single @solana/wallet-adapter-wallets package?

No. I recommend using the `@solana/wallet-adapter-wallets` package. However, if you're running into issues where the dependencies you resolve are out of sync, try doing `rm -rf node_modules yarn.lock` and then run `yarn install` from your project to make sure you're resolving the latest deps. `yarn upgrade-interactive --latest` also works (sometimes).

**Comment by heldrida** [comment]
Just got back to the project where this happens, and I still see the Phantom RPC error, on latest `@solana/wallet-adapter-wallets`

**Comment by valentyn-solana** [comment]
Hi, have the same problem,
Brave doesn't inject to window object solflare (as well as Backpack and Trust) initially, only after 200-400 ms delay
