### ISSUE TITLE
Uncaught (in promise) ReferenceError: on production.

### ISSUE THREAD

**Issue by mindell** [solana-labs/wallet-adapter#331]
**Describe the bug**
I am trying to use this wallet adapter with a component from the candy machine mint code. It works as expected on the development server but the production has an Uncaught (in promise) ReferenceError: $65c8042aedc48db2$exports is not defined
**To Reproduce**
1. Go to https://dev.theshitz.io/
2.Inspect > Console
3. I already tried 2 different candy machine code and the error always point to this line
4. const provider = new anchor.Provider(connection, anchorWallet, {
        preflightCommitment: "recent",
    });

**Expected behavior**
The "Mint" button should display "Sold Out"

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jordansexton** [comment]
Sorry, this isn't the place for reporting errors with Anchor. See https://github.com/solana-labs/wallet-adapter/issues/244#issuecomment-1006049972. Also see https://github.com/solana-labs/wallet-adapter/issues/270
