### ISSUE TITLE
When will Svelte be supported?

### ISSUE THREAD

**Issue by alvinsga** [solana-labs/wallet-adapter#332]
Hi, this project is great and we would like to integrate this with our Svelte app. When is Svelte support being released?

**Comment by alvinsga** [comment]
I just ended up refactoring some of the code in the svelte package to work with the latest dependencies. If anyone wants to use this, its on here: https://github.com/alvinsga/svelte-wallet-adaptor-solana

**Comment by jordansexton** [comment]
It won't be, at least not within this repo. #298 will remove it, and there will be a community maintained version.

@cogoo and @silvestrevivo can provide more information.
