### ISSUE TITLE
the demo example won't work unless you install "stream"

### ISSUE THREAD

**Issue by merlox** [solana-labs/wallet-adapter#335]
**Describe the bug**
When copying the code from the example demo in the readme and compiling it with a basic webpack configuration, a very nasty error shows up. The solution is to install `stream` from npm. No idea why is that.

**To Reproduce**
1. Copy the code from the readme demo
2. Run the app after compiling with webpack

**Expected behavior**
Should work without errors but it doesn't unless the library `stream` is installed

**Comment by jordansexton** [comment]
The example starter project, which is built with Next.js, isn't intended to work with Webpack. This isn't a bug with the library, but an issue with Webpack requiring additional configuration for polyfills of specific Node APIs. The dependencies are already included in the packages they are used. See https://github.com/solana-labs/wallet-adapter/blob/master/packages/starter/create-react-app-starter/config-overrides.js for how to configure these.
