### ISSUE TITLE
Vue Wallet Adapter with iOS app & Phantom doesn't work

### ISSUE THREAD

**Issue by robypez** [solana-labs/wallet-adapter#341]
Hello everybody, I have a desktop vue app with the Solana Wallet Adapter.
Everything works fine on the desktop version.

With the release of the iOS Phantom app we provide also the mobile version of the website, without any change in the code.
One the mobile version the connection doesn't work: the popup appear but when I select Phantom nothing happen, no connection.

I cannot understand if is there a way to intercept the javascript console from the Phantom app, and so I cannot check if there is a particular error. 

I suppose that the integration must work out of the box

**Comment by jordansexton** [comment]
Vue isn't supported in this repo. Please see https://github.com/lorisleiva/solana-wallets-vue
