### ISSUE TITLE
Vue package link is dead and any planned support for Nuxt 3?

### ISSUE THREAD

**Issue by VidarDev** [solana-labs/wallet-adapter#345]
![B8OgAr9](https://user-images.githubusercontent.com/98586665/156521631-bd789542-6259-4247-8347-3a38812a5be0.png)

my question is in header ;)

**Comment by jordansexton** [comment]
The Vue package is linked from the readme:

https://github.com/lorisleiva/solana-wallets-vue aka https://www.npmjs.com/package/solana-wallets-vue
