### ISSUE TITLE
[QUESTION] Does this work with vite.js?

### ISSUE THREAD

**Issue by Aadhinana** [solana-labs/wallet-adapter#35]
So I tried making this work with vitejs instead of the normal create-react-app but it seems to not work. 

Fails with a `Buffer` not defined. Probably something to do with the vite config as it works well with the create-react-app. 
Any pointers on how to go around debugging it? 

because Buffer is a dependency listed in @solaan/web3.js. Is there handling these dependencies.

I have matched all the versions as given in this package and that doesnt seem to fix it.

**Comment by danmt** [comment]
I'm not sure if this is your problem, but every time I start a new project I struggle with Buffer. What I do now is adding this snippet to the polyfills:

```ts
import { Buffer } from 'buffer';
(window as any).global = window;
global.Buffer = global.Buffer || Buffer;
(window as any).process = {
  version: '',
};
```

I'm not familiar with vite.js but it should have a polyfills mechanism. In case that vite.js pollyfills don't accept Typescript, just remove the `as any`, probably replace the ES6 import for a require, and don't forget to install buffer.

BTW - If you're using webpack you might need to add a fallback for the `crypto` package like this:

```js
resolve.fallback = {
    crypto: false
}
```

**Comment by jordansexton** [comment]
I'm not familiar with vite.js. But I think @danmt is right. We may want to add something to the readme for supporting different build systems.

There's one place in the library that strictly depends on Buffer in JS rather than just as a type: https://github.com/solana-labs/wallet-adapter/blob/8b07c6db3318e1c99fba0e474a07eb4e06f981ca/packages/ledger/src/util.ts#L6

I think we could refactor this to use Uint8Array.

**Comment by jordansexton** [comment]
Nevermind, can't refactor this to use a Uint8Array. Ledger's library expects a Buffer object. I think the path forward for this issue and #30 will be to add a build system.

**Comment by jordansexton** [comment]
Copied from https://github.com/solana-labs/wallet-adapter/issues/30#issuecomment-912863207 --

I created a throwaway branch using esbuild: #50

I'm not happy with the result though. There are various issues with the webpack starter projects using it, and from what I can tell we'd lose tree shaking for the wallets package, which is kind of a dealbreaker IMO.

> perhaps the solution to this problem can be in the form of documentation

Let's go with this approach. I would be happy to accept any PRs to document use with different frameworks and build systems.

**Comment by Aadhinana** [comment]
I would try my best to get this working with [vite](https://vitejs.dev/)

**Comment by jordansexton** [comment]
@Aadhinana please let us know if it requires additional config to work with Vite, so that we can mention that somewhere in the project :)

**Comment by mdhrumil** [comment]
@Aadhinana @exogenesys and I are trying to solve the same problem. We added a shims.ts file in our /src and imported it as a script in index.html. That seems to work well on the local dev but then doesn't work on Vercel build. Any inputs on how were you able to solve this? Much appreciated :)

**Comment by jordansexton** [comment]
I think the vui-ui package in this library is being built with Vite? I might check the config there

**Comment by mdhrumil** [comment]
We solved the error by injecting the Buffer module during the build using rollup. Here's our updated vite.config.ts:

`import { defineConfig } from 'vite';
import viteTsconfigPaths from 'vite-tsconfig-paths';
import react from '@vitejs/plugin-react';
import inject from '@rollup/plugin-inject';
import path from 'path'

export default defineConfig({
    plugins: [viteTsconfigPaths(), react()],
    resolve: {
		alias: {
			'@': path.resolve(__dirname, 'src'),
		}
	},
    build: {
		rollupOptions: {
			plugins: [inject({ Buffer: ['buffer', 'Buffer'] })],
		},
	},
});
`
