### ISSUE TITLE
Unable to Sign Transactions with Torus

### ISSUE THREAD

**Issue by akarys92** [solana-labs/wallet-adapter#350]
**Describe the bug**
I am able to sign transactions in my local development environment against a solana-test-validator for all wallets except Torus. When I try to use Torus I get the following error: 
```
Translating error Error: Signature verification failed
    at Transaction.serialize (transaction.ts:586:1)
    at Provider.send (provider.ts:112:1)
    at async Object.rpc [as createReceipt] (rpc.ts:24:1)
    at async sendPayment (patron.js:33:1)
```
I can't find anything in the docs but is there some other configuration step I need to do to use the Torus wallet against a local test validator? 

**To Reproduce**
1. Start a local test validator
2. Connect using the Torus wallet with one of the Social Login features
3. Attempt to sign and send a transaction
4. See error above

**Expected behavior**
Transaction should be signed and sent successfully as it is with other wallets in the adapter that we've tested. 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave

**Comment by ArpitAgrawal321** [comment]
1) Are you on the latest adapter version ?
2) Are you using the starter to test or another repo ?

**Comment by metallicalfa2** [comment]
Also, can you send us a sample transaction which fails ? (we have seen cases where Transaction.from(transaction.serialize()) results in different instructions)

**Comment by akarys92** [comment]
One other thing I noticed, when the Torus confirmation screen comes up it says 'mainnet'. I'm wondering there's some configuration on Torus I have to do to point it at localnet?

**Comment by metallicalfa2** [comment]
> One other thing I noticed, when the Torus confirmation screen comes up it says 'mainnet'. I'm wondering there's some configuration on Torus I have to do to point it at localnet?

You can pass the network during initialization. 

> Again this we're working against localnet running in our dev environments. The transaction in this block works perfectly for wallets other than Torus. With Torus we get the message above.

One difference is, torus wallet relies on reserialization of wire format transactions. Can you checking if (Transaction.from(transaction.serialize()) results in the same transaction instruction ?

**Comment by akarys92** [comment]
Thank you @metallicalfa2 ! I'm not sure what this means `Can you checking if (Transaction.from(transaction.serialize()) results in the same transaction instruction ?`, can you clarify or point me at a doc on how to do that?

**Comment by metallicalfa2** [comment]
Looking into it. The issue might be related to https://github.com/solana-labs/solana/issues/21722

**Comment by jordansexton** [comment]
https://github.com/solana-labs/solana/pull/23720 has been merged and published in @solana/web3.js@1.39.1. I'm closing this since this is an issue with Torus Wallet and not with the adapter.
