### ISSUE TITLE
Add language support (localization)

### ISSUE THREAD

**Issue by wheeeliam** [solana-labs/wallet-adapter#351]
**Is your feature request related to a problem? Please describe.**
Hi there, I'm currently trying to implement localization within our app, however cannot find a solution to translate the wallet UI.

**Describe the solution you'd like**
I think it would be a great feature if I was able to pass in localisation as a property within the `WalletProvider` or `Wallet` object to dynamically change the locale.

**Additional context**
I have seen other Solana wallet libraries do this feature and so thought this would be helpful. If this already exists, or if there is an existing solution, please feel free to let me know and close this issue.

**Comment by jordansexton** [comment]
Hey, sounds like a great initiative. Not one I'm personally likely to undertake, but I'd be happy to accept PRs!

**Comment by jordansexton** [comment]
Iceboxing this until someone wants to take it on.
