### ISSUE TITLE
Sollet Extension Timeout

### ISSUE THREAD

**Issue by kierangillen** [solana-labs/wallet-adapter#354]
**Describe the bug**
When connecting with Sollet extension, Sollet will display a "Allow this site to access your Solana account?" page with a `Connect` CTA. If you don't click the `Connect` button immediately the request fails with `WalletTimeoutError`. 

**To Reproduce**
1. Connect using Sollet Wallet Extension for the first time
2. Sollet Extension displays page with title "Allow this site to access your Solana account?"
3. Wait more than 3 seconds, the request to connect throws an error, `WalletTimeoutError`
4. If you click `Connect` quickly the request works as expected

**Desktop:**
 - Browser Chrome
 - Sollet Extension version: `0.3.1`

**Comment by jordansexton** [comment]
Hmm. So the default timeout _should be_ 10 seconds: https://github.com/solana-labs/wallet-adapter/blob/e89adf6cdc59ca33db0fcc3a27841a1f94a8b8ed/packages/wallets/sollet/src/base.ts#L51

The timeout is set here: https://github.com/solana-labs/wallet-adapter/blob/e89adf6cdc59ca33db0fcc3a27841a1f94a8b8ed/packages/wallets/sollet/src/base.ts#L157-L158

This hack is unfortunate but Sollet sucks and there is no way to tell if the window has been closed, unlike Phantom and most other wallets.

Is any config being passed to the adapter?

**Comment by kierangillen** [comment]
I was using your example settings:

```
new SolletExtensionWalletAdapter({ network }),
```

We could just chalk this up to an issue with Sollet and move on. Thanks for looking into it, and probably good to be aware of it.
