### ISSUE TITLE
Send 1 lamport "Transaction may fail to confirm"

### ISSUE THREAD

**Issue by schwjustin** [solana-labs/wallet-adapter#355]
**Describe the bug**
 'Transaction may fail to confirm' is displayed in Phantom when using Transaction().

**To Reproduce**
Implement Setup and Usage code from README. Run react project on localhost. Set 'const network' to 'WalletAdapterNetwork.Testnet;' Set Phantom Wallet Chrome extension network to Testnet. Click 'Send 1 lamport to a random address address!' button. 'Transaction may fail to confirm' is displayed in Phantom. 

**Screenshots**
<img width="358" alt="Screen Shot 2022-03-15 at 6 04 35 PM" src="https://user-images.githubusercontent.com/18671480/158480209-ca630426-6fa7-4fb3-88cb-3c2db3d5dd81.png">

**Comment by bfriel** [comment]
> **Describe the bug** 'Transaction may fail to confirm' is displayed in Phantom when using Transaction().
> 
> **To Reproduce** Implement Setup and Usage code from README. Run react project on localhost. Set 'const network' to 'WalletAdapterNetwork.Testnet;' Set Phantom Wallet Chrome extension network to Testnet. Click 'Send 1 lamport to a random address address!' button. 'Transaction may fail to confirm' is displayed in Phantom.
> 
> **Screenshots** <img alt="Screen Shot 2022-03-15 at 6 04 35 PM" width="358" src="https://user-images.githubusercontent.com/18671480/158480209-ca630426-6fa7-4fb3-88cb-3c2db3d5dd81.png">

Hi @schwjustin can you confirm if your Phantom wallet has any lamports credited to it on **Testnet**? I am not able to reproduce this locally with an account that has sufficient Testnet lamports. I am, however, able to see this error if I try and send lamports from an empty Testnet wallet.

**Comment by jordansexton** [comment]
Closing this issue since there's been no response.

**Comment by schwjustin** [comment]
@bfriel I did have lamports credited on the Testnet and the transaction was successful. The issue is that when I initiate the transaction, Phantom has that 'Transaction may fail to confirm' message.
