### ISSUE TITLE
Enormous bundle size

### ISSUE THREAD

**Issue by brihter** [solana-labs/wallet-adapter#356]
**Describe the bug**

Using the wallet adapter and bundling it with `esbuild` produces an enormous bundle (1.3MB for a simple script). A minimal example [here](https://github.com/brihter/solana-test) with reproduction steps below.

Is this expected, perhaps a regression or am I doing something wrong?

**To Reproduce**

```
cd ~
git clone git@github.com:brihter/solana-test.git
cd solana-test/
npm install
rm index.min.js
npm run build
ls -lh index.min.js # 1.3M
```

**Expected behavior**

Smaller bundle sizes.

**Comment by jordansexton** [comment]
`getWalletAdapters` is importing every single adapter and all their dependencies:
https://github.com/solana-labs/wallet-adapter/blob/e89adf6cdc59ca33db0fcc3a27841a1f94a8b8ed/packages/wallets/wallets/src/adapters.ts#L25-L47

However that still sounds like a lot. Any chance you can come up with a chart to identify the worst offenders?

**Comment by brihter** [comment]
My intuition says Torus, because of it's explicit `stream` dependency and the `stream-browserify` [workaround](https://github.com/brihter/solana-test/blob/main/package.json#L11-L13), I'll dig deeper though.

**Comment by brihter** [comment]
```js
import { PhantomWalletAdapter as adapter } from '@solana/wallet-adapter-wallets'
console.log(adapter())
```

Importing only one adapter still produces a bundle size of 463.3kb.

**Comment by brihter** [comment]
Bundle sizes per adapter:

```
457K BitKeepWalletAdapter.min.js
458K BitpieWalletAdapter.min.js
832K BloctoWalletAdapter.min.js
456K CloverWalletAdapter.min.js
459K Coin98WalletAdapter.min.js
460K CoinhubWalletAdapter.min.js
458K GlowWalletAdapter.min.js
497K LedgerWalletAdapter.min.js
461K MathWalletAdapter.min.js
458K PhantomWalletAdapter.min.js
457K SafePalWalletAdapter.min.js
458K SlopeWalletAdapter.min.js
482K SolflareWalletAdapter.min.js
467K SolletExtensionWalletAdapter.min.js
463K SolletWalletAdapter.min.js
457K SolongWalletAdapter.min.js
457K TokenPocketWalletAdapter.min.js
795K TorusWalletAdapter.min.js
```

Build [here](https://github.com/brihter/solana-test/blob/main/build.js), bundles [here](https://github.com/brihter/solana-test/tree/main/adapters).

**Comment by jordansexton** [comment]
Yeah, makes sense. Torus and Blocto look like the big offenders. The rest are basically coming in around the same, the bulk of which I imagine comes from the base package (minimal) and dependencies like crypto libs.

Surprisingly low for Sollet and Ledger, which load external libs. Still, half a meg is a lot for what we're doing. Is this with tree shaking? And Torus is quite commonly used. @metallicalfa2 do you happen to have any info on what's leading to the large output here?

And I just noticed SolletExtensionWalletAdapter.min.js -- there is no SolletExtensionWalletAdapter now, it's been absorbed into the Sollet adapter. Is this with the latest packages built from master?

**Comment by metallicalfa2** [comment]
>Surprisingly low for Sollet and Ledger, which load external libs. Still, half a meg is a lot for what we're doing. Is this with tree shaking? And Torus is quite commonly used. @metallicalfa2 do you happen to have any info on what's leading to the large output here?

Looking into it now. will get back to you soon.

**Comment by brihter** [comment]
A bunch of hashes, for example `e60fce93b59e9ec53011aabc21c23e97b2a31369b87a5ae9c44ee89e2a6dec0a`, got my attention while looking at [Phantom's bundle](https://raw.githubusercontent.com/brihter/solana-test/main/adapters/PhantomWalletAdapter.min.js).

Top offenders as follows:

- `@blocto/sdk` + 280 kB
- `@solana/web3.js` + 120 kB
- `lodash` + 100 kB
- `elliptic` + 100 kB

**Comment by ieow** [comment]
> Going deeper into the void that is `node_modules/`.
> 
> ```
> @solana/wallet-adapter-base@0.9.5      +   7 kB (ok)
> 
> @solana/web3.js@1.36.0                 ~ 415 kB (worth looking into)
>   self                                 + 122 kB
>   elliptic                             + 100 kB
>   bn.js                                +  40 kB
>   tweetnacl                            +  30 kB
>   ...
> 
> @solana/wallet-adapter-wallets@0.15.5  ~ 1.2 MB (worth looking into)
>   @blocto/sdk                          + 281 kB (whoa)
>   @solana/web3.js                      + 123 kB
>   lodash                               + 101 kB (is full lodash needed here?)
>   elliptic                             + 100 kB
>   bn.js                                +  40 kB
>   readable-stream                      +  38 KB
>   @toruslabs/base-controllers          +  38 KB
>   tweetnacl                            +  30 kB
>   @toruslabs/solana-embed              +  28 kB
>   ...
> 
> @solana/wallet-adapter-torus@0.11.11   ~ 424 kB (worth looking into)
>   @solana/web3.js                      +  65 kB (50% less, different bundler/settings?)
>   lodash                               +  53 kB (is full lodash needed here?)
>   elliptic                             +  51 kB
>   bn.js                                +  20 kB
>   readable-stream                      +  20 KB
>   ...
> ```
> 
> Top offenders:
> 
> * `@blocto/sdk` + 280 kB
> * `@solana/web3.js` + 120 kB
> * `lodash` + 100 kB
> * `elliptic` + 100 kB
> * `bn.js` + 40 kB
> 
> Data from [bundlephobia.com](https://bundlephobia.com).

Torus wallet adapter does uses a number of packages.
however, more than half of the packages is absorbed. 
eg, web3js, elliptic, bn.js
as you can check thru the bundlephobia
https://bundlephobia.com/package/@solana/wallet-adapter-wallets@0.15.5

On lodash and other packages, we are trying to trim it down.

**Comment by brihter** [comment]
> Torus wallet adapter does uses a number of packages. however, more than half of the packages is absorbed. eg, web3js, elliptic, bn.js as you can check thru the bundlephobia https://bundlephobia.com/package/@solana/wallet-adapter-wallets@0.15.5

I know. I wanted to point out Torus as it seems there's a complete `lodash` import somewhere in there.

> On lodash and other packages, we are trying to trim it down.

Good to hear.

**Comment by mwilc0x** [comment]
Has anyone else tried experimenting with [deno](https://deno.land/)? The new React 18 streaming SSR + deno is really fast. 
Maybe an experiment|split to ESM modules could improve performance?

**Comment by Veterangrail** [comment]
> **Describe the bug**
> 
> Using the wallet adapter and bundling it with `esbuild` produces an enormous bundle (1.3MB for a simple script). A minimal example [here](https://github.com/brihter/solana-test) with reproduction steps below.
> 
> Is this expected, perhaps a regression or am I doing something wrong?
> 
> **To Reproduce**
> 
> ```
> cd ~
> git clone git@github.com:brihter/solana-test.git
> cd solana-test/
> npm install
> rm index.min.js
> npm run build
> ls -lh index.min.js # 1.3M
> ```
> 
> **Expected behavior**
> 
> Smaller bundle sizes.

https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by Veterangrail** [comment]
> **Describe the bug**
> 
> Using the wallet adapter and bundling it with `esbuild` produces an enormous bundle (1.3MB for a simple script). A minimal example [here](https://github.com/brihter/solana-test) with reproduction steps below.
> 
> Is this expected, perhaps a regression or am I doing something wrong?
> 
> **To Reproduce**
> 
> ```
> cd ~
> git clone git@github.com:brihter/solana-test.git
> cd solana-test/
> npm install
> rm index.min.js
> npm run build
> ls -lh index.min.js # 1.3M
> ```
> 
> **Expected behavior**
> 
> Smaller bundle sizes.

https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by jordansexton** [comment]
Closing since tree shaking + enforced async loading for all adapters with external dependencies takes care of this locally.

For browser extension wallets, work is underway on https://github.com/wallet-standard/wallet-standard
