### ISSUE TITLE
Connection is undefined after connecting to wallet

### ISSUE THREAD

**Issue by keshrisohit** [solana-labs/wallet-adapter#36]
I am able to retrieve the public Key as specified in Readme.MD but getting an error with the connection.
Unhandled Rejection (WalletSendTransactionError): connection is undefined

**Comment by exogenesys** [comment]
+1

**Comment by jordansexton** [comment]
Can you check to make sure the context is properly initialized? The reason I can think of for `connection` being undefined is that the `ConnectionProvider` perhaps wasn't added. If that's not the case, can you provide a reproduction of the issue?

```tsx
    return (
        <ConnectionProvider endpoint={endpoint}>
            <WalletProvider wallets={wallets} autoConnect>
                <WalletDialogProvider>
                    <WalletMultiButton/>
                    <WalletDisconnectButton/>
                </WalletDialogProvider>
            </WalletProvider>
        </ConnectionProvider>
    );
```

**Comment by jordansexton** [comment]
Closing this issue for now, please reopen with steps to reproduce if your ConnectionProvider is configured and you're still experiencing this.
