### ISSUE TITLE
Optionally keep wallet focused after error

### ISSUE THREAD

**Issue by kierangillen** [solana-labs/wallet-adapter#360]
**Is your feature request related to a problem? Please describe.**
We would love an option to not clear the wallet after an error happens on `connect()` seen here: https://github.com/solana-labs/wallet-adapter/blob/master/packages/core/react/src/WalletProvider.tsx#L202. These errors can happen quite easily if, for example, the user opens the wallet and decided to close the wallet without entering the password during connect. With our desired UX a customer should never have a wallet cleared unless they manually choose to clear it by selecting a different wallet. For context we have `autoConnect` disabled. 

**Describe the solution you'd like**
I'm interested if all of these `setName(null)` calls in the `catches` are specific to `autoConnect` functionality and if they can be disabled if `autoConnect = false`. Otherwise if we could pass an optional param that would disable them?

**Comment by kierangillen** [comment]
I believe this is the main call that is clearing the wallet after disconnecting, https://github.com/solana-labs/wallet-adapter/blob/master/packages/core/react/src/WalletProvider.tsx#L146 - if there's anyway we could pass a param to skip this, it'd be amazing.

**Comment by jordansexton** [comment]
Hmm my initial impression is that I haven't heard this request commonly enough to consider adding to the API for this yet, and I have reservations about changing established connection/disconnection behavior without more tests. But you could fork and just remove those lines for your use case.

I'm going to icebox this for now, and if it comes up again we can reconsider.

**Comment by jordansexton** [comment]
Yeah, that's a fair critique. I'm open to refactor, but probably won't have time to get around to it anytime soon. PRs are welcome though!
