### ISSUE TITLE
Cannnot build 

### ISSUE THREAD

**Issue by MichaelMuz** [solana-labs/wallet-adapter#363]
Hello I am attempting to make the example work, with nothing changed. I followed the steps by copy and pasting the commands. I cloned, yarn install, and yarn build. During yarn build I get the error:

lerna ERR! yarn run build exited 137 in '@solana/wallet-adapter-mathwallet'
lerna ERR! yarn run build stdout:
$ yarn clean && tsc -p tsconfig.json && tsc-esm -p tsconfig.json && tsc -p tsconfig.cjs.json
$ shx rm -rf lib/*
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:
Killed
error Command failed with exit code 137.
lerna ERR! yarn run build exited 137 in '@solana/wallet-adapter-mathwallet'
lerna WARN complete Waiting for 16 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 137.

Basically it seems like App.tsx (in wallet-adapter/packages/starter/create-react-app-starter/src) "Cannot find module '@solana/wallet-adapter-react' or its corresponding type declarations." and "Cannot find module '@solana/wallet-adapter-react-ui' or its corresponding type declarations" and "Cannot find module '@solana/wallet-adapter-wallets' or its corresponding type declarations." 

I figured that the yarn install should have taken care of it but I figured I could install them individually when I do yarn add @solana/wallet-adapter-base, that failed import goes away, however when I try to individually install the other ones, not only do the other failed imports not go away but @solana/wallet-adapter-base also somehow stops working. 

This is a very weird problem and I assume it has something to do with my machine since I simply cloned the repo with no changes and it seems to be working for everyone else. Any ideas?

Edit: it seems that it is not specific to any part of the program, just anytime there is an import I get a "Cannot find module '@(any module)' or its corresponding type declarations.". These usually start with an @. It can find @solana.web3.js just fine I think it cannot find anything without a .something ending such as '@solana/wallet-adapter-wallets'. 
@jordansexton

**Comment by cboseb** [comment]
I have the same problem and still trying to figure it out.

**Comment by gokul-jagannath** [comment]
I am having the same issue. Please help.

**Comment by sn0rlacks** [comment]
@jordansexton maybe? there was a recent shift in dependency management involving peerdependencies. I am also having this error

**Comment by MichaelMuz** [comment]
> 
I did now what?

**Comment by charly-helio** [comment]
Hi!
 try to add to devDependencies on package.json what is missing:
@solana/wallet-adapter-react-ui
@solana/wallet-adapter-wallets

**Comment by jordansexton** [comment]
I just ran the following commands:

```shell
git clone https://github.com/solana-labs/wallet-adapter.git

cd wallet-adapter
yarn install
yarn build
```

This builds all the packages, including the example and all its dependencies.

I then ran:

```shell
cd packages/starter/example
yarn dev

open http://localhost:3000
```

The example builds and runs successfully.

**Comment by jordansexton** [comment]
In case it helps, I'm using

- Mac OS 12.2.1 (M1 Pro)
- Node v16.14.0
- Yarn 1.22.17

**Comment by cboseb** [comment]
I tried many thing to get this code work, but I can figure it out yet.

@jordansexton I followed your step 

```
git clone https://github.com/solana-labs/wallet-adapter.git
cd wallet-adapter
yarn install
yarn build
```

### Here is the result when I try to build

```
..\crypto\wallet-adapter> yarn build
yarn run v1.22.17
$ lerna run build
lerna notice cli v4.0.0
lerna info versioning independent
lerna info Executing command in 29 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in '@solana/wallet-adapter-base'
lerna ERR! yarn run build stdout:
$ yarn clean && tsc -p tsconfig.json && tsc-esm -p tsconfig.json && tsc -p tsconfig.cjs.json
$ shx rm -rf lib/*
$ echo '{"type":"commonjs"}' | npx json > lib/cjs/package.json && echo '{"type":"module"} ' | npx json > lib/esm/package.json
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:
json: error: input is not JSON: Unexpected ''' at line 1, column 1:
        '{"type":"commonjs"}'
        ^
error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in '@solana/wallet-adapter-base'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Here  what I'm using
Git 2.35.1
Node 17.8.0  (I also tried with v16.14.0 with same result)
yarn 1.22.17
npm 8.5.4 (I also tried using npm instead of yarn with similar result)
Windows 10, x64 based PC


I tried to individually install modules like @MichaelMuz did and I was stuck at the same place.

Any suggestion for the next move ?

Thanks

**Comment by cboseb** [comment]
If it can help others... I solved my problem by installing WSL for Windows https://docs.microsoft.com/en-us/windows/wsl/install-win10
