### ISSUE TITLE
Phamtom wallet auto connection issue on gatsby

### ISSUE THREAD

**Issue by sergejmh** [solana-labs/wallet-adapter#364]
**Phamtom wallet auto connection issue on gatsby**
The auto connection is not working well on gatsby project when using Phatom wallet.
The other wallets are working well like Softflare, Slope wallets.
I've used @solana/wallet-adapter-material-ui library to connect wallet.
How can I fix this issue?
Thanks

**Comment by Veterangrail** [comment]
> **Phamtom wallet auto connection issue on gatsby** The auto connection is not working well on gatsby project when using Phatom wallet. The other wallets are working well like Softflare, Slope wallets. I've used @solana/wallet-adapter-material-ui library to connect wallet. How can I fix this issue? Thanks

https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by SvenDowideit** [comment]
@sergejmh is this still an issue? I _think_ its working right with phantom on https://dme.sh/ - source at https://github.com/workbenchapp/dme.sh

(or is this only an issue with mui wallet-adapter?

**Comment by jordansexton** [comment]
This is probably the same issue as https://github.com/solana-labs/wallet-adapter/issues/519 and therefore likely fixed by https://github.com/solana-labs/wallet-adapter/pull/527. If it persists, please open a new issue with reproduction details.
