### ISSUE TITLE
Standard wallet connector interface

### ISSUE THREAD

**Issue by gyorgy-kurucz-vacuum** [solana-labs/wallet-adapter#367]
**Is your feature request related to a problem? Please describe.**
Currently there does not seem to be a standard wallet connector interface, each wallet adapter is implemented separately. This causes a lot of repetition and extra maintenance burden. (Currently every wallet adapter is published as a separate npm package, which seems quite excessive to me.)

**Describe the solution you'd like**
Ideally I would like a standard connector interface, like Cardano's [CIP-30](https://cips.cardano.org/cips/cip30/).

# Additional context

We would like to support solana dApps in our wallet. I am trying to figure out what would be the best interface to present on the wallet's side.

## A standardized wallet connector
The ideal solution would be something like Cardano's [CIP-30](https://cips.cardano.org/cips/cip30/) standard, which would make supporting each wallet separately unnecessary, and instead any wallet presenting the standard interface would be automatically supported. (I couldn't find anything like this for solana, but maybe I just missed it.)

Are there any plans for such standardization? What would be the process for that? (I don't know how the solana community is structured, whether you have anything similar to Cardano's CIPs or Ethereum's ERCs.)

## The best solution in the current situation
On an initial look, the current wallet interfaces seem to be all over the place. Some are placed under [`window[wallet_name].solana`](https://github.com/solana-labs/wallet-adapter/blob/e15287221b90f8d7bee60726d251a5b4c76d243a/packages/wallets/bitkeep/src/adapter.ts#L24), some simply under [`window[wallet_name]`](https://github.com/solana-labs/wallet-adapter/blob/e15287221b90f8d7bee60726d251a5b4c76d243a/packages/wallets/coinhub/src/adapter.ts#L21), some under some generic key like [`window.network`](https://github.com/solana-labs/wallet-adapter/blob/e15287221b90f8d7bee60726d251a5b4c76d243a/packages/wallets/blocto/src/adapter.ts#L20).

Even worse, multiple wallets simply expose their interfaces under `window.solana`, and I don't really see how this scheme won't eventually cause conflicts:
https://github.com/solana-labs/wallet-adapter/blob/e15287221b90f8d7bee60726d251a5b4c76d243a/packages/wallets/mathwallet/src/adapter.ts#L23
https://github.com/solana-labs/wallet-adapter/blob/e15287221b90f8d7bee60726d251a5b4c76d243a/packages/wallets/tokenpocket/src/adapter.ts#L34

The interfaces themselves are also quite different between wallets.

My questions are:
- What would be the best place to inject the interface? The most logical place would be under `window.solana[wallet_name]`, similar to the scheme [CIP-30](https://cips.cardano.org/cips/cip30/) uses, but this would conflict with wallets already using the whole `window.solana` property for themselves. (Something like `window.dappConnector[blockchain][wallet_name]` would also be an option, but in the current situation it seems quite far fetched that multiple different blockchains would standardize on a common scheme.)
- What would be the best interface to present? To me it seems like the easiest would be to just follow the interface of [`BaseSignerWalletAdapter`](https://github.com/solana-labs/wallet-adapter/blob/a5b1ebd70ae9753d188fec60e95e252402f3f371/packages/core/base/src/signer.ts#L12) as closely as possible. Does anyone have any additional suggestions?

Thank you in advance for any help with this :)

**Comment by steveluscher** [comment]
I have some thoughts on a standard interface, particularly in so far as it can serve startup performance. Take a read and let me know what you think! #215

**Comment by gyorgy-kurucz-vacuum** [comment]
Wow, really nicely written :) It hasn't yet occurred to me that polling would be an issue, I was just assuming that the extension's content script ran before the page loaded.

What's your opinion on somehow generalizing the detection and the interface across wallets? AFAICT your proposal does not address this, and you still have to separately check for them. I am also not fond of the `window` object being polluted with all these different properties.

Do you know if solana has a process for proposing these kinds of changes? (Like Cardano's CIPs or Ethereum's ERCs.)

**Comment by steveluscher** [comment]
> Do you know if solana has a process for proposing these kinds of changes? (Like Cardano's CIPs or Ethereum's ERCs.)

https://twitter.com/jordaaash/status/1534987050537173013 👀 cc/ @gyorgy-kurucz-vacuum

**Comment by ndevmetax** [comment]
> **Is your feature request related to a problem? Please describe.** Currently there does not seem to be a standard wallet connector interface, each wallet adapter is implemented separately. This causes a lot of repetition and extra maintenance burden. (Currently every wallet adapter is published as a separate npm package, which seems quite excessive to me.)
> 
> **Describe the solution you'd like** Ideally I would like a standard connector interface, like Cardano's [CIP-30](https://cips.cardano.org/cips/cip30/).
> 
> # Additional context
> We would like to support solana dApps in our wallet. I am trying to figure out what would be the best interface to present on the wallet's side.
> 
> ## A standardized wallet connector
> The ideal solution would be something like Cardano's [CIP-30](https://cips.cardano.org/cips/cip30/) standard, which would make supporting each wallet separately unnecessary, and instead any wallet presenting the standard interface would be automatically supported. (I couldn't find anything like this for solana, but maybe I just missed it.)
> 
> Are there any plans for such standardization? What would be the process for that? (I don't know how the solana community is structured, whether you have anything similar to Cardano's CIPs or Ethereum's ERCs.)
> 
> ## The best solution in the current situation
> On an initial look, the current wallet interfaces seem to be all over the place. Some are placed under [`window[wallet_name].solana`](https://github.com/solana-labs/wallet-adapter/blob/e15287221b90f8d7bee60726d251a5b4c76d243a/packages/wallets/bitkeep/src/adapter.ts#L24), some simply under [`window[wallet_name]`](https://github.com/solana-labs/wallet-adapter/blob/e15287221b90f8d7bee60726d251a5b4c76d243a/packages/wallets/coinhub/src/adapter.ts#L21), some under some generic key like [`window.network`](https://github.com/solana-labs/wallet-adapter/blob/e15287221b90f8d7bee60726d251a5b4c76d243a/packages/wallets/blocto/src/adapter.ts#L20).
> 
> Even worse, multiple wallets simply expose their interfaces under `window.solana`, and I don't really see how this scheme won't eventually cause conflicts:
> 
> https://github.com/solana-labs/wallet-adapter/blob/e15287221b90f8d7bee60726d251a5b4c76d243a/packages/wallets/mathwallet/src/adapter.ts#L23
> 
> 
> https://github.com/solana-labs/wallet-adapter/blob/e15287221b90f8d7bee60726d251a5b4c76d243a/packages/wallets/tokenpocket/src/adapter.ts#L34
> 
> The interfaces themselves are also quite different between wallets.
> 
> My questions are:
> 
> * What would be the best place to inject the interface? The most logical place would be under `window.solana[wallet_name]`, similar to the scheme [CIP-30](https://cips.cardano.org/cips/cip30/) uses, but this would conflict with wallets already using the whole `window.solana` property for themselves. (Something like `window.dappConnector[blockchain][wallet_name]` would also be an option, but in the current situation it seems quite far fetched that multiple different blockchains would standardize on a common scheme.)
> * What would be the best interface to present? To me it seems like the easiest would be to just follow the interface of [`BaseSignerWalletAdapter`](https://github.com/solana-labs/wallet-adapter/blob/a5b1ebd70ae9753d188fec60e95e252402f3f371/packages/core/base/src/signer.ts#L12) as closely as possible. Does anyone have any additional suggestions?
> 
> Thank you in advance for any help with this :)


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/

**Comment by gyorgy-kurucz-vacuum** [comment]
Thanks. From that twitter thread:

> I'll get started with a draft API specification in the open, solicit feedback from wallets and apps, and identify a scope for the work.

> Importantly, I won't do any of this alone. This process will be successful because I'll get help from wallet teams, application developers, and open source contributors on Solana.

Do you know whether the work has started already? Should we keep this issue open, or is the work already tracked somewhere else?

As part of a wallet team, I would be happy to offer feedback/advice on any draft if needed.

**Comment by gyorgy-kurucz-vacuum** [comment]
Found it: https://github.com/solana-labs/wallet-standard/tree/master/packages/core/standard

**Comment by jordansexton** [comment]
Yes, would love to talk with you about it. If you want to DM me on Twitter or Discord, we can discuss the design and the current state of development.

**Comment by jordansexton** [comment]
Closing here since this work is well underway @ https://github.com/wallet-standard/wallet-standard
