### ISSUE TITLE
Can't use custom RPC

### ISSUE THREAD

**Issue by u3j** [solana-labs/wallet-adapter#368]
I cannot use a custom RPC. In this example, I want to use genesys DAO:
![bilde](https://user-images.githubusercontent.com/90964656/159529161-967078e1-34f5-4454-ae2e-3c8441f1ff26.png)

But I end up with api.mainnet-beta.solana.com no matter how I try to configure it (even if I pass in the RPC as a plain string)
![bilde](https://user-images.githubusercontent.com/90964656/159529394-a773213e-78de-4380-b17f-95c4d066fad3.png)

**Comment by u3j** [comment]
It's passing back the endpoint to @solana/web3.js

**Comment by jordansexton** [comment]
Yeah, so the endpoint you pass to the `ConnectionProvider` is what the `WalletProvider` uses, but it doesn't change what `ProgramProvider` uses (and idk what `ProgramProvider` is doing).
