### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by danmt** [solana-labs/wallet-adapter#37]
# Overview

I'm trying to replicate the [react library](https://github.com/solana-labs/wallet-adapter/tree/master/packages/react) in Angular, I'm getting to a point where things start to make sense. I was wondering if this is something you'd like to include in the library set.

I think the pain point of doing this would be the UI part, from the top of my head I can think of two alternatives:

- Make UI libs framework agnostic (hard to code IMO)
- Create different sets of UI libs per framework (easier to code, harder to maintain)

Given the React-ish approach of everything Solana-related, I'm thinking of doing this on my own in a different monorepo. Not having Angular-support held me back for a while, would love to make it easy for other Angular fellas like me.

**Comment by jordansexton** [comment]
I think an Angular package for this would be great and could definitely be part of the core in this repo. I haven't used Angular personally in many years, so I'd rely on you to establish some idiomatic conventions, but I would definitely review and accept a PR for this.

**Comment by jordansexton** [comment]
What I would suggest first is a PR for a package analogous to the react package that has no UI components. We can decide on good conventions there and then expand to UI components.

**Comment by danmt** [comment]
Right on friend, you got it. 

I'm atm wrapping up the signTransaction/signAllTransactions methods. I'm basing my design heavily on the react package, we won't need any design documents for that (I'd expect). The UI part, well, different story, and we'll address it then lol. 

I'll be raising the PR this week and reference this issue for tracking purposes.

**Comment by jordansexton** [comment]
Sounds great, looking forward to it.
