### ISSUE TITLE
Improve Transaction success rate

### ISSUE THREAD

**Issue by wisefool769** [solana-labs/wallet-adapter#373]
**Describe the bug**
When the network is under high load, I frequently see instances where transactions fail to confirm, with a message like 'Transaction may fail to confirm in 30.01 seconds' . 

**Additional context**
The default settings in the web3 js library aren't necessarily the best for production usage. 
Here's some context: https://twitter.com/GenesysGo/status/1502726745149030405

I think if we add retries and a longer timeout window, we can achieve a lower transaction failure rate. 
This would entail  modifications to //core/base/src/signer.ts to be more inline with 
https://solanacookbook.com/guides/retrying-transactions.html#an-in-depth-look-at-sendtransaction

**Comment by jordansexton** [comment]
It's up to apps or wallets to handle retries with application-specific logic. This isn't in scope for wallet-adapter, but you could build a library that does this.
