### ISSUE TITLE
RPC Error: Transaction creation failed.

### ISSUE THREAD

**Issue by cmitjans-at-wiris** [solana-labs/wallet-adapter#374]
**Describe the bug**
Whenever I try to send a transaction, I get the following error:

```
Phantom - RPC Error: Transaction creation failed. {code: -32003, message: 'Transaction creation failed.'}
```

**To Reproduce**

```
const phantomWalletAdapter = new PhantomWalletAdapter();
await phantomWalletAdapter.connect();
phantomWalletAdapter.sendTransaction(transaction, connection);
```

**Comment by jordansexton** [comment]
This isn't an issue with wallet-adapter. It's probably not an issue with Phantom either. But we don't do developer support on Github. If you're still experiencing the issue, please try the #developer-support channel on Discord: https://discord.com/invite/solana
