### ISSUE TITLE
Phantom creates invalid transactions randomly, but does not throw any errors.

### ISSUE THREAD

**Issue by german-schneck** [solana-labs/wallet-adapter#377]
**Describe the bug**
When I run a transaction in Phantom, most of the time it processes it correctly, but sometimes it does not.
This happens only on Mainnet. In Testnet it executes them correctly 100% of the time.

**To Reproduce**
1. Execute a transaction in Phantom using the solana.sendTransaction() function.
2. Approve the transaction within the PopUp.
3. Access within the first few seconds the Solana browser with the transaction hash returned by sendTransaction().

**Invalid transactions look like this in the browser.**
![image](https://user-images.githubusercontent.com/15254932/161165736-8262a38c-a3f9-40be-a3de-01f42b2f733f.png)

**Expected behavior**
The transaction is successfully executed, and the explorer should look like this.

![image](https://user-images.githubusercontent.com/15254932/161165818-824fab3e-dd40-4eba-be51-914fa91d0018.png)

**Desktop (please complete the following information):**
 - OS: Windows/Mac
 - Browser: Brave, Mozilla, Google Chrome
 - Version: Brave (V1.37.109), Google Chrome (100.0.4896.60), Mozilla (98.0.2)

**Additional context**

**Details to consider:**

- Phantom returns a transactionHash once the transaction is approved. But in the browser this transfer does not exist and in reality it never ends up being applied correctly.

- There is no error LOG to indicate the problem.

- As far as I can count, 2 of the 10 transactions I performed had this behavior.

**Comment by jordansexton** [comment]
Hmm. This sounds like an issue with Phantom. What specifically leads you to think this is an issue with WalletAdapter?

**Comment by german-schneck** [comment]
> Hmm. This sounds like an issue with Phantom. What specifically leads you to think this is an issue with WalletAdapter?

@solana/wallet-adapter-react

That's what I'm really trying to define, where the relationship of this might be.

I'm currently running the transaction as follows with this data:
![image](https://user-images.githubusercontent.com/15254932/161168733-c6412ee8-4b9e-450c-95c0-f3e21a512fa8.png)

I am sending these instructions through this function.
![image](https://user-images.githubusercontent.com/15254932/161168770-b10f4764-c911-4959-bb6b-c0ef26be5f33.png)

The variable "signature" always returns me the hash of the transaction, but actually there are times when the transaction is confirmed and sometimes not.

**So, I don't know if:**
1. I am passing some information to you incorrectly.
2. Phantom is failing
3. WalletAdapter is not catching a particular error.

Thank you for your prompt response!

**Comment by jordansexton** [comment]
Ah, there's a 4th and 5th option:

4. The RPC node is somehow failing to broadcast the transaction.
5. The network has not found and confirmed the transaction.

These sound most likely, given the above description.

The hash phantom is returning is just the signature of the transaction. Since Phantom has returned it, this likely suggests the RPC node has received it. But after that, it's out of Phantom's (or WalletAdapter's) control.
