### ISSUE TITLE
Add react app transaction sample 

### ISSUE THREAD

**Issue by tomoima525** [solana-labs/wallet-adapter#38]
Hi,

I recently created a react application that showcases the usage of `wallet-adapter` and `solana/web3` for viewing transactions and making transactions from your wallet. I'm wondering if I can bring this project somewhere under this repository(e.g. `packages/example/transaction-tool`) so that it helps devs to develop front-end tools. What do you think?

Here's the link to my project
https://github.com/tomoima525/solana-transaction-tool

I'm happy to create a PR if that idea sounds good to `wallet-adapter` project owner :)

**Comment by jordansexton** [comment]
I'm glad you're finding the library useful! Looking at your project, it seems like some of the functionality we want to highlight is already demonstrated in the Usage sample code in the readme: https://github.com/solana-labs/wallet-adapter#usage

The example code also has some of this kind of functionality: https://github.com/solana-labs/wallet-adapter/blob/e6bcd3c36929709a604637260de556275573c726/packages/example/src/SendTransaction.tsx#L20-L31

These use the `sendTransaction` interface here: https://github.com/solana-labs/wallet-adapter/blob/e6bcd3c36929709a604637260de556275573c726/packages/base/src/signer.ts#L13-L40

Is there something you think it would be valuable to add to these? I think where this library can use the most help is in documenting the features it has.

**Comment by tomoima525** [comment]
Oh actually I did not notice about `SendTransaction.tsx` implementation was there! So `BaseSignerWalletAdapter` covers the transaction implementation which I implemented in my project. Cool! 

Yeah perhaps adding some documents for `useWallet` hooks might be helpful for devs. I'll try to see if I can contribute to anything in the project. Meanwhile let me close this issue, thanks for your input!
