### ISSUE TITLE
Get Started button in Dialog does not open onboarding flow.

### ISSUE THREAD

**Issue by safaiyeh** [solana-labs/wallet-adapter#380]
**Describe the bug**
When using the Dialog/Modal Button as shown in the demo: https://solana-labs.github.io/wallet-adapter/example/
When the browser does not have a wallet installed, we get a "Get Started" button, this button connects a detected wallet if the adapter exists.

**To Reproduce**
1. Go to https://solana-labs.github.io/wallet-adapter/example/
2. Select wallet in Dialog/Modal + react-ui section 
3. Click the "Get Started" button
4. Observe nothing happens and the other buttons are connected to a wallet.

**Expected behavior**
This button should try to connect to the wallet to start the onboarding flow. i.e Phantom will open a new tab for users to download the extension

Also could we have a prop that allows picking the fallback wallet for the Get Started button. It picks Torus wallet then Phantom by default but we'd like a different order

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome+Brave
 - Version "@solana/wallet-adapter-react-ui": "^0.9.5"

**Comment by Veterangrail** [comment]
> **Describe the bug** When using the Dialog/Modal Button as shown in the demo: https://solana-labs.github.io/wallet-adapter/example/ When the browser does not have a wallet installed, we get a "Get Started" button, this button connects a detected wallet if the adapter exists.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to https://solana-labs.github.io/wallet-adapter/example/
> 2. Select wallet in Dialog/Modal + react-ui section
> 3. Click the "Get Started" button
> 4. Observe nothing happens and the other buttons are connected to a wallet.
> 
> **Expected behavior** This button should try to connect to the wallet to start the onboarding flow. i.e Phantom will open a new tab for users to download the extension
> 
> Also could we have a prop that allows picking the fallback wallet for the Get Started button. It picks Torus wallet then Phantom by default but we'd like a different order
> 
> **Desktop (please complete the following information):**
> 
> * OS: macOS
> * Browser: Chrome+Brave
> * Version "@solana/wallet-adapter-react-ui": "^0.9.5"

https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by jordansexton** [comment]
Closing since this is an instance/symptom of https://github.com/solana-labs/wallet-adapter/issues/394, which we will address. Thanks for your patience on this, we're going to revamp the Getting Started UX. Please subscribe to that issue!
