### ISSUE TITLE
Nextjs Server Side Instructions

### ISSUE THREAD

**Issue by MarioProjects** [solana-labs/wallet-adapter#383]
Hello! Thanks for the adapters. I have a question that probably is solved but I don't know-how. There is a way to move the transactions to the server side?

I have 2 casuistics. 

#1. Which is the secure way to verify that a user signed a message, and then perform an action?
#2. I implement a purchase system. If the wallet used is not on a database I want to block the operation. That is done in the server side, an API route, could I move there too the Solana instruction?

Thanks!

**Comment by jordansexton** [comment]
Please don't ask general questions in this repo, which I'm sure you recognize has nothing to do with your question.
