### ISSUE TITLE
Support Phantom universal links/deeplinks

### ISSUE THREAD

**Issue by o-c-e-a-n** [solana-labs/wallet-adapter#385]
https://phantom.app/blog/introducing-phantom-deeplinks

#319 #312 #311 #309

**Comment by alirezaayande** [comment]
Earning solano Is it possible?#help

**Comment by acrens** [comment]
Looking forward to adding to adapter

**Comment by Veterangrail** [comment]
> https://phantom.app/blog/introducing-phantom-deeplinks
> 
> #319 #312 #311 #309

https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by ndevmetax** [comment]
> https://phantom.app/blog/introducing-phantom-deeplinks
> 
> #319 #312 #311 #309


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/

**Comment by jordansexton** [comment]
Closing since this feature doesn't make sense in Wallet Adapter.

https://github.com/solana-mobile/mobile-wallet-adapter covers this use case for other wallets.

**Comment by jordansexton** [comment]
This has been _loosely_ implemented: https://github.com/solana-labs/wallet-adapter/pull/673

Phantom (and soon Solflare) support deep linking on iOS, to jump into the in-wallet dapp browser.
