### ISSUE TITLE
Critical Security vulnerability - Prototype Pollution in minimist dependency 

### ISSUE THREAD

**Issue by brianchitester** [solana-labs/wallet-adapter#390]
**Describe the bug**

Critical Security vulnerability - Prototype Pollution in minimist dependency 

  Package: minimist
  Patched in: >=1.2.6
  Dependency of: shx, eslint-config-react-app, lerna
  More info: [https://www.npmjs.com/advisories/1067342](https://www.npmjs.com/advisories/1067342)
  Severity: critical
  Title: Prototype Pollution in minimist

**To Reproduce**
1. Clone the repo
2. run yarn audit

**Expected behavior**
No critical security vulnerabilities

**Screenshots**
<img width="596" alt="image" src="https://user-images.githubusercontent.com/311848/164030765-405be329-0d13-47f6-a2e7-d6dcd2099848.png">

**Desktop**
 - OS: macOS
 - Browser N/A
 - Version 12.3.1

**Comment by Veterangrail** [comment]
> **Describe the bug**
> 
> Critical Security vulnerability - Prototype Pollution in minimist dependency
> 
> Package: minimist Patched in: >=1.2.6 Dependency of: shx, eslint-config-react-app, lerna More info: https://www.npmjs.com/advisories/1067342 Severity: critical Title: Prototype Pollution in minimist
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Clone the repo
> 2. run yarn audit
> 
> **Expected behavior** No critical security vulnerabilities
> 
> **Screenshots** <img alt="image" width="596" src="https://user-images.githubusercontent.com/311848/164030765-405be329-0d13-47f6-a2e7-d6dcd2099848.png">
> 
> **Desktop**
> 
> * OS: macOS
> * Browser N/A
> * Version 12.3.1

https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by jordansexton** [comment]
Closing since this has been resolved (our resolved version of minimist is 1.2.7)
