### ISSUE TITLE
FEATURE: Add support to programatically close Wallet Transaction windows

### ISSUE THREAD

**Issue by AnderUstarroz** [solana-labs/wallet-adapter#393]
**Problem**
If some transactions are allowed between certain periods of time we should be able to programatically close transaction windows when period has expired, for instance, a transaction like following:

```
        const transaction = new Transaction().add(
            SystemProgram.transfer({
                fromPubkey: publicKey,
                toPubkey: Keypair.generate().publicKey,
                lamports: 1,
            })
        );

        const signature = await sendTransaction(transaction, connection);

        await connection.confirmTransaction(signature, 'processed');
```
Will open a transaction popup asking for confirmation. But the window can only be closed manually (or at least there are no docs showing how to do it programatically)

**Proposed solution**
I would like to be able to close the transaction window programatically via JS when required. (Disconnecting the user is way too aggresive)

**Comment by jordansexton** [comment]
This feature request misunderstands what this library is capable of. The UI for signing transactions is owned by the wallet, typically a browser extension, popup window, or iframe, which may be controlled by an SDK. We can't call a function to close or cancel this unless wallets provide that capability.
