### ISSUE TITLE
Error -32004: Transaction creation failed.

### ISSUE THREAD

**Issue by schwjustin** [solana-labs/wallet-adapter#395]
I implemented the started code to create a transaction and send one lamport. It worked for weeks but now it doesn't work on the Devnet or the Testnet. I am able to connect my wallet to my application and initiate the transaction but after I approve in Phantom I get this error:

Phantom - RPC Error: Transaction creation failed. {code: -32003, message: 'Transaction creation failed.'}

To reproduce implement the starter code and approve a transaction in Phantom.

**Comment by jordansexton** [comment]
Sorry, we don't handle dev support on Github. Please ask for help on Discord! Nothing has changed about the library or example code, so if it worked until now, it's likely that this is an issue with your project or the network.

**Comment by schwjustin** [comment]
@jordansexton I tried to join the Discord but the Anti-dupe Bot is kicking me "You have been kicked for using a duplicate username on the server, please change it before joinning again" so I am unable to join.
