### ISSUE TITLE
Overriding WalletMultiButton style from react-ui

### ISSUE THREAD

**Issue by squidniiie** [solana-labs/wallet-adapter#397]
Hi there! 

I'm looking to customize the WalletMultiButton for the frontend of my web app, and having a hard time overriding the styling. Here is what I've tried so far: 

- Changing the background color in the styles.css node module: 

`.wallet-adapter-button-trigger {
    background-color: #70faec;
}`

- Adding style to the App.css file following this guide: https://lorisleiva.com/create-a-solana-dapp-from-scratch/integrating-with-solana-wallets

- Lastly, I just tried adding a Tailwind className to the button just for kicks, and the button disappeared.

`import React, { useMemo } from 'react';
import {
  ConnectionProvider,
  WalletProvider,
} from '@solana/wallet-adapter-react';
import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
import {
  GlowWalletAdapter,
  // LedgerWalletAdapter,
  PhantomWalletAdapter,
  SlopeWalletAdapter,
  SolflareWalletAdapter,
  // SolletExtensionWalletAdapter,
  // SolletWalletAdapter,
  TorusWalletAdapter,
} from '@solana/wallet-adapter-wallets';
import {
  WalletModalProvider,
  WalletDisconnectButton,
  WalletMultiButton,
} from '@solana/wallet-adapter-react-ui';
import { clusterApiUrl } from '@solana/web3.js';
// Default styles that can be overridden by your app
import '@solana/wallet-adapter-react-ui/styles.css';
import './App.css';
// require('@solana/wallet-adapter-react-ui/styles.css');

const App = () => {
  // export const Wallet: FC = () => {
  // The network can be set to 'devnet', 'testnet', or 'mainnet-beta'.
  const network = WalletAdapterNetwork.Devnet;

  // You can also provide a custom RPC endpoint.
  const endpoint = useMemo(() => clusterApiUrl(network), [network]);

  // @solana/wallet-adapter-wallets includes all the adapters but supports tree shaking and lazy loading --
  // Only the wallets you configure here will be compiled into your application, and only the dependencies
  // of wallets that your users connect to will be loaded.
  const wallets = useMemo(
    () => [
      new PhantomWalletAdapter(),
      new GlowWalletAdapter(),
      new SlopeWalletAdapter(),
      new SolflareWalletAdapter({ network }),
      new TorusWalletAdapter(),
    ],
    [network]
  );

  return (
    <ConnectionProvider endpoint={endpoint}>
      <WalletProvider wallets={wallets} autoConnect>
        <WalletModalProvider>
          <button className='bg-red-300 rounded-3xl p-2'>Select Wallet</button>
          <WalletMultiButton />
          <WalletDisconnectButton />
          {/* Your app's components go here, nested within the context providers. */}
        </WalletModalProvider>
      </WalletProvider>
    </ConnectionProvider>
  );
};
export default App;`

Any suggestions on how to effectively change the button color?

**Comment by CameronButcher** [comment]
Hey, I recently went through a similar struggle. My goal was to fully customise the look of the buttons but keep the same UI of the modal. If all you're looking to do is change the button colour but keep the styling of everything else this may be a little overkill, but nevertheless, its an option which may be useful.

```
import React, { useEffect, useState } from 'react';
import { useConnection, useWallet } from '@solana/wallet-adapter-react';
import { WalletModalProvider, WalletMultiButton, useWalletModal } from '@solana/wallet-adapter-react-ui';
require('@solana/wallet-adapter-react-ui/styles.css');

const SolanaConnector = () => {
  const [connect, setConnect] = useState(false);

  const renderConnectButton = () => {
      return (
        <div onClick={() => setConnect(true)} className='h-10 lg:h-12 px-4 lg:px-10 flex gap-x-3 max-w-48 justify-around items-center hover:opacity-50 w-full rounded-full cursor-pointer bg-leke-blue-100'>
          <div className="whitespace-nowrap py-2 lg:py-3 lg:px-5 text-sm lg:text-base">Connect wallet</div>
        </div>
      )
  }

  const renderSolana = () => { 
    return (
      <WalletModalProvider>
        <div className="hidden">
          <WalletMultiButton>
            <OpenModal onConnectChange={(e) => setConnect(e)} connect={connect} address={address}/>
          </WalletMultiButton>
        </div>
        <ConnectionSaver onConnect={() => setConnect(false)} disconnectWallet={disconnect}/>
      </WalletModalProvider>
    )
  }

  return (
    <>
      {renderSolana()}
      {renderConnectButton()}
    </>
  );

}


const OpenModal = ({ connect, onReject, onConnectChange, address }) => {
  const { setVisible, visible } = useWalletModal();

  useEffect(() => {
    if (connect) {
      setVisible(true)
    }
  }, [connect)
  
  return null
}
```

The main thing is that, the Wallet Multi Button is being hidden by a div. Instead, the opening of the modal is being controlled via state (connect/setConnect) and if connect is true, I then use the setVisible function provided by the UseWalletModal() hook.

Also fyi, my other Solana components such as Connection Provider + Wallet Provider are surrounding my App components from app.js

Finally, you can also tell when the modal has been closed by using the "visible" variable (again provided by UseWalletModal()) and just listening when this is set to false.

Hope this helps!

**Comment by jordansexton** [comment]
We don't use Github for developer support. Please try the Solana Discord: https://discord.com/invite/solana

**Comment by scottwilson312** [comment]
What about ```.wallet-adapter-button, .wallet-adapter-button-trigger{
  all:unset !important;
}
```

**Comment by OrmEmbaar** [comment]
Using Tailwind in `global.css`

```css
button.wallet-adapter-button-trigger {
  @apply bg-secondary rounded-sm; /* etc */
}

```
