### ISSUE TITLE
Babel loader error

### ISSUE THREAD

**Issue by richard-fisher** [solana-labs/wallet-adapter#4]
I'm trying to use this in a react project created with create-react-app and I'm getting this error

```
./node_modules/@solana/wallet-adapter-base/lib/errors.js 2:7
Module parse failed: Unexpected token (2:7)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export class WalletError extends Error {
>   error;
|
|   constructor(message, error) {
```

Is there a specific babel plugin that I need to parse the syntax?

**Comment by jordansexton** [comment]
Hmm, good question. It looks like it's failing to parse this "esnext" syntax. Did you use a particular template or configuration for create-react-app? I'll try to reproduce this today.

**Comment by jordansexton** [comment]
I think the issue is that create-react-app doesn't process files in the node_modules directory, and this library doesn't transpile from TypeScript to ES5. https://stackoverflow.com/a/64785265 has a reasonable solution using craco to be able to configure babel without ejecting your create-react-app project.

**Comment by jordansexton** [comment]
@richard-fisher I changed the TypeScript build target in the project from `esnext` to `es6`. It should work out of the box in modern browsers.

I also added a starter project using CRA, also with a TS target of `es6`: [`@solana/wallet-adapter-material-ui-starter`](https://github.com/solana-labs/wallet-adapter/tree/master/packages/material-ui-starter)

**Comment by richard-fisher** [comment]
That's great, thanks for that!  Confirmed that it works out of the box in my project now.

**Comment by jordansexton** [comment]
Unfortunately this change broke tree shaking, causing https://github.com/solana-labs/wallet-adapter/issues/69

I've changed the module type back to esnext @ 6d9c3a7e23c7dc7bad2234e828400571634fdc8b

However, the starter projects using CRA and Next.js still work by transpiling these modules.

@richard-fisher please let me know if you need some additional configuration to support Babel specifically, and I'll add it to https://github.com/solana-labs/wallet-adapter/blob/master/FAQ.md#can-i-use-this-with-___

**Comment by richard-fisher** [comment]
I ended up creating a fork because I needed signMessage but I think you have added this now as an optional interface? 

I'll switch back to this repo and do some tests and let you know, thanks!

**Comment by jordansexton** [comment]
Awesome, I appreciate that. Thank you!

**Comment by richard-fisher** [comment]
It works without any problems :)

Just on signMessage it's supported by Sollet too https://github.com/project-serum/sol-wallet-adapter/blob/master/src/index.ts#L188 any chance of including it?

**Comment by jordansexton** [comment]
Sure, please open an issue -- or PR if you use that! It should be very simple to implement using Phantom as a template.
