### ISSUE TITLE
@parcel/resolver-default: Could not load './lib/esm/index.mjs' from module '@solana/wallet-adapter-react-ui' found in package.json#module

### ISSUE THREAD

**Issue by victoredet** [solana-labs/wallet-adapter#400]
**build failiure**
i cloned the wallet-adapter repo and after installing dependencies, i get this error '@parcel/resolver-default: Could not load './lib/esm/index.mjs' from module
'@solana/wallet-adapter-react-ui' found in package.json#module

**To Reproduce**
1. clone the wallet-adaptor repo
2. run yarn install
3.cd packages/starter/react...
4. yarn start
5. see the error

**Expected behavior**
Application will fail to build and start

**Comment by brianchitester** [comment]
did you run `yarn build` in the root directory after running `yarn install`?

**Comment by victoredet** [comment]
Yes I did.
