### ISSUE TITLE
Set global for detecting whether a wallet is supported or not

### ISSUE THREAD

**Issue by olistic** [solana-labs/wallet-adapter#405]
**Is your feature request related to a problem? Please describe.**
We're trying to detect from a browser extension whether a website supports a given wallet and would like to avoid having to inspect the DOM for this.

**Describe the solution you'd like**
The wallet adapters could set a global flag (e.g. `window.__SolanaWalletAdapterExodus__ = true`) so that the browser extension can just look at that.

**Describe alternatives you've considered**
This could be done by inspecting the DOM, like this:

<details>
  <summary>See code</summary>

```js
const isExodusSupported = () => {
    // Open modal.
    const walletAdapterTrigger = document.getElementsByClassName('wallet-adapter-button-trigger')[0]
    walletAdapterTrigger.click()

    // Hide it.
    const walletAdapterModal = document.getElementsByClassName('wallet-adapter-modal')[0]
    walletAdapterModal.style.display = 'none'

    // Search for Exodus.
    const walletButtons = [...document.getElementsByClassName('wallet-adapter-button')]
    const exodusSupported = walletButtons.some(button => /exodus/i.test(button.textContent))

    // Close modal.
    const walletAdapterModalOverlay = document.getElementsByClassName('wallet-adapter-modal-overlay')[0]
    walletAdapterModalOverlay.click()

    // Profit :)
    return exodusSupported
}
```

</details>

**Comment by jordansexton** [comment]
Please see https://github.com/solana-labs/wallet-adapter/issues/215. The goal is to move away from detection based on window (or DOM) properties, and to an array + event based interface.

**Comment by jordansexton** [comment]
Ah, I see that you're coming at a related issue from the other direction -- you have a browser extension wallet, and you're trying to find out if the page you're on is going to show it to a user. Still, I'd like to see if you can incorporate this into #215, which is the tracking issue for the overall effort to improve detection.

**Comment by olistic** [comment]
@jordansexton I read #215 and left [my thoughts about it](https://github.com/solana-labs/wallet-adapter/issues/215#issuecomment-1120433444). However, I think it would be better to handle this outside of that proposal for the following reasons:

- The RFC in #215 is concerned with improving wallet detection by the adapters, whereas this proposal is a new addition to allow wallets to detect whether the web3 site supports them through a wallet adapter or not (other way around, as you identified already).
- The RFC in #215 is a more ambitious change that requires coordination with wallet developers and deprecations, whereas this would be a non-breaking change with almost no moving pieces.
- Handling this as part of #215 would not allow to move as fast as we could, stagnating this while that RFC is discussed.

Thoughts?

**Comment by olistic** [comment]
## Proposal

Modify `BaseWalletAdapter` to write to the global scope (e.g. `window.solanaWallets`) on instantiation and push the wallet `name` to that array.

## Example Implementation

```ts
class BaseWalletAdapter extends EventEmitter<WalletAdapterEvents> implements WalletAdapter {
    abstract name: WalletName;
    // ...

    constructor() {
        window.solanaWallets ??= []
        window.solanaWallets.push(this.name)
    }

    // ...
}
```

@jordansexton If you agree with the above comment and this proposal, I'm happy to submit a PR with this change.
