### ISSUE TITLE
Transaction too large

### ISSUE THREAD

**Issue by laniTheLadyDog** [solana-labs/wallet-adapter#408]
**When I mint a nft at solsea.io and I can confirm the upload to arweave, but conformation of the transaction afterwards runs endless. The console says Error : Transaction too large: 1361 > 1232**

**To Reproduce**
1. Go to [solseas.io](https://solsea.io/create)
2. Fill out the formular and click mint
3. Accept the first transaction
4. See error in console on plugin

**Expected behavior**
Transaction can be confirmed

**Screenshots**
Console Log of plugin window:
![bug pahntom](https://user-images.githubusercontent.com/105109323/167252243-d8ae4cb2-6eb7-4f2c-9ca1-a237cc47c2f8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome and Firefox
 - Version from May 3rd

**Comment by laniTheLadyDog** [comment]
Sorry this is maybe not you. I thought this is the phantom wallet repo, but I might be wrong.

**Comment by jordansexton** [comment]
Yeah, we don't have any control of how individual wallets (or RPC nodes) handle transactions. If this seems to only be happening on Phantom, please report it to them!
