### ISSUE TITLE
Use Context Hooks with Recoil

### ISSUE THREAD

**Issue by callensm** [solana-labs/wallet-adapter#410]
Is there an easy integration path for using the context hooks provided by the wallet adapter providers in order to populate `recoil` atoms or selectors?

I've tried using the standard `atom` effects with `setSelf` and the `selector#get` functions and using the hooks within them to try and build the state but they don't seem to update as I thought it would when the adapter context values change as it would with regular `useEffect` patterns.

**Comment by jordansexton** [comment]
We don't use Github for general support questions. Someone may have an answer in Discord though! We also don't use Recoil in this repository, and your question sounds like a more general one and not something to do specifically with this library.
