### ISSUE TITLE
Can't import the named export 'Connection' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by springrainroni** [solana-labs/wallet-adapter#416]
import React, { FC, useMemo } from 'react';
import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
import {
    GlowWalletAdapter,
    PhantomWalletAdapter,
    SlopeWalletAdapter,
    SolflareWalletAdapter,
    SolletExtensionWalletAdapter,
    SolletWalletAdapter,
    TorusWalletAdapter,
} from '@solana/wallet-adapter-wallets';
import {
    WalletModalProvider,
    WalletDisconnectButton,
    WalletMultiButton
} from '@solana/wallet-adapter-react-ui';
import { clusterApiUrl } from '@solana/web3.js';

// Default styles that can be overridden by your app
require('@solana/wallet-adapter-react-ui/styles.css');
const PhanthomLogin = props => {
// const Wallet: FC = () => {
    // The network can be set to 'devnet', 'testnet', or 'mainnet-beta'.
    const network = WalletAdapterNetwork.Devnet;

    // You can also provide a custom RPC endpoint.
    const endpoint = useMemo(() => clusterApiUrl(network), [network]);

    // @solana/wallet-adapter-wallets includes all the adapters but supports tree shaking and lazy loading --
    // Only the wallets you configure here will be compiled into your application, and only the dependencies
    // of wallets that your users connect to will be loaded.
    const wallets = useMemo(
        () => [
            new PhantomWalletAdapter(),
            new GlowWalletAdapter(),
            new SlopeWalletAdapter(),
            new SolflareWalletAdapter({ network }),
            new TorusWalletAdapter(),
        ],
        [network]
    );

    return (
        <ConnectionProvider endpoint={endpoint}>
            <WalletProvider wallets={wallets} autoConnect>
                <WalletModalProvider>
                    <WalletMultiButton />
                    <WalletDisconnectButton />
                    { /* Your app's components go here, nested within the context providers. */ }
                </WalletModalProvider>
            </WalletProvider>
        </ConnectionProvider>
    );
};
export default PhanthomLogin;
it shows me error
Can't import the named export 'Connection' from non EcmaScript module (only default export is available)

**Comment by vladimir0524** [comment]
I am also have same issue

**Comment by yuloskov** [comment]
> 

Btw, I'm using React 17. However in the docs it requires Reac 18, I think. I was able to make the library work with React 18.

**Comment by andychoww** [comment]
@yuloskov can you share your package.json? I'm encountering the same error

**Comment by Joan1590** [comment]
> I was able to fix this error with the following piece in craco config
> 
> ```
> webpack: {
>     configure: {
>       module: {
>         rules: [
>           {
>             type: 'javascript/auto',
>             test: /\.mjs$/,
>             use: [],
>           },
>         ],
>       },
>     },
>   },
> ```
> 
> However, then I get the error
> 
> ```
> You have tried to  read "publicKey" on a WalletContext without providing one. Make sure to render a WalletProvider as an ancestor of the component that uses WalletContext
> ```

You error is with Context, you need add Provider Context to app.js for use it

**Comment by markgalang** [comment]
Found a way to fix this following this answer [issue#265](https://github.com/solana-labs/wallet-adapter/issues/265#issuecomment-1025285873)

**Comment by Veterangrail** [comment]
> import React, { FC, useMemo } from 'react'; import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react'; import { WalletAdapterNetwork } from '@solana/wallet-adapter-base'; import { GlowWalletAdapter, PhantomWalletAdapter, SlopeWalletAdapter, SolflareWalletAdapter, SolletExtensionWalletAdapter, SolletWalletAdapter, TorusWalletAdapter, } from '@solana/wallet-adapter-wallets'; import { WalletModalProvider, WalletDisconnectButton, WalletMultiButton } from '@solana/wallet-adapter-react-ui'; import { clusterApiUrl } from '@solana/web3.js';
> 
> // Default styles that can be overridden by your app require('@solana/wallet-adapter-react-ui/styles.css'); const PhanthomLogin = props => { // const Wallet: FC = () => { // The network can be set to 'devnet', 'testnet', or 'mainnet-beta'. const network = WalletAdapterNetwork.Devnet;
> 
> ```
> // You can also provide a custom RPC endpoint.
> const endpoint = useMemo(() => clusterApiUrl(network), [network]);
> 
> // @solana/wallet-adapter-wallets includes all the adapters but supports tree shaking and lazy loading --
> // Only the wallets you configure here will be compiled into your application, and only the dependencies
> // of wallets that your users connect to will be loaded.
> const wallets = useMemo(
>     () => [
>         new PhantomWalletAdapter(),
>         new GlowWalletAdapter(),
>         new SlopeWalletAdapter(),
>         new SolflareWalletAdapter({ network }),
>         new TorusWalletAdapter(),
>     ],
>     [network]
> );
> 
> return (
>     <ConnectionProvider endpoint={endpoint}>
>         <WalletProvider wallets={wallets} autoConnect>
>             <WalletModalProvider>
>                 <WalletMultiButton />
>                 <WalletDisconnectButton />
>                 { /* Your app's components go here, nested within the context providers. */ }
>             </WalletModalProvider>
>         </WalletProvider>
>     </ConnectionProvider>
> );
> ```
> 
> }; export default PhanthomLogin; it shows me error Can't import the named export 'Connection' from non EcmaScript module (only default export is available)

https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by ndevmetax** [comment]
> import React, { FC, useMemo } from 'react'; import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react'; import { WalletAdapterNetwork } from '@solana/wallet-adapter-base'; import { GlowWalletAdapter, PhantomWalletAdapter, SlopeWalletAdapter, SolflareWalletAdapter, SolletExtensionWalletAdapter, SolletWalletAdapter, TorusWalletAdapter, } from '@solana/wallet-adapter-wallets'; import { WalletModalProvider, WalletDisconnectButton, WalletMultiButton } from '@solana/wallet-adapter-react-ui'; import { clusterApiUrl } from '@solana/web3.js';
> 
> // Default styles that can be overridden by your app require('@solana/wallet-adapter-react-ui/styles.css'); const PhanthomLogin = props => { // const Wallet: FC = () => { // The network can be set to 'devnet', 'testnet', or 'mainnet-beta'. const network = WalletAdapterNetwork.Devnet;
> 
> ```
> // You can also provide a custom RPC endpoint.
> const endpoint = useMemo(() => clusterApiUrl(network), [network]);
> 
> // @solana/wallet-adapter-wallets includes all the adapters but supports tree shaking and lazy loading --
> // Only the wallets you configure here will be compiled into your application, and only the dependencies
> // of wallets that your users connect to will be loaded.
> const wallets = useMemo(
>     () => [
>         new PhantomWalletAdapter(),
>         new GlowWalletAdapter(),
>         new SlopeWalletAdapter(),
>         new SolflareWalletAdapter({ network }),
>         new TorusWalletAdapter(),
>     ],
>     [network]
> );
> 
> return (
>     <ConnectionProvider endpoint={endpoint}>
>         <WalletProvider wallets={wallets} autoConnect>
>             <WalletModalProvider>
>                 <WalletMultiButton />
>                 <WalletDisconnectButton />
>                 { /* Your app's components go here, nested within the context providers. */ }
>             </WalletModalProvider>
>         </WalletProvider>
>     </ConnectionProvider>
> );
> ```
> 
> }; export default PhanthomLogin; it shows me error Can't import the named export 'Connection' from non EcmaScript module (only default export is available)


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/

**Comment by jordansexton** [comment]
Closing since this issue can be avoided using any of the React starter projects

https://github.com/solana-labs/wallet-adapter#starter-projects
