### ISSUE TITLE
Select wallet modal (wallet-adapter-modal) not showing up after WalletMultiButton is clicked

### ISSUE THREAD

**Issue by sanjayrjs16** [solana-labs/wallet-adapter#419]
**Describe the bug**
I configured next.js project as stated in the docs. When I click on the WalletMultiButton , the Modal that is supposed to show up doesn't. It can be seen in the DOM, but can't see it on the page for some reason.

**To Reproduce**
Create a nextjs project using create-next-app, add chakra UI and set up the rest of the wallet-adapter as mentioned in docs.
Add the` < WalletMultiButton  /> `component at required place. Now upon clicking it, the Select wallet modal can't be seen

**Expected behavior**
Pop up modal should be shown.

**Screenshots**
![Screenshot from 2022-05-19 00-46-51](https://user-images.githubusercontent.com/36541242/169139098-2aa8ba66-d5a0-427b-8bf7-5c32f11dea16.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser : Brave browser
 - Version: Version 1.38.111 Chromium: 101.0.4951.54 (Official Build) (64-bit)](https://brave.com/latest/)

**Additional context**

**Comment by igortullio** [comment]
You need import the styles: `require('@solana/wallet-adapter-react-ui/styles.css');`

**Comment by Veterangrail** [comment]
> **Describe the bug** I configured next.js project as stated in the docs. When I click on the WalletMultiButton , the Modal that is supposed to show up doesn't. It can be seen in the DOM, but can't see it on the page for some reason.
> 
> **To Reproduce** Create a nextjs project using create-next-app, add chakra UI and set up the rest of the wallet-adapter as mentioned in docs. Add the`< WalletMultiButton />`component at required place. Now upon clicking it, the Select wallet modal can't be seen
> 
> **Expected behavior** Pop up modal should be shown.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. ![Screenshot from 2022-05-19 00-46-51](https://user-images.githubusercontent.com/36541242/169139098-2aa8ba66-d5a0-427b-8bf7-5c32f11dea16.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ubuntu 20.04
> * Browser : Brave browser
> * Version: Version 1.38.111 Chromium: 101.0.4951.54 (Official Build) (64-bit)](https://brave.com/latest/)
> 
> **Additional context** Add any other context about the problem here.

https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by ndevmetax** [comment]
> **Describe the bug** I configured next.js project as stated in the docs. When I click on the WalletMultiButton , the Modal that is supposed to show up doesn't. It can be seen in the DOM, but can't see it on the page for some reason.
> 
> **To Reproduce** Create a nextjs project using create-next-app, add chakra UI and set up the rest of the wallet-adapter as mentioned in docs. Add the`< WalletMultiButton />`component at required place. Now upon clicking it, the Select wallet modal can't be seen
> 
> **Expected behavior** Pop up modal should be shown.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. ![Screenshot from 2022-05-19 00-46-51](https://user-images.githubusercontent.com/36541242/169139098-2aa8ba66-d5a0-427b-8bf7-5c32f11dea16.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ubuntu 20.04
> * Browser : Brave browser
> * Version: Version 1.38.111 Chromium: 101.0.4951.54 (Official Build) (64-bit)](https://brave.com/latest/)
> 
> **Additional context** Add any other context about the problem here.


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/

**Comment by sanjayrjs16** [comment]
That solves it! Thanks :)
