### ISSUE TITLE
Provide the Wallet Adapter github pages example un-minified code?

### ISSUE THREAD

**Issue by conard-milliononmars** [solana-labs/wallet-adapter#421]
**Is your feature request related to a problem? Please describe.**
The example clearly demonstrates the modal for selecting a wallet working really nicely. In our experience, the modal looks terrible or doesn't pop at all. It would be great to be able to reference the code of the example instead of just using the example. 
Referring to: https://github.com/solana-labs/wallet-adapter/tree/gh-pages/example

**Describe the solution you'd like**
A version of the code that is not webpack chunked and not minified.

**Comment by jordansexton** [comment]
Pretty sure what you're looking for is https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/example

**Comment by jordansexton** [comment]
This is what gets built and deployed to Github Pages: https://github.com/solana-labs/wallet-adapter/blob/71721308116452f07293bc8f543a6b7f094a75cb/package.json#L26
