### ISSUE TITLE
Solflare signing stopped working

### ISSUE THREAD

**Issue by grimAgent** [solana-labs/wallet-adapter#423]
**Describe the bug**
I updated the `wallet-adapter-wallets` package from `0.14.1` to `0.16.1` and now Solflare signing doesn't work anymore. It opens up the prompt to perform the signing, but after confirming, nothing happens.

Other wallets still work fine. 
 
**To Reproduce**
1. Select and connect to Solflare wallet (extension)
2. Try to sign a message using the `signMessage` method
3. Get the confirmation popup from the extension and click on Approve
4. See how the response of `signMessage` is `undefined` 

**Expected behavior**
Response should be a `Uint8Array` like when using Phantom for example

**Screenshots**

Response using Solflare
<img width="651" alt="Screen Shot 2022-05-19 at 4 47 57 PM" src="https://user-images.githubusercontent.com/90475821/169401963-67672ca3-847b-4088-ba42-77e519f6a5ce.png">

Response using Phantom
<img width="651" alt="Screen Shot 2022-05-19 at 4 47 10 PM" src="https://user-images.githubusercontent.com/90475821/169401849-995e0d12-de1c-4b4a-b392-56c8c393d699.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 99.0.4844.84

**Comment by jordansexton** [comment]
You seem to be calling private APIs of the adapter object. This is unsupported.

Why aren't you using the exposed `adapter.signMessage` method? Can you try that and see if this behavior persists?

**Comment by jordansexton** [comment]
Actually, that's exactly what's going on. Wallets are not guaranteed to have the same interface, which is why these adapters exist. Please us_e the provided API, which _adapts_ them to the same return value (a byte array). Don't try to access private properties of the adapter or the underlying wallet unless you're sure that's what you want.

**Comment by grimAgent** [comment]
Hey @jordansexton I'm not sure why the code was using the private property, this piece of code was done by some else from my team. But I just changed it to use the exposed method, and I'm still getting an undefined response

<img width="520" alt="Screen Shot 2022-05-20 at 2 04 57 PM" src="https://user-images.githubusercontent.com/90475821/169587221-b8541c5b-9635-4d41-9241-79c1ebd058f2.png">

Hopefully you can reopen the issue and have a look. 

Thanks!

**Comment by jordansexton** [comment]
That's because it doesn't return an object with a `signature` property. It returns a `Uint8Array`. Please read the code or the TypeScript docs.

Also, if you use TypeScript in your project, you won't have this issue because it will tell you what the return type is.

**Comment by grimAgent** [comment]
Thank you for your time and sorry to bother you
