### ISSUE TITLE
Can't use wallet-adapter

### ISSUE THREAD

**Issue by vecnazmaga** [solana-labs/wallet-adapter#424]
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }

webpack compiled with 1 error and 1 warning

**Comment by beamsies** [comment]
Same issue here, new to wallet-adapter. 

I can't seem to get this to work. I've tried a few suggestions on the internet to no avail.

**Comment by jordansexton** [comment]
There's a reason the repo has a template for new issues. That template needs to be filled out, not deleted.

Please open a new issue, provide as much context as you can, and especially provide steps that you use to reproduce the issue. Happy to help if you do that!
