### ISSUE TITLE
Cannot get wallet-adapter example or quickstart to work

### ISSUE THREAD

**Issue by beamsies** [solana-labs/wallet-adapter#425]
**Describe the bug**

Awesome library, I did get it up and running but still getting weird errors that I'm not sure how to solve at this time. I also was not able to get any of the example/starters working but will open a separate bug for that. Below is my bug report.

When following the quick-start guide in the readme [located here](https://github.com/solana-labs/wallet-adapter#quick-setup-using-react-ui) I get errors when running and building the react app. I created a react typescript app with create-react-app to get started.

**To Reproduce**
1. ```npx create-react-app my-app --template typescript```
2. ```cd my-app```
3. ```rm -rf node_modules && package-lock.json``` (since I'm using yarn)
4. ```yarn install```
5. `yarn add @solana/wallet-adapter-base \
         @solana/wallet-adapter-react \
         @solana/wallet-adapter-react-ui \
         @solana/wallet-adapter-wallets \
         @solana/web3.js`

6. ```yarn build```

####  ```yarn start``` errors

```
Failed to compile.

Module not found: Error: Can't resolve 'crypto' in '~/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/@toruslabs/eccrypto'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
WARNING in ./node_modules/@solana/buffer-layout/lib/Layout.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '~/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/@solana/buffer-layout/src/Layout.ts' file: Error: ENOENT: no such file or directory, open '~/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/@solana/buffer-layout/src/Layout.ts'

WARNING in ./node_modules/eth-rpc-errors/dist/classes.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '~/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/eth-rpc-errors/src/classes.ts' file: Error: ENOENT: no such file or directory, open '~/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/eth-rpc-errors/src/classes.ts'

WARNING in ./node_modules/eth-rpc-errors/dist/error-constants.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '~/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/eth-rpc-errors/src/error-constants.ts' file: Error: ENOENT: no such file or directory, open '~/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/eth-rpc-errors/src/error-constants.ts'

WARNING in ./node_modules/eth-rpc-errors/dist/errors.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '~/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/eth-rpc-errors/src/errors.ts' file: Error: ENOENT: no such file or directory, open '~/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/eth-rpc-errors/src/errors.ts'

WARNING in ./node_modules/eth-rpc-errors/dist/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '~/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/eth-rpc-errors/src/index.ts' file: Error: ENOENT: no such file or directory, open '~/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/eth-rpc-errors/src/index.ts'

WARNING in ./node_modules/eth-rpc-errors/dist/utils.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '~/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/eth-rpc-errors/src/utils.ts' file: Error: ENOENT: no such file or directory, open '~/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/eth-rpc-errors/src/utils.ts'

WARNING in src/App.tsx
  Line 9:5:   'SolletExtensionWalletAdapter' is defined but never used  @typescript-eslint/no-unused-vars
  Line 10:5:  'SolletWalletAdapter' is defined but never used           @typescript-eslint/no-unused-vars

ERROR in ./node_modules/@toruslabs/eccrypto/browser.js 9:17-34
Module not found: Error: Can't resolve 'crypto' in '~/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/@toruslabs/eccrypto'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }

ERROR in ./node_modules/cipher-base/index.js 3:16-43
Module not found: Error: Can't resolve 'stream' in '~/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/cipher-base'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }

webpack compiled with 2 errors and 7 warnings
```
####  ```yarn build``` errors

```
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'crypto' in '/home/beams/develop/blockchain/solana-wallet-adapter-bug-repro/node_modules/@toruslabs/eccrypto'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**

It was expected I could run ```yarn start``` and ```yarn build``` out-of-the-gate, but I encountered errors that relate to webpack and polyfills.

**Screenshots**
```yarn start``` error:
![image](https://user-images.githubusercontent.com/6827052/169677126-ea34bc15-3cdf-438d-81ce-ba1cf0af103c.png)

```yarn build``` error:
![image](https://user-images.githubusercontent.com/6827052/169677108-bdc068cc-35ac-45e1-8b12-71495503197f.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 21.10 x86_64
 - Browser: Chrome
 - Version: Chrome Version 101.0.4951.64 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
Not applicable 

**Additional context**

Also, as a new user of the wallet-adapter library, I cannot get the examples/starters to work either. I may have to open another bug for that as well. Maybe just try a fresh clone and install to check it out. Thanks!

**Comment by jordansexton** [comment]
Thanks for the report!

So at a glance, this issue is probably related to how CRA5 ships with Webpack 5, which doesn't polyfill a bunch of stuff by default.

But check out this starter project: https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/create-react-app-starter

This uses CRA5 with react-app-rewired and provides the necessary config. You don't need to use the starter project as is, but it should be traightforward to configure your project the same way.

If you do want to run the starter project, the instructions on building from source in the readme should work. Just run `yarn install` and `yarn build` from the root to build all the linked deps, and then build/run from the CRA5 starter directory.

Please let me know if this works!

**Comment by beamsies** [comment]
It worked! Thanks a ton.

It did have a partial build error on the build step, but the example you referenced does work now.

Here's the build error I got from the ```yarn build``` at root:

![image](https://user-images.githubusercontent.com/6827052/169704277-efbb914f-86bd-4c53-907a-75c2c6772046.png)

**Comment by polianamorandi** [comment]
Hello!
Can you help me please too? 
I'm with the same problem but didn't work with your solve. 
![warn](https://user-images.githubusercontent.com/72170872/190040960-bcbdd44f-efcf-48a6-8950-4c56c39ce328.jpeg)

**Comment by jordansexton** [comment]
@polianamorandi please ask any support questions at https://solana.stackexchange.com/
