### ISSUE TITLE
Wallet connection through an iframe

### ISSUE THREAD

**Issue by natbutter** [solana-labs/wallet-adapter#430]
**Is your feature request related to a problem? Please describe.**
When trying to connect a wallet through an iframe the wallet-adapter does not work. The button works, but does not seem to be aware of the the wallet browser extension (e.g. phantom).

**Describe the solution you'd like**
Have the browser extension in the parent window respond with the embedded wallet-adapter button correctly.

**Describe alternatives you've considered**
Various hacks to get it to work. Have tried various options in the parent window iframe embed to get it to expose the connection to the browser extension. 

**Additional context**
Minimal html to reproduce the problem:
```
<html>
    <body>
        <iframe src="https://solana-labs.github.io/wallet-adapter/example/"></iframe>
    </body>
</html>
```

**Comment by jordansexton** [comment]
This is not a limitation of wallet-adapter. This is an intentional security feature of Phantom.

**Comment by phips28** [comment]
We stumbled across this issue, with Sui Wallet.

Is there a workaround to get the event listener connecting iframe and parent window?
