### ISSUE TITLE
WalletNotReadyError: Phantom wallet

### ISSUE THREAD

**Issue by 0x99999** [solana-labs/wallet-adapter#439]
**Describe the bug**
Cannot connect phantom wallet after deployed. It worked on localhost, and after deployed, I got an error

```
adapter.ts:103 Uncaught (in promise) WalletNotReadyError
    at r.<anonymous> (adapter.ts:103:72)
    at f (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at n (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at r.<anonymous> (asyncToGenerator.js:21:12)
    at r.<anonymous> (adapter.ts:53:1)
 ```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: "@solana/wallet-adapter-phantom": "^0.9.3",

**Comment by pimvdmolen** [comment]
Same problem here 😣

**Comment by 0x99999** [comment]
@pimvdmolen @hellomuffintech I solved it, please deploy to https domain.

**Comment by dungkv-1044** [comment]
> @pimvdmolen @hellomuffintech I solved it, please deploy to https domain.

thank you

**Comment by pimvdmolen** [comment]
> @pimvdmolen @hellomuffintech I solved it, please deploy to https domain.

I also found out that it works when you use laravel and run php artisan serve. Or when you for example integrate it within a vue application and run yarn dev. When you run yarn build it didnt work anymore so locally it works when you create a running process for your application.

**Comment by shin101004** [comment]
i use ngrok, its not working.

did you guys deploy it ?
