### ISSUE TITLE
Exodus adapter contains hacks from Phantom adapter

### ISSUE THREAD

**Issue by jordansexton** [solana-labs/wallet-adapter#449]
I noticed when doing some reviews of wallet adapters that the Exodus wallet adapter has some wonky code that was copied from the Phantom adapter:
https://github.com/solana-labs/wallet-adapter/blob/112c54463a3d069e5b756dacf78e20a0711939ae/packages/wallets/exodus/src/adapter.ts#L112-L129

Here's the Phantom code it was copied from:
https://github.com/solana-labs/wallet-adapter/blob/112c54463a3d069e5b756dacf78e20a0711939ae/packages/wallets/phantom/src/adapter.ts#L115-L133

The reason this code is wonky is that Phantom doesn't correctly reject the pending Promise that's created by wallet.connect() when the user closes the Phantom extension window.

Hopefully, Exodus doesn't have this problem. This can be simplified to something like this:
https://github.com/solana-labs/wallet-adapter/blob/112c54463a3d069e5b756dacf78e20a0711939ae/packages/wallets/tokenpocket/src/adapter.ts#L102-L106

**Comment by olistic** [comment]
@jordansexton Will address.
