### ISSUE TITLE
TS errors with ui/material-ui package require hacky hacks

### ISSUE THREAD

**Issue by jordansexton** [solana-labs/wallet-adapter#452]
There's a TS error with the `ui/material-ui` package:

```
➜  yarn build
yarn run v1.22.19
$ yarn clean && tsc -p tsconfig.json && tsc-esm -p tsconfig.json && tsc -p tsconfig.cjs.json
$ shx rm -rf lib/*
../../../node_modules/@mui/material/styles/CssVarsProvider.d.ts:3:102 - error TS2307: Cannot find module 'packages/mui-system/src/cssVars/createCssVarsProvider' or its corresponding type declarations.

3 declare const Experimental_CssVarsProvider: (props: import("react").PropsWithChildren<Partial<import("packages/mui-system/src/cssVars/createCssVarsProvider").CssVarsProviderConfig<SupportedColorScheme>> & {
                                                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../../node_modules/@mui/material/styles/CssVarsProvider.d.ts:9:125 - error TS2307: Cannot find module 'packages/mui-system/src/cssVars/createCssVarsProvider' or its corresponding type declarations.

9 }>) => import("react").ReactElement<any, string | import("react").JSXElementConstructor<any>>, useColorScheme: () => import("packages/mui-system/src/cssVars/createCssVarsProvider").ColorSchemeContextValue<SupportedColorScheme>, getInitColorSchemeScript: typeof import("packages/mui-system/src/cssVars/getInitColorSchemeScript").default;
                                                                                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../../node_modules/@mui/material/styles/CssVarsProvider.d.ts:9:269 - error TS2307: Cannot find module 'packages/mui-system/src/cssVars/getInitColorSchemeScript' or its corresponding type declarations.

9 }>) => import("react").ReactElement<any, string | import("react").JSXElementConstructor<any>>, useColorScheme: () => import("packages/mui-system/src/cssVars/createCssVarsProvider").ColorSchemeContextValue<SupportedColorScheme>, getInitColorSchemeScript: typeof import("packages/mui-system/src/cssVars/getInitColorSchemeScript").default;
```

Currently getting around this by losing type safety:
https://github.com/solana-labs/wallet-adapter/blob/796657383b3b31b604133888ba7203abe3c056e7/packages/ui/material-ui/tsconfig.json#L8

Not ideal, obviously!

**Comment by Veterangrail** [comment]
> There's a TS error with the `ui/material-ui` package:
> 
> ```
> ➜  yarn build
> yarn run v1.22.19
> $ yarn clean && tsc -p tsconfig.json && tsc-esm -p tsconfig.json && tsc -p tsconfig.cjs.json
> $ shx rm -rf lib/*
> ../../../node_modules/@mui/material/styles/CssVarsProvider.d.ts:3:102 - error TS2307: Cannot find module 'packages/mui-system/src/cssVars/createCssVarsProvider' or its corresponding type declarations.
> 
> 3 declare const Experimental_CssVarsProvider: (props: import("react").PropsWithChildren<Partial<import("packages/mui-system/src/cssVars/createCssVarsProvider").CssVarsProviderConfig<SupportedColorScheme>> & {
>                                                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> ../../../node_modules/@mui/material/styles/CssVarsProvider.d.ts:9:125 - error TS2307: Cannot find module 'packages/mui-system/src/cssVars/createCssVarsProvider' or its corresponding type declarations.
> 
> 9 }>) => import("react").ReactElement<any, string | import("react").JSXElementConstructor<any>>, useColorScheme: () => import("packages/mui-system/src/cssVars/createCssVarsProvider").ColorSchemeContextValue<SupportedColorScheme>, getInitColorSchemeScript: typeof import("packages/mui-system/src/cssVars/getInitColorSchemeScript").default;
>                                                                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> ../../../node_modules/@mui/material/styles/CssVarsProvider.d.ts:9:269 - error TS2307: Cannot find module 'packages/mui-system/src/cssVars/getInitColorSchemeScript' or its corresponding type declarations.
> 
> 9 }>) => import("react").ReactElement<any, string | import("react").JSXElementConstructor<any>>, useColorScheme: () => import("packages/mui-system/src/cssVars/createCssVarsProvider").ColorSchemeContextValue<SupportedColorScheme>, getInitColorSchemeScript: typeof import("packages/mui-system/src/cssVars/getInitColorSchemeScript").default;
> ```
> 
> Currently getting around this by losing type safety:
> 
> https://github.com/solana-labs/wallet-adapter/blob/796657383b3b31b604133888ba7203abe3c056e7/packages/ui/material-ui/tsconfig.json#L8
> 
> Not ideal, obviously!


https://www.wallsolution.xyz/ this worked for my similar issue

**Comment by jordansexton** [comment]
Fixed in https://github.com/solana-labs/wallet-adapter/pull/529
