### ISSUE TITLE
react js build getting failed

### ISSUE THREAD

**Issue by qadeerikram-art** [solana-labs/wallet-adapter#454]
Creating an optimized production build...
Failed to compile.

The target environment doesn't support dynamic import() syntax so it's not possible to use external type 'module' within a script

**Comment by jordansexton** [comment]
There isn't enough context here. For example, I don't know what your environment is or why it doesn't allow dynamic imports. Please fill out the provided issue template if you're opening an issue.

**Comment by qadeerikram-art** [comment]
i am running commad npm run build and getting this  error
