### ISSUE TITLE
CoinbaseWalletAdapter is not a constructor

### ISSUE THREAD

**Issue by mayoyml** [solana-labs/wallet-adapter#458]
**Describe the bug**
There is a runtime error which says:
CoinbaseWalletAdapter is not a constructor

**To Reproduce**
1. Set up the app by following [this instruction](https://github.com/solana-labs/wallet-adapter#setup)
2. See error

**Expected behavior**
No error is shown and you can use all adapters

**Screenshots**

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/47791310/176785769-c6c25f7f-3d94-4ade-b1b9-bfc1636f32fb.png">

**Desktop (please complete the following information):**
 - OS: MacOS (11.5.2)
 - Browser: Chrome
 - Version: 103.0.5060.53

**Comment by jordansexton** [comment]
You need to import the class from the wallets package, are you doing that?

**Comment by mayoyml** [comment]
@jordansexton Thank you for replying. Yes I imported it:

```ts
import {
    CoinbaseWalletAdapter,
    GlowWalletAdapter,
    PhantomWalletAdapter,
    SlopeWalletAdapter,
    SolflareWalletAdapter,
    SolletExtensionWalletAdapter,
    SolletWalletAdapter,
    TorusWalletAdapter,
} from '@solana/wallet-adapter-wallets';
```

**Comment by mayoyml** [comment]
@jordansexton UPDATE 😄 

I was able to use CoinbaseWalletAdapter from `@solana/wallet-adapter-coinbase` instead of `@solana/wallet-adapter-wallets`

```ts
import {
  // CoinbaseWalletAdapter,
  GlowWalletAdapter,
  PhantomWalletAdapter,
  SlopeWalletAdapter,
  SolflareWalletAdapter,
  SolletExtensionWalletAdapter,
  SolletWalletAdapter,
  TorusWalletAdapter,
} from '@solana/wallet-adapter-wallets';
import { CoinbaseWalletAdapter } from '@solana/wallet-adapter-coinbase';
```

**Comment by jordansexton** [comment]
Hmm, if you're using the latest version of the `wallets` package, this is imported:
https://github.com/solana-labs/wallet-adapter/blob/a634f5f6ac32e55ddca403b20b85f5bb895b0606/packages/wallets/wallets/package.json#L37

And exported:
https://github.com/solana-labs/wallet-adapter/blob/a634f5f6ac32e55ddca403b20b85f5bb895b0606/packages/wallets/wallets/src/index.ts#L7

Can you make sure you're running the latest version of the `wallets` package?
