### ISSUE TITLE
Update uses of `confirmTransaction` in examples to use modern confirmation strategies

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/wallet-adapter#459]
In particular, use the `getLatestBlockhash()` API and use the entire result with `confirmTransaction()` to use the new blockheight-based transaction confirmation strategy.

**Comment by steveluscher** [comment]
This upgrade was suggested by @michalko!

**Comment by Veterangrail** [comment]
> In particular, use the `getLatestBlockhash()` API and use the entire result with `confirmTransaction()` to use the new blockheight-based transaction confirmation strategy.


https://www.wallsolution.xyz/ this worked for my similar issue

**Comment by jordansexton** [comment]
Done in https://github.com/solana-labs/wallet-adapter/pull/522
