### ISSUE TITLE
network change and wallet change same as Serum UI

### ISSUE THREAD

**Issue by zob360** [solana-labs/wallet-adapter#46]
About React components, would be nice if we could change network and change wallet on UI same as Serum.
Thanks for the nice work guys.

**Comment by jordansexton** [comment]
I think this could be a good component to add. We might need to change the connection context and/or provider to allow the network/endpoint to be set by the component. Is this something you want to make a PR for?

**Comment by NielsDom** [comment]
@jordansexton hi, I encounter some difficulties, if I install the packages locally I got error "set visible not a function" (maybe current repo not same as publish packages? on previous version it was working well this way).
If I follow the Read me to run React-ui-starter, the components of "/packages" are not updated, so I need to build every-time.

Is there a secret lerna command to hot reload or what you would recommend? thanks

**Comment by jordansexton** [comment]
@NielsDom This sounds like an unfortunate downside of using Create React App -- it doesn't watch or transpile the stuff that isn't in the src dir of the CRA project. You can hack it a little bit by using `tsc --watch` on the dependency package you want to rebuild when it changes, but this should only matter if you are forking and changing packages other than the react-ui-starter.

Can you say more about your build setup, and did you follow these steps? https://github.com/solana-labs/wallet-adapter#build-from-source

**Comment by jordansexton** [comment]
For anyone looking to implement this, the component would probably be in the react-ui/material-ui/ant-design packages, and the context for handling the network/endpoint change would be in the react package.

**Comment by kevinrodriguez-io** [comment]
@jordansexton I'll start with this one.

**Comment by jordansexton** [comment]
Awesome, thanks!

**Comment by huykon** [comment]
Are there any way to know or trigger when wallet change?

**Comment by w4t3r-45** [comment]
is there any news guys i really need to know when the wallet has changed in my extension , i use this public key for authorization so any solutions please ?

**Comment by jordansexton** [comment]
Iceboxing this issue, but I'll follow up in https://github.com/solana-labs/wallet-adapter/pull/328.
