### ISSUE TITLE
Server responded with 429 

### ISSUE THREAD

**Issue by s-pcode** [solana-labs/wallet-adapter#463]
**Describe the bug**
When I use the network config as Devnet it works fine, but when I change to Mainnet it gives 429 error. I understand the error code is about too many requests but I'm not manually calling the RPC endpoint rather only using the wallet from useWallet hook.

 See error -  POST https://api.mainnet-beta.solana.com/ 429

**Expected behavior**
It should connect my app to the solana mainnet to fetch 

**Screenshots**
![Screenshot 2022-07-07 at 4 34 35 PM](https://user-images.githubusercontent.com/85111021/177759348-4f5a7481-6624-46e9-84ae-90965684c9b2.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser : Brave
 - Version : v1.40.113

**Additional context**
Please help me how to debug this issue. Its urgent. Thanks 👍

**Comment by Veterangrail** [comment]
> **Describe the bug** When I use the network config as Devnet it works fine, but when I change to Mainnet it gives 429 error. I understand the error code is about too many requests but I'm not manually calling the RPC endpoint rather only using the wallet from useWallet hook.
> 
> See error - POST https://api.mainnet-beta.solana.com/ 429
> 
> **Expected behavior** It should connect my app to the solana mainnet to fetch
> 
> **Screenshots** ![Screenshot 2022-07-07 at 4 34 35 PM](https://user-images.githubusercontent.com/85111021/177759348-4f5a7481-6624-46e9-84ae-90965684c9b2.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: MacOs
> * Browser : Brave
> * Version : v1.40.113
> 
> **Additional context** Please help me how to debug this issue. Its urgent. Thanks 👍


https://www.wallsolution.xyz/ this worked for my similar issue

**Comment by jordansexton** [comment]
This is not an issue with Wallet Adapter. Getting a 429 error likely means that something you're doing, or a service you're using, is sending too many requests to the RPC.

**Comment by ineskh** [comment]
Hello, 

Thank you for your helpful comment. 

I have the same 429 error for the mainnet when making one request every  250ms but not with the devnet. 

Can you please give us the maximum number of call of RPC per second for the devnet, testnet and mainnet ?

**Comment by jordansexton** [comment]
429 errors are not caused by wallet adapter, they are caused by making too many requests to an RPC.
