### ISSUE TITLE
Demo on Mobile chrome won't launch phantom app

### ISSUE THREAD

**Issue by jasan-s** [solana-labs/wallet-adapter#464]
**Describe the bug**
On chrome mobile I tried the GitHub demo and it does not launch phantom app.(installed)  when the phantom is clicked on the dialog/modal 

On desktop the phantom chrome extension is detected successfully in the demo.

**Comment by Veterangrail** [comment]
> **Describe the bug** On chrome mobile I tried the GitHub demo and it does not launch phantom app.(installed) when the phantom is clicked on the dialog/modal
> 
> On desktop the phantom chrome extension is detected successfully in the demo.


https://www.wallsolution.xyz/ this worked for my similar issue

**Comment by Ash-exp** [comment]
Same issue !! I guess it's only compatible with the browser extension and as because in mobile browsers these extensions don't support the wallet adaptor is unable to detect the wallet.

**Comment by jordansexton** [comment]
That's correct, this is not an issue that Wallet Adapter can fix on its own. However, the mobile wallet adapter that is coming soon as a part of the Solana Mobile Stack will integrate with Wallet Adapter and will work with Chrome.

I'll leave this open for now. It's not necessary to comment further, but please subscribe to the issue and you'll get an update when it's closed (when mobile wallet adapter is fully integrated).

**Comment by EkaterinaEvseeva** [comment]
@jordansexton Do we know how soon the mobile wallet adapter will be ready?

**Comment by ndevmetax** [comment]
> **Describe the bug** On chrome mobile I tried the GitHub demo and it does not launch phantom app.(installed) when the phantom is clicked on the dialog/modal
> 
> On desktop the phantom chrome extension is detected successfully in the demo.


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/

**Comment by jordansexton** [comment]
MWA is ready! https://github.com/solana-labs/wallet-adapter/pull/598 is going to be merged very soon.

Release Candidate upgrade guide here: https://github.com/solana-labs/wallet-adapter/issues/604

Closing this since we finally have a clear direction this is headed. Thanks for your patience everyone.
