### ISSUE TITLE
Phantom - RPC Error: Signature verification failed

### ISSUE THREAD

**Issue by sunnyzhifei** [solana-labs/wallet-adapter#466]
**Describe the bug**
when i sendTransaction , its fail ,and error : 
Phantom - RPC Error: Signature verification failed

**To Reproduce**
1.  my code :
```  es6
 const { publicKey, sendTransaction } = useWallet();
 .....

 const buyNFT_v1 = useCallback(
    async (instructionData: string) => {
      if (!publicKey) throw new WalletNotConnectedError();
      const keys: AccountMeta[] = await generateAccountList(
        currentMintAddress,
        publicKey,
        connection
      );
      let allocateTransaction = new Transaction({
        feePayer: publicKey,
      });
      const databuf = Buffer.from(instructionData, "hex");
      allocateTransaction.add(
        new TransactionInstruction({
          keys: keys,
          programId: new PublicKey(
            "MEisE1HzehtrDpAAT8PnLHjpSSkRYakotTuJRPjTpo8"
          ),
          data: databuf,
        })
      );
      try {
        const signature = await sendTransaction(
          allocateTransaction,
          connection
        );
        await connection
          .confirmTransaction(signature, "processed")
          .then((a) => {
            busy_transaction.current = false;
            setTransactionData("");
          });
      } catch (e) {
        busy_transaction.current = false;
        setTransactionData("");
      }
    },
    [
      publicKey,
      sendTransaction,
      connection,
      currentMintAddress,
      busy_transaction,
    ]
  );
```
2. when the phantom pop approve window, i click approve ,and then failed ,console show `Phantom - RPC Error: Signature verification` failed, this is a shot below:

**Expected behavior**
i want fix this ,and dont fail

**Screenshots**
![image](https://user-images.githubusercontent.com/34208561/178222452-c19aa94f-a249-40b0-bcd1-10d21f34429f.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome 
 - Version 99.0.4844.84
**Additional context**
- Phantom version : 22.6.27.3

**Comment by Veterangrail** [comment]
> **Describe the bug** when i sendTransaction , its fail ,and error : Phantom - RPC Error: Signature verification failed
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. my code :
> 
> ```js
>  const { publicKey, sendTransaction } = useWallet();
>  .....
> 
>  const buyNFT_v1 = useCallback(
>     async (instructionData: string) => {
>       if (!publicKey) throw new WalletNotConnectedError();
>       const keys: AccountMeta[] = await generateAccountList(
>         currentMintAddress,
>         publicKey,
>         connection
>       );
>       let allocateTransaction = new Transaction({
>         feePayer: publicKey,
>       });
>       const databuf = Buffer.from(instructionData, "hex");
>       allocateTransaction.add(
>         new TransactionInstruction({
>           keys: keys,
>           programId: new PublicKey(
>             "MEisE1HzehtrDpAAT8PnLHjpSSkRYakotTuJRPjTpo8"
>           ),
>           data: databuf,
>         })
>       );
>       try {
>         const signature = await sendTransaction(
>           allocateTransaction,
>           connection
>         );
>         await connection
>           .confirmTransaction(signature, "processed")
>           .then((a) => {
>             busy_transaction.current = false;
>             setTransactionData("");
>           });
>       } catch (e) {
>         busy_transaction.current = false;
>         setTransactionData("");
>       }
>     },
>     [
>       publicKey,
>       sendTransaction,
>       connection,
>       currentMintAddress,
>       busy_transaction,
>     ]
>   );
> ```
> 
> 2. when the phantom pop approve window, i click approve ,and then failed ,console show `Phantom - RPC Error: Signature verification` failed, this is a shot below:
> 
> **Expected behavior** i want fix this ,and dont fail
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/34208561/178222452-c19aa94f-a249-40b0-bcd1-10d21f34429f.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: windows
> * Browser chrome
> * Version 99.0.4844.84
>   **Additional context**
> * Phantom version : 22.6.27.3


https://www.wallsolution.xyz/ this worked for my similar issue

**Comment by jordansexton** [comment]
I don't think there's enough context for me to tell what's going on here, and the code isn't something I can test.

Do you have a reason to think this is an issue with Wallet Adapter, the Phantom adapter, or Phantom itself?

Are you possibly attempting to send the transaction on devnet and Phantom is set to to use mainnet or vice versa?

**Comment by jordansexton** [comment]
@bfriel any ideas?

**Comment by GeneralMB** [comment]
same like u

**Comment by smrnjeet222** [comment]
having similar issue here , https://havana.ag/
weird that all other wallets work, except for phantom

**Comment by bfriel** [comment]
Hey @smrnjeet222 , are there any instances in your codebase where you are mutating a transaction in place via `signTransaction`? See https://twitter.com/bfriel_/status/1604641581855698944 for more context on this

**Comment by smrnjeet222** [comment]
Thank You so much @bfriel , this was the exact issue, been looking for a fix for days 😅.
I got very helpful response from phantom support too, thank you ❤️
