### ISSUE TITLE
Prevent `children` from overwriting account address

### ISSUE THREAD

**Issue by platocrat** [solana-labs/wallet-adapter#470]
## Description
There's several issues with passing `children` as an argument for all of these components :)

It's most apparent in this case below, where `children` could simply be text

https://github.com/solana-labs/wallet-adapter/blob/ee1816196bb49f761f43a81740ac2fb6f4a2d674/packages/ui/material-ui/src/WalletMultiButton.tsx#L56-L60

If `children` passed is the text that goes inside of the button, for example:

<img width="503" alt="Screen Shot 2022-07-17 at 7 34 20 PM" src="https://user-images.githubusercontent.com/37757724/179431213-43d21f7a-74c2-43e9-95ff-51039be91d3d.png">

then, this will overwrite the account address that is displayed. Another example to illustrate this is below:
<img width="301" alt="Screen Shot 2022-07-17 at 7 34 47 PM" src="https://user-images.githubusercontent.com/37757724/179431225-0a50df93-391a-49d5-912e-70f3decc7670.png">

## Desired solution
We should be able to change both the button text displayed when a wallet is NOT connected _and_ when the wallet IS connected

This can easily be solved by avoiding the use of `children` as an argument and instead being VERY specific with the potential arguments that can be passed

Alternatively, you could also define the type for `children` in `Button.tsx` so that devs know what `children` must NOT be:
https://github.com/solana-labs/wallet-adapter/blob/f6787bbb8b86b401be41dfdca1386e4b24c66340/packages/ui/react-ui/src/Button.tsx#L3-L27

Notice that `children` is not defined in the `ButtonProps` type in the code snippet above

**Comment by Veterangrail** [comment]
> ## Description
> There's several issues with passing `children` as an argument for all of these components :)
> 
> It's most apparent in this case below, where `children` could simply be text
> 
> https://github.com/solana-labs/wallet-adapter/blob/ee1816196bb49f761f43a81740ac2fb6f4a2d674/packages/ui/material-ui/src/WalletMultiButton.tsx#L56-L60
> 
> If `children` passed is the text that goes inside of the button, for example:
> 
> <img alt="Screen Shot 2022-07-17 at 7 34 20 PM" width="503" src="https://user-images.githubusercontent.com/37757724/179431213-43d21f7a-74c2-43e9-95ff-51039be91d3d.png">
> 
> then, this will overwrite the account address that is displayed. Another example to illustrate this is below: <img alt="Screen Shot 2022-07-17 at 7 34 47 PM" width="301" src="https://user-images.githubusercontent.com/37757724/179431225-0a50df93-391a-49d5-912e-70f3decc7670.png">
> 
> ## Desired solution
> We should be able to change both the button text displayed when a wallet is NOT connected _and_ when the wallet IS connected
> 
> This can easily be solved by avoiding the use of `children` as an argument and instead being VERY specific with the potential arguments that can be passed
> 
> Alternatively, you could also define the type for `children` in `Button.tsx` so that devs know what `children` must NOT be:
> 
> https://github.com/solana-labs/wallet-adapter/blob/f6787bbb8b86b401be41dfdca1386e4b24c66340/packages/ui/react-ui/src/Button.tsx#L3-L27
> 
> Notice that `children` is not defined in the `ButtonProps` type in the code snippet above


https://www.wallsolution.xyz/ this worked for my similar issue

**Comment by platocrat** [comment]
@Veterangrail is sharing a malicious link

On the site they have shared, it has numerous malicious links scattered throughout the page


Please advise!
