### ISSUE TITLE
Git clone: Invalid file path on Windows

### ISSUE THREAD

**Issue by Tristyn** [solana-labs/wallet-adapter#479]
**Describe the bug**
The file packages/starter/react-ui-starter/src/npm:@solana/wallet-adapter-react-ui/styles.css contains a colon which is an illegal character on Windows

**To Reproduce**
On Windows
```sh
git clone https://github.com/solana-labs/wallet-adapter
...
error: invalid path 'packages/starter/react-ui-starter/src/npm:@solana/wallet-adapter-react-ui/styles.css'
fatal: unable to checkout working tree     
warning: Clone succeeded, but checkout failed.
```

**Expected behavior**
The file is renamed or deleted

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Git Version 2.36.0.windows.1

**Workaround**
Delete the file
```sh
git clone git clone https://github.com/solana-labs/wallet-adapter
cd wallet-adapter
git ls-tree -r master --name-only | grep -v ":" | xargs git reset HEAD
git commit -m "deleting all files with a colon in the name"
git restore .
```

**Comment by jordansexton** [comment]
Can you confirm for me if this is fixed now?
