### ISSUE TITLE
Feature request: Get all wallets residing in Phantom wallet chrome extension

### ISSUE THREAD

**Issue by DitJee** [solana-labs/wallet-adapter#483]
**Is your feature request related to a problem? Please describe.**
I am working on how to display all wallets residing in Phantom wallet chrome extension, so the user can select him/her desired wallet.

**Describe the solution you'd like**
The ideal solution would be the ability to call, for example, `getAllWallets()` function which returns all wallets  residing in Phantom wallet chrome extension as shown in the figure below.
![image](https://user-images.githubusercontent.com/56587469/180702459-e5f5fd6a-71e4-4f9e-aef1-9d268c6e694a.png)

**Comment by jordansexton** [comment]
This is something you'd have to take up with Phantom. Wallet adapter can't invent APIs for wallets. :)
