### ISSUE TITLE
Javascript compatible package

### ISSUE THREAD

**Issue by nishant537** [solana-labs/wallet-adapter#484]
**Is your feature request related to a problem? Please describe.**
As per my knowledge, the current wallet adapter plugin can only be integrated with a react web app. I am not able to integrate the plugin with my html/css/js website.

**Describe the solution you'd like**
I wish to integrate the functionality on my html/css/js website which is a payment gateway for accepting SOL and SPL-TOKENS. 

**Describe alternatives you've considered**
I have tried translating the react typescript code to javascript functions but couldn't make it work. I also tried using cdn for these packages but no clear documentation has been provided for using these packages in vanilla js.

**Comment by jordansexton** [comment]
> As per my knowledge, the current wallet adapter plugin can only be integrated with a react web app.

Nope, React is definitely the suggested way of using it, but you can import the `@solana/wallet-adapter-wallets` package and use the adapters in it directly. You lose the [automatic state management](https://github.com/solana-labs/wallet-adapter/blob/master/packages/core/react/src/WalletProvider.tsx) that you get from the React package, but you can do everything it can do without React.
