### ISSUE TITLE
SolanaMobileWalletAdapter cluster setting doesn't allow a private validator

### ISSUE THREAD

**Issue by SvenDowideit** [solana-labs/wallet-adapter#489]
I'm doing some local testing and development, using a local validator setup on one of my servers, and thus am setting the endpoint to `http://10.10.10.190:8899`. however, SolanaMobileWalletAdapter's `cluster: Cluster` is required, and requires it to be set to one of 

`type Cluster = "devnet" | "testnet" | "mainnet-beta";`

```
    const wallets = useMemo(
        () => [
            new SolanaMobileWalletAdapter({
                appIdentity: { name: 'DAOnetes' },
                authorizationResultCache: createDefaultAuthorizationResultCache(),
                cluster: endpoint,
            }),
```

```
Type '"http://10.10.10.190:8899"' is not assignable to type 'Cluster'.ts(2322)
index.d.ts(24, 9): The expected type comes from property 'cluster' which is declared here on type '{ appIdentity: Readonly<{ uri?: string | undefined; icon?: string | undefined; name?: string | undefined; }>; authorizationResultCache: AuthorizationResultCache; cluster: Cluster; }'
```

**Comment by SvenDowideit** [comment]
mmm, and while I'm here, the example on the project README.md leaves out `cluster`, but my eslint complains bitterly

**Comment by jordansexton** [comment]
cc @steveluscher

At a glance, I suspect the right place for this issue is https://github.com/solana-mobile/mobile-wallet-adapter

It should probably be closed here, but I'll leave that to you two.

**Comment by steveluscher** [comment]
Thanks for the note @SvenDowideit! This is very much intentional. Post this is a question on https://solana.stackexchange.com (ie. ‘why does SMWA not accept an endpoint URL’) and post a link to it back here. I'll be happy to go into details there.
