### ISSUE TITLE
account changed event

### ISSUE THREAD

**Issue by TimonPeng** [solana-labs/wallet-adapter#49]
Should we implement a new event to make it easier for users to switch wallet?

**Comment by jordansexton** [comment]
Yeah, I think this would be a really nice feature. Maybe we can start with making a list of which wallets support switching accounts, and what interfaces and events they provide to do it?

**Comment by TimonPeng** [comment]
I think almost all extensions and web wallets can support that, except apps and ledger(hardware)? under my observation.

**Comment by jordansexton** [comment]
Ledger supports multiple accounts too. The issue (and the work to implement this) is adapting each of their different interfaces and behaviors to support this in a generalized way, which requires an in-depth understanding of what each one does.

**Comment by jordansexton** [comment]
Basically, if someone wants to implement this, the first step is to go through the wallet adapters we have and do a writeup of

1. Is account switching supported?
2. How is it supported (is it a method we call, is it an array of accounts, what format are they in, etc.)
3. What internal events and interfaces do we need to adapt?

And then, what's the common denominator of all these?

**Comment by jordansexton** [comment]
@TimonPeng is this something you want to try to make a PR for?

**Comment by TimonPeng** [comment]
- Coin98 https://docs.coin98.com/products/developer-guide/solana-dapps-integration#list-of-events

**Comment by TimonPeng** [comment]
I'm not sure which one is best

```
const onChange = (accounts) => setAccount(accounts.length > 0 ? accounts[0] : null);
```

```
const onChange = (account) => setAccount(account);
```

```
const onChange = () => {
  const { publicKey } = adapter;
  setAccount(publicKey);
};
```

**Comment by cryptogosu** [comment]
@TimonPeng Are you working on this at this time?

**Comment by spencergray96** [comment]
Any update on this?

**Comment by jordansexton** [comment]
Just got back from vacation! I'll be reviewing the work in #109 soon.

**Comment by jordansexton** [comment]
Iceboxing this issue, but I'll follow up with the work in #109

**Comment by samia-invozone** [comment]
How can i detect in my React App if user switches his wallet from Phantom extension?

**Comment by Mahdibayat** [comment]
same issue, need switch account event

**Comment by glitch-txs** [comment]
have this been resolved somewhere? We would like to add this event to the WalletConnect v2 protocol but would like to follow an already established standard.
