### ISSUE TITLE
WalletNotSelectedError - trying to connect wallet to my dApp

### ISSUE THREAD

**Issue by ricardo-passos** [solana-labs/wallet-adapter#490]
**Describe the bug**
I'm trying to connect my phantom wallet to my dApp. I've created a button; when it's clicked, it should fire a callback function that would open the Phantom plugin. Instead, the error in the title is thrown and the wallet isn't connected.

**To Reproduce**
```tsx
import { createContext, useContext } from 'react'
import {
  ConnectionProvider,
  WalletProvider as SolanaWalletProvider
} from '@solana/wallet-adapter-react'
import { WalletAdapterNetwork } from '@solana/wallet-adapter-base'
import { PhantomWalletAdapter } from '@solana/wallet-adapter-phantom'
import { clusterApiUrl } from '@solana/web3.js'
import { useWallet as useSolanaWallet } from '@solana/wallet-adapter-react'

const WalletContext = createContext({})
const WalletProvider = ({ children }) => {
    const { publicKey, connect } = useSolanaWallet()
    
    async function handleWalletConnection() {
        try {
            await connect()
            // `window?.phantom?.solana.connect()` works
            window.alert(publicKey?.toString())
        } catch (err) {
            console.log('error connecting wallet:', err)
        }
    }

    return (
        <WalletContext.Provider value={{ handleWalletConnection }}>
            {children}
        </WalletContext.Provider>
    )
}
const useWallet = () => useContext(WalletContext)

const ContextProviders = ({ children }) => {
    return <ConnectionProvider
        endpoint={clusterApiUrl(WalletAdapterNetwork.Mainnet)}
      >
        <SolanaWalletProvider
          wallets={[new PhantomWalletAdapter()]}
          autoConnect
        >
          <WalletProvider>
              {children}
          </WalletProvider>
        </SolanaWalletProvider>
      </ConnectionProvider>
}

const Home = () => {
    const { handleWalletConnection } = useWallet()

    return (
        <button onClick={handleWalletConnection}>
            Connect Phantom wallet
        </button>
    )
}

const App = () => {
    return (
      <ContextProviders>
          <Home />
      </ContextProviders>
    )
}
```

**Expected behavior**
When the button is clicked, it should open the Phantom pop-up to connect my wallet to my dApp.

**Desktop (please complete the following information):**
 - OS: Windows 10 (code is in WSL2, but the browser is running on Windows)
 - Browser: Edge (chromium-based)

**Additional context**
Could the fact that I'm calling `useSolanaWallet` hook inside my `WalletContext` be the problem? As stated in the code (the line commented out), if I access the Phantom API directly, I can connect my wallet.

**Comment by jordansexton** [comment]
Hi, we don't handle developer support questions on Github. For other questions, please ask on https://solana.stackexchange.com/

It looks like you're creating your contexts all wrong. For example:

```tsx
const WalletContext = createContext({})
```

This is, conceptually, completely invalid. You can't just create an empty context, pass it around, and expect it to work.

Please start with the starter projects or the simple example code found here: https://github.com/solana-labs/wallet-adapter#setup
