### ISSUE TITLE
Compile error: Module not found '@ledgerhq/devices/hid-framing'

### ISSUE THREAD

**Issue by dFohlen** [solana-labs/wallet-adapter#499]
**Describe the bug**
Compiling React app fails due to Ledger dependencies. A module named '@ledgerhq/devices/hid-framing' is not found.

**To Reproduce**
1. Create test React app
2. Add Solana-Wallet-Adapter as described in the Readme.md
3. Compile error `yarn build`: 
     ```
     yarn run v1.22.19
     $ react-scripts build
     Creating an optimized production build...
     Failed to compile.

     ./node_modules/@ledgerhq/hw-transport-webhid/lib-es/TransportWebHID.js
     Cannot find module: '@ledgerhq/devices/hid-framing'. Make sure this package is installed.

     You can install this package by running: yarn add @ledgerhq/devices/hid-framing.


     error Command failed with exit code 1.
     info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     ```

**Expected behavior**
The React app should compile without any errors. The Ledger dependency has been moved because, `yarn add @ledgerhq/devices/hid-framing` turn also into an error:
```
yarn add v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@ledgerhq%2fdevices/hid-framing: Request \"https://registry.yarnpkg.com/@ledgerhq%2fdevices/hid-framing\" returned a 405".
info If you think this is a bug, please open a bug report with the information provided in "/Users/volker/Projekte/solana/nft-geocaching/react-app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Screenshots**
![Bildschirmfoto 2022-08-03 um 17 53 32](https://user-images.githubusercontent.com/28490587/182654203-2ee34875-2e6c-4072-8f41-6798b35b25c8.png)

**Additional context**
package.json:

```
 "dependencies": {
    "@solana-mobile/wallet-adapter-mobile": "^0.0.1-alpha.8",
    "@solana/spl-token": "^0.2.0",
    "@solana/wallet-adapter-base": "^0.9.9",
    "@solana/wallet-adapter-react": "^0.15.8",
    "@solana/wallet-adapter-react-ui": "^0.9.11",
    "@solana/wallet-adapter-wallets": "^0.17.0",
    "@types/react": "^18.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.1.0",
    "react-range": "^1.8.12",
    "react-router-dom": "^6.3.0",
    "react-scripts": "^4.0.3",
    "typescript": "^4.5.5"
 }
```

**Comment by dFohlen** [comment]
Edit: Is already addressed to Ledger: https://github.com/LedgerHQ/ledger-live/issues/763

**Comment by jordansexton** [comment]
Based on https://github.com/LedgerHQ/ledger-live/issues/763#issuecomment-1198967469 and subsequent comments it sounds like this is a problem with your build tool. I see you're using `react-scripts` (aka CRA) 4, which uses Webpack 4, leading to this issue. This is not supported (CRA 5 is required, along with react-app-rewired). Check out the [CRA 5 starter project](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/create-react-app-starter).

**Comment by jordansexton** [comment]
Getting some other reports of this happening, reopened

**Comment by jordansexton** [comment]
This appears to be an issue with the latest release of the dependencies, see https://github.com/LedgerHQ/ledger-live/issues/763#issuecomment-1205887506

Will fix this by pinning the previous version.
