### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by PomegranateApps** [solana-labs/wallet-adapter#502]
**Describe the bug**
I'm not able to build the project with `yarn build`.

**To Reproduce**
git clone https://github.com/solana-labs/wallet-adapter.git
cd wallet-adapter
yarn install
yarn build

**Expected behavior**
It should build.

**Screenshots**
<img width="476" alt="Error" src="https://user-images.githubusercontent.com/7399834/182953870-514e9052-4479-4659-8264-bbdc60b19fb2.png">

```
lerna notice cli v5.3.0
lerna info versioning independent
lerna info Executing command in 45 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in '@solana/wallet-adapter-base'
lerna ERR! yarn run build stderr:
No matches found: "lib/*"
lerna ERR! yarn run build exited 1 in '@solana/wallet-adapter-base'
```

**Desktop (please complete the following information):**
 - OS: Mac 12.3.1

**Comment by PomegranateApps** [comment]
Node Version: 16.16.0
Yarn Version: 3.2.1

**Comment by jordansexton** [comment]
This should be fixed now, please try again.

**Comment by jordansexton** [comment]
Closing this since I can build from the project root. I see your Yarn version is listed as 3.2.1, but this project uses legacy yarn (I have 1.22.19).

**Comment by PomegranateApps** [comment]
I tried with yarn 1.22.19, but I'm getting this error now.

```
🚨 Build failed.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:
@parcel/core: Failed to resolve '@ledgerhq/devices/hid-framing' from 
'./node_modules/@ledgerhq/hw-transport-webhid/lib-es/TransportWebHID.js'
  /TransportWebHID.js:7:24
    6 |         return extendStatics(d, b);
  > 7 |     };
  >   |       ^
    8 |     return function (d, b) {
    9 |         if (typeof b !== "function" && b !== null)
error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in '@solana/wallet-adapter-react-ui-starter'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
```

**Comment by jordansexton** [comment]
This was fixed in https://github.com/solana-labs/wallet-adapter/commit/88f3576894702d8978172ad5673cd17a53148e68

Make sure you're pulling the latest from master, and run `yarn nuke && yarn install` before building.

**Comment by Skandesh** [comment]
> Closing this since I can build from the project root. I see your Yarn version is listed as 3.2.1, but this project uses legacy yarn (I have 1.22.19).


Facing the same issue in WSL, Distro -  Kali linux 

node version - 18.7.0
yarn version - 3.2.2


(I tried downgrading `yarn` to 1.22.19 using `yarn set version 1.22.19` but it doesn't get downgraded)

Any help on this would be much helpful.
