### ISSUE TITLE
Make 'Get Started Wallet' configurable

### ISSUE THREAD

**Issue by taycaldwell** [solana-labs/wallet-adapter#503]
**Is your feature request related to a problem? Please describe.**
Can't configure getting started wallet for modal

**Describe the solution you'd like**
I'd like to be able to modify / configure which wallet users are directed to using the' Get started' button when no wallet is installed.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ndevmetax** [comment]
> **Is your feature request related to a problem? Please describe.** Can't configure getting started wallet for modal
> 
> **Describe the solution you'd like** I'd like to be able to modify / configure which wallet users are directed to using the' Get started' button when no wallet is installed.
> 
> **Describe alternatives you've considered** N/A
> 
> **Additional context** N/A


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/

**Comment by jordansexton** [comment]
Closing since this is an instance/symptom of https://github.com/solana-labs/wallet-adapter/issues/394, which we will address. Thanks for your patience on this, we're going to revamp the Getting Started UX. Please subscribe to that issue!
