### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by adigarg** [solana-labs/wallet-adapter#51]
When using the react ui starter or material ui starter - both use create react app, get an error

`./src/Wallet.tsx
Module not found: Can't resolve '@solana/wallet-adapter-base' in '/Users/aditig/Documents/git/jelly-beasts-nft/wallet-adapter/packages/react-ui-starter/src'`

**Comment by jordansexton** [comment]
Did you follow the instructions on building from source?

 https://github.com/solana-labs/wallet-adapter#build-from-source

**Comment by adigarg** [comment]
Have nextjs in the project, saw the other issue, closing this one.
