### ISSUE TITLE
Ledger-hq issue.

### ISSUE THREAD

**Issue by raghibislam** [solana-labs/wallet-adapter#512]
This issue is occurred when trying to install node_modules.

Might be due to depreciation of ledger: https://github.com/LedgerHQ/ledgerjs
![image](https://user-images.githubusercontent.com/46419375/184266625-b874f1e9-7354-4fdb-8fb4-be3f872d3e99.png)

**Comment by jordansexton** [comment]
Please see https://github.com/solana-labs/wallet-adapter/issues/499#issuecomment-1205902623

If you're still having an issue, please fill out the bug template instead of wiping it.
