### ISSUE TITLE
Unable to use example from build from source

### ISSUE THREAD

**Issue by r4881t** [solana-labs/wallet-adapter#52]
So, I am new and trying to get this right. I followed the steps on building from source. So I cloned the repo, yarn install and on running the react-ui-starter I get the error

```
Failed to compile.

./src/Wallet.tsx
Module not found: Can't resolve '@solana/wallet-adapter-base' in '/Users/abcxyz/workspace/crypto_projects/wallet-adapter/packages/react-ui-starter/src'
```

Any directions are highly appreciated. Thanks

**Comment by jordansexton** [comment]
> So I cloned the repo, yarn install and on running the react-ui-starter I get the error

The [third step](https://github.com/solana-labs/wallet-adapter#build-from-source) is to run `yarn build` from the base directory, did you do that?

**Comment by jordansexton** [comment]
I just ran all the instructions from scratch on building from source without issue. Please make sure you follow the instructions and run the build, and if there's still an issue, please reopen.

**Comment by r4881t** [comment]
I retried everything and it worked. I must have missed the step. Sorry! And thanks a lot for pointing me correctly.
