### ISSUE TITLE
`particle` wallet is missing in npm modules

### ISSUE THREAD

**Issue by katopz** [solana-labs/wallet-adapter#520]
**Describe the bug**
- `particle` missing in `node_modules` and cause error when import

**To Reproduce**
1.  use examples from `/packages/starter/material-ui-starter/`
2.  use `"@solana/wallet-adapter-wallets": "^0.18.1",` // not "@solana/wallet-adapter-wallets": "*",
3.  yarn start 

**Expected behavior**
Can start

**Screenshots**
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/97060/185106515-34091b73-b730-4e7e-b8bf-021b1450f973.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - chrome
 - Version 104.0.5112.79 (Official Build) (x86_64)

**Work around**
Delete this line and everything fine.
```ts
export * from '@solana/wallet-adapter-particle';
```

**Comment by jordansexton** [comment]
Hmm not sure why it's not working for you, it's definitely published:
```
➜  wallet-adapter git:(master) npm info @solana/wallet-adapter-particle

@solana/wallet-adapter-particle@0.1.0 | Apache-2.0 | deps: 2 | versions: 1
...
published 2 days ago by jordansexton <jordan@jordansexton.com>
```

The published `@solana/wallet-adapter-wallets` package lists it as a dependency. Try deleting your project's `node_modules` dir and doing a fresh `yarn install` / `npm install`.

**Comment by katopz** [comment]
Completely copy out of folder `packages` seem to work. Maybe `yarn` workspace is mess up for me. 😳
