### ISSUE TITLE
SafePal wallet not work

### ISSUE THREAD

**Issue by nftmsg** [solana-labs/wallet-adapter#535]
After import the SafePal wallet
import {
  GlowWalletAdapter,
  PhantomWalletAdapter,
  SlopeWalletAdapter,
  SolflareWalletAdapter,
  SafePalWalletAdapter,
} from "@solana/wallet-adapter-wallets";

and try to connect through                  

<WalletMultiButton className="connect_but" />

It shows the following error
next-dev.js?3515:20 WalletPublicKeyError: Cannot read properties of undefined (reading '_bn')
    at SafePalWalletAdapter.connect (adapter.mjs?4d2b:58:1)
    at async eval (WalletProvider.mjs?8dda:125:1)

and it is working fine with Phantom wallet.

**Comment by jordansexton** [comment]
@SafePalWallet @bryanForSafe

**Comment by jordansexton** [comment]
Closing since this isn't the place for issues with specific wallets. If you have a reason to believe the issue is caused by the code in https://github.com/solana-labs/wallet-adapter/blob/master/packages/wallets/safepal/src/adapter.ts, please expand on this and we can reopen it.
