### ISSUE TITLE
@solana/wallet-adapter-base 0.9.15 is breaking on SvelteKit

### ISSUE THREAD

**Issue by silvestrevivo** [solana-labs/wallet-adapter#541]
**Describe the bug**
Using on SvelteKit the next packages:

```javascript
    "@sveltejs/kit": "1.0.0-next.400",
    "@solana/wallet-adapter-base": "0.9.15",
    "@solana/wallet-adapter-wallets": "0.18.4",
    "@solana/web3.js": "^1.53.0",
    "@svelte-on-solana/wallet-adapter-anchor": "^1.0.15-alpha.0",
    "@svelte-on-solana/wallet-adapter-core": "^1.0.7-alpha.0",
    "@svelte-on-solana/wallet-adapter-ui": "^1.0.19-alpha.0",
```

I get the next error when I run `npm run dev`:

```
exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'node_modules/@solana/wallet-adapter-base/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'node_modules/@solana/wallet-adapter-base/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///node_modules/@solana/wallet-adapter-base/lib/cjs/index.js:16:23
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async nodeImport (file:///node_modules/vite/dist/node/chunks/dep-0fc8e132.js:50619:21)
    at async eval (/node_modules/@svelte-on-solana/wallet-adapter-core/lib/esm/errors.mjs:3:44)
    at async instantiateModule (file:///node_modules/vite/dist/node/chunks/dep-0fc8e132.js:50548:9)
```

When I build the project and run the preview, there is no errors and the production build works perfectly. 

**Expected behavior**
The last version working well with the Svelte adapter on dev and production is the "0.9.13". 

**Additional context**
Placing a package.json file in the `cjs` and `esm` folders with the next content, it works fine on development but not in production. 

```javascript
{ "type": "module" }
```

This issue is not coming from the `@solana/wallet-adapter-base` package. It seems more related with a conflict between Vite and CommonJS. I am wondering if it is possible to find a solution in between the "0.9.13" and "0.9.15" version. 

Thanks!

**Comment by jordansexton** [comment]
Thanks for this. If the approach from https://github.com/solana-labs/solana-program-library/pull/3529 works, placing `{ "type": "commonjs" }` into the cjs folder is all that should be needed since the base package.json is already ESM.

**Comment by silvestrevivo** [comment]
@jordansexton I've placed manually `{ "type": "commonjs" }` in the cjs folder and it is working on DEV and PROD. You have saved my day/night!

**Comment by jordansexton** [comment]
Awesome. This is something we used to do in Wallet Adapter, and I thought it wasn't necessary. Apparently it's impossible, with a single package.json, to express "this package can be consumed as either CJS or ESM without configuration".

**Comment by silvestrevivo** [comment]
@jordansexton  Exactly, I was dealing today with this and it seems that this is the "only" way to do it. By the way, the Svelte Adapter has not implemented the Torus flow because an old Vite compatibility. Now it seems to be solved ( I can run it on DEV ), but in production I get the next error: 

```
WalletLoadError: require is not defined
    at qi.connect (index-fc029250.js:2:146079)
    at async autoConnect (index-649f4fb0.js:12:42770)
```

Do you think this could be related with the issue described before?

**Comment by jordansexton** [comment]
Fixed by #542, publishing now.

**Comment by jordansexton** [comment]
Published.

**Comment by silvestrevivo** [comment]
@jordansexton Svelte adapter updated too and working on production https://solana-svelte-counter.netlify.app/ 

Thanks so much for your support!!
