### ISSUE TITLE
Closing of WalletConnect modal does not change button connecting state

### ISSUE THREAD

**Issue by nelsontky** [solana-labs/wallet-adapter#552]
**Describe the bug**
Closing the WalletConnect Modal causes the wallet connect button to be stuck in the "Connecting..." state.

**To Reproduce**
1. Go to http://poised-lumber.surge.sh/
2. Click on any of the "Connect" buttons and choose WalletConnect
3. Close the WalletConnect modal without connecting any wallet
4. Wallet connect button is stuck in the "Connecting..." state

**Expected behavior**
Wallet connect button should allow for click and reconnection

**Screenshots**
![output](https://user-images.githubusercontent.com/7272103/187836029-2e0b2348-a0da-4eb1-9694-eaf1e5204e1d.gif)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 104.0.5112.101 (Official Build) (arm64) 

**Additional context**
Issue is due to the `QRCodeModal` error being thrown in a callback. I have a PR [here](https://github.com/jnwng/walletconnect-solana/pull/3) that fixes the issue.

**Comment by jordansexton** [comment]
cc @jnwng

**Comment by jnwng** [comment]
fixed in jnwng/walletconnect-solana#3, released in `@jnwng/walletconnect-solana@0.1.1`. please re-open if this is still an issue @nelsontky!
