### ISSUE TITLE
Cant resolve 'crypto' Torus Labs Wallet Adapter

### ISSUE THREAD

**Issue by baileyspraggins** [solana-labs/wallet-adapter#554]
Getting a can't resolve 'crypto' in '/node_modules/@toruslabs/eccrypto' error.

I have crypto and crypto-browserify in my package.json and have also added a fallback for crypto but still am getting this error. 

Below is a screenshot of the fallback in my config-overrides.js file.
<img width="467" alt="Screen Shot 2022-09-03 at 12 24 07 PM" src="https://user-images.githubusercontent.com/62624378/188281744-437df037-edb9-4af7-bb69-1676cbc4bf7b.png">

**Comment by jordansexton** [comment]
There was a release of the Torus package this week in https://github.com/solana-labs/wallet-adapter/pull/548 that updated the version of the Torus SDK used. Can you try pinning the previous version? Might need to use yarn resolutions / npm overrides to do it.

cc @ieow @metallicalfa2

**Comment by baileyspraggins** [comment]
I tired doing so and it did not work. Correct me if I wrong, but the solution you provided is related to a different package.

**Comment by ieow** [comment]
Do you mind share your code so that I could check on it?
Or you could refer this https://web3auth.io/docs/troubleshooting/webpack-issues to troubleshoot

here is my repo with cra+wallet-adapter-torus, you can refer this as well 
https://github.com/ieow/cra-wallet-adpater

**Comment by baileyspraggins** [comment]
The web3auth troubleshooting fixed the issue. Thank you!
