### ISSUE TITLE
Missing entry point in wallet-adapter-react

### ISSUE THREAD

**Issue by aa-deet-eeya** [solana-labs/wallet-adapter#56]
Similar issue to #52 

Tho looking at the package inside node_modules it seems like the entry point mentioned in package.json as  
`"main": "lib/index.js",` is missing inside wallet-adapter-react

![image](https://user-images.githubusercontent.com/26107248/132117719-2000c805-da19-480b-ba0f-0331f4248204.png)

version : `0.9.0`

**Comment by jordansexton** [comment]
Just as with the issue you linked, did you run the instructions on building from source? That directory should only be missing if you didn't run `yarn build` after `yarn install`. Please reopen if this doesn't fix your issue.

**Comment by aa-deet-eeya** [comment]
@jordansexton 
Actually I used `npm i @solana/wallet-adapter-react` to install the package. And from my understanding `yarn build` inside my project won't build the dependencies.

**Comment by aa-deet-eeya** [comment]
Did the same test again in a fresh install with just `@solana/wallet-adapter-react` as a dependency,
here's the package.json
![image](https://user-images.githubusercontent.com/26107248/132119322-e9476e63-7a3c-4658-8a43-c7b697cce5a1.png)


And here's the index.tsx, still has the same issue 
![image](https://user-images.githubusercontent.com/26107248/132119304-a12fcb70-b1ee-4c8e-9de8-e4514c841a17.png)

**Comment by jordansexton** [comment]
Thanks for the steps to reproduce! I'll check it out.

**Comment by beautyfree** [comment]
Same issue, found the same reasons

**Comment by jordansexton** [comment]
New build running now :)

**Comment by jordansexton** [comment]
Published, version 0.9.1 should fix the issue. Looks like there was a problem with the build before publishing. Thanks for the report!
