### ISSUE TITLE
Mobile wallet adapter

### ISSUE THREAD

**Issue by Tataklim** [solana-labs/wallet-adapter#562]
**Is your feature request related to a problem? Please describe.**
I am trying to connect Trust wallet, but extension doesn't support Solana by now. Also wallet-adapter doesn't support mobile devices(

**Describe the solution you'd like**
Implement browser checking to let wallets connect for mobile users. This may require also another class for mobile wallet adapters. Or maybe it's better just to update Trust wallet adapter with some additional logic idk

**Additional context**
For example, for trust wallet it's enough just to open [link to the app](https://community.trustwallet.com/t/mobile-dapps-with-deep-linking-and-trust-wallet/201)

**Comment by jordansexton** [comment]
Opening wallet-specific deep links is out of scope for Wallet Adapter (https://github.com/solana-labs/wallet-adapter/issues/319, https://github.com/solana-labs/wallet-adapter/issues/409) which is designed to run in browser windows. The good news is this is being developed as part of https://github.com/solana-mobile/mobile-wallet-adapter (not using wallet-specific deep/universal/app link schemes, but a standard scheme).

This will require mobile wallets to implement this, but that's where the work is being done! Once it's ready, MWA support will likely be directly integrated into Wallet Adapter (along with [Wallet Standard](https://github.com/wallet-standard/wallet-standard) support, see https://github.com/solana-labs/wallet-adapter/pull/528) such that dapps will only have to update their Wallet Adapter versions and will get support for implementing wallets of both.
