### ISSUE TITLE
What response we need to return to dapps 

### ISSUE THREAD

**Issue by AndonMitev** [solana-labs/wallet-adapter#566]
Hello guys, I'm trying to implement wallet injection  ( DAPP- Wallet communication) and i'm playing the role of wallet side. So far i managed to make my wallet recognizable by the dapps with some config faking it as it is Phantom Wallet. I'm receiving `connect` request successfully but i feel like I'm not returning response correctly. Here you can see my existing code implementation:

https://solana.stackexchange.com/questions/3070/create-wallet-injection-using-solana-wallet-adapter

can you share what i need to do in order to successfully return a response to the dapp's. Thanks a'lot in advance!

**Comment by jordansexton** [comment]
Github isn't the place for this. Please don't create issues (bug reports or feature requests) without filling out the provided template.

**Comment by AndonMitev** [comment]
Yes sorry for that! I have asked in SSE and discord but i can't get any answer back and get really depressed. Tried to research any wallet for their source but seems like none of them is really public and really idk from where i can extract this piece of data :(. Sorry for posting here

**Comment by jordansexton** [comment]
I don't mean to be rude, but the Stack Exchange question you linked was only created 3 hours ago, and is not very high quality. I'll attempt to answer it there, but when you take things to Github like this, you are wasting the time of maintainers and also spamming the people watching this repo.

**Comment by AndonMitev** [comment]
Totally understand, apologise one more time!
