### ISSUE TITLE
wallet-adapter-torus uses `require('stream')` and `require('crypto')`

### ISSUE THREAD

**Issue by stijlist** [solana-labs/wallet-adapter#584]
**Describe the bug**
Bundling @solana/wallet-adapter-wallets fails because wallet-adapter-torus references `require('stream')` and `require('crypto')`.

I'll file an issue against torusresearch/solana-embed - just wanted to mention the issue here as well.

**To Reproduce**
1. Download the files in this gist: https://gist.github.com/stijlist/174b3b3c8bc6e4d009826c8a13a7e6612. 
2. Run `esbuild index.tsx --bundle --sourcemap --outfile=src/assets/index.js`

```
~/mkt:minimal-repro-wallet-adapter-torus: (1)> esbuild index.tsx --bundle --outdir=.
✘ [ERROR] Could not resolve "stream"

    node_modules/cipher-base/index.js:2:24:
      2 │ var Transform = require('stream').Transform
        ╵                         ~~~~~~~~

  The package "stream" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

✘ [ERROR] Could not resolve "crypto"

    node_modules/@toruslabs/eccrypto/browser.js:9:25:
      9 │ var nodeCrypto = require('crypto');
        ╵                          ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

2 errors
```
 
**Expected behavior**
wallet-adapter-torus includes dependencies to polyfill `stream` and `crypto`.

**Comment by jordansexton** [comment]
> wallet-adapter-torus includes dependencies to polyfill `stream` and `crypto`.

But it does:
https://github.com/solana-labs/wallet-adapter/blob/e56613051e494ba6cf85c1dfac4415a09e20b376/packages/wallets/torus/package.json#L35-L56

Wallet Adapter doesn't bundle anything though. Bundling (and accordingly, polyfilling) is left to applications.

Here's an example of how Create React App can be configured to do this:
https://github.com/solana-labs/wallet-adapter/blob/e56613051e494ba6cf85c1dfac4415a09e20b376/packages/starter/create-react-app-starter/config-overrides.js#L31-L36

It sounds like, arguably, `@toruslabs` packages should do their own bundling if they require polyfills.

**Comment by ieow** [comment]
I think this is the same issue as the #554 
you could refer this https://web3auth.io/docs/troubleshooting/webpack-issues to troubleshoot

here is my repo with cra+wallet-adapter-torus, you can refer this as well
https://github.com/ieow/cra-wallet-adpater

**Comment by chungquantin** [comment]
You can refer to this boilerplate for configuration using `react-app-wired` and `config-overrides.js`: https://github.com/snowflake-so/safe-app-boilerplate-js

**Comment by steveluscher** [comment]
It sounds like it's up to Torus to bundle polyfills or eliminate the need for them from their browser-bound code.
