### ISSUE TITLE
Type '(PhantomWalletAdapter | etc..)[]' is not assignable to type 'Adapter[]'.

### ISSUE THREAD

**Issue by AlexMGN** [solana-labs/wallet-adapter#586]
**Describe the bug**
It seems that the type expected in the props wallet is not the same as the Adapters return

**To Reproduce**
Nothing special, I upgraded the lib to the latest version (0.15.3) and now I can't build my app anymore because the Adapters are not good anymore. It seems that there is a problem with VersionedTransactions. I actually have the exact same logic as the Github README

**Expected behavior**
Wallets should be accepted in the props

**Screenshots**
<img width="422" alt="image" src="https://user-images.githubusercontent.com/25293823/194402667-f3f4cc9c-48be-481f-b6d2-1c761e058a9b.png">
<img width="378" alt="image" src="https://user-images.githubusercontent.com/25293823/194402502-f25ec7bb-9da9-4158-b52c-9984f316e563.png">
<img width="723" alt="image" src="https://user-images.githubusercontent.com/25293823/194402540-ef660a46-41c9-43d7-bb8e-af9054019724.png">
<img width="781" alt="image" src="https://user-images.githubusercontent.com/25293823/194402201-afee79c4-cd33-4af1-b969-f7d21e9be8cf.png">

**Desktop (please complete the following information):**
 - Mac OS
 - Chrome
 - N/A

**Comment by jordansexton** [comment]
Can you update to the latest version of the `wallets` package? It's currently `0.19.0`.

**Comment by jordansexton** [comment]
I see what the problem is though -- effectively an accidental breaking change to the `base` package that breaks compatibility with `wallets`. Fix incoming.

**Comment by AlexMGN** [comment]
Thanks for the feedback! I'm waiting for the fix in that case :)

**Comment by AlexMGN** [comment]
Did I need to still upgrade ```wallets``` to 0.19.0 or wait for the 0.19.1 ?

**Comment by jordansexton** [comment]
Just published! You'll need to update to `@solana/wallet-adapter-base` 0.9.18 which fixes the breaking change. Your other packages should be fine (but it's not a bad idea to update them all, including `@solana/wallet-adapter-wallets` 0.19.1).

**Comment by AlexMGN** [comment]
Okey thanks ! Actually I don't have 0.19.1 for wallets but I will upgrade wallet-adapter :)

**Comment by AlexMGN** [comment]
Updated all packages : 
<img width="414" alt="image" src="https://user-images.githubusercontent.com/25293823/194417775-c44e209c-4712-4ac8-b551-6428c7215258.png">

Still have the error (but the error message is different)
<img width="741" alt="image" src="https://user-images.githubusercontent.com/25293823/194417874-c328ff5f-95f1-4dfc-8fd8-f2f95be89b39.png">

**Comment by jordansexton** [comment]
Hmm, this sounds like a mismatch of installed versions. Can you try with these:

```json
"@solana/wallet-adapter-base": "^0.9.18",
"@solana/wallet-adapter-react": "^0.15.20",
"@solana/wallet-adapter-react-ui": "^0.9.18",
"@solana/wallet-adapter-wallets": "^0.19.1",
```

And after installing these, if the issue persists, can you post your full package.json and package-lock.json or yarn.lock file on gist.github.com and link it here?

**Comment by AlexMGN** [comment]
It is corrected! It must be from the ```wallets: 0.19.1``` because when I tried to install it, yarn only found 0.19.0. I was probably too fast in my test without giving the package time to be published

**Comment by vasudeveloper001** [comment]
Thanks @AlexMGN for this thankless job.

**Comment by AlexMGN** [comment]
@vasudeveloper001 always happy to help, but @jordansexton did all the work 😅 I did nothing except wait 45 seconds for him to answer me and fix the problem. He’s so reactive

**Comment by vasudeveloper001** [comment]
Thanks @jordansexton
