### ISSUE TITLE
Phantom wallet immidiately times out after the transaction confirmation request

### ISSUE THREAD

**Issue by Dizotoff** [solana-labs/wallet-adapter#589]
**Describe the bug**
The phantom wallet times out when I try to send a transaction giving me no time to sign it.

<img width="362" alt="Screenshot 2022-10-09 at 14 04 46" src="https://user-images.githubusercontent.com/9533646/194753438-14d111c2-d5c0-4e8a-bab4-0f611187ef74.png">

**To Reproduce**

<img width="447" alt="Screenshot 2022-10-09 at 14 04 37" src="https://user-images.githubusercontent.com/9533646/194753490-b5023e52-a63e-4963-b5aa-2b4712996c1a.png">

**Desktop (please complete the following information):**
 - OS: [macOS Monterey]
 - Browser [Brave]
 - Version [1.44.105]

**Comment by jordansexton** [comment]
Have you tried setting the blockhash you get back from `getLatestBlockhash` on the transaction?

**Comment by jordansexton** [comment]
Alternatively don't call `getLatestBlockhash` at all, because `sendTransaction` will do this for you (and set the blockhash) if you don't set it.

**Comment by Dizotoff** [comment]
Hi @jordansexton 
Thanks for your suggestions! I have tried not calling `getLatestBlockhash` at all, but it didn't help. It's probably worth mentioning that this code (without calling `getLatestBlockhash`): 

![Screenshot 2022-10-10 at 10 49 18](https://user-images.githubusercontent.com/9533646/194819876-e841ec08-8e37-46e2-8a20-997da1dd6afd.png)

was working before and then stopped after some time (as far as I remember). So I also suspect some API change there, which could have led to this error. 

Here are my adapter-related package versions. Maybe the issue is there?

```
    "@solana/wallet-adapter-base": "^0.9.5",
    "@solana/wallet-adapter-react": "^0.15.5",
    "@solana/wallet-adapter-react-ui": "^0.9.7",
    "@solana/wallet-adapter-wallets": "^0.19.1",
```

**Comment by jordansexton** [comment]
Posting screenshots of code makes this harder than pasting your formatted code into Github.

Try this:

```ts
const { connection } = useConnection();

const transaction = new Transaction().add(
    new TransactionInstruction({
        data: Buffer.from('Hello, world!'),
        keys: [],
        programId: new PublicKey('MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr'),
    })
);

const signature = await sendTransaction(transaction, connection);
```

OR this:

```ts
const { publicKey } = useWallet();
const { connection } = useConnection();

const {
    context: { slot: minContextSlot },
    value: { blockhash },
} = await connection.getLatestBlockhashAndContext();

const transaction = new Transaction({
    feePayer: publicKey,
    recentBlockhash: blockhash
}).add(
    new TransactionInstruction({
        data: Buffer.from('Hello, world!'),
        keys: [],
        programId: new PublicKey('MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr'),
    })
);

const signature = await sendTransaction(transaction, connection, { minContextSlot });
```

I _think_ the issue with your code may be that you're doing a bit of both. Either you can set the transaction's `feePayer` and `recentBlockhash` and provide the `minContextSlot` you used to obtain it OR you can let the adapter / wallet do this stuff for you. It's perfectly fine to not call `getLatestBlockhashAndContext` at all, because the adapter will do this.

**Comment by jordansexton** [comment]
Closing this as resolved since there hasn't been a response. Please let me know if the code in the comment above doesn't work for you.
