### ISSUE TITLE
How to get keypair types from users wallet adapter.

### ISSUE THREAD

**Issue by Mago2022** [solana-labs/wallet-adapter#594]
In Solana SPL documentation it was saying that wallet-adapter can handle keypair generation for you. But i am using the feature and i can't seem to finda ny keypair which i can createMint token with.

If you see code below the second parameter is a `Signer` type. Which is an object of  `{publicKey: PublicKey; secretKey: Uint8Array;}`. If i don't have these types from users wallet i can't create a mint.

```
const mint = await createMint(
  connection,
  payer ??? how to get this one,
  wallet.publicKey,
  wallet.publicKey,
  9 // We are using 9 to match the CLI decimal default exactly
);
```

**Comment by jordansexton** [comment]
Generating keypairs is not what wallet adapter is for.

The thing you're looking for is `Keypair.generate()` from @solana/web3.js.

Please ask questions on Stack Exchange though. The provided issue templates are only for bug reports and feature requests, not questions.
