### ISSUE TITLE
How to detect a wallet change ?

### ISSUE THREAD

**Issue by MathieuCesbron** [solana-labs/wallet-adapter#600]
Hello,

Is there an easy to way to know when the user change his wallet ?

I can only come with ugly solutions where I compare the previous `publicKey` to the current `publicKey`.

Have a good day,

**Comment by jordansexton** [comment]
See https://solana.stackexchange.com/questions/141/what-method-should-a-dapp-use-to-detect-a-change-in-wallet-network-for-any-walle/309

There is no reliable way to detect changes to accounts in most wallets. To the extent wallets support this, Wallet Adapter attempts to support it.

Pubkeys are the only thing that identifies the account. Comparing them is what you would expect, right?
