### ISSUE TITLE
Strike wallet adapter throwing "Can't import the named export 'EventEmitter' from non EcmaScript module"

### ISSUE THREAD

**Issue by sunlee-newyork** [solana-labs/wallet-adapter#601]
**Describe the bug**
Upgrading `@solana/wallet-adapter-wallets` throws this compile error:

```
Failed to compile.

./node_modules/@strike-protocols/solana-wallet-adapter/lib/esm/strikewallet.mjs
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)
```

**To Reproduce**
1. Upgrade `@solana/wallet-adapter-wallets` to 0.19.2
2. Run npm command `npm start` to run `react-scripts start`
3. See compile error

**Expected behavior**
Should compile without non EcmaScript module export error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.6
 - Browser Chrome
 - Version 106.0.5249.103

**Additional context**

**Comment by jordansexton** [comment]
You're using `react-scripts`, this is a Create React App problem (it doesn't handle ESM imports without .mjs extensions).

See the [CRA starter project](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/create-react-app-starter). Specifically, you need react-app-rewired and [this config](https://github.com/solana-labs/wallet-adapter/blob/master/packages/starter/create-react-app-starter/config-overrides.js).

**Comment by sunlee-newyork** [comment]
> You're using `react-scripts`, this is a Create React App problem (it doesn't handle ESM imports without .mjs extensions).
> 
> See the [CRA starter project](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/create-react-app-starter). Specifically, you need react-app-rewired and [this config](https://github.com/solana-labs/wallet-adapter/blob/master/packages/starter/create-react-app-starter/config-overrides.js).

ok thanks, saw that solution but was wondering if this was a global issue for other people. thanks for the suggestion will update webpack on my end 👍

**Comment by jordansexton** [comment]
np! Yeah, this needs to be documented better and more visibly
