### ISSUE TITLE
How to useRef with the WalletMultiButton component

### ISSUE THREAD

**Issue by script8888** [solana-labs/wallet-adapter#602]
I'm trying to link the onClick function of the WalletMultiButton so I can use another element to trigger the popup but it doesn't work
The ref value returns undefined

` <WalletMultiButton ref={props.connectRef} />`

**Comment by jordansexton** [comment]
You shouldn't need to do that. Instead, you can do something like 

```tsx
const { setVisible } = useWalletModal();

// ... when you want to open it ...
setVisible(true);
```
