### ISSUE TITLE
Early Access: Mobile Wallet Adapter & Wallet Standard

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/wallet-adapter#604]
# Early Access: Mobile Wallet Adapter & Wallet Standard

Solana Labs is about to release a new version of the React Wallet Adapter that comes with support for the Solana Mobile Stack’s Mobile Wallet Adapter and the new Solana Wallet Standard built in.

Upgrading comes with some benefits that we think you will like:

* Your app will automatically work with all mobile wallet apps – the first of which will be released before Breakpoint this year.
* Your app will automatically work with all present and future wallets that support the Wallet Standard.
* Once the majority of wallets you wish to support have shipped Wallet Standard support, you will be able to reduce code bloat and supply chain attack surface in your app by deleting their legacy wallet adapter plugins.

For much more detail about how the Mobile Wallet Adapter and the Wallet Standard work, refer to [this podcast](https://open.spotify.com/episode/75mjCPN6riznV41FPKji7y).

## Why you might like to participate

Apps that successfully upgrade for Mobile Wallet Adapter and Wallet Standard compatiblity will be demoable with the upcoming Solana Mobile Saga phone on the showroom floor of [Breakpoint](https://solana.com/breakpoint) (Nov 4&ndash;7). The Solana Mobile team wants to showcase great user experiences with as many apps as possible, and we want you to be a part of that.

## Goal of the early access program

Before we release this to the public and encourage the entire world to upgrade, we want to gather feedback from you. Please help us to find bugs and rough edges in the user experience before we announce this to the world.

## Eligibility

If you use any of these packages connect to wallets from your app, you are eligible to upgrade.

* `@solana/wallet-adapter-react`
* `@solana/wallet-adapter-react-ui`
* `@solana/wallet-adapter-ant-design`
* `@solana/wallet-adapter-material-ui`

## How to upgrade

From the directory where your `package.json` file is located, run the following commands:

#### Instructions for `yarn`

```
yarn

# If your app uses wallet-adapter-react
yarn upgrade @solana/wallet-adapter-react@latest

# If your app uses wallet-adapter-react-ui
yarn upgrade @solana/wallet-adapter-react-ui@latest

# If your app uses wallet-adapter-ant-design
yarn upgrade @solana/wallet-adapter-ant-design@latest

# If your app uses wallet-adapter-material-ui
yarn upgrade @solana/wallet-adapter-material-ui@latest
```

#### Instructions for `npm`

```
# If your app uses wallet-adapter-react
npm i --save @solana/wallet-adapter-react@latest

# If your app uses wallet-adapter-react-ui
npm i --save @solana/wallet-adapter-react-ui@latest

# If your app uses wallet-adapter-ant-design
npm i --save @solana/wallet-adapter-ant-design@latest

# If your app uses wallet-adapter-material-ui
npm i --save @solana/wallet-adapter-material-ui@latest
```

Alternatively, you can manually edit your `package.json` file to update to those versions, then re-run your package manager's install command.

If your site is locked to a version of `@solana/web3.js` older than 1.58.0, you may need to upgrade that too.

### Testing Mobile Wallet Adapter

You will need a Solana Mobile Stack Mobile Wallet Adapter compatible wallet app installed in order to test your integration. As of this writing, there are no commercially available wallets. In the meantime, you can download the `fakewallet` app from the Solana Mobile Stack SDK ([click on this link from your phone](https://github.com/solana-mobile/mobile-wallet-adapter/releases/download/fakedapp_fakewallet_binaries_v1.0.1/fakewallet-debug.apk)).

#### Without a compatible mobile wallet installed

1. Open your app on Android in a mobile web browser
   **Expect**: Your connect button should be armed and read ‘connect’
2. Click ‘connect’
   **Expect**: Since you have no mobile wallet installed, you should be redirected to https://solanamobile.com/wallets

#### With a compatible mobile wallet installed

1. Open your app on Android in a mobile web browser
   **Expect**: Your connect button should be armed and read ‘connect’
2. Click ‘connect’
   **Expect**: Your mobile wallet app should open and ask you to authorize your web app for use
3. Accept the authorization
   **Expect**: You should be redirected back to your web app and the wallet should be connected

#### Inside a wallet's in-app browser

1. Open your app on Android in a wallet's in-app browser (eg. the browser _inside_ the Phantom app)
   **Expect**: Your connect button should read ‘select wallet’
2. Click ‘select wallet’
   **Expect**: Your regular wallet set should be displayed. Mobile Wallet Adapter should not be an option.

### Testing the Wallet Standard

Any wallet extension that supports the new Solana Wallet Standard will _automatically_ attach to your list of selectable wallets, without you having to configure it. Install a Wallet Standard compliant wallet like [Backpack's latest release](https://github.com/coral-xyz/backpack/releases) to see this in action.

1. Open your app on desktop web
   **Expect**: Your connect button should read ‘select wallet’
2. Click ‘select wallet’
   **Expect**: Installed wallets that support the Wallet Standard should appear as choices in the dialog, alongside your regularly configured wallet set. If you don't have any installed wallets that support the Wallet Standard yet, you will just see the wallet adapters you are using.
3. If you have the Backpack wallet adapter in your code, remove it and rebuild
  **Expect**: Backpack is still detected by your app and works. (Make sure you're using Backpack's latest release from Github and have the right RPC connection network selected in Backpack.)
   
## How to give feedback

If you encounter issues with the integration or with the use of a Standard or Mobile wallet please [file an issue](https://github.com/solana-labs/wallet-adapter/issues/new?assignees=&labels=&template=bug_report.md&title=).

If your app happens to be open source, feel free to reference this GitHub issue in the commit message or the pull request of the change where you do the upgrade.

## Products that have upgraded

Search https://cs.github.com/?scopeName=All+repos&scope=&q=path%3Apackage.json+%5C%22%40solana%2Fwallet-adapter-react%5C%22%3A and send PRs to open source libraries. Track them here.

### Open Source PRs

- [x] https://github.com/solana-labs/dapp-scaffold/pull/268
- [x] https://github.com/metaplex-foundation/candy-machine-ui/pull/15
- [ ] https://github.com/blockworks-foundation/mango-ui-v3/pull/423
- [x] https://github.com/project-serum/serum-dex-ui/pull/157
- [x] https://github.com/GooseFX1/gfx-web-app/pull/532
- [x] https://github.com/GooseFX1/gfx-web-app/pull/536
- [ ] https://github.com/exiled-apes/candy-machine-mint/pull/231
- [x] https://github.com/alchemyplatform/create-web3-dapp/pull/52
- [x] https://github.com/solana-labs/governance-ui/pull/1135
- [x] https://github.com/cardinal-labs/cardinal-rental-ui/pull/189
- [x] https://github.com/dialectlabs/react/pull/210
- [ ] ADD MORE

### Open Source Repos

- [ ] https://github.com/wormhole-foundation/wormhole
- [ ] https://github.com/holaplex/holaplex
- [ ] https://github.com/cardinal-labs/cardinal-staking-ui
- [ ] https://github.com/metaplex-foundation/js-examples
- [ ] https://github.com/metaplex-foundation/token-entangler-ui
- [ ] https://github.com/ribbon-finance/ribbon-frontend
- [ ] https://github.com/jet-lab/jet-v2
- [ ] https://github.com/raydium-io/raydium-frontend
- [ ] ADD MORE

### Closed Source Projects

- [x] Solend
- [x] JungleDefi
- [x] Zeta Markets
- [x] Coinable Pay
- [x] Parcl
- [x] Tiexo
- [x] Civic
- [x] Marinade
- [x] Jupiter
- [x] Snowflake
- [x] Solana Mobile Saga Preorder site
- [x] Light Shield
- [x] Orca
- [x] Friktion
- [x] Dispatch Forums
- [x] Magic Eden
- [x] BizFirst
- [x] SkyWallet
- [x] Solana.fm
- [ ] Buddy Link
- [x] Art of Niko
- [x] Saga TV
- [x] Gorecats
- [x] Dual Finance
- [x] Droplinks
- [ ] Tulip
- [x] Squads
- [x] Step Finance
- [ ] Hedge
- [ ] Phantasia
- [ ] BlockLive
- [ ] ADD MORE

**Comment by jordansexton** [comment]
Added versions and a note about removing Backpack's adapter to test.

**Comment by jordansexton** [comment]
PR to add support to GooseFX: https://github.com/GooseFX1/gfx-web-app/pull/532

**Comment by gabRiel-bit20** [comment]
Port Finance (https://port.finance/) would love to use the latest wallet adaptor.

**Comment by jordansexton** [comment]
@gabRiel-bit20 can you try to follow the steps in this issue? Let us know if you run into issues!

**Comment by platocoreteam** [comment]
@jordansexton - we are already using @solana/wallet-adapter-react and @solana/wallet-adapter-react-ui in one of our web app for our eat and earn users. How do we submit PR if our project is closed source? do we add you into our team?

**Comment by jordansexton** [comment]
@platocoreteam yes, you can add me to the repo you want to update.

**Comment by platocoreteam** [comment]
@jordansexton - we just added you to our repo. can you check?

**Comment by steveluscher** [comment]
Done!

**Comment by skywalletadmin** [comment]
@steveluscher @jordansexton SKY Wallets' dApps (https://www.getsky.app/) are also now compatible with the Mobile Wallet Adapter and Wallet Standard. Please add SKY Wallet to the compatible products list as well! Thanks.

**Comment by adminbizfirst** [comment]
Hi @steveluscher @jordansexton Our product (https://www.bizfirst.xyz/) is now compatible with the Wallet Standard and Mobile Wallet Adapter. Please add us to the compatible list as well. Thank you!

**Comment by zfaizal2** [comment]
Hey @steveluscher @jordansexton 

We've got https://app.dispatch.forum/ up to date with the new wallet standard and MWA, please add us to the list -- thanks!

**Comment by steveluscher** [comment]
Hey @adminbizfirst, DM me on Twitter! I have some questions.

**Comment by steveluscher** [comment]
Hey @skywalletadmin, I have some questions for you too. DM me on Twitter!

**Comment by adminbizfirst** [comment]
@steveluscher Done, please check.

**Comment by skywalletadmin** [comment]
Hey @steveluscher just DM'd you via our twitter handle (https://twitter.com/GetSkyApp)

**Comment by diegofigs** [comment]
Hey @steveluscher @jordansexton, [Dual Finance](https://beta.dual.finance) updated to RC a couple days back and will be updating latest version soon. Please add to list, thanks!

**Comment by josip-volarevic** [comment]
Hey there @steveluscher 👋

Dropping off a few of my dApps in case it's not too late:
- **Gorecats Comic** [LINK](https://gorecats.netlify.com/) [SOURCE CODE](https://github.com/open-sauce-labs/gorecats-comic-reader-frontend)
- **Art of Niko Comic** [LINK](https://rewards.artofniko.com/) [SOURCE CODE](https://github.com/open-sauce-labs/niko-rewards-frontend)
- **Saga TV** [LINK](https://saga-tvnetlify.com/) [SOURCE CODE](https://github.com/open-sauce-labs/saga-tv)

Proof video for all 3 apps is located here: _(upload in progress)_

I might've missed something crucial and also applied too late so worries if you miss adding these dApps to your list!

**Comment by flodef** [comment]
Hey @steveluscher 👋 
Just wanted to THANK YOU for this fantastic job you are doing.
I did the integration and it was very easy. You did all the hard work !!!
It is definitively life changing for mobile adoption.

**Comment by anoushk1234** [comment]
@steveluscher correct me if im wrong, does this mean that we can connect mobile web apps to mobile wallets like phantom? I'm a bit confused since I tried to use the compatible dapps on mobile browser and they didn't connect.

**Comment by arihantbansal** [comment]
> @steveluscher correct me if im wrong, does this mean that we can connect mobile web apps to mobile wallets like phantom? I'm a bit confused since I tried to use the compatible dapps on mobile browser and they didn't connect.

It's working with the updated dApps. Eg: https://github.com/solana-labs/wallet-adapter/issues/604#issuecomment-1304336855

**Comment by josip-volarevic** [comment]
> @steveluscher correct me if im wrong, does this mean that we can connect mobile web apps to mobile wallets like phantom? I'm a bit confused since I tried to use the compatible dapps on mobile browser and they didn't connect.

@anoushk1234 you should be able to connect mobile web apps to mobile wallets. Currently working mobile wallets are Phantom, Solflare and "fakewallet".

There is most likely an error on your end. Are you on iOS? I'm not sure if there is any support for Solana mobile there.
Did you update your packages to correct dependencies? Do you use the correct cluster on your mobile wallet? e.g. if your local web dapp is on `devnet`, make sure to switch Phantom to `devnet` as well

**Comment by anoushk1234** [comment]
> > @steveluscher correct me if im wrong, does this mean that we can connect mobile web apps to mobile wallets like phantom? I'm a bit confused since I tried to use the compatible dapps on mobile browser and they didn't connect.
> 
> @anoushk1234 you should be able to connect mobile web apps to mobile wallets. Currently working mobile wallets are Phantom, Solflare and "fakewallet".
> 
> There is most likely an error on your end. Are you on iOS? I'm not sure if there is any support for Solana mobile there. Did you update your packages to correct dependencies? Do you use the correct cluster on your mobile wallet? e.g. if your local web dapp is on `devnet`, make sure to switch Phantom to `devnet` as well

I'm on safari yes

**Comment by anoushk1234** [comment]
@steveluscher just checked this works flawlessly on android, can we get this on ios as well?

**Comment by josip-volarevic** [comment]
@anoushk1234 copy pasting this from Solana mobile stack discord channel:

> Hello Solana friends, 

>  I'm <name> - I lead the engineering team at FastAF (an iOS application that recently launched an integrated Solana wallet to power token-gated experiences, NFT Rewards and soon to be... crypto payments). ⭐ 

> As a fun follow-up to Steven's news, my team will be working on the iOS spec for the Mobile Wallet Adapter. 🎉

> Here's a brief overview on the ups / downs we faced embarking on this fun journey in the iOS world..

> We have performed a technical feasibility study for using a variety of transport methods for MWA communication.
Findings: The existing Android specification for MWA calls for two-way app communication over a websocket server. 
This is significantly limited by background processing limitations on iOS. (approx. 30 second limit)
However, opening a Websocket or HTTP server via NSURLConnection on iOS does not appear to be a problem.

> We are moving forward with two communication schemas:
> - Websocket communication for when the dapp and wallet are not on the same physical device
> - Deep link-based communication (or Safari App Extensions) for when the dapp and wallet are on the same physical device

> Will post more updates in this channel as we dive further into the implementation stage.

I don't think iOS integration is expected in the short term roadmap

**Comment by anoushk1234** [comment]
> @anoushk1234 copy pasting this from Solana mobile stack discord channel:
> 
> > Hello Solana friends,
> 
> > I'm  - I lead the engineering team at FastAF (an iOS application that recently launched an integrated Solana wallet to power token-gated experiences, NFT Rewards and soon to be... crypto payments). ⭐
> 
> > As a fun follow-up to Steven's news, my team will be working on the iOS spec for the Mobile Wallet Adapter. 🎉
> 
> > Here's a brief overview on the ups / downs we faced embarking on this fun journey in the iOS world..
> 
> > We have performed a technical feasibility study for using a variety of transport methods for MWA communication.
> > Findings: The existing Android specification for MWA calls for two-way app communication over a websocket server.
> > This is significantly limited by background processing limitations on iOS. (approx. 30 second limit)
> > However, opening a Websocket or HTTP server via NSURLConnection on iOS does not appear to be a problem.
> 
> > We are moving forward with two communication schemas:
> > 
> > * Websocket communication for when the dapp and wallet are not on the same physical device
> > * Deep link-based communication (or Safari App Extensions) for when the dapp and wallet are on the same physical device
> 
> > Will post more updates in this channel as we dive further into the implementation stage.
> 
> I don't think iOS integration is expected in the short term roadmap

yep works on android for me, hope ios is also sorted soon

**Comment by flodef** [comment]
It works for me on Android, with Solflare, but Phantom don't display the "accept" button. Seems like a phantom wallet problem...

**Comment by josip-volarevic** [comment]
> It works for me on Android, with Solflare, but Phantom don't display the "accept" button. Seems like a phantom wallet problem...

This is an issue with Phantom not detecting your selected cluster automatically which fakewallet and solflare do out of the box.
e.g. if your app is using `devnet` but phantom has `mainnet-beta` selected, you will experience such an issue

It's asked and answered on solana stackexchange [here](https://solana.stackexchange.com/questions/4346/phantom-mobile-app-fails-silently-when-interacting-with-new-mobile-wallet-adapte/4347#4347)

**Comment by steveluscher** [comment]
> @steveluscher just checked this works flawlessly on android, can we get this on ios as well?

Check out the iOS effort announcement here and cheer them on! https://discord.com/channels/988649555283308564/988902872773181491/1030613038350475264

**Comment by Bewinxed** [comment]
I would love to participate but I'm using svelte at the moment, and the mobile wallet adapter for them is not maintained often :(

**Comment by steveluscher** [comment]
Thanks for all of your help everyone! We made incredible progress; MWA and Wallet Standard are supported in most places now.

**Comment by LFerronato** [comment]
Guys/SolanaTeam, I need some help here.

I'm having a serious problem with this point in the documentation.

"(In this description)
Expect: Since you have no mobile wallet installed, you should be redirected to https://solanamobile.com/wallets
"

Guys, this worries me a lot. is a very intrusive definition. and causes distrust in our customers.
How do I disable this, I'm facing problems

How can i disable this redirect 🙏?
