### ISSUE TITLE
An internal error has occurred

### ISSUE THREAD

**Issue by dannymanzano172** [solana-labs/wallet-adapter#613]
**Describe the bug**
Internal errors are not surfaced anywhere for us to catch them  when using the wallet modal. For me to track that a user already was logged in I keep a value in localStorage and remove it when they disconnect but when something like an internal error happens Im stuck in a loading state waiting for the wallet to attempt a connection or disconnect. Is there a way to know the connection attempt crashed?

**To Reproduce**
1. Refreshing a couple times on Brave will prompt the brave wallet even though I don't have it connected and then causes the phantom wallet connection attempt to crash.
2. Need to have autoConnect set to true

**Expected behavior**
A property informing me of possible failures or crashes could be helpful in tracking failed connections

**Screenshots**
<img width="670" alt="Screen Shot 2022-10-19 at 2 44 14 PM" src="https://user-images.githubusercontent.com/23584182/196710149-0d8740a0-35e4-4240-8ca1-f4cc271ba60d.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey v12.5
 - Browser Brave
 - Packages used: 
 ```
    "@solana/wallet-adapter-base": "0.9.18",
    "@solana/wallet-adapter-react": "0.15.20",
    "@solana/wallet-adapter-react-ui": "0.9.18",
    "@solana/wallet-adapter-wallets": "0.19.2",
    "@solana/web3.js": "1.66.1",
```

**Comment by jordansexton** [comment]
It sounds like a specific set of code and circumstances is necessary to trigger this. Can you a post a repo link and repro steps?

**Comment by jordansexton** [comment]
And are you using the `onError` handler passed to the WalletProvider?

https://github.com/solana-labs/wallet-adapter/blob/29ae052e6a742a645bb1247e4d8063ae4d5c6af1/packages/core/react/src/WalletProvider.tsx#L22

**Comment by dannymanzano172** [comment]
1. onError worked for me. thank you!
2. So, I cant post my repo currently but it's a very simple setup with autoConnect on and only phantom as the adapter. The issue is actually caused on the Brave browser side. By default, Brave sets their wallet to try to connect first and thus make the wallet adapter crash. To force, this exact case go to settings > wallet and set the default to brave and then refresh the app that has autoConnect on. It will prompt you to unlock your brave browser in a new tab and then your actually connection attempt fails
<img width="725" alt="Screen Shot 2022-10-20 at 3 30 37 PM" src="https://user-images.githubusercontent.com/23584182/197333949-1c2854b5-5967-40cd-a377-7c9d9e35f7c5.png">

**Comment by jordansexton** [comment]
Closing this since it's not an issue with Wallet Adapter. But I've reached out to the Brave team about adding support for the Wallet Standard, and Phantom is already working on it. This issue will be fixed when that happens.
