### ISSUE TITLE
Error related to wallet ,no such directory found #bug

### ISSUE THREAD

**Issue by anusriesto** [solana-labs/wallet-adapter#616]
**Describe the bug**
At first, I was getting the webpack issue  which I resolved using this [https://web3auth.io/docs/troubleshooting/webpack-issues]url ,
after that, I am facing this issue to run my react app,

![image](https://user-images.githubusercontent.com/52596463/197131949-2f242d1d-310e-46c3-b4ff-1f7d38ffd40c.png)

My dependencies

![image](https://user-images.githubusercontent.com/52596463/197132189-b76bdc95-f692-4afb-8d8d-eb669afa724b.png)

**Comment by jordansexton** [comment]
You're using `react-scripts`, this is a Create React App problem. See the [CRA starter project](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/create-react-app-starter). Specifically, you need react-app-rewired and [this config](https://github.com/solana-labs/wallet-adapter/blob/master/packages/starter/create-react-app-starter/config-overrides.js).

**Comment by jordansexton** [comment]
You may also wish to update your version of the `wallet-adapter-wallets` package so you're not getting the alpha tagged version. The latest version is `0.19.4`.
