### ISSUE TITLE
Same issue as #236 now with newly added Fractal

### ISSUE THREAD

**Issue by Rkrushanovskij** [solana-labs/wallet-adapter#625]
**Describe the bug**
With newly added `@solana/wallet-adapter-fractal` i am facing the error that seems to be similar to faced and fixed before with other wallet adapters:
```
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|         FractalWalletClass = (await import('@fractalwagmi/solana-wallet-adapter')).FractalWalletAdapterImpl;
|       } catch (error) {
>         throw new WalletLoadError(error?.message, error);
|       }
```

**To Reproduce**
1. Try to use `@solana/wallet-adapter-fractal` lib to get it into your project

**Comment by Rkrushanovskij** [comment]
It is similar issue to [this issue](https://github.com/solana-labs/wallet-adapter/issues/241)

**Comment by jordansexton** [comment]
You're using react-scripts, this is a Create React App issue. Please search the issues for that 😄
