### ISSUE TITLE
Is there a way to get wallet network from the adapter?

### ISSUE THREAD

**Issue by bozhang0504** [solana-labs/wallet-adapter#629]
**Is your feature request related to a problem? Please describe.**
I wonder if there is a way to know what network a user is on, e.g. devnet / testnet / mainnet

**Describe the solution you'd like**
something like [wagmi's useNetwork](https://wagmi.sh/docs/hooks/useNetwork) hook, it returns the chain user's wallet connects to

**Comment by jordansexton** [comment]
> what network a user is on

Do you mean what network the user's connected wallet is using?

**Comment by bozhang0504** [comment]
> > what network a user is on
> 
> Do you mean what network the user's connected wallet is using?

yes, sir

**Comment by jordansexton** [comment]
See https://twitter.com/0xMukesh/status/1583851463314673664 and https://solana.stackexchange.com/questions/141/what-method-should-a-dapp-use-to-detect-a-change-in-wallet-network-for-any-walle/309?noredirect=1#comment366_309
