### ISSUE TITLE
Impossible to install the package: fractal-ts-lib is not available on NPM registry

### ISSUE THREAD

**Issue by laxmes** [solana-labs/wallet-adapter#632]
**Describe the bug**
Impossible to install the `@solana/wallet-adapter-wallets` package, `fractal-ts-lib` is not available on NPM official registry. 

Error: `'@fractalwagmi/fractal-ts-lib@^1.0.1' is not in this registry.`

**To Reproduce**
1. Install the latest version of `@solana/wallet-adapter-wallets` package on a newly created NPM project

**Expected behavior**
No error when installing. Fractal wallet should be removed?

**Edit 1**
It looks like the problem comes from the `@fractalwagmi/popup-connection` package.

**Edit 2**
Github page of the  `@fractalwagmi/popup-connection` package is not available ([link](https://github.com/fractalwagmi/popup-connection))

**Comment by jordansexton** [comment]
Looking into this, thanks!

**Comment by jordansexton** [comment]
This is fixed! Thanks for your patience. A transitive dependency was unpublished from npm, breaking downstream packages. The thing that depended on it has been republished to no longer use the missing dep.
