### ISSUE TITLE
Persist Sollet wallet popup on top when it requests a signature

### ISSUE THREAD

**Issue by jennifer-notifi** [solana-labs/wallet-adapter#634]
**Describe the bug**
The Sollet wallet popup disappears into the background when the wallet requests to sign a transaction. We would like Sollet wallet popup to open on top of all browsers when the wallet is requesting to sign a transaction. 

Is there a way to persist the Sollet wallet popup on top until all login steps and signature requests have been completed?

**To Reproduce**
1. Go to any dapp that has Sollet integration that requires a signature before logging (ex. https://notifi.network/login)
2. Click on Sollet.
3. Go through the steps to sign in. The popup disappears into the background and you stall on the login page of Notifi.Network.
4. If you open the Sollet wallet, then you will see that it required you to sign.

**Expected behavior**
Sollet wallet popup should remain at the top until all login steps and signature requests have been completed. 

**Screenshots**

https://user-images.githubusercontent.com/108922885/198428523-649a78ce-9dbc-4554-97a2-9365e0a652f7.mov

**Desktop (please complete the following information):**
 - OS: Mac
 - Chrome 
 - 06.0.5249.119 (Official Build) (arm64)

**Comment by jordansexton** [comment]
All behavior of the Sollet wallet is defined by the `@project-serum/sol-wallet-adapter` SDK. This isn't the right repo for this request. If there was one, it would be https://github.com/project-serum/sol-wallet-adapter. But Sollet is deprecated and has not had a commit in over a year.
