### ISSUE TITLE
Updating `WalletProvider.onError` prop incorrectly disconnects the adapter

### ISSUE THREAD

**Issue by zpalmtree** [solana-labs/wallet-adapter#636]
**Describe the bug**
I am using the wallet adapter in React, with Phantom wallet.
I am passing in the `endpoint` value as a prop.

I recently upgraded from 0.9.5 to 0.9.18, and now, when I change/set the RPC value in react, the wallet disconnects.

I tried to narrow it down to a more specific version to find the commit that introduced the bug but I couldn't get npm to install the older versions without using my old lock file.

If I downgrade back to 0.9.5 and my old lock file, changing the RPC lets the wallet remain connected.

Some additional things I noticed if it helps:

On the working version, it looks like the wallet state just changes once. In the current version, I see it change state twice after swapping RPC.

Possibly helpful state values after changing rpc:

0.9.5:
```
autoConnect: true
connected: true
connecting: false
disconnecting: false
readyState: "Installed'
publicKey: defined
```

0.9.18:

```
autoConnect: true
connected: false
connecting: false
disconnecting: false
readyState: 'Installed'
publicKey: null
```

**To Reproduce**
1. Setup simple react ui app doing something like logging the users public key
2. Use react variable for endpoint prop
3. Change endpoint on action, e.g. clicking a button
4. Wallet will disconnect and public key is no longer available for logging

**Expected behavior**
Wallet stays connected if previously connected

**Screenshots**

https://user-images.githubusercontent.com/22151537/198815343-205bcad1-7523-4ca7-ac7e-25a138efdd57.mp4

**Desktop (please complete the following information):**
 - OS: gahnoo loonix
 - Browser: Firefox
 - Version: 106.0.1

**Comment by jordansexton** [comment]
Thanks so much for the report, can you share which other wallet adapter package versions are in your package.json?

**Comment by jordansexton** [comment]
Or maybe the lockfile, since the resolved versions could be higher?

**Comment by jordansexton** [comment]
And, if your project is open source or you have a reproduction repo, or a link to the running app, that helps too!

Specifically I'm first trying to first isolate of this issue is caused by something in the base package or the react package.

**Comment by jordansexton** [comment]
As for why this may be happening, some example code --

```tsx
    const [network, setNetwork] = useState(WalletAdapterNetwork.Mainnet);
    const endpoint = useMemo(() => clusterApiUrl(network), [network]);
    const wallets = useMemo(
        () => [
            new PhantomWalletAdapter(),
            new SolletWalletAdapter({ network })
        ],
        [network]
    );
    
    return <WalletProvider wallets={wallets}>{ children }</WalletProvider>
    
    // Somewhere, you call `setNetwork` to change the cluster.
```

I don't know if your code looks like this, but conceptually why this would cause the adapter to disconnect is straightforward -- when the network changes, the entire array of adapters will be recreated, reinstantiating all the adapters. Since the adapters are stateful, this will leave them with a default `publicKey: null`, `connected: false`, etc.

One thing you can do about this is add `autoConnect` to the `WalletProvider`. This will reconnect the last used adapter by name, which for most wallets will update without prompting the user. Another thing you might do is this:

```tsx
    const walletsWithoutNetwork = useMemo(
        () => [new PhantomWalletAdapter()],
        []
    );
    const walletsWithNetwork = useMemo(
        () => [new SolletWalletAdapter({ network })],
        [network]
    );
    const wallets = useMemo(
        () => [
            ...walletsWithoutNetwork,
            ...walletsWithNetwork
        ],
        [walletsWithoutNetwork, walletsWithNetwork]
    );

    return <WalletProvider wallets={wallets}>{ children }</WalletProvider>
```

This will cause only adapters that take a `network` config to be reinstantiated.

**Comment by jordansexton** [comment]
I _suspect_ this commit is what caused this behavior: https://github.com/solana-labs/wallet-adapter/commit/12d92a3b6f437df76b2e8ac0ce01e25afd4623e3 This fixed a longstanding bug which went unnoticed, which is that when new adapter instances were passed to the provider, in fact they weren't being used at all.

In effect, your app using the old "working" version is likely updating the adapters with new `network` config, and they aren't actually changing in the provider -- the ones you instantiated first are, with whatever config they originally have. It looks like you're changing networks, but in fact nothing is happening.

**Comment by zpalmtree** [comment]
Working `package.json`:

```
{
   "devDependencies": {
    "@types/bs58": "^4.0.1",
    "@types/lodash": "^4.14.184",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-lazyload": "^3.2.0",
    "@types/react-router-dom": "^5.3.2",
    "@types/webfontloader": "^1.6.33",
    "process": "^0.11.10",
    "webpack-bundle-analyzer": "^4.5.0"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/free-brands-svg-icons": "^6.1.1",
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "@fortawesome/react-fontawesome": "^0.1.18",
    "@headlessui/react": "^1.6.5",
    "@jup-ag/core": "^2.0.0-beta.3",
    "@project-serum/anchor": "^0.25.0",
    "@project-serum/serum": "^0.13.65",
    "@solana/spl-token": "^0.3.4",
    "@solana/spl-token-registry": "^0.2.1365",
    "@solana/wallet-adapter-base": "^0.9.5",
    "@solana/wallet-adapter-exodus": "^0.1.11",
    "@solana/wallet-adapter-glow": "^0.1.6",
    "@solana/wallet-adapter-phantom": "^0.9.9",
    "@solana/wallet-adapter-react": "^0.15.5",
    "@solana/wallet-adapter-react-ui": "^0.9.7",
    "@solana/wallet-adapter-slope": "^0.5.10",
    "@solana/wallet-adapter-solflare": "^0.6.11",
    "@solana/wallet-adapter-sollet": "^0.11.6",
    "@solana/web3.js": "^1.54.0",
    "abort-controller": "^3.0.0",
    "assert": "^2.0.0",
    "autoprefixer": "^10.4.7",
    "bn.js": "^5.2.0",
    "crypto-browserify": "^3.12.0",
    "framer-motion": "^6.5.1",
    "jsbi": "^4.3.0",
    "lodash": "^4.17.21",
    "postcss": "^8.4.14",
    "react": "^17.0.2",
    "react-app-rewired": "^2.2.1",
    "react-dom": "^17.0.2",
    "react-lazyload": "https://github.com/zpalmtree/react-lazyload.git",
    "react-router-dom": "^5.3.0",
    "react-scripts": "^5.0.1",
    "react-toastify": "^9.0.8",
    "recoil": "^0.7.6",
    "stream-browserify": "^3.0.0",
    "tailwindcss": "^3.1.3",
    "typescript": "^4.1.2",
    "url": "^0.11.0"
  },
}
```

Working `yarn.lock`: [yarn.lock.zip](https://github.com/solana-labs/wallet-adapter/files/9893082/yarn.lock.zip)

Not working `package.json`: 
```
{
  "devDependencies": {
    "@types/bs58": "^4.0.1",
    "@types/lodash": "^4.14.184",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-lazyload": "^3.2.0",
    "@types/react-router-dom": "^5.3.2",
    "@types/webfontloader": "^1.6.33",
    "process": "^0.11.10",
    "webpack-bundle-analyzer": "^4.5.0"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/free-brands-svg-icons": "^6.1.1",
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "@fortawesome/react-fontawesome": "^0.1.18",
    "@headlessui/react": "^1.6.5",
    "@jup-ag/core": "^2.0.0-beta.3",
    "@project-serum/anchor": "^0.25.0",
    "@project-serum/serum": "^0.13.65",
    "@solana/spl-token": "^0.3.4",
    "@solana/spl-token-registry": "^0.2.1365",
    "@solana/wallet-adapter-backpack": "^0.1.9",
    "@solana/wallet-adapter-base": "^0.9.18",
    "@solana/wallet-adapter-exodus": "^0.1.11",
    "@solana/wallet-adapter-glow": "^0.1.6",
    "@solana/wallet-adapter-phantom": "^0.9.9",
    "@solana/wallet-adapter-react": "^0.15.5",
    "@solana/wallet-adapter-react-ui": "^0.9.7",
    "@solana/wallet-adapter-slope": "^0.5.10",
    "@solana/wallet-adapter-solflare": "^0.6.11",
    "@solana/wallet-adapter-sollet": "^0.11.6",
    "@solana/web3.js": "^1.54.0",
    "abort-controller": "^3.0.0",
    "assert": "^2.0.0",
    "autoprefixer": "^10.4.7",
    "bn.js": "^5.2.0",
    "crypto-browserify": "^3.12.0",
    "framer-motion": "^6.5.1",
    "jsbi": "^4.3.0",
    "lodash": "^4.17.21",
    "postcss": "^8.4.14",
    "react": "^17.0.2",
    "react-app-rewired": "^2.2.1",
    "react-dom": "^17.0.2",
    "react-lazyload": "https://github.com/zpalmtree/react-lazyload.git",
    "react-router-dom": "^5.3.0",
    "react-scripts": "^5.0.1",
    "react-toastify": "^9.0.8",
    "stream-browserify": "^3.0.0",
    "tailwindcss": "^3.1.3",
    "typescript": "^4.1.2",
    "url": "^0.11.0"
  },
}
```

Not working `yarn.lock`: [yarn.lock.zip](https://github.com/solana-labs/wallet-adapter/files/9893088/yarn.lock.zip)

I appreciate the really speedy response!

You can see a working app here: https://sol-incinerator.com/

And you can see the bug being demonstrated here: https://sol-incinerator.com/redesign/

and this is what my wallet component looks like:

```tsx
export function WalletWrapper(props: WalletWrapperProps) {
    const {
        children,
    } = props;

    const network = WalletAdapterNetwork.Mainnet;

    const [ rpc ] = useRecoilState(rpcState);

    const wallets = React.useMemo(() => [
        new PhantomWalletAdapter(),
        new SlopeWalletAdapter(),
        new SolflareWalletAdapter(),
        new SolletWalletAdapter({ network }),
        new SolletExtensionWalletAdapter({ network }),
        new GlowWalletAdapter({ network }),
        new ExodusWalletAdapter(),
    ], [network]);

    function onError(err: any) {
        /* ... */
    }

    return (
        <ConnectionProvider endpoint={rpc}>
            <WalletProvider wallets={wallets} onError={onError} autoConnect>
                <WalletModalProvider>
                    {children}
                </WalletModalProvider>
            </WalletProvider>
        </ConnectionProvider>
    );
}
```

**Comment by jordansexton** [comment]
Yep, that's exactly what's happening. Your network changes, you blow away all the adapter instances. If you were to compare the object instances of the adapters, you'd find they were different -- the old one will still be connected.

**Comment by jordansexton** [comment]
Well, hmm. You're not updating the `network` param passed to the `wallets` memo, even when updating the `rpc`?

**Comment by jordansexton** [comment]
Could you try updating to the latest versions of _all_ `@solana/wallet-adapter-` packages you use to see if the issue persists?

**Comment by zpalmtree** [comment]
Yeah, `network` is static. I thought it was a fixed mainnet-beta / devnet flag, not the RPC server?

I believe I did try upgrading everything wallet adapter related, including the phantom version etc, just not in the `package.json` I posted here, but I can try it again.

**Comment by jordansexton** [comment]
```
    "@solana/wallet-adapter-backpack": "^0.1.9",
    "@solana/wallet-adapter-base": "^0.9.18",
    "@solana/wallet-adapter-exodus": "^0.1.11",
    "@solana/wallet-adapter-glow": "^0.1.6",
    "@solana/wallet-adapter-phantom": "^0.9.9",
    "@solana/wallet-adapter-react": "^0.15.5",
    "@solana/wallet-adapter-react-ui": "^0.9.7",
    "@solana/wallet-adapter-slope": "^0.5.10",
    "@solana/wallet-adapter-solflare": "^0.6.11",
    "@solana/wallet-adapter-sollet": "^0.11.6",
```

Several of these are older -- `"@solana/wallet-adapter-react": "^0.15.22"` is the latest for example.

**Comment by zpalmtree** [comment]
Okay, I retried with these packages, got the same behavior.

```
"@solana/wallet-adapter-base": "^0.9.18",
    "@solana/wallet-adapter-exodus": "^0.1.13",
    "@solana/wallet-adapter-glow": "^0.1.13",
    "@solana/wallet-adapter-phantom": "^0.9.17",
    "@solana/wallet-adapter-react": "^0.15.22",
    "@solana/wallet-adapter-react-ui": "^0.9.20",
    "@solana/wallet-adapter-slope": "^0.5.16",
    "@solana/wallet-adapter-solflare": "^0.6.18",
    "@solana/wallet-adapter-sollet": "^0.11.12",
```

[yarn.lock.zip](https://github.com/solana-labs/wallet-adapter/files/9893105/yarn.lock.zip)

**Comment by jordansexton** [comment]
Okay, thanks for trying that. I'll take a closer look...

**Comment by zpalmtree** [comment]
Did a bit more investigation, and it seems like it might be the `onError` function being passed in when the component re-renders due to the rpc change causing the disconnect.

If I remove my `onError` function the disconnect no longer occurs even when changing the RPC. I see the behaviour exhibited even when the onError function body is completely empty. 

If I replace the onError raw function with a `React.useCallback`, the issue seems fixed.

```tsx
export function WalletWrapper(props: WalletWrapperProps) {
    const {
        children,
    } = props;

    const network = WalletAdapterNetwork.Mainnet;

    const [ rpc ] = useRecoilState(rpcState);

    const wallets = React.useMemo(() => [
        new PhantomWalletAdapter(),
        new SlopeWalletAdapter(),
        new SolflareWalletAdapter(),
        new SolletWalletAdapter({ network }),
        new SolletExtensionWalletAdapter({ network }),
        new GlowWalletAdapter({ network }),
        new ExodusWalletAdapter(),
    ], [network]);

    const onError = React.useCallback(() => {
    }, []);

    return (
        <ConnectionProvider endpoint={rpc}>
            <WalletProvider wallets={wallets} onError={onError} autoConnect>
                <WalletModalProvider>
                    {children}
                </WalletModalProvider>
            </WalletProvider>
        </ConnectionProvider>
    );
}

**Comment by jordansexton** [comment]
In your video of the issue

1. Click "Connect Wallet"
2. Phantom connected
3. Button text changes to "Disconnect Wallet", and text to the right of the button changes
4. Click settings icon, change RPC
5. Button text still stays "Disconnect Wallet", but text to the right of the button changes

> And you can see the bug being demonstrated here: https://sol-incinerator.com/redesign/

I attempted to replicate the issue, using this link:

https://www.loom.com/share/13df880b31a24c1ca722812ece2185cc

I wasn't able to. The wallet appears to remain connected as I click various RPCs.

**Comment by jordansexton** [comment]
It _seems like_ the wallet connect button is still showing the wallet as connected, but the rest of the UI isn't? Since the source of https://sol-incinerator.com/redesign/ is compiled for production, this will be pretty time consuming for me to see what's going on. If you want to add me to a closed source repo, I can take a look.

**Comment by zpalmtree** [comment]
It seems like your wallet never fully connected there. Normally it would start loading your nfts/tokens, but instead it just hung on the homepage screen.
Not quite sure the reason for that - though sometimes I do notice phantom kinda 'half' connecting - where `wallet` is defined, but `publicKey` is not. Sometimes when that occurs you would expect it to pop up this style of screen but it never does: 
![image](https://user-images.githubusercontent.com/22151537/198817579-10c3b13e-f276-467d-97ad-7b2717d95190.png)

**Comment by zpalmtree** [comment]
I added you as a collaborator to the repo: https://github.com/SolSlugs/sol-incinerator

This is the relevant code: https://github.com/SolSlugs/sol-incinerator/blob/master/src/components/WalletWrapper.tsx#L56

Changing this `React.useCallback` back to a standard function reproduces the issue for me.

**Comment by jordansexton** [comment]
So, here's another video where the rest of the UI updates:

https://www.loom.com/share/8ee31e68eff443588e53842e413946b9

I see what you're seeing. But why does the connect button show as connected still?

**Comment by zpalmtree** [comment]
It displays it as Connected in this block: https://github.com/SolSlugs/sol-incinerator/blob/master/src/components/Home.tsx#L52-L82

```ts
    const {
        connected,
        wallet,
        publicKey,
    } = useWallet();
```

When `publicKey` is null and `wallet` is defined. Not quite sure how it manages to get in that state, but clicking the disconnect button does seem to get you out of it and let you connect again.

**Comment by jordansexton** [comment]
> Changing this React.useCallback back to a standard function reproduces the issue for me.

I really should have asked what I was thinking about this example code you shared before:

```
    function onError(err: any) {
        /* ... */
    }
```

This function is instantiated every render, and passed to `WalletProvider.onError`. When you change your RPC, this forces a rerender, recreating this function, and updating the `WalletProvider` again. This sounds like it may be causing the issue.

You're saying if you memoize that function (which you should) it works as expected?

**Comment by jordansexton** [comment]
Looking at the code now...

**Comment by zpalmtree** [comment]
> > Changing this React.useCallback back to a standard function reproduces the issue for me.
> 
> I really should have asked what I was thinking about this example code you shared before:
> 
> ```
>     function onError(err: any) {
>         /* ... */
>     }
> ```
> 
> This function is instantiated every render, and passed to `WalletProvider.onError`. When you change your RPC, this forces a rerender, recreating this function, and updating the `WalletProvider` again. This sounds like it may be causing the issue.
> 
> You're saying if you memoize that function (which you should) it works as expected?

Yes, exactly, i solved my issue by memoizing the `onError`.

**Comment by jordansexton** [comment]
Oh. Okay, that's great then!

So, what happens when you change `onError` -- it destroys a bunch of callbacks in the wallet provider context and recreates them with the new `onError` handler. There might still be a bug here -- I think that shouldn't cause the wallet to disconnect.

**Comment by jordansexton** [comment]
I found the issue: https://github.com/solana-labs/wallet-adapter/blob/2315777cd9de7951127166c23835526091486b83/packages/core/react/src/WalletProviderBase.tsx#L141-L153

This teardown function was meant to clean up any state the context might have left when the active adapter is changed.

But because `handleError` is a dependency of it, and `onError` is a dependency of that, it's spontaneously wiping all the state when that function changes.

**Comment by jordansexton** [comment]
Thanks for finding this! We just released the version of `@solana/wallet-adapter-react` with this bug today. I'll fix it. Also, cool app you made!

**Comment by jordansexton** [comment]
PR to track fix @ https://github.com/solana-labs/wallet-adapter/pull/637

**Comment by steveluscher** [comment]
Thanks for this! Wrote a test so that this doesn't happen again: 2c17fc69e6934588cb4491d5bed1017571f9ae0b.

**Comment by zpalmtree** [comment]
Great, thanks for the help and super quick responses!

**Comment by jordansexton** [comment]
Release of updated packages going out via CI in #638
