### ISSUE TITLE
How do I integrate into my project that doesn't use React or any framework?

### ISSUE THREAD

**Issue by indynov** [solana-labs/wallet-adapter#639]
How do I integrate this into my project if I do not use React or any framework? I would like a Pure JavaScript wallet adapter that doesn't rely on anything else and is just a code-only JavaScript API preferably. For instance, I like the way Phantom Wallet's API is set up, however I just want a universal API that works as a layer on top so you can connect to any wallet provider, but is API only, no user interface. So I can call "connect()" and it will connect to Phantom Wallet, Solflare, Ledger, etc. I think it would help Solana in the future to have a wallet package like this that is JavaScript only in the examples and API and not TypeScript or reliant on any framework, then people can adapt it to any project they are working on easily.

**Comment by jordansexton** [comment]
All of the adapters in this repo, and the base package in this repo, and https://github.com/solana-labs/wallet-standard/tree/master/packages/wallet-adapter/base in the Solana Wallet Standard, are pure JS. Wallet Adapter can be used without any frontend framework.

**Comment by indynov** [comment]
Is there a guide on how to do that?

**Comment by jordansexton** [comment]
No. You'll need to read the code and perhaps generated TypeScript API docs. You can also use the npm published packages without using TypeScript at all. We publish ESM and CJS builds.

**Comment by indynov** [comment]
Could you create an API reference and would Solana Foundation be willing to pay for something like that? It would help the Solana Blockchain a lot to have good documentation on how this works with well written tutorials. This is very un-accessible without those things.

**Comment by jordansexton** [comment]
I would start here: https://github.com/solana-labs/wallet-adapter/tree/master/packages/core/base

All adapters have the same interface and extend from this package. That's all the help I can provide though.

**Comment by indynov** [comment]
I cannot use this. I would need documentation so I will not be able to develop with it unless I create my own via Phantom Wallet docs and then writing code for each Wallet I will support, which seems very silly considering you work at Solana and you are getting paid to do that. All you would need to do is write some documentation for how this wallet adapter works that you wrote so that it is accessible to people. You have no explanation written for how this works at all, not even spending 1 afternoon writing an article on it.
