### ISSUE TITLE
Link to informational resources to learn more about how Solana Wallets work

### ISSUE THREAD

**Issue by indynov** [solana-labs/wallet-adapter#642]
Hello, would you be willing to link to this in an FAQ in the Readme for people who may not want to use React and want to learn how to build their own Adapter and may be using PHP, Python, Ruby, Java, C#, etc Server-Side? I spent a good amount of time working on this to figure it out and think it will help people to learn more about how these wallet adapters work in the future. It would be good if you compiled a list of resources for people to learn more about it with a link to it on the front page because there isn't much information how Solana works.

solana.stackexchange.com/questions/4157/how-can-you-send-an-nft-with-phantom-wallet-without-react-and-using-something-li/4159

**Comment by jordansexton** [comment]
A link to the Solana Stack Exchange has been added to https://github.com/solana-labs/wallet-adapter/blob/master/FAQ.md

Wallet Adapter is a set of client-side JavaScript libraries. We don't intend to document how to do server-side development, or development in any other language.
