### ISSUE TITLE
Module parse failed: Unexpected token at Wallet Provider

### ISSUE THREAD

**Issue by Merrick17** [solana-labs/wallet-adapter#644]
**Describe the bug**
Hello i'm trying to update my current project to latest version of the latest version of wallet adapter. 
I get the following error `./node_modules/@solana/wallet-adapter-react/lib/esm/WalletProvider.js 12:38
Module parse failed: Unexpected token (12:38)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js     
You may need an additional loader to handle the result of these loaders.   
| function getUserAgent() {
|   if (_userAgent === undefined) {
>     _userAgent = globalThis.navigator?.userAgent ?? null;
|   }
|   return _userAgent;`

React: 17.0.2
Craco: 5.64

**Comment by bryantanjw** [comment]
Bumped into this error as well. Did you manage to resolve this?

**Comment by OlexBeatable** [comment]
@Merrick17 I just checked this issue out and it was helpful for me. https://github.com/solana-labs/wallet-adapter/issues/633

**Comment by jordansexton** [comment]
This is an issue with Create React App. Definitely check out #633 or search the other issues for Create React App / CRA.
