### ISSUE TITLE
I'm getting Hydration failed because the initial UI

### ISSUE THREAD

**Issue by ZeyadSaeed** [solana-labs/wallet-adapter#648]
I'm getting Uncaught Error: Hydration failed because the initial UI when I'm using @solana/wallet-adapter-react-ui package

![Screenshot 2022-11-05 095828](https://user-images.githubusercontent.com/89784930/200109981-0ba4af5a-f822-4081-a9a1-eeca9ed8ff09.png)

**Comment by vitormancio** [comment]
I'm have the same problem ...

**Comment by jordansexton** [comment]
This isn't a bug with Wallet Adapter -- you'll need to use `dynamic` components in Next.js to avoid SSR hydration issues.

See the example starter project in this repo for how to do that!

**Comment by ZeyadSaeed** [comment]
Thank you! The problem solved when I used dynamic import.

**Comment by haris-aqeel** [comment]
[@jordansexton I am receiving the same issue?
](https://github.com/solana-labs/wallet-adapter/commit/70fd5aac6eaf9584b0e3034685236a850e3488e4)

**Comment by slashplusdash** [comment]
I have a problem with my next js project which adds to do on a list, marks them to be complete or removes the to do. I have tried using dynamic but when I try to add to dos a supposed transaction modal will appear but it won't. I need help with this...
