### ISSUE TITLE
Compatibility with NextJS 13?

### ISSUE THREAD

**Issue by schellenbergk** [solana-labs/wallet-adapter#655]
I tried to get it working with the newest NextJS 13 but getting some errors:

```
Server Error
TypeError: (0 , react_1.createContext) is not a function
```

Here's my source code:

https://github.com/schellenbergk/solana-wallet-adapter-nextjs13-example

**Comment by gabster-code** [comment]
Any luck on this? Been trying stuff out but can't find a stable solution.. Either I get that context error or some random module is not getting imported/used or something.

**Comment by schellenbergk** [comment]
@gabster-code , Still stuck on the same error... Was hoping someone else with more expertise could look into this issue...

**Comment by tribixbite** [comment]
my _app.tsx, then just use <WalletMultiButton /> in the navbar component
![image](https://user-images.githubusercontent.com/381345/205145894-7a23c885-d288-4b5c-9bd5-fc0dead18483.png)

**Comment by schellenbergk** [comment]
:(... does not work on my end... Still getting:
```
Server Error
TypeError: (0 , react_1.createContext) is not a function
```
https://github.com/schellenbergk/solana-wallet-adapter-nextjs13-example

**Comment by tribixbite** [comment]
> :(... does not work on my end... Still getting:
> ```
> Server Error
> TypeError: (0 , react_1.createContext) is not a function
> ```
> https://github.com/schellenbergk/solana-wallet-adapter-nextjs13-example

I'm only seeing one commit on one branch from 20 days ago on that repo. Please link the relevant file. Also you are using a very atypical structure for your app. I'd suggest cloning a different scaffold/example repo. For example, the one from solana labs react ui

**Comment by jordansexton** [comment]
There is a Next.js starter project in the Wallet Adapter repo. Has anyone here tried using it, updating to the latest version of Next?

**Comment by gabster-code** [comment]
> _app.tsx, `<WalletMultiButton />` is in the AppNavbar component
> 
> ```
> const [isHydrated, setIsHydrated] = useState(false);
>   //Wait till NextJS rehydration completes
>   useEffect(() => {
>     setIsHydrated(true);
>   }, []);
> ```
> 
> deployed: https://go.moonshinelabs.io/condo ![image](https://user-images.githubusercontent.com/381345/205145894-7a23c885-d288-4b5c-9bd5-fc0dead18483.png)

I think this still uses the pages folder instead of the new App folder structure of NextJS 13.

**Comment by gabster-code** [comment]
So... i saw a video of a nextjs 13 tutorial for implementing Next-Auth in the new App Structure and tried using the pattern for solana-wallet-adapter.

_on /context/providers.js_
![image](https://user-images.githubusercontent.com/88597385/205314238-c19b9be4-20b9-446d-b8b4-1fdb4745c659.png)


_then on /app/layout.tsx_
![image](https://user-images.githubusercontent.com/88597385/205314494-4071c832-f018-481b-b319-d1bb0a34f7d8.png)


This will throw a Hydration error on npm run dev...but if you build it or deploy it on vercel it works just fine. 
Demo: https://connext13.vercel.app/ (It's just a test thing..)

My current challenges now are:
- The connection shows "false" when console logging the output of the "connected" function/variable from  `const { publicKey, signTransaction, connected } = useWallet(); `
- The hydration error on dev mode makes it hard to continue developing as you won't know which causes the hydration error or is just the adapter


Hoping for a NextJS 13 compatible version of the adapters soon. 🙏

**Comment by tribixbite** [comment]
> So... i saw a video of a nextjs 13 tutorial for implementing Next-Auth in the new App Structure and tried using the pattern for solana-wallet-adapter.
> 
> _on /context/providers.js_
> ![image](https://user-images.githubusercontent.com/88597385/205314238-c19b9be4-20b9-446d-b8b4-1fdb4745c659.png)
> 
> 
> _then on /app/layout.tsx_
> ![image](https://user-images.githubusercontent.com/88597385/205314494-4071c832-f018-481b-b319-d1bb0a34f7d8.png)
> 
> 
> This will throw a Hydration error on npm run dev...but if you build it or deploy it on vercel it works just fine. 
> Demo: https://connext13.vercel.app/ (It's just a test thing..)
> 
> My current challenges now are:
> - The connection shows "false" when console logging the output of the "connected" function/variable from  `const { publicKey, signTransaction, connected } = useWallet(); `
> - The hydration error on dev mode makes it hard to continue developing as you won't know which causes the hydration error or is just the adapter
> 
> 
> Hoping for a NextJS 13 compatible version of the adapters soon. 🙏

Try adding the hydration error avoidance code I shared above

**Comment by jordansexton** [comment]
I haven't seen a reason why Wallet Adapter wouldn't be compatible with Next 13. If you're having hydration issues, you want to use `dynamic` for components that may change between SSR and client side render. See https://github.com/solana-labs/wallet-adapter/blob/98be91396f1d586761451c23c80c4cf54c101567/packages/starter/example/src/pages/index.tsx#L42-L45

**Comment by schellenbergk** [comment]
I wasn't able to get it working with any of the examples above inside the `app` folder.  If anyone does get it working, if you could submit a pull request to the following repo please: https://github.com/schellenbergk/solana-wallet-adapter-nextjs13-example

**Comment by tyirenkyi** [comment]
Ran into this issue today. Took me a while to realise what was happening. You're probably calling a client-side hook in a server component. All you need to do is export the wallet adapter component from a file marked with `'use client'` and you should be able to use it anywhere in your app. 

For example:

```
'use client'

import dynamic from 'next/dynamic'

export const WalletConnectButton = dynamic(
  async () => (await import('@solana/wallet-adapter-react-ui')).WalletConnectButton,
  { ssr: false }
)
```

`import { WalletConnectButton } from '@components/ConnectButton'`
