### ISSUE TITLE
Slope Wallet

### ISSUE THREAD

**Issue by indynov** [solana-labs/wallet-adapter#657]
Hello, we shouldn't advertise Slope Wallet anymore or include it as a feature in the wallet adapter I think, if anyone has Slope Wallet they shouldn't be buying anything with it just trying to get their money out of it to another wallet. They sent their private keys over the network and they got leaked most likely someone in the project itself who did it. Also if you have close contact with Solana at all they should try to prevent this from happening in the future somehow and work more closely with people who develop Wallets Apps to try to make them more secure. In the future Solana should move closer towards a wallet they would feel secure using themselves.

I wanted to share this information with you in case you can get it to the person who runs Solana as it may help them in the future refine their idea of a Blockchain Wallet that is secure-

I have an idea on how to make the Blockchain more secure but still needs some refining but if you can adapt and improve it at all and ever want to present it to people it is (copy pasted):

I have a solution to make the Blockchain Wallets more secure if Blockchains would implement it. When you open a wallet it should send a message to the blockchain so the blockchain generates different keys and sends them to different key holding services. You need to use multiple keys to sign a transaction and no 1 particular organization has them all and as long as they don't tell eachother they only have 1 of the keys. When you do a transaction you could sign into a key provider and it may be like a Google Authenticator also to get a 6 digit code generated to type it in when approving a transaction. It may even be possible that the key providers wouldn't be able to identify you to put them together possibly to know which go with which account possibly. This would make blockchain wallets 1000x more secure. The key providers can keep them on their servers, and if you have 1 of the keys you can send a message to the blockchain and it will send reminders out to everyone in case anyone ever loses 1 of them so this makes it much more difficult you would ever lose access to your account also. 
So basically in other words, when you open an account you know how you normally generate a mnemonic phrase? Well instead you could send a message to the blockchain and it could generate multiple mnemonic phrases and send them to different companies so no 1 company has the entire key. The keys will possibly get generated by different Nodes on the blockchain or possibly Nodes that those key providers are maintaining
Then when it's time to sign a transaction the companies can send something to prove they have the key like a Google Authenticator type code that the blockchain can confirm was generated from the key. Or instead of something similar to Google Authenticator it could be a text message or email verification to prove access to the email account also.
I think there is something that could exist so no 1 company could possibly have full access to accounts on the blockchain like with what happened with Slope Wallet and even accounts on the blockchain can have email verification and 2 step authentication, etc. Also there may be some way to implement something so people are much less likely to ever lose their keys or lose access to their account if they forget their secret key.

**Comment by jordansexton** [comment]
See https://github.com/solana-labs/wallet-adapter/issues/573#issuecomment-1254008084 and please search the issues before opening one.

Also, do not open issues that are not bug reports or feature requests, and use the provided templates. There is a reason those templates exist, and this isn't a discussion forum.

Finally, new features that add functionality to wallets are out of scope for Wallet Adapter. If you have a feature request for wallets to implement, please direct that to wallets themselves.
