### ISSUE TITLE
Replace lerna with yarn v2 workspaces

### ISSUE THREAD

**Issue by jordansexton** [solana-labs/wallet-adapter#66]
`lerna version` doesn't correctly update peer dependencies before pushing git tags. This breaks tags and forces us to manually update versions before releases. Since Lerna appears to be unmaintained, I'm not expecting this to be fixed, so I think we need to move away from using it.

**Comment by danmt** [comment]
Lerna has been a PITA for the Angular package, the build process for Angular isn't the typical JS-package flow and the Lerna maintainers refuse to support the use-case.

Would you take a look at Nx workspace? If you like it, I can definitely help to get that working, their team is friendly and helpful.

**Comment by jordansexton** [comment]
Sure. The criteria I can think of are --

1. Make it easy to independently update, version, tag, and publish single and multiple packages built with different frameworks.
2. Link dependencies, including peer dependencies, between the packages, symlink them locally, and update them when they build or versions change.
3. Handle most tasks with simple scripts in package.json and don't make us jump through hoops or think about the tool very much.

If it sounds like Nx workspaces will do these, let's give it a shot!

**Comment by danmt** [comment]
Wait, were you describing our needs or Nx workspaces? Lol

It does support all of those, one caveat is that I've never used it for React apps. I know they support it, just never gave it a try.

You can take a look at Nx while I wrap up #42 and then we can discuss how to architect it.

**Comment by jordansexton** [comment]
Yeah, just describing the requirements upfront. Sounds good. 👍

**Comment by jordansexton** [comment]
Iceboxing this since it's not a priority right now.
