### ISSUE TITLE
@solana/wallet-adapter-react error

### ISSUE THREAD

**Issue by Smart133594** [solana-labs/wallet-adapter#664]
After changing react-scripts from version "5.0.0" to "4.0.3" and installed solana wallets adapters successfully. Then importing this
@solana-wallet-react brings this error,

I am working with typescript.
./node_modules/@solana/wallet-adapter-react/lib/esm/WalletProvider.js 13:155
Module parse failed: Unexpected token (13:155)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   if (_userAgent === undefined) {
|     var _globalThis$navigator;
>     _userAgent = ((_globalThis$navigator = globalThis.navigator) === null || _globalThis$navigator === void 0 ? void 0 : _globalThis$navigator.userAgent) ?? null;
|   }
|   return _userAgent;

Has anyone got this kind of error?

**Comment by jordansexton** [comment]
Check this out: https://github.com/solana-labs/wallet-adapter/issues/633#issuecomment-1293848338

This is an issue with CRA 4. While I recommend not using CRA 4 at all, and instead using the [CRA 5 starter project](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/create-react-app-starter), if you use CRA 4, you'll need Craco, and the above comment should help with your configuration.
