### ISSUE TITLE
How can I get wallet address when connecting to wallet

### ISSUE THREAD

**Issue by ShotikoS** [solana-labs/wallet-adapter#668]
Hello. I'm trying to get wallet address when users click on select wallet button and selects phantom wallet for example.
I tried to get wallet address from useWallet hook but I can not find wallet address in object which returned from useWallet

**Comment by jordansexton** [comment]
The value you're looking for is the `publicKey` returned by `useWallet`. Please don't open GitHub issues with questions though 🙂 The provided issue templates are only for bug reports or feature requests.
