### ISSUE TITLE
Sollet wallet is not working

### ISSUE THREAD

**Issue by IvanBurzakovskyi** [solana-labs/wallet-adapter#672]
**Describe the bug**
The `https://www.sollet.io/` is not responding. The Chrome extension also is not working (infinite loader is shown)

**To Reproduce**
1. Go to `https://www.sollet.io/`
2. See the `This site can’t be reached`
OR
3. Open the Chrome extension `Sollet`;
4. See the infinite loaders;

**Expected behavior**
The `https://www.sollet.io/` and the extension are working.

**Screenshots**
<img width="715" alt="image" src="https://user-images.githubusercontent.com/85485485/206855744-49a7fcd6-f157-48f8-8408-a721e812c721.png">

<img width="372" alt="image" src="https://user-images.githubusercontent.com/85485485/206855755-9e1bed24-5377-45c9-a703-9fc43014bd5c.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.1
 - Browser Chrome
 - Version 107.0.5304.87

**Comment by jordansexton** [comment]
Sollet is deprecated, and no longer works because it relies on Serum RPCs which are no longer active.

Check out this thread for how to export your key from Sollet, which you can use with a different wallet:

https://twitter.com/steveluscher/status/1593075105042944000

**Comment by jordansexton** [comment]
If you have the extension, you may be able to export it directly from there.
