### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by hyetigran** [solana-labs/wallet-adapter#675]
**Describe the bug**
Adding the wallet-adapter-backpack library to my next.js 11 dApp causes loader error.

**To Reproduce**
1. Grab starter project from `commit 10655364d6945c49fb14a14056cedd175eb04479`
2. yarn add '@solana/wallet-adapter-backpack'
3. Add BackpackWalletAdapter to `WalletConnectionProvider`
4. run `yarn dev`

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5153613/207468473-f22e6e58-5272-43c2-bbd7-67dcf5003d8c.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Brave
 - Version 12.5

**Additional context**
My next.config.js file appears similar to this starter example:
https://github.com/solana-labs/wallet-adapter/blob/2c29262405f971f950563f2ff229c1a7a2ff2582/packages/starter/nextjs-starter/next.config.js

next.config.js
```
const path = require('path');
const withTM = require('next-transpile-modules')([
  '@blocto/sdk',
  '@project-serum/sol-wallet-adapter',
  '@solana/wallet-adapter-base',
  '@solana/wallet-adapter-react',
  '@solana/wallet-adapter-wallets',
  '@solana/wallet-adapter-bitkeep',
  '@solana/wallet-adapter-bitpie',
  '@solana/wallet-adapter-blocto',
  '@solana/wallet-adapter-coin98',
  '@solana/wallet-adapter-ledger',
  '@solana/wallet-adapter-mathwallet',
  '@solana/wallet-adapter-phantom',
  '@solana/wallet-adapter-safepal',
  '@solana/wallet-adapter-slope',
  '@solana/wallet-adapter-solflare',
  '@solana/wallet-adapter-sollet',
  '@solana/wallet-adapter-solong',
  '@solana/wallet-adapter-torus',
]);

module.exports = withTM({
  target: 'serverless',
  distDir: 'build',
  trailingSlash: true,
  webpack5: false,
  webpack(config) {
    config.module.rules.push(
      {
        test: /\.svg$/,
        issuer: {
          test: /\.(js|ts)x?$/,
        },
        use: ['@svgr/webpack'],
      },
      {
        test: /\.png$/,
        issuer: {
          test: /\.(js|ts)x?$/,
        },
        use: ['file-loader'],
      },
      {
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto',
      },
    );
    config.resolve.alias = {
      ...config.resolve.alias,
      assets: path.resolve(__dirname, './public/assets'),
    };
    config.node = {
      fs: 'empty',
    };

    return config;
  },
});
```

**Comment by jordansexton** [comment]
See this FAQ: https://github.com/solana-labs/wallet-adapter/blob/master/FAQ.md#nextjs-with-react

`next-transpile-modules` is not required. Please try using the starter project @ https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/nextjs-starter
