### ISSUE TITLE
Cannot re-connect to Sollet web after closing the window

### ISSUE THREAD

**Issue by danmt** [solana-labs/wallet-adapter#68]
# Overview

As an end-user, if you connect to Sollet web and close the window, you're not capable of connecting again to Sollet web by selecting it again.

## Reproduction steps

- Go to `/packages/example`
- Run `yarn start`
- Select Sollet web with any of the UI options
- Connect to the wallet
- Close the window
- Select Sollet web again

## Expected behavior

As a user I would expect to be able to select Sollet web again and get prompted again. Even after closing the window.

## Behavior found

The only way to get prompted again after closing the window is to select another wallet and then select Sollet web again.

## Proposed solution

While working on #42 I noticed that if you close the window, an adapter disconnect event is fired leading to a "reset" of the state using `initialState`. When this happens, the state gets set to its initial value but the "selected wallet name" remains unchanged. I'm not sure if this is happening for the React package as well, but maybe all it takes is to call `setName(null)` on adapter disconnect.

**Comment by jordansexton** [comment]
Wow, thanks for the excellent report. I'll get to the bottom of this. I imagine https://github.com/solana-labs/wallet-adapter/pull/64 broke something.

**Comment by jordansexton** [comment]
Fixed and published in @solana/wallet-adapter-react 0.10.1
