### ISSUE TITLE
Phantom iOS connect requires an extra tap

### ISSUE THREAD

**Issue by mcintyre94** [solana-labs/wallet-adapter#684]
**Describe the bug**

Opening this as an issue because there's some fiddly stateful logic to work through

In #673 we added a redirect to Phantom's wallet browser when connecting to Phantom in iOS safari

This change introduced an `autoConnect` function, which is called both when the wallet is first restored from localstorage and when a new wallet is selected, and just replaces existing logic to call MWA autoconnect or adapter `connect`. 

In Phantom this `autoConnect` is set to a no-op on iOS Safari, because when the page first loads we can't redirect to the Phantom universal link (nor would we want to, it'd make it impossible to disconnect from the dapp in Safari)

This means that we need to select Phantom in the wallet modal (this triggers the no-op), and then click the connect/multi button to trigger the redirect

We should be able to redirect on select, because this is a result of user action. But currently it's a no-op so we don't. 

**To Reproduce**

1. Open a dapp using the latest dependencies (eg a starter from this repo) in iOS Safari
2. Connect to Phantom

**Expected behavior**

Selecting the Phantom wallet should be sufficient to trigger the redirect

**Screenshots**

Current UX:

https://user-images.githubusercontent.com/1711350/208091596-8eb85722-b6c4-4e29-9cbc-906c5050979d.mov

**Additional context**

Basically the data flow going on here is:

On page load:

`WalletProvider`
- Get wallet name from localstorage (initial value of `walletName`)
- Set adapter from wallet name
`WalletProviderBase`
- Set wallet from adapter (prop)
- Run a `useEffect` when `wallet` changes which calls `autoConnect`

Here the behaviour is correct: we want a no-op for Phantom on iOS

On wallet select:
`WalletProvider`
- Update wallet name on select (call `setWalletName`)
- Set adapter from wallet name
`WalletProviderBase`
- Set wallet from adapter (prop)
- Run a `useEffect` when `wallet` changes which calls `autoConnect`

Here it's incorrect: we'd prefer to call `connect`

---

Considerations:

- The `autoConnect` function is by default just a call to `connect`. But Phantom and MWA have custom implementations. For MWA the current behaviour is correct in both cases and needs to stay the same. For Phantom it's incorrect only on wallet select
- There are no other calls to `setWalletName` except to set it to null

---

Suggested solutions:

- We could extend the `autoConnect` function call to pass an indication of whether the wallet has been selected automatically or by user action. Then the Phantom adapter could differentiate based on that. We could probably achieve this by having the `select` function set some ref that indicates a selection has been made. This would be a one way switch: once a select call has been made it'd be set to true and all future changes would be assumed to be by user select. This does rely on the fact that no other code sets another wallet elsewhere though. If we added any other code setting the wallet without user input it'd have to reset the ref. 
- We could try to remove some of the reactive code, and write an explicit behaviour on first connect then only runs once (when we have a wallet to connect to). And then write an explicit function for select that also connects, rather than being through this chain of updates. But a lot of code relies on the intermediate values (`adapter` and `wallet`), so we'd still have to maintain them in all cases. And I think this would probably be very difficult to do without breaking anything.

**Comment by script8888** [comment]
How did you get it to request connect in the Phantom app? mine just takes me to the phatom website
can you show code please?

**Comment by mcintyre94** [comment]
@script8888 We recently updated Wallet Adapter to add this: https://github.com/solana-labs/wallet-adapter/pull/673
You'll need to update the wallet-adapter packages and then it should just work. If you're using NPM then `npm upgrade @solana/wallet-adapter-base @solana/wallet-adapter-react @solana/wallet-adapter-react-ui @solana/wallet-adapter-wallets` should do it :)

**Comment by script8888** [comment]
Awesome
I am on the latest version tho, I read through #673  but cant seem to understand how to use the autoConnect
currently from the browser, Im redirected to the phantom app when I click on the button
But Im not given the modal to connect the wallet in the app as seen in 0:08 of your videw

**Comment by mcintyre94** [comment]
@script8888 would you mind opening a question on solana.stackexchange.com please? If you can include your code (or better yet a repro in CodeSandbox or similar) hopefully we'll be able to get to the bottom of it. We'll need more detail than makes sense to go into here though.

**Comment by script8888** [comment]
sure
https://solana.stackexchange.com/questions/4882/how-to-initiate-connect-wallet-on-phantom-mobile-app

**Comment by script8888** [comment]
[This is a video of how it currently behaves](https://cdn.discordapp.com/attachments/984069971040698429/1053750227204591746/VID-20221217-WA0094.mp4)
