### ISSUE TITLE
Chakra UI package for the react wallet adapter

### ISSUE THREAD

**Issue by AnishDe12020** [solana-labs/wallet-adapter#687]
**Is your feature request related to a problem? Please describe.**
There are material ui and ant design packages for the wallet adapter but not for Chakra UI

**Describe the solution you'd like**
A Chakra UI wallet adapter packages, similar to the material ui and ant design ones

**Describe alternatives you've considered**
None

I will see if I can create one

**Comment by jordansexton** [comment]
Closing per https://github.com/solana-labs/wallet-adapter/pull/688#issuecomment-1361685767
