### ISSUE TITLE
Torus Wallet not working on Solana plugin

### ISSUE THREAD

**Issue by webdevelopersbc** [solana-labs/wallet-adapter#690]
On login window after login with torus wallet showing an console error in node_module packages. Here is the screenshot https://prnt.sc/bncnuxpk43BL

**Comment by steveluscher** [comment]
From the screenshot, you appear to be experiencing an error thrown from here:

https://github.com/solana-labs/wallet-adapter/blob/cbc15185a32db508faf677fbb572d97c9ae75bd3/packages/wallets/torus/src/adapter.ts#L87

Take this up with Torus! It appears that the problem emanates from `@toruslabs/solana-embed`.

https://github.com/torusresearch/solana-embed/issues
