### ISSUE TITLE
Partial-Sign transactions for multi signing.

### ISSUE THREAD

**Issue by muhitrhn** [solana-labs/wallet-adapter#697]
Is it possible to partial sign transactions approved by users so the transaction can be directed to another user for their part of approving? In case where a transaction needs two people to sign it. Can anyone help in this case? @jordansexton

**Comment by muhitrhn** [comment]
Thanks @jordansexton . Sorry for the issue here in issue tracker but someone suggested I somehow contact you in this case. Can you please check [partial-sign-transaction-from-front-end](https://solana.stackexchange.com/questions/5007/partial-sign-transaction-from-front-end/5015#5015) in stackexchange?

**Comment by jordansexton** [comment]
Yes, please don't do this (open Github issues to ask questions.) Especially when you already asked the question in the right place (thanks for opening it there though!)

**Comment by muhitrhn** [comment]
I'll keep that in mind. Maybe open up `Discussions` in case someone wants to ask here also?

**Comment by jordansexton** [comment]
We don't want to answer questions or host discussions here, that's what we use Stack Exchange for. We want to allow maintainers to focus on projects, and have one place for Solana support. I'll respond to your question there though!

**Comment by muhitrhn** [comment]
> We don't want to answer questions or host discussions here, that's what we use Stack Exchange for. We want to allow maintainers to focus on projects, and have one place for Solana support. I'll respond to your question there though!

Gotcha thank you for the clarification. Makes sense!
