### ISSUE TITLE
WalletSignTransactionError: undefined is not an object

### ISSUE THREAD

**Issue by MoizYousuf** [solana-labs/wallet-adapter#703]
**Describe the bug**
I am trying to use SolanaMobileWalletAdapter with react native and unable to sign or send transactions, when using the wallet.signTransaction it throws the following error.

**To Reproduce**
Use a simple scaffold with wallet provider and SolanaMobileWalletAdapter, and sign a transaction to reproduce.

**Expected behavior**
Expected a signed transaction

**Screenshots**
<img width="755" alt="image" src="https://user-images.githubusercontent.com/35624356/211747832-8761eadf-d7f9-43b3-ba64-102509f129fe.png">

<img width="568" alt="image" src="https://user-images.githubusercontent.com/35624356/211747653-7c82329f-3b72-4ca2-9086-72373553d7c5.png">

**Desktop (please complete the following information):**
Macbook Pro 2015 15'

**Smartphone (please complete the following information):**
Android Emulator

**Additional context**

**Comment by steveluscher** [comment]
Can you look at your package-lock.json or yarn.lock file and see what version of `@solana/web3.js` you are running? If it's missing `VersionedMessage`, that could be the problem.

**Comment by MoizYousuf** [comment]
I tried upgrading `@solana/web3.js` but got another error. nothing changed only upgraded `@solana/web3.js` to latest
<img width="563" alt="image" src="https://user-images.githubusercontent.com/35624356/212317180-32f0ea0b-3430-406d-b560-11d107dfab4f.png">

**Comment by steveluscher** [comment]
Ah yes! That's the right version, _but_ now you must upgrade React Native past 0.7. See the ‘compatibility’ section of the [`README`](https://github.com/solana-labs/solana/tree/master/web3.js#compatibility) for minimum system requirements, and check out the React Native [example app](https://github.com/solana-mobile/mobile-wallet-adapter/tree/main/examples/example-react-native-app).

**Comment by MoizYousuf** [comment]
Hello @steveluscher, After updating everything `web3.Keypair.generate()` function broke down, it's throwing the following error.
`err [TypeError: undefined is not a function]`

Thanks for all the support.

**Comment by steveluscher** [comment]
A stacktrace would be helpful, at the point that error is thrown. Also, can you confirm that you’re running the Hermes engine in React Native >0.70 now?

**Comment by MoizYousuf** [comment]
yes its running

**Comment by steveluscher** [comment]
Alright! Without a stacktrace it’s hard to know what’s wrong. Why don’t we take this over to stackoverflow.com; at this point it sounds related to your build and not to wallet adapter.

**Comment by MoizYousuf** [comment]
okay thanks! 👍🏻
