### ISSUE TITLE
Sync wallet address with wallet extension

### ISSUE THREAD

**Issue by Somnus007** [solana-labs/wallet-adapter#708]
**Is your feature request related to a problem? Please describe.**
For example, I have 4 wallets in Phantom, I have connected wallet-1 via wallet-adaper sdk, then I change selected wallet to wallet-2 in Phantom, wallet-adaper sdk can not sync the new selected wallet in Phantom. I have to refresh my page.

**Describe the solution you'd like**
Auto-sync function from wallet-adaper sdk

**Describe alternatives you've considered**
Manual-sync function from wallet-adaper sdk

**Additional context**
No

**Comment by jordansexton** [comment]
Phantom has an event (`accountChanged`) for this. The Phantom wallet adapter [supports it](https://github.com/solana-labs/wallet-adapter/blob/f599b16fd259ada6a41365c27b46e98702abd851/packages/wallets/phantom/src/adapter.ts#L290-L305). However, if the app doesn't have access to the account that was switched to, I don't think this will work (it will just disconnect). This behavior is up to Phantom, and not something the adapter can do anything about.
