### ISSUE TITLE
Can wallet logo pics be somewhere central location that wont change?

### ISSUE THREAD

**Issue by nukec** [solana-labs/wallet-adapter#74]
I guess a lot of websites were broken:
![image](https://user-images.githubusercontent.com/3589518/133326967-cf828547-40cb-4692-855e-5b1ed786d410.png)

**Comment by jordansexton** [comment]
Just fixed. Yeah, I'll compile them into the wallets package and/or make sure they don't move. Sorry about that!

**Comment by jordansexton** [comment]
I'll leave this open until it's done.

**Comment by jordansexton** [comment]
https://github.com/solana-labs/wallet-adapter/blob/master/packages/wallets/icons/__DO_NOT_MOVE__.txt

Wallet icon image files will remain at this location until at least version 1.0 is released.

However, all wallets have been converted to use base64 for embedding images, so this kind of thing won't happen for anyone who upgrades.

https://github.com/solana-labs/wallet-adapter/blob/a630fdb746e7d9f152bc507e49b1b7b62b556307/packages/core/wallets/src/wallets.ts#L88
