### ISSUE TITLE
Phantom Wallet Not deducting using solana wallet adapater

### ISSUE THREAD

**Issue by prashantcrypto** [solana-labs/wallet-adapter#741]
Recently i made a next js app and it works smoothly o the windows 10 while i tried to test on  the  linux(Ubantu and Kali) it deducted the phantom wallet in localhost as well in the VPS also it doesnt worked

**To Reproduce**
1. Download the Nextjs solana starter
3. Run it using yarn dev or after building using yarn start
4. Download the phantom wallet extension(i used edge , Chrome and brave)
5. See it wont deduct it neither it will connect on selecting the phantom
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: UBANTU 22.04.2 LTS (GNU/Linux 5.2.0 x86_64)
 - Browser MS Edge, Chrome and Brave

**Comment by jordansexton** [comment]
There's no indication of a bug with Wallet Adapter, and I can't replicate this with the [example](https://solana-labs.github.io/wallet-adapter/example/). Issues with Phantom should be reported to Phantom.
