### ISSUE TITLE
Uncaught (in promise) WalletNotSelectedError

### ISSUE THREAD

**Issue by shin101004** [solana-labs/wallet-adapter#743]
**Describe the bug**
Uncaught (in promise) WalletNotSelectedError 

**To Reproduce**
I wrapped component with context from https://github.com/solana-labs/wallet-adapter/blob/master/packages/starter/react-ui-starter/src/App.tsx

**Expected behavior**

**Screenshots**

<img width="570" alt="스크린샷 2023-02-28 오후 12 01 22" src="https://user-images.githubusercontent.com/61345090/221742550-00f8ada6-5fa8-430d-8d78-18a71944ca1d.png">

**Desktop (please complete the following information):**
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**
here is my code
```javascript
import "./App.css";
import { WalletAdapterNetwork } from "@solana/wallet-adapter-base";
import {
  ConnectionProvider,
  WalletProvider,
} from "@solana/wallet-adapter-react";
import { UnsafeBurnerWalletAdapter } from "@solana/wallet-adapter-wallets";
import { clusterApiUrl } from "@solana/web3.js";
import React, { useMemo } from "react";
import Button from "./Button";

function App() {
  const Context = ({ children }) => {
    // The network can be set to 'devnet', 'testnet', or 'mainnet-beta'.
    const network = WalletAdapterNetwork.Devnet;

    // You can also provide a custom RPC endpoint.
    const endpoint = useMemo(() => clusterApiUrl(network), [network]);

    const wallets = useMemo(
      () => [
        /**
         * Wallets that implement either of these standards will be available automatically.
         *
         *   - Solana Mobile Stack Mobile Wallet Adapter Protocol
         *     (https://github.com/solana-mobile/mobile-wallet-adapter)
         *   - Solana Wallet Standard
         *     (https://github.com/solana-labs/wallet-standard)
         *
         * If you wish to support a wallet that supports neither of those standards,
         * instantiate its legacy wallet adapter here. Common legacy adapters can be found
         * in the npm package `@solana/wallet-adapter-wallets`.
         */
        new UnsafeBurnerWalletAdapter(),
      ],
      // eslint-disable-next-line react-hooks/exhaustive-deps
      [network]
    );

    return (
      <ConnectionProvider endpoint={endpoint}>
        <WalletProvider wallets={wallets} autoConnect>
          <Button />
        </WalletProvider>
      </ConnectionProvider>
    );
  };

  return (
    <div className="App">
      <Context>
        <Button />
      </Context>
    </div>
  );
}

export default App;
```

**Comment by jordansexton** [comment]
I'm not sure what `Button` does but you have to select and then connect to a wallet to use it. If you are attempting to call `connect` without having selected a wallet first, you'll get a `WalletNotSelectedError`. The recommended way to handle this is to not call `connect` at all, but use the `autoConnect` behavior that you already have enabled on `WalletProvider`. You still need to use a button or some other user action to call `select`.

**Comment by alchemist0803** [comment]
You should add `select` and `connect` wallet function on `Button`.
Here is how.
```

const { select, connect } = useWallet();

const buttonClicked = async () => {
     select();
     await connect();
}

return (
  <div className="App">
      <Context>
        <Button onClick={buttonClicked} />
      </Context>
    </div>
)
```

**Comment by justgeek** [comment]
This is stupid, but it looks like calling `await select()` works even it is not documented as a promise!

**Comment by nokdoot** [comment]
select function must be async function

**Comment by kima-bastian** [comment]
> select function must be async function select(walletName); connect(); always returns WalletNotSelectedError just after loading page

same here, have to "connect" two times in order to work...

**Comment by aymanch-03** [comment]
> > select function must be async function select(walletName); connect(); always returns WalletNotSelectedError just after loading page
> 
> same here, have to "connect" two times in order to work...

same problem

**Comment by kima-bastian** [comment]
Solved it using this logic:

```
const connectWallet = async (walletName) => {
    currentWallet?.adapter.name === walletName
      ? await connect()
      : select(walletName)
  }
```
