### ISSUE TITLE
Wallet connect fails when user switches sub-wallet in phantom during connect.

### ISSUE THREAD

**Issue by mschneider** [solana-labs/wallet-adapter#747]
**Describe the bug**
Wallet connect fails when user switches sub-wallet in phantom during connect.

**To Reproduce**
1. switch phantom to the wrong wallet
2. open v4.mango.markets
3. connect wallet - phantom
4. switch wallet in phantom window

phantom window disappears, but wallet is now connected allthough i never pressed "connect"

5. try to deposit: 
Phantom - RPC Error: The requested method and/or account has not been authorized by the user. 

**Expected behavior**
Phantom should allow me to press connect

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 110

**Additional context**
Someone in Mango had a look and thinks this is a wallet adapter issue and not related to our integration, I didn't verify it personally.

**Comment by bfriel** [comment]
Hey @mschneider thanks for reporting. Do you mind sharing what version of Phantom you're running (Settings -> About Phantom). Is this a multichain version of Phantom?

**Comment by mschneider** [comment]
23.2.4

**Comment by jordansexton** [comment]
I have built the Mango v4 UI project locally, and can't replicate this (using Chrome, Phantom 23.2.3)

1. Switching accounts within Phantom before connecting works.
2. Switching accounts within Phantom during connecting (while the connect prompt is open) works.
3. Switching accounts within Phantom after connecting works (and disconnects the connected account).
4. Switching accounts within Phantom after connecting to the newly selected account within Phantom works.
5. Switching accounts within Phantom between two previously connected accounts works (correctly autoconnecting to either in the app).

**Comment by mschneider** [comment]
Just tried again and can't reproduce the issue anymore.
