### ISSUE TITLE
iOS Phantom app wallet lose connection (does not auto connect) after reload 

### ISSUE THREAD

**Issue by ghtea** [solana-labs/wallet-adapter#748]
**Describe the bug**
iOS Phantom app wallet lose connected after reload 

**To Reproduce**
1. Download iOS Phantom app and get wallet
2. Go to browser tab (the far right) and access https://g99lxl.csb.app/
3. Select wallet and choose Phantom
4. Reload browser and see the wallet is disconnected

**Expected behavior**
A wallet should be still connected (should auto connect) after reload

**Screenshots**

// the issue does not happen in Desktop
**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 110.0.5481.77 (Official Build) (arm64)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 16.3.1
 - Browser: Phantom App
 - Version: 23.2.1

**Additional context**
- this issue does not happen in desktop
- the website in the reproduction steps is from this codesandbox
  - https://codesandbox.io/s/coinbase-wallet-demo-solana-wallet-adapter-g99lxl
- the phantom provider seems fine
  - reload does not let connection lose in this site
    - https://1ssci.csb.app/
    - https://codesandbox.io/s/phantom-wallet-1ssci?file=/src/TestApp.tsx

**Comment by bfriel** [comment]
Thanks for reporting @ghtea ! We will investigate this.

**Comment by jordansexton** [comment]
Closing this as it's likely not a Wallet Adapter issue and has been reported to Phantom. @bfriel any update?

**Comment by bfriel** [comment]
This has been fixed in `23.3.0`!
