### ISSUE TITLE
Phantom Chrome extension 23.3.1 not loading with on Chrome or Brave

### ISSUE THREAD

**Issue by mintavenger** [solana-labs/wallet-adapter#749]
**Describe the bug**

With Phantom latest version 23.3.1 released on March 13, 2023, I started noticing issues running my next.js app. where not in the console Phantom app would not load intermittently.

On successful case I would see:
`Phantom was registered as a Standard Wallet. The Wallet Adapter for Phantom can be removed from your app.`

On failed cases I would see:

```
Uncaught TypeError: Reflect.get called on non-object
    at Reflect.get (<anonymous>)
    at Object.get (<anonymous>:14:24)
    at isMetaMask (chunk-I72G2FFW.js?b8f6:11:1)
    at metaMaskWallet (chunk-I72G2FFW.js?b8f6:30:1)
    at eval (_app.js?e0ad:59:21)
    at ./pages/_app.js (_app.js?ts=1678823697738:7096:1)
    at options.factory (webpack.js?ts=1678823697738:733:31)
    at __webpack_require__ (webpack.js?ts=1678823697738:37:33)
    at fn (webpack.js?ts=1678823697738:388:21)
    at eval (?6782:5:16)
    at eval (route-loader.js?ea34:211:51)
```

or sometimes

```
main-1ccbc73bdf43a7e9.js:1 TypeError: Reflect.get called on non-object
    at Reflect.get (<anonymous>)
    at Object.get (<anonymous>:14:24)
    at nc (_app-64df1872adc46904.js:336:432493)
    at nu (_app-64df1872adc46904.js:336:432706)
    at 4796 (_app-64df1872adc46904.js:336:444079)
    at b (webpack-32251b5c8e5e3c1e.js:1:167)
    at _app-64df1872adc46904.js:336:523722
    at main-1ccbc73bdf43a7e9.js:1:25603
```

Strange thing it was intermittent and I couldn't reproduce reliably until I tried running the app locally with `npm run dev`. Then I was able to reproduce the error every time and unable to connect my wallet. By running the app with `npm run build; npm run start` I was able to run fine most of the time.

**To Reproduce**
1. Requires Phantom Chrome extension 23.3.1 (most recent version released 3/13/2023)
2. Run your app in with `npm run start`
3. Try to connect a wallet

Sorry, no real way to reproduce this outside of running this locally or doing hard refreshes when hitting out app. Could be an issue with our app, but doesn't happen with version 23.2.4 of Phantom extension.

**Expected behavior**
Expect phantom to load properly with message in console:
`Phantom was registered as a Standard Wallet. The Wallet Adapter for Phantom can be removed from your app.`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows, Mac
 - Browser: Chrome and Brave with Phantom extension 23.3.1

**Smartphone (please complete the following information):**
 - No issue with smartphone since no phantom extension required
 - Worked on Brave on iphone 11

**Additional context**

This very well could be an implementation issue with our app but wanted to document it in case someone else runs across this. I'm beginning to think this is a race condition with the new version of the Phantom extension.

**Comment by jordansexton** [comment]
cc @bfriel

This is unlikely to be a Wallet Adapter issue. From your code snippet, the error looks like it's being thrown from something related to `metamaskWallet`. This could have to do with Phantom's EVM support. Are you using this in a Solana app?

**Comment by mintavenger** [comment]
@jordansexton I think you're right. It must be something else. Closing. Nice work on this project! Thanks for the help.
