### ISSUE TITLE
React UI components do not work in Next.js

### ISSUE THREAD

**Issue by IAmConnorWilson** [solana-labs/wallet-adapter#75]
Next.js throws errors when libraries try to import global styling. See the following issue:

https://github.com/vercel/next.js/issues/19936

Looks like there might be a patch on the way in Next but is there any way we can pull this out and have users manually add css file? Open to other suggestions

**Comment by jordansexton** [comment]
Hmm, interesting. What about using the IgnorePlugin for Webpack in the Next.js config to ignore the file, then import it manually?

**Comment by IAmConnorWilson** [comment]
Wasn't able to get anything going with webpack/babel but I think this library does the trick 

https://github.com/martpie/next-transpile-modules

added to the next.config.js file: 

```javascript
const withTM = require('next-transpile-modules')(['@solana/wallet-adapter-react-ui']);

// reactStrictMode: true,
module.exports = (_, { defaultConfig }) => {
  // Next.js config
  const nextConfig = {
    ...defaultConfig,
    reactStrictMode: true,
  };

  return withTM(nextConfig);
};
```

**Comment by jordansexton** [comment]
Oh, this is what the Next.js starter project already does: https://github.com/solana-labs/wallet-adapter/blob/2c29262405f971f950563f2ff229c1a7a2ff2582/packages/starter/nextjs-starter/next.config.js#L2

**Comment by jordansexton** [comment]
Since the React UI package is already being transpiled this way, I'll close this issue:
https://github.com/solana-labs/wallet-adapter/blob/2c29262405f971f950563f2ff229c1a7a2ff2582/packages/starter/nextjs-starter/next.config.js#L11

**Comment by jordansexton** [comment]
Please check https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/example which has a complete example of using every provided UI framework for React with Next.js, and also shows how to import the styles and the Next config setup needed.

**Comment by carlosbane** [comment]
For next 13, sprinkling a little "use client" at the top of the file did it for me :)
