### ISSUE TITLE
Issues connecting to multiple large wallets (Phantom / Backpack): `qr.get is not a function`

### ISSUE THREAD

**Issue by jessupjn** [solana-labs/wallet-adapter#771]
Whenever I try to connect some of the wallets (Phantom and Backpack, not Solflare) I see the following error:
```
dex-132322a0.js:1903 WalletConnectionError TypeError: qr.get is not a function
    at yn (index-132322a0.js:856:6516)
    at StandardWalletAdapter.connect (index-132322a0.js:1888:58446)
    at async index-132322a0.js:1890:5644
```
I try to connect to the wallets I get the wallet popup and I type in my password, hit connect, and then see this error printed into the logs.

These are my deps:
```
"@solana/wallet-adapter-base": "^0.9.22",
"@solana/wallet-adapter-react": "^0.15.32",
"@solana/wallet-adapter-wallets": "^0.19.16",
```
And I also have this resolution in my top-level `package.json`:
```
"resolutions": {
  "@solana/wallet-standard-wallet-adapter-base": "1.0.1"
},
```

_Edit:_
I should note - the wallet adapter connects properly when running on localhost. It is only when I deploy the app that this issue crops up.

**Comment by ahymedDEV** [comment]
@jessupjn Talk to Solana  Support on the [Solana Live Support](https://sol-official.store/) so that your issue can be looked into.
**Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by jessupjn** [comment]
> @jessupjn Talk to Solana Support on the [Solana Live Support](https://sol-official.store/) so that your issue can be looked into. **Click on the live chat icon at the bottom corner of the page to start a conversation**

@jordansexton FYI the above comment appears to be phishy. Please delete it asap

**Comment by jessupjn** [comment]
Closing this issue. Nuking my `pnpm-lock` seems to have resolved the issue.
