### ISSUE TITLE
filter error create in module @solana/wallet-adaptater-react

### ISSUE THREAD

**Issue by cSarcasme** [solana-labs/wallet-adapter#779]
**Describe the bug**

**To Reproduce**
Server Error
TypeError: Cannot read properties of undefined (reading 'filter')

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///C:/Users/haatman/Desktop/dbq2formydev-main/dbq2formydev-main/frt/node_modules/@solana/wallet-standard-wallet-adapter-react/lib/esm/useStandardWalletAdapters.js (17:21)

i use nodejs 18 and nexjs13

this is my file when i use @solana/wallet-adaptater-react

```ts
import Header from '../Header/Header';
import Footer from '../Footer/Footer';
import {useMemo} from'react';
import {ConnectionProvider, WalletProvider} from '@solana/wallet-adapter-react';
//import {walletAdaptaterNetwork} from '@solana/wallet-adapter-base';
import {PhantomWalletAdapter, SolflareWalletAdapter } from '@solana/wallet-adapter-wallets';
import { WalletModalProvider } from '@solana/wallet-adapter-react-ui';
require('@solana/wallet-adapter-react-ui/styles.css');

export default function Layout(props) {
  const endpoint = '<snip>';

  const wallets = useMemo ( () => 
    [
      new PhantomWalletAdapter(),
      new SolflareWalletAdapter()
    ]
    ,[]);

  return (
    <>
    <ConnectionProvider endpoint ={endpoint}>
      <WalletProvider>
        <WalletModalProvider wallets={wallets} autoConnect>
          <Header />
          <main className='container'>{props.children}</main>
          <Footer />
        </WalletModalProvider>
      </WalletProvider>
      </ConnectionProvider>
    </>
  );
}
```

the error come about a filter in useStandartWalletAdaptater.js

a pitcure from the file

![image](https://github.com/solana-labs/wallet-adapter/assets/39191127/1f915f17-89f3-45f3-a248-fac0924e3578)

In the wait of your help i wish you a good day

**Comment by steveluscher** [comment]
It’s too late. The edit is in the history.

**Comment by steveluscher** [comment]
@cSarcasme you have not supplied a wallets prop to WalletProvider. That’s why it’s erroring.

At your next opportunity, enable typescript in your project.

**Comment by cSarcasme** [comment]
dam it for the end point i will create a new one.
first thank you for your quick answer.

yes on my project i dont use typescript so it is disable, but if i understand right the module is writte with typescript so i need to enable it on my project for work. i will do a try and comeback to you.

**Comment by steveluscher** [comment]
TypeScript will prevent you from having to come back. 😄 

If you have further questions, post them on https://solana.stackexchange.com.

**Comment by Aminkavoos** [comment]
9AunvjrXkqjR35215+VoCu3ZGOBdrLOLyfUWLILla7g=
<https://drive.google.com/file/d/1jPL9MZrmyo5XXTaBpQxAyIcDJe2Urbvv/view?usp=drivesdk>



در تاریخ سه‌شنبه ۱۶ مهٔ ۲۰۲۳،‏ ۱۹:۵۷ cSarcasme ***@***.***>
نوشت:
