### ISSUE TITLE
Wallet Connect issue

### ISSUE THREAD

**Issue by y2kappa** [solana-labs/wallet-adapter#787]
Getting reports from users that WalletConnect is not working well anymore. I can't test it. 

What the user says:

> "It's a problem with the WalletConnect provider in mostly all Solana dApps. I never had any success to connect a mobile wallet to a dapp via ConnectWallet QR-codes. As I said no such problems in the Eth ecosystem."

> It's a niche feature but as it's available in the wallet provider component it should work. There was some changes in the standard and think Solana Labs hasn't updated their libs.

**Comment by jordansexton** [comment]
@jnwng not a lot of info here, but do you have an idea? My initial take is that few wallets actually support WC2, which is needed for non-EVM chain support, and it's not possible to tell from the report what wallets are being tested with what apps.

**Comment by jnwng** [comment]
yep, agreed. the user is probably trying to use an Ethereum mobile wallet thinking its just going to work (but it wont)

nothing actionable here without confirmation that they're not just using WCv1

**Comment by jordansexton** [comment]
Closing this issue since there isn't enough detail to act on. The WalletConnect adapter was just updated, but I don't think the changes will be relevant here unless there was an underlying bug that was fixed in a dependency.
