### ISSUE TITLE
Need some advice to add wallet standard for Svelte wallet adapter

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/wallet-adapter#788]
> _Hey Jordan, this is more just "I some help a hand fixing something in a community repo" rather than a bug / feature request. I'm asking here because you seem to be the best person to ask about Wallet Standard for Solana._

Per the [FAQ](https://github.com/solana-labs/wallet-adapter/blob/master/FAQ.md) I'm using the [Svelte adapter](https://github.com/svelte-on-solana/wallet-adapter) in a project. Right now Svelte adapter doesn't support the Wallet Standard, i.e. a Wallet app that works with the [Example DApp](https://solana-labs.github.io/wallet-adapter/example/) won't show up with the [Svelte equivalent](https://github.com/silvestrevivo/solana-svelte-counter/).

**I want to fix the Svelte adapter to [match the behavior of the React libraries](https://github.com/solana-labs/wallet-adapter/blob/master/APP.md)**:

```
             * Wallets that implement either of these standards will be available automatically.
             *
             *   - Solana Mobile Stack Mobile Wallet Adapter Protocol
             *     (https://github.com/solana-mobile/mobile-wallet-adapter)
             *   - Solana Wallet Standard
             *     (https://github.com/solana-labs/wallet-standard)
             *
             * If you wish to support a wallet that supports neither of those standards,
             * instantiate its legacy wallet adapter here. Common legacy adapters can be found
             * in the npm package `@solana/wallet-adapter-wallets`.
```

Right now `initialize` from `@svelte-on-solana/wallet-adapter-core` takes a list of wallet adapters from the `@solana/wallet-adapter-wallets` package.

Q. Is wallet standard support implemented as an adapter? Eg can I import a specific adapter which provides support for all wallets using Wallet Standard? I've looked but I haven't found it so far.

Q. How any other tips? Or a link to the code where the react library implements wallet standard when no wallet adapters are supplied?

**Comment by steveluscher** [comment]
> Is wallet standard support implemented as an adapter? Eg can I import a specific adapter which provides support for all wallets using Wallet Standard? I've looked but I haven't found it so far.

Yeah!
* https://www.npmjs.com/package/@solana/wallet-standard-wallet-adapter-base
* https://www.npmjs.com/package/@solana/wallet-standard-wallet-adapter-react

> How any other tips?

https://github.com/solana-labs/wallet-adapter/blob/0d0178c5d3c54e3f3e4d002042189701f6156fc0/packages/core/react/src/WalletProvider.tsx#L54

**Comment by mikemaccana** [comment]
Thanks @steveluscher! I'm in the original Svelte Wallet Adapter code at https://github.com/svelte-on-solana/wallet-adapter/blob/master/packages/ui/src/lib/WalletProvider.svelte#L4.

```
import { StandardWalletAdapter } from "@solana/wallet-standard-wallet-adapter-base";
```

And expecting to do a... 

```
wallets.push(new StandardWalletAdapter());
```

What I don't quite understand is what the constructor for `StandardWalletAdapter` wants as it's first argument - it seems like `StandardWalletAdapter` wants a concrete wallet implementation, but I don't know how to detect that from every wallet-standard-supporting wallet.

**Comment by mikemaccana** [comment]
Might have figured this out - it's midnight here, and I'm guessing since I can't find any docs, but LMK if this sounds correct:

```
  import { getWallets } from "@wallet-standard/core";
  
  onMount(async () => {
    const standardWalletApps = await getWallets();
    const firstStandardWalletApp = standardWalletApps[0];
    // TODO: we should probably map over all the apps and start a StandardWalletAdapter instance for each
    walletAdapters.push(new StandardWalletAdapter(firstStandardWalletApp));
  });
```

**Comment by steveluscher** [comment]
@mikemaccana Why guess when you can steal!

https://github.com/solana-labs/wallet-adapter/blob/0d0178c5d3c54e3f3e4d002042189701f6156fc0/packages/core/react/src/WalletProvider.tsx#L54

**Comment by baindlapranayraj** [comment]
Is this svelte adapter is dead ?
