### ISSUE TITLE
Unable to sign off chain messages with Ledger

### ISSUE THREAD

**Issue by iffrit01** [solana-labs/wallet-adapter#800]
Hi,
On one of my websites I am using signMessage on front-end and verify that signature on the backend to prove wallet ownership, but I am getting the following error:
"[unsupported] signing off chain messages with ledger is not yet supported"
Not sure if it's a library issue, cause I'm signing messages on other sites without any issue. Blind signing enabled.
Warm wallets work fine.
Thanks in advance

**Comment by jordansexton** [comment]
Yep, the error is correct. Solana off chain messages can't be signed with the Ledger app yet, with or without blind signing. There's a Foundation RFP being developed to build this, but it's out of scope for Wallet Adapter. We can't do anything here until it's supported by the device.

**Comment by eydelrivero** [comment]
> 

@jordansexton can you please clarify a bit on this? I thought support to sign off chain messages with Ledger was added last year after [this announcement from Anatoly](https://github.com/solana-labs/solana/issues/21366#issuecomment-1300913051). Is there anything I'm missing?

**Comment by izoukhai** [comment]
@jordaaash I +1 @eydelrivero, the announcement says it's supported but it doesn't work.
Do you have any information?

**Comment by yosriady** [comment]
Any updates on this?

**Comment by bowenli86** [comment]
why can it be implemented?

**Comment by nymiezer** [comment]
I am having the same issue with a SOL DAap, can't sign with my ledger. Funds are now stuck until this is resolved. Is this something ledger plans to implement in a future release?

**Comment by mfoolady** [comment]
same problem here.
![image](https://github.com/user-attachments/assets/9ddd8f5c-4781-432e-a9d2-c8e045a0d355)

**Comment by ulrickpsp** [comment]
Need to be able to sign offiline messages..

**Comment by synasapmob** [comment]
resolved this issues with documentation

```
  /* 
    repsect and thank for supports
      - https://github.com/LedgerHQ/app-solana/blob/develop/examples/example-sign.js#L52 (main)
      - https://github.com/phantom/sandbox/pull/33
      - https://github.dev/anza-xyz/wallet-adapter/pull/1047/files
      - https://github.com/LedgerHQ/developer-portal/blob/main/pages/docs/device-interaction/ledgerjs/integration/web-application/web-hid-usb.mdx
  */
```
