### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by elie222** [solana-labs/wallet-adapter#808]
That `export const dynamic = 'force-dynamic'` is needed when the GET is dynamic. This should be added to the docs instead of having to reach SO for the answer:
https://stackoverflow.com/questions/76191857/dynamicservererror-dynamic-server-usage-headers-in-nextjs-13-3

`DYNAMIC_SERVER_USAGE` is the error I was getting but didn't see anywhere in the docs.

**Comment by jordansexton** [comment]
Can you help explain how this relates to Wallet Adapter?
