### ISSUE TITLE
Coin98 implementation doesn't detect the extension and always send you to coin98.com

### ISSUE THREAD

**Issue by MexicanSparker** [solana-labs/wallet-adapter#81]
This issue qualifies more as a question.
The sub-package states in its readme that it is coming soon but since many other things say coming soon I don't know if Coin98 wallet provider implementation is done.

I have cloned the example app and added `getCoin98Wallet()` to the list of wallets to initialize and it indeed appears on the list but clicking in the Coin98 wallet option it takes me to their website even when I already installed the extension and I am connected. The wallet provider seems to not detect the extension.

If someone knows the status of Coin98 it would be great to know to make it available in my dApp.
Sorry if this doesn't have issue format, it is more a question.

**Comment by MexicanSparker** [comment]
After a while it started working, no idea why.

**Comment by jordansexton** [comment]
Glad you worked it out. I checked with the Coin98 team and they verified that the adapter is using the expected API. Can you mention what browser / device you are using? Just want to track this in case it occurs again.

**Comment by MexicanSparker** [comment]
Hey @jordansexton now I have confirmed that there is nothing wrong in the implementation. It seems that it is not enough with adding the Coin98 browser extension to pop it up. It needs to be initialized for the first time for Solana and as soon as you add (create/import) your first wallet for the current browser (tested with latest versions of Chrome, Opera and Brave) it starts popping up when the Coin98 option is clicked.
So essentially the only thing that is wrong that users can be frustrated with is the fact that they don't know this until they actually create a wallet for solana. None of my teammates had a Coin98 wallet so they all stopped there and none went through the process of creating a Wallet as "the solution of the problem", they simply complained and threw the implementation issue in JIRA, classic.
I hope this helped somehow.

**Comment by jordansexton** [comment]
Thanks for the extra details, that's very helpful. I'll test and raise this issue with the Coin98 team.

**Comment by jordansexton** [comment]
Closing this issue as the Coin98 team is aware and it's up to them to fix.
