### ISSUE TITLE
Can I have a network state from useWallet

### ISSUE THREAD

**Issue by v1xingyue** [solana-labs/wallet-adapter#820]
**Is your feature request related to a problem? Please describe.**
I use wallet-adapter to communicate with solana wallet like phanto. While when I change the wallet to a diffrent network, I want to change my dapp settings with the network change from wallet.

**Describe the solution you'd like**
I think we can provide network state from useWallet, and the network contains the current networkinfo .

**Comment by jordansexton** [comment]
Please search the issues in this repo. This is a request that's come up a few times, but it's not something Wallet Adapter can support because no wallets support this.
