### ISSUE TITLE
Changing wallet on Phantom chrome extension doesn't update publicKey anymore

### ISSUE THREAD

**Issue by AnderUstarroz** [solana-labs/wallet-adapter#826]
**Describe the bug**
Changing wallet when using Phantom chrome extension is not triggered in react (I am pretty sure it used to work on previous versions)

For instance the following minimum example in React works when connecting a wallet or disconnecting, but not when changing one wallet by another:

```
import {useWallet } from "@solana/wallet-adapter-react";


export default function SomeReactComponent() {
  const { publicKey } = useWallet();

  useEffect(() => {
    if (publicKey) {
        console.log("Wallet changed!", publicKey.toBase58());
   } else {
       console.log ("Wallet disconnected");
   }     
  }, [publicKey]);
  
  return <></>
}
```

**To Reproduce**
1. Using the minimum example provided within a Connection provider.
2. Connect one wallet using Phantom chrome extension.
3. `"Wallet changed!"`will be displayed in the console.
4. Go to Phantom extension and choose a different wallet.
5. `"Wallet changed!"`should be displayed again showing the new wallet address, but doesn't work anymore.

**Expected behavior**
`"Wallet changed!"` should be logged whenever the wallet is changed.

**Desktop:**
 - OS: OS X
 - Browser: Chrome
 - Version:
```
    "@solana-mobile/wallet-adapter-mobile": "^2.0.1",
    "@solana/wallet-adapter-base": "^0.9.23",
    "@solana/wallet-adapter-react": "^0.15.34",
    "@solana/wallet-adapter-react-ui": "^0.9.33",
    "@solana/wallet-adapter-wallets": "^0.19.20",
```

**Comment by AnderUstarroz** [comment]
The issue can be replicated even in your [demo](https://solana-labs.github.io/wallet-adapter/example/):
- Connect one wallet using Phantom chrome extension
- Click on `sign a message` (you will see that the wallet address is the correct one)
- Go to Phantom extension and change the wallet.
- Click again on `sign a message`, the wallet address is the old one.

**Comment by jordansexton** [comment]
This probably isn't an issue with Wallet Adapter, it's almost certainly a bug in new version of Phantom. Nothing relevant in the Phantom adapter has changed, and the demo/example is not using the Phantom adapter anyway.

Closing here but tagging @bfriel for help.

**Comment by bfriel** [comment]
Thanks for the report @AnderUstarroz . This is indeed a Phantom-specific bug which we believe is only occurring on Solana-only Mode. We have a separate thread tracking this [here](https://github.com/orgs/phantom/discussions/78).
