### ISSUE TITLE
TypeError: off is not a function - nextjs example crashes

### ISSUE THREAD

**Issue by ohaddahan** [solana-labs/wallet-adapter#837]
**Describe the bug**
Adapter no longer works.

**To Reproduce**
Use nextjs example supplied by `solana-labs/wallet-adapter`.
React-UI not working too.

**Expected behavior**
Not to crash.

**Screenshots**

![image](https://github.com/solana-labs/wallet-adapter/assets/20769037/f2e5ec0c-1ace-49e4-904d-3db526d4db1a)

**Comment by ohaddahan** [comment]
Seems like the `example` works but the `starter` for `nextjs` and `react-ui` aren't.

**Comment by jordansexton** [comment]
Can you link to a repo where you're doing this?

**Comment by ohaddahan** [comment]
> Can you link to a repo where you're doing this?

I clone this repo, cd into the directories, `yarn install`, took latest versions for all.

**Comment by jordansexton** [comment]
Okay, thanks. We'll test this and follow up.

**Comment by jordansexton** [comment]
I can't replicate this.

Did you make sure to [follow the instructions on building from source](https://github.com/solana-labs/wallet-adapter/blob/master/BUILD.md), and install the dependencies and build from the root first?

I followed them, and the `react-ui-starter` builds and runs with `pnpm run start`, and the `nextjs-starter` project builds and runs with `pnpm run dev`.

**Comment by ohaddahan** [comment]
> I can't replicate this.
> 
> 
> 
> Did you make sure to [follow the instructions on building from source](https://github.com/solana-labs/wallet-adapter/blob/master/BUILD.md), and install the dependencies and build from the root first?
> 
> 
> 
> I followed them, and the `react-ui-starter` builds and runs with `pnpm run start`, and the `nextjs-starter` project builds and runs with `pnpm run dev`.


The original issue is with some private repo I tried adding the wallet adapter to.
The I tried this repo, with yarn not pnpm.
I'll post a sample repo that replicate it tomorrow.

**Comment by jordansexton** [comment]
> Can you link to a repo where you're doing this?

That's precisely why I asked for this, and you said you cloned and ran it from this repo.

> I'll post a sample repo that replicate it tomorrow.

No need, it's not a bug with Wallet Adapter. Those starter projects aren't able to be run as-is outside of the repo, because the repo depends on pnpm workspaces.

If you're using the starter projects in your own repos, and those repos are not forks of this repo, or using its package or build system, you will need to replace the `"workspace:^"` references with links to the actual npm package versions.

**Comment by ohaddahan** [comment]
> > Can you link to a repo where you're doing this?
> 
> That's precisely why I asked for this, and you said you cloned and ran it from this repo.
> 
> > I'll post a sample repo that replicate it tomorrow.
> 
> No need, it's not a bug with Wallet Adapter. Those starter projects aren't able to be run as-is outside of the repo, because the repo depends on pnpm workspaces.
> 
> If you're using the starter projects in your own repos, and those repos are not forks of this repo, or using its package or build system, you will need to replace the `"workspace:^"` references with links to the actual npm package versions.

Didn't use a starter project, followed the FAQ , `yarn add`, copied over the `setup`.
Here's a sample repo that reproduces that issue.

https://github.com/ohaddahan/wallet-adapter-issue
