### ISSUE TITLE
Ledger Wallet Address Selection

### ISSUE THREAD

**Issue by manugildev** [solana-labs/wallet-adapter#84]
**Is your feature request related to a problem? Please describe.**
Ledger Wallet adapter doesn't allow you to select wallet address / derivation path. When you connect your ledger it auto selects the first address, which might not be the one the users want to use or where they have their funds.

**Describe the solution you'd like**
When selecting the ledger wallet, open a dropdown menu (see how phantom wallet does it in the image) to let the user choose its address.

**Describe alternatives you've considered**
Users usually need to link their ledger to phantom or other wallet that allows them to select their address, instead of using ledger itself in the dapp. This is not ideal.

**Additional context**
![image](https://user-images.githubusercontent.com/13288771/133677603-61d8b775-2aa9-4e09-b4cd-b118143273c4.png)

**Comment by jordansexton** [comment]
Related: https://github.com/solana-labs/wallet-adapter/issues/49

**Comment by p1tch-black** [comment]
Same issue here.
