### ISSUE TITLE
Wallet (Phantom) does not connect for some users

### ISSUE THREAD

**Issue by eeebad** [solana-labs/wallet-adapter#853]
Describe the bug

I've encountered reports from multiple users who are experiencing difficulty connecting their wallets. While I haven't been able to reproduce the issue personally, some users mention that after selecting a wallet from the modal listing available options, nothing further occurs – it seems the extension popup fails to appear.

Desktop:

Browser [e.g. chrome, firefox, safari]

**Comment by jordaaash** [comment]
Please raise issues with Phantom with Phantom. You can use the "Start a Chat" feature here: https://help.phantom.app/hc/en-us
