### ISSUE TITLE
TypeError: setOpen is not a function in WalletDialogButton.tsx

### ISSUE THREAD

**Issue by kefalet98** [solana-labs/wallet-adapter#89]
**Describe the bug**
With the commit held in 6 hours ago WalletDialogButton.tsx break down.

**To Reproduce**
1. Go to 'wallet-material-ui/src/walletdialogbutton.tsx'
2. Click on 'line 17'
3. See error setOpen is not a function

**Expected behavior**
Hence useState function took one param at the leftend side react consider it as a var not a as a function.

**Screenshots**
![image](https://user-images.githubusercontent.com/70665954/133912240-da85f6bf-7ae5-46a8-8615-d6b9813f4df5.png)

**Comment by jordansexton** [comment]
Please see this FAQ section: https://github.com/solana-labs/wallet-adapter/blob/master/FAQ.md#-is-not-a-function---is-undefined--uncaught-typeerror-cannot-destructure-property--uncaught-in-promise-walletnotconnectederror

This error typically occurs if your WalletDialogContext is not configured correctly as a parent of the button you're using.
