### ISSUE TITLE
setOpen is not a function

### ISSUE THREAD

**Issue by kefalet98** [solana-labs/wallet-adapter#90]
**Describe the bug**
Today suddenly WalletDialogButton starts to give setOpen is not a function error on react.

**To Reproduce**
1. Go to 'material-ui/src/'
2. Click on 'WalletDialogButton.tsx'
3. Scroll down to 'line 17'
4. See error { setOpen } = useWallet(); gives setOpen is not a function error in 

**Screenshots**
![image](https://user-images.githubusercontent.com/70665954/133912588-b1ce7e46-bef4-463e-bd1d-1d2511056b6b.png)

**Comment by jordansexton** [comment]
Please see this FAQ section: https://github.com/solana-labs/wallet-adapter/blob/master/FAQ.md#-is-not-a-function---is-undefined--uncaught-typeerror-cannot-destructure-property--uncaught-in-promise-walletnotconnectederror

This error typically occurs if your WalletDialogContext is not configured correctly as a parent of the button you're using.

**Comment by kefalet98** [comment]
Okey totally my problem i put it in walletmodelprovider instead of a walletdialogprovider thanks for your help

**Comment by kefalet98** [comment]
Great project by the way goob job

**Comment by jordansexton** [comment]
Glad you sorted it out. And thanks :)
