### ISSUE TITLE
The `wallet.adapter` function out of `useWallet` is never correct

### ISSUE THREAD

**Issue by maoueh** [solana-labs/wallet-adapter#96]
**Describe the bug**
When using `useWallet`, it appears the `wallet` object returned never has the correct `adapter` associated with.

**To Reproduce**

```
const { connected, wallet, adapter } = useWallet()

console.log('Wallet connected', connected)
console.log('Wallet', wallet?.adapter()?.publicKey)
console.log('Adapter', adapter?.publicKey)
```

If you connect a wallet with `autoConnect: true` in the `WalletProvider`, you will see that `console.log('Adapter', adapter?.publicKey)` will correctly log the public key at some point but `console.log('Wallet', wallet?.adapter()?.publicKey)` will never show the correct one.

**Expected behavior**
There is a mismatch between the wallet.adapter and the direct adapter. This caused a confusion when I use it because I thought `wallet.adapter` would work.

This is probably related to the fact the `setState` properly adjust the `adapter` state but the `wallet` should be updated at the same time.

It could be seen as a documentation problem also.

**Comment by jordansexton** [comment]
See https://github.com/solana-labs/wallet-adapter#usage

In the general case, `const { wallet, publicKey, sendTransaction } = useWallet()` encapsulates all you need --

- `wallet` tells you which wallet is selected (name and icon)
- `publicKey` tells you the public key, _iff_ the wallet is connected, and `null` otherwise, so you usually don't need `connected` either.
- `sendTransaction` is the method to send a transaction, which also handles signing, and it will error if `publicKey` is `null`, so you should always check before calling it.

`wallet.adapter()` gives you a second independent instance of the underlying adapter. If you want low level access to the adapter, you're using it outside the React context by design, and it's up to you to call `connect` on it before you can get the public key.

The React context exposes this to you for flexibility, but you shouldn't use it unless you know that's what you need (and you probably don't need it).

**Comment by maoueh** [comment]
Like I described in the issue, the `wallet.adapter()` do not return the correct instance after connection, and most probably in all other circumstances.

Showing the the `publicKey` on the `wallet.adapter().publicKey` was just to show case the problem. 

Some of our shared code required a `WalletAdapter`, hence in the component I had something like that:

```
const { wallet } = useWallet()
const { setVisible } = useWalletModal()

<Button onClick={() => { setVisible(true) }>Connect</Button>
<Button onClick={() => { performAction(wallet.adapter()) }>Send Transaction</Button>
```

But this was always throwing a `WalletNotConnectedError`. Why, because the `wallet.adapter()` was stuck to the actual initial instance that was not connected anymore.

Using `adapter` straight from the `useWallet` works correctly, but I lost a few hours understanding the problem.

IMO, it's a bug that `wallet.adapter()` is not working correctly.

**Comment by jordansexton** [comment]
> `wallet.adapter()` gives you a second independent instance of the underlying adapter. If you want low level access to the adapter, you're using it outside the React context by design, and it's up to you to call `connect` on it before you can get the public key.

This means you must call `connect` on the instance of the adapter you are instantiating, you must handle it asynchronously, and the public key you get from it will also be a new instance. It's a second, totally independent instance. The fact that you called `connect` on the instance in the React context has no bearing on it.

But you don't need to do any of this, and this isn't a bug. It's designed this way to provide low level access to the adapter outside of React, and when you do that, anything you do in the React context will not affect it. Like I said, you really shouldn't use the low level adapter API unless you know you need to use it and you know how it works.

**Comment by maoueh** [comment]
> `wallet.adapter()` gives you a second independent instance of the underlying adapter.

So I re-read your response a second time (maybe a third time :)). While I now get a bit more context about the usage of `wallet.adapter()`, it still feels weird that it's not working directly. When you see `wallet.adapter()`, I expected that it would give me a correct valid tied to the wallet adapter.

The documentation should probably warn that if an adapter is required, the `adapter` directly on the `useWallet` context should be used. I could even see some changes in the API for other developers to not fall in the pitfall I hit.

For example, `wallet.adapter()` could always be the correct adapter, `adapter` on `useWallet` could be removed and a free form method not provide on `useWallet` could exist if someone wants to create a manual adapter outside of React context.

If those are not acceptable, an other suggestion from me would be to rename the `wallet.adapter` method to something in the like of `wallet.createIndependentAdapter`, `wallet.createUnmanagedAdapter`, etc.

Might not be a bug in the end even though I personally feel discutable that it was not working, looking at the available types and method, I really felt `wallet.adapter()` would work. My goal is really for other developer to not fall in the same problem I had.
