### ISSUE TITLE
issue with button 

### ISSUE THREAD

**Issue by Shafique007** [solana-labs/wallet-adapter#98]
I want you to build 2 buttons on my website, first button will be "Connect Wallet" to connect Phantom wallet or sollet.io wallet to the website, after connection, a button will appear at bottom of the page named "Send transaction" that will send 0.05 sol to our address after user's confirmation. but there is an issue with the code I found on your account it's not working.
please reply to me ASAP. I am looking forward to your positive response. Thankx

**Comment by jordansexton** [comment]
You're posting in the wrong place, my friend.

**Comment by Shafique007** [comment]
sorry
[image: GeoTrack]
<https://geotrack.email/?utm_source=gmail&utm_medium=signature&utm_campaign=viralSignature>
Sender
notified with GeoTrack
<https://geotrack.email/?utm_source=gmail&utm_medium=signature&utm_campaign=viralSignature>
[image: 44]
